### ISSUE TITLE
Recording will fail if events.xml is too large.

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#10055]
**Describe the bug**
It seems the xml parser has a size limit. `internal error: Huge input lookup`

**To Reproduce**
Create a two-three hour session with average user paticipation activity (cursor movement, slide changes, talking events etc.)

**Expected behavior**
Recorder should still process the event file

**Actual behavior**
Recording fails at process step.

```
cat /var/log/bigbluebutton/presentation/process-7f0ffabdf0c0e92ada13f12440d7ccdbadc60cc3-1593587135973.log

...
I, [2020-07-09T16:29:37.585552 #15322]  INFO -- : Executing: mkclean --quiet /var/bigbluebutton/recording/process/presentation/7f0ffabdf0c0e92ada13f12440d7ccdbadc60cc3-1593587135973/audio.encode.webm /var/bigbluebutton/recording/process/presentation/7f0ffabdf0c0e92ada13f12440d7ccdbadc60cc3-1593587135973/audio.pp0.webm
I, [2020-07-09T16:36:03.944846 #15322]  INFO -- : The MinCache element at -1 is not part of profile 'webm', skipping
I, [2020-07-09T16:36:03.945063 #15322]  INFO -- : The TrackTimecodeScale element at -1 is not part of profile 'webm', skipping
I, [2020-07-09T16:36:03.945182 #15322]  INFO -- : The MaxBlockAdditionID element at -1 is not part of profile 'webm', skipping
I, [2020-07-09T16:36:03.945301 #15322]  INFO -- : The CodecDecodeAll element at -1 is not part of profile 'webm', skipping
I, [2020-07-09T16:42:36.216349 #15322]  INFO -- : Exit status: 0
I, [2020-07-09T16:42:36.887414 #15322]  INFO -- : Task: Getting presentations from events
I, [2020-07-09T16:42:37.417687 #15322]  INFO -- : Task: Getting meeting metadata
I, [2020-07-09T16:42:37.624439 #15322]  INFO -- : Created an updated metadata.xml with start_time and end_time
I, [2020-07-09T16:42:37.624520 #15322]  INFO -- : Generating closed captions
I, [2020-07-09T16:42:37.624544 #15322]  INFO -- : Executing: utils/gen_webvtt -i /var/bigbluebutton/recording/raw/7f0ffabdf0c0e92ada13f12440d7ccdbadc60cc3-1593587135973 -o /var/bigbluebutton/recording/process/presentation/7f0ffabdf0c0e92ada13f12440d7ccdbadc60cc3-1593587135973
I, [2020-07-09T16:42:38.896232 #15322]  INFO -- : INFO:__main__:Reading recording events file
I, [2020-07-09T16:42:39.916673 #15322]  INFO -- : Traceback (most recent call last):
I, [2020-07-09T16:42:39.916791 #15322]  INFO -- :   File "utils/gen_webvtt", line 409, in <module>
I, [2020-07-09T16:42:39.916812 #15322]  INFO -- :     events = parse_events(rawdir)
I, [2020-07-09T16:42:39.916870 #15322]  INFO -- :   File "utils/gen_webvtt", line 350, in parse_events
I, [2020-07-09T16:42:39.916889 #15322]  INFO -- :     root = etree.parse("{}/events.xml".format(directory))
I, [2020-07-09T16:42:39.916903 #15322]  INFO -- :   File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:85131)
I, [2020-07-09T16:42:39.916919 #15322]  INFO -- :   File "src/lxml/parser.pxi", line 1782, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:124005)
I, [2020-07-09T16:42:39.916935 #15322]  INFO -- :   File "src/lxml/parser.pxi", line 1808, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:124374)
I, [2020-07-09T16:42:39.916954 #15322]  INFO -- :   File "src/lxml/parser.pxi", line 1712, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:123169)
I, [2020-07-09T16:42:39.916969 #15322]  INFO -- :   File "src/lxml/parser.pxi", line 1115, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:117533)
I, [2020-07-09T16:42:39.916984 #15322]  INFO -- :   File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:110510)
I, [2020-07-09T16:42:39.916999 #15322]  INFO -- :   File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:112276)
I, [2020-07-09T16:42:39.917070 #15322]  INFO -- :   File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:111124)
I, [2020-07-09T16:42:39.917125 #15322]  INFO -- : lxml.etree.XMLSyntaxError: internal error: Huge input lookup, line 192556, column 3
I, [2020-07-09T16:42:39.941039 #15322]  INFO -- : Exit status: 1
E, [2020-07-09T16:42:39.941281 #15322] ERROR -- : Generating closed caption files failed
E, [2020-07-09T16:42:39.941331 #15322] ERROR -- : process/presentation.rb:204:in `<main>'

```

A quick internet search shows this is a known flaw in the xml parser. I could not find any work arounds other than to manually delete lines in the event.xml until the recorder could process it. This is obviously not practical.

I think this happens at around 800,000 lines of xml. the data.xml was about 40Mb.

**Comment by iSamof** [comment]
Great catch @aogilvie - we have not started offering recording to our users as yet. It is good to know of this limitation (until a solution is found).

**Comment by uozbek** [comment]
I have the same problem with some recordings. Do you find any solution to this problem?

**Comment by aogilvie** [comment]
@uozbek I did not. We no longer conduct sessions of this scale anymore because of this and other issues.
