### ISSUE TITLE
Update BigBlueButton 2.2.24 update make my system unusable 

### ISSUE THREAD

**Issue by dseral** [bigbluebutton/bigbluebutton#10463]
**Bug Description**
Today i was update bigbluebutton from 2.2.23 to 2.2.24 and my system become unusable. 

**To Reproduce**
> apt-get update
> apt-get dist-upgrade

> bbb-conf --setip mydomain.com

Greenlight  start to gave me 
"Invalid BigBlueButton Endpoint and Secret"

Also demo server gave following error
"java.lang.NullPointerException
	at org.apache.jsp.demoHTML5_jsp.getJoinURLExtended(demoHTML5_jsp.java:259)
	at org.apache.jsp.demoHTML5_jsp._jspService(demoHTML5_jsp.java:1257)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:400)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:344)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)"

#bbb-conf --secret
URL: https://mydomain.com/bigbluebutton/
Secret: bcw0yK92XFvd8SQb2kfOaRpNG80YeTlmYmq4zitg

**/var/log/bigbluebutton/bbb-web.log** 
2020-09-16T00:17:40.704+03:00 ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'meetingService' defined in class path resource [spring/resources.xml]: Cannot resolve reference to bean 'paramsProces
sorUtil' while setting bean property 'paramsProcessorUtil'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'paramsProcessorUtil' defined in class
 path resource [spring/resources.xml]: Initialization of bean failed; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to req
uired type 'java.lang.Boolean' for property 'endWhenNoModerator'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value [${endWhenNoModerator}]
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1534)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1281)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:84)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:393)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:380)
        at grails.boot.GrailsApp$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
        at org.bigbluebutton.web.Application.main(Application.groovy:8)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'paramsProcessorUtil' defined in class path resource [spring/resources.xml]: Initialization of bean failed;
 nested exception is org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Boolean' for property 'endWhenNoModerator'; nes
ted exception is java.lang.IllegalArgumentException: Invalid boolean value [${endWhenNoModerator}]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'paramsProcessorUtil' defined in class path resource [spring/resources.xml]: Initialization of bean failed;
 nested exception is org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Boolean' for property 'endWhenNoModerator'; nes
ted exception is java.lang.IllegalArgumentException: Invalid boolean value [${endWhenNoModerator}]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
        ... 32 common frames omitted
Caused by: org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Boolean' for property 'endWhenNoModerator'; nested except
ion is java.lang.IllegalArgumentException: Invalid boolean value [${endWhenNoModerator}]
        at org.springframework.beans.AbstractNestablePropertyAccessor.convertIfNecessary(AbstractNestablePropertyAccessor.java:608)
        at org.springframework.beans.AbstractNestablePropertyAccessor.convertForProperty(AbstractNestablePropertyAccessor.java:615)
        at org.springframework.beans.BeanWrapperImpl.convertForProperty(BeanWrapperImpl.java:216)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.convertForProperty(AbstractAutowireCapableBeanFactory.java:1580)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1539)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1281)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
        ... 38 common frames omitted
Caused by: java.lang.IllegalArgumentException: Invalid boolean value [${endWhenNoModerator}]
        at org.springframework.beans.propertyeditors.CustomBooleanEditor.setAsText(CustomBooleanEditor.java:123)
        at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:470)
        at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:443)
        at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:200)
        at org.springframework.beans.AbstractNestablePropertyAccessor.convertIfNecessary(AbstractNestablePropertyAccessor.java:588)
        ... 44 common frames omitted
                 
   -- Errors found in /var/log/nginx/error.log --
2020/09/16 00:17:24 [error] 21407#21407: *2 connect() failed (111: Connection refused) while connecting to upstream, client: xxxx.xxx.xxx, server: xxxxx.com, request: "GET /bigbluebutton/api HTTP/1.1", upstream: "http://127.0.0.1:8090/bigbluebutton/api", host: "meet.petraeducation.com"
2020/09/16 00:17:24 [error] 21407#21407: *2 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: xxxx.xxx.xxx, server: xxxxx.com, request: "GET /bigbluebutton/api HTTP/1.1", upstream: "http://127.0.0.1:8090/bigbluebutton/api", host: "meet.petraeducation.com"
2020/09/16 00:17:25 [error] 21407#21407: *4 connect() failed (111: Connection refused) while connecting to upstream, client: xxxx.xxx.xxx, server: xxxxx.com, request: "GET /bigbluebutton/api HTTP/1.1", upstream: "http://127.0.0.1:8090/bigbluebutton/api", host: "meet.petraeducation.com"
                                                                                     
**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Chrome 
 - Version: 85.0.4183.102
 - Browser: Firefox
 - Version: 80.0.1

**Additional context**
Server OS:  Ubuntu 16.04.7 LTS
Kernel: 4.4.0-189-generic #219-Ubuntu SMP

**Comment by ffdixon** [comment]
Can you run the command

~~~
bbb-conf --secret
~~~

and see if the hostname and shared secret no longer match the settings for Greenlight.

**Comment by dseral** [comment]
bbb-conf --secret
 URL: https://example.com/bigbluebutton/
    Secret: bcw0yK92XFvd8SQb2kfOaRpNG80YeTlmYmq4zitg

My greenlight .env 
BIGBLUEBUTTON_ENDPOINT=https://example.com/bigbluebutton/
BIGBLUEBUTTON_SECRET=bcw0yK92XFvd8SQb2kfOaRpNG80YeTlmYmq4zitg

**Comment by ritzalam** [comment]
Please check if you have this value set.

```
> cat /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties | grep endWhen
endWhenNoModerator=false

```

**Comment by muellerlukas** [comment]
`Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'meetingService' defined in class path resource [spring/resources.xml]: Cannot resolve reference to bean 'paramsProcessorUtil' while setting bean property 'paramsProcessorUtil'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'paramsProcessorUtil' defined in class path resource [spring/resources.xml]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'endWhenNoModerator' of bean class [org.bigbluebutton.api.ParamsProcessorUtil]: Bean property `

**Comment by dseral** [comment]
> Please check if you have this value set.
> 
> ```
> > cat /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties | grep endWhen
> endWhenNoModerator=false
> ```

Thank for your advice..
This config parameter makes problem..
Thank you ritzalam

**Comment by dseral** [comment]
After bigbluebutton updated in the end of /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties file there is new option called 
endWhenNoModerator=false
However my apply-config.sh overwrite configs from previous edition. That make trouble. 
Can we find out better way to handle this config changes? Or is it possible to add default parameters to applications?

**Comment by ffdixon** [comment]
We would recommend that your `apply-config.sh` update the values you changed using sed commands.  That way, you can apply changes to the configuration file but still allow new parameters to be introduced in newer versions of BigBlueButton.

**Comment by frahman80** [comment]
Hi,

How to set the time limit on endWhenNoModerator

Like if I want to set the limit to 5 mins

Thanks

**Comment by ritzalam** [comment]
The endWhenNoModerator isn't complete yet. The param is just being handled by bbb-web. The part that use it needs to be implemented in akka-apps.

**Comment by frahman80** [comment]
Good to know that this feature is in the pipeline.

**Comment by defnull** [comment]
> We would recommend that your `apply-config.sh` update the values you changed using `sed` commands. That way, you can apply changes to the configuration file but still allow new parameters to be introduced in newer versions of BigBlueButton.

Actually, why not just use two config files. One for default values (installed by package) and one for changes. Like every other configurable debian package out there?

**Comment by ffdixon** [comment]
It's a good suggestion.   Since March we've been focused on improving the core product.   It's our intent to improve the packaging in future versions of BigBlueButton (and follow the norms).  We had planned to do some of this in 2.3, but I think it's more likely we'll be revamping the packaging in 2.4.
