### ISSUE TITLE
red5 status failed in 2.2.27

### ISSUE THREAD

**Issue by tom230764** [bigbluebutton/bigbluebutton#10679]
Since version 2.2.27 I get this errors:
- red5 has status failed (in bbb-status)
- Error: Unable to connect to port 1935 (RTMP) on ...(fqdn) (in bbb-conf --restart/bbb-conf --check)

These errors I get regardless whether I do (a) an update from 2.2.26, (b) a clean install step-by-step or (c) a clean install with bbb-install.sh.
As a result the audio quality is instable and bad and all 5 minutes i loose the microphone. I think this last behaviour is caused by the connection via TURN-server.

BBB-Server is an 16-core dedicated server from IONOS (1&1) in Germany, other servers (VM from netcup and 2 more VMs in our DMZ ) don't show this problem. Here the update was also from 2.2.26 to 2.2.27 and the servers are running fine. 

What was changed in 2.2.27, that could cause such a behaviour? Am I the only one with such a problem ?
And what to do to get rid of these errors? 

some logs:

/var/log/red5/error.log:
2020-10-18T11:55:11.038+02:00 [0.0.0.0-startStop-1] WARN  o.s.w.s.h.SimpleUrlHandlerMapping - Neither 'urlMap' nor 'mappings' set on SimpleUrlHandlerMapping
2020-10-18T11:55:15.115+02:00 [pool-6-thread-1] ERROR o.r.server.service.ShutdownServer - Cannot bind to port: 9999, ensure no other instances are bound or choose another port
java.net.BindException: Address already in use (Bind failed)
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
        at java.net.ServerSocket.bind(ServerSocket.java:390)
        at java.net.ServerSocket.<init>(ServerSocket.java:252)
        at java.net.ServerSocket.<init>(ServerSocket.java:143)
        at org.red5.server.service.ShutdownServer.start(ShutdownServer.java:161)
        at org.red5.server.service.ShutdownServer$1.run(ShutdownServer.java:129)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-10-18T11:55:15.141+02:00 [Loader:] WARN  o.s.w.c.s.XmlWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'web.context' defined in ServletContext resource [/WEB-INF/red5-web.xml]: Unsatisfied dependency expressed through bean property 'scopeResolver'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'red5.scopeResolver' defined in URL [file:/usr/share/red5/webapps/red5-default.xml]: Cannot resolve reference to bean 'global.scope' while setting bean property 'globalScope'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'global.scope' defined in URL [file:/usr/share/red5/webapps/red5-default.xml]: Cannot resolve reference to bean 'red5.server' while setting bean property 'server'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'red5.server' defined in class path resource [red5-common.xml]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext

grep error /var/log/bbb-webrtc-sfu/bbb-webrtc-sfu.log:
{"message":"[sfu-mcs-api] SFU socket connection to mcs-core failed due to connect ECONNREFUSED 127.0.0.1:3010","level":"error","timestamp":"2020-10-18T09:49:06.192Z"}
{"level":"error","message":"[sfu-mcs-api] SFU socket connection to mcs-core closed unexpectedly","timestamp":"2020-10-18T09:49:06.193Z"}

**Comment by tom230764** [comment]
I found the Problem: IONOS used an new backup agent inside of the machine. This agent occupied some of the ports bbb needed. 
After disabling it bbb runs fine.

**Comment by matiasilva** [comment]
red5 is no longer used in BBB, so any errors with it can probably be ignored.
