### ISSUE TITLE
Error 500 java  java.lang.NullPointerException

### ISSUE THREAD

**Issue by Anubys** [bigbluebutton/bigbluebutton#10867]
Hi
After fresh instalation step-by-step, after changes in config files requieres by SSL access , when click link access Big Blue Button show internal error 500.

I set my domain with setconf -setip and have valid certificate 

Can yo help me ?

Thanx 
![blue-error](https://user-images.githubusercontent.com/5467624/99667435-b10a2a00-2a6c-11eb-9614-3db0c0daf473.PNG)

**Comment by ffdixon** [comment]
Check the settings for `/var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp` that it has `https` for the server URL.

**Comment by Anubys** [comment]
Yes 

<%!
// This is the security salt that must match the value set in the BigBlueButton server
String salt = "4s35lzaP0kGiKE0rhspIgqCkrUHwX7X05tZLTDtKIIg";

// This is the URL for the BigBlueButton server
String BigBlueButtonURL = "https://xxxxx/bigbluebutton/";
%>

**Comment by Anubys** [comment]
In tomcat logs show next error 

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:456)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:323)
        at sun.security.validator.Validator.validate(Validator.java:271)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:315)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:223)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
        ... 45 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:451)

¿certificate problems?

**Comment by Anubys** [comment]
Sorry solved the problem --> https://mkyong.com/webservices/jax-ws/suncertpathbuilderexception-unable-to-find-valid-certification-path-to-requested-target/ 

More thanx
