### ISSUE TITLE
Exception in setInterval callback: TypeError: Meteor.server.sessions.values(...) is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#10882]
**Describe the bug**
In testing 2.2.30, seeing this message appear in the `/var/log/syslog` every 2 seconds.  Not seeing it in 2.3-dev server.
~~~
Nov 22 20:58:17 droplet-3321 systemd_start.sh[18392]: Exception in setInterval callback: TypeError: Meteor.server.sessions.values(...) is not a function or its return value is not iterable
Nov 22 20:58:17 droplet-3321 systemd_start.sh[18392]:     at Meteor.setInterval (imports/startup/server/index.js:66:5)
Nov 22 20:58:17 droplet-3321 systemd_start.sh[18392]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Nov 22 20:58:17 droplet-3321 systemd_start.sh[18392]:     at packages/meteor.js:550:25
Nov 22 20:58:17 droplet-3321 systemd_start.sh[18392]:     at runWithEnvironment (packages/meteor.js:1286:24)
~~~

**To Reproduce**
  1. Install latest build of BigBluebutton 2.2.30
  2. run `tail -f /var/log/syslog`

**Comment by mindevolution** [comment]
Met this issue too, https://stackoverflow.com/questions/38748445/uncaught-typeerror-object-values-is-not-a-function-javascript
Update file imports/startup/server/index.js line 65 to fix this issue.
`  Meteor.setInterval(() => {
    const sessions = Object.keys(Meteor.server.sessions).map(key => Meteor.server.sessions[key]);
    for (const session of sessions) {
      const { socket } = session;
      const recv = socket._session.recv;

      if (session.bbbFixApplied || !recv || !recv.ws) {
        continue;
      }

      recv.ws.meteorHeartbeat = session.heartbeat;
      recv.__proto__.heartbeat = newHeartbeat;
      recv.ws.__proto__.send = newSend;
      session.bbbFixApplied = true;
    }
  }, 5000);`

**Comment by mabras** [comment]
We see this in all our `2.2.31` servers.

**Comment by ffdixon** [comment]
> Nov 22 20:58:17 droplet-3321 systemd_start.sh[18392]: Exception in setInterval callback: TypeError: Meteor.server.sessions.values(...) is not a function or its return value is not iterable

@mabras We're not seeing this on our demo servers.  Did you make any custom changes to your BigBlueButton server?

**Comment by burakguder** [comment]
This error is being received within the 2.2.31 development environment. Meeting does not open and stays at 3 points



[[[[[ /home/ubuntu/dev/bigbluebutton-2.2.31/bigbluebutton-html5 ]]]]]

```
=> Started proxy.                             
=> A patch (Meteor 1.8.1) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.                           
I20201230-10:44:45.130(1)? warn: Custom heartbeat functions are enabled
I20201230-10:44:45.203(1)? warn: SERVER STARTED.
I20201230-10:44:45.203(1)? ENV=development,
I20201230-10:44:45.204(1)? nodejs version=v8.11.4
I20201230-10:44:45.204(1)? CDN=
I20201230-10:44:45.205(1)?  {"mobileFontSize":"16px","desktopFontSize":"14px","audioChatNotification":false,"autoJoin":true,"listenOnlyMode":true,"forceListenOnly":false,"skipCheck":false,"clientTitle":"BigBlueButton","appName":"BigBlueButton HTML5 Client","bbbServerVersion":2.2,"copyright":"©2020 BigBlueButton Inc.","html5ClientBuild":"HTML5_CLIENT_VERSION","helpLink":"https://bigbluebutton.org/html5/","lockOnJoin":true,"cdn":"","basename":"/html5client","askForFeedbackOnLogout":false,"allowDefaultLogoutUrl":true,"allowUserLookup":false,"enableNetworkInformation":false,"enableLimitOfViewersInWebcam":false,"enableMultipleCameras":false,"enableTalkingIndicator":true,"mirrorOwnWebcam":false,"viewersInWebcam":8,"ipv4FallbackDomain":"","allowLogout":true,"allowFullscreen":true,"remainingTimeThreshold":30,"remainingTimeAlertThreshold":1,"breakoutRoomLimit":8,"customHeartbeat":true,"defaultSettings":{"application":{"animations":true,"chatAudioAlerts":false,"chatPushAlerts":false,"userJoinAudioAlerts":false,"userJoinPushAlerts":false,"fallbackLocale":"en","overrideLocale":null},"audio":{"inputDeviceId":"undefined","outputDeviceId":"undefined"},"dataSaving":{"viewParticipantsWebcams":true,"viewScreenshare":true}},"shortcuts":{"openOptions":{"accesskey":"O","descId":"openOptions"},"toggleUserList":{"accesskey":"U","descId":"toggleUserList"},"toggleMute":{"accesskey":"M","descId":"toggleMute"},"joinAudio":{"accesskey":"J","descId":"joinAudio"},"leaveAudio":{"accesskey":"L","descId":"leaveAudio"},"togglePublicChat":{"accesskey":"P","descId":"togglePublicChat"},"hidePrivateChat":{"accesskey":"H","descId":"hidePrivateChat"},"closePrivateChat":{"accesskey":"G","descId":"closePrivateChat"},"openActions":{"accesskey":"A","descId":"openActions"}},"branding":{"displayBrandingArea":false},"connectionTimeout":60000,"showHelpButton":true,"effectiveConnection":["critical","danger","warning"]}
=> Started your app.

=> App running at: http://127.0.0.1/html5client
I20201230-10:44:45.205(1)? info: Added record prop id=56592c41933d4828c8022d2c793339c4065f3113-1609321401241
I20201230-10:44:45.206(1)? info: Added meeting id=56592c41933d4828c8022d2c793339c4065f3113-1609321401241
I20201230-10:44:45.206(1)? warn: Notes are disabled for 56592c41933d4828c8022d2c793339c4065f3113-1609321401241
I20201230-10:44:45.206(1)? info: Added presentation id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607 meeting=56592c41933d4828c8022d2c793339c4065f3113-1609321401241
I20201230-10:44:45.206(1)? info: Added presentation pod id=DEFAULT_PRESENTATION_POD meeting=56592c41933d4828c8022d2c793339c4065f3113-1609321401241
I20201230-10:44:45.206(1)? info: Added group-chat name=MAIN-PUBLIC-GROUP-CHAT meetingId=56592c41933d4828c8022d2c793339c4065f3113-1609321401241
I20201230-10:44:45.206(1)? info: Added slide position id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/14 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.206(1)? info: Added slide position id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/9 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.207(1)? info: Added slide position id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/6 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.207(1)? info: Changed meeting={56592c41933d4828c8022d2c793339c4065f3113-1609321401241} updated lock settings
I20201230-10:44:45.207(1)? info: Added slide position id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/13 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.207(1)? info: Added slide id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/14 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.207(1)? info: Added slide position id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/10 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.207(1)? info: Added slide position id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/3 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.207(1)? info: Added slide position id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/7 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.207(1)? info: Added slide id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/3 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.208(1)? info: Added slide id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/9 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.208(1)? info: Added slide id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/7 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.208(1)? info: Added slide id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/6 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.208(1)? info: Added slide id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/13 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.208(1)? info: Added slide id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/10 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.208(1)? info: Added slide position id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/11 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.208(1)? info: Added slide position id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/2 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.209(1)? info: Added slide position id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/8 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.209(1)? info: Added slide id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/2 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.209(1)? info: Added slide id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/11 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.209(1)? info: Added slide position id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/5 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.209(1)? info: Added slide position id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/4 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.209(1)? info: Added slide position id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/12 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.209(1)? info: Added slide id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/8 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.209(1)? info: Added slide id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/12 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.209(1)? info: Added slide id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/4 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.210(1)? info: Added slide id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/5 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.210(1)? info: Added slide position id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/1 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.210(1)? info: Added slide id=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/1 pod=DEFAULT_PRESENTATION_POD presentation=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607
I20201230-10:44:45.210(1)? info: Added multiUser flag=false meetingId=56592c41933d4828c8022d2c793339c4065f3113-1609321401241 whiteboardId=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/14
I20201230-10:44:45.210(1)? info: Added multiUser flag=false meetingId=56592c41933d4828c8022d2c793339c4065f3113-1609321401241 whiteboardId=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/3
I20201230-10:44:45.210(1)? info: Added multiUser flag=false meetingId=56592c41933d4828c8022d2c793339c4065f3113-1609321401241 whiteboardId=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/9
I20201230-10:44:45.210(1)? info: Added multiUser flag=false meetingId=56592c41933d4828c8022d2c793339c4065f3113-1609321401241 whiteboardId=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/7
I20201230-10:44:45.210(1)? info: Added multiUser flag=false meetingId=56592c41933d4828c8022d2c793339c4065f3113-1609321401241 whiteboardId=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/6
I20201230-10:44:45.210(1)? info: Added multiUser flag=false meetingId=56592c41933d4828c8022d2c793339c4065f3113-1609321401241 whiteboardId=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/13
I20201230-10:44:45.211(1)? info: Added multiUser flag=false meetingId=56592c41933d4828c8022d2c793339c4065f3113-1609321401241 whiteboardId=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/10
I20201230-10:44:45.211(1)? info: Added multiUser flag=false meetingId=56592c41933d4828c8022d2c793339c4065f3113-1609321401241 whiteboardId=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/2
I20201230-10:44:45.211(1)? info: Added multiUser flag=false meetingId=56592c41933d4828c8022d2c793339c4065f3113-1609321401241 whiteboardId=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/11
I20201230-10:44:45.211(1)? info: Added multiUser flag=false meetingId=56592c41933d4828c8022d2c793339c4065f3113-1609321401241 whiteboardId=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/8
I20201230-10:44:45.211(1)? info: Added multiUser flag=false meetingId=56592c41933d4828c8022d2c793339c4065f3113-1609321401241 whiteboardId=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/12
I20201230-10:44:45.211(1)? info: Added multiUser flag=false meetingId=56592c41933d4828c8022d2c793339c4065f3113-1609321401241 whiteboardId=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/4
I20201230-10:44:45.211(1)? info: Added multiUser flag=false meetingId=56592c41933d4828c8022d2c793339c4065f3113-1609321401241 whiteboardId=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/5
I20201230-10:44:45.211(1)? info: Added multiUser flag=false meetingId=56592c41933d4828c8022d2c793339c4065f3113-1609321401241 whiteboardId=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1609321402607/1
I20201230-10:44:46.521(1)? Exception in setInterval callback: TypeError: Meteor.server.sessions.values(...) is not a function or its return value is not iterable
I20201230-10:44:46.522(1)?     at Meteor.setInterval (imports/startup/server/index.js:91:52)
I20201230-10:44:46.522(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20201230-10:44:46.523(1)?     at packages/meteor.js:550:25
I20201230-10:44:46.523(1)?     at runWithEnvironment (packages/meteor.js:1286:24)
I20201230-10:44:51.524(1)? Exception in setInterval callback: TypeError: Meteor.server.sessions.values(...) is not a function or its return value is not iterable
I20201230-10:44:51.525(1)?     at Meteor.setInterval (imports/startup/server/index.js:91:52)
I20201230-10:44:51.525(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20201230-10:44:51.526(1)?     at packages/meteor.js:550:25
I20201230-10:44:51.526(1)?     at runWithEnvironment (packages/meteor.js:1286:24)
I20201230-10:44:56.525(1)? Exception in setInterval callback: TypeError: Meteor.server.sessions.values(...) is not a function or its return value is not iterable
I20201230-10:44:56.526(1)?     at Meteor.setInterval (imports/startup/server/index.js:91:52)
I20201230-10:44:56.526(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20201230-10:44:56.526(1)?     at packages/meteor.js:550:25
I20201230-10:44:56.527(1)?     at runWithEnvironment (packages/meteor.js:1286:24)

```

**Comment by mariogasparoni** [comment]
I can confirm this is happening on current develop branch: 5713fa54f3d8a63678704658af9dc4890c764d6a
I have just set a clean 2.3 dev environment and his problem happended.
mindevolution's workaround makes this Exception disappear.

Using Nodejs 12

**Comment by jfsiebel** [comment]
Hi @burakguder,
Do you still have this problem?

I see your Meteor version is < 1.8.1, hence the issue. Could update the meteor version and run `meteor clear; rm -r node_modules; meteor npm i; npm start`?
