### ISSUE TITLE
records take too long to process!

### ISSUE THREAD

**Issue by burakguder** [bigbluebutton/bigbluebutton#11015]
I want the machine to process records at night with full CPU. But it doesn't process existing records either. I don't see any ffmpeg processes running. I gave the images in the attachment

bbb-record --debug 

```
root@Ubuntu-1604-xenial-64-minimal ~ # bbb-record --debug
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:40:59.845736 #6726] ERROR -- : SIGTERM
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:40:59.845877 #6726] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:124:in `each_line'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:40:59.845903 #6726] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:124:in `block in exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:40:59.845922 #6726] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in `popen'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:40:59.845939 #6726] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in `exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:40:59.845956 #6726] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:80:in `block (2 levels) in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:40:59.845973 #6726] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:56:in `each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:40:59.845990 #6726] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:56:in `block in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:40:59.846007 #6726] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:30:in `each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:40:59.846023 #6726] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:30:in `process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:40:59.846040 #6726] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:155:in `<main>'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.335945 #62601] ERROR -- : Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.335996 #62601] ERROR -- : /var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis/client.rb:362:in `rescue in establish_connection'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336006 #62601] ERROR -- : /var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis/client.rb:344:in `establish_connection'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336014 #62601] ERROR -- : /var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis/client.rb:106:in `block in connect'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336021 #62601] ERROR -- : /var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis/client.rb:306:in `with_reconnect'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336028 #62601] ERROR -- : /var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis/client.rb:105:in `connect'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336035 #62601] ERROR -- : /var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis/client.rb:381:in `ensure_connected'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336042 #62601] ERROR -- : /var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis/client.rb:231:in `block in process'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336049 #62601] ERROR -- : /var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis/client.rb:319:in `logging'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336056 #62601] ERROR -- : /var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis/client.rb:230:in `process'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336063 #62601] ERROR -- : /var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis/client.rb:125:in `call'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336070 #62601] ERROR -- : /var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis.rb:2287:in `block in publish'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336077 #62601] ERROR -- : /var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis.rb:52:in `block in synchronize'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336094 #62601] ERROR -- : /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336101 #62601] ERROR -- : /var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis.rb:52:in `synchronize'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336108 #62601] ERROR -- : /var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis.rb:2286:in `publish'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336115 #62601] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:151:in `put_message'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336122 #62601] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:155:in `put_message_workflow'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336131 #62601] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:177:in `put_process_started'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336138 #62601] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:69:in `block (2 levels) in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336145 #62601] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:56:in `each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336152 #62601] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:56:in `block in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336159 #62601] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:30:in `each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336173 #62601] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:30:in `process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:41:37.336180 #62601] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:155:in `<main>'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:51:19.797476 #64828] ERROR -- : SIGTERM
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:51:19.797626 #64828] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:124:in `each_line'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:51:19.797651 #64828] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:124:in `block in exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:51:19.797669 #64828] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in `popen'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:51:19.797686 #64828] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in `exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:51:19.797702 #64828] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:80:in `block (2 levels) in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:51:19.797719 #64828] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:56:in `each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:51:19.797736 #64828] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:56:in `block in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:51:19.797753 #64828] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:30:in `each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:51:19.797770 #64828] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:30:in `process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-12-09T22:51:19.797787 #64828] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:155:in `<main>'
  -- ERRORS found while processing slides /var/log/bigbluebutton/presentation/process-* -- 
/var/log/bigbluebutton/presentation/process-7a7d9cf47a00b59587808cc3e25ec66a7e55497a-1607322526002.log:E, [2020-12-07T19:15:26.464441 #7897] ERROR -- : Error: stderr: Syntax Warning: matrix not invertible<0a>

root@Ubuntu-1604-xenial-64-minimal ~ # 
```

![bbb_watch](https://user-images.githubusercontent.com/560147/102025898-e247f280-3dab-11eb-8751-5347c48cc50b.png)
![bbb_cpu](https://user-images.githubusercontent.com/560147/102025900-e542e300-3dab-11eb-9bbc-2f78436b2a55.png)

**Comment by burakguder** [comment]
+++
```

tail -f /var/log/nginx/bigbluebutton.access.log | grep get
116.203.230.211 - - [13/Dec/2020:23:57:38 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:57:42 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:57:46 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:57:49 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:57:53 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:57:56 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:58:00 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:58:03 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:58:07 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:58:10 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:58:14 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:58:17 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:58:21 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:58:24 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:58:28 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:58:31 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:58:35 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:58:38 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:58:42 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:58:45 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"
116.203.230.211 - - [13/Dec/2020:23:58:49 +0100] "GET /bigbluebutton/api/getMeetings?&checksum=878edea0c0b0f957e43b1448296794b1280d4f3b HTTP/1.1" 200 171 "-" "-"

```

**Comment by ffdixon** [comment]
What version of BigBlueButton are you running?

**Comment by burakguder** [comment]
2.2.30

```
ii  bbb-apps                               1:2.2.0-50                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                          2.2.0-96                                        all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                   1:2.2.0-50                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                           1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                         1:2.2.0-48                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast               1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                             1:2.2.0-40                                      amd64        BigBlueButton Flash client
ii  bbb-config                             1:2.2.0-225                                     amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                           1:2.2.0-63                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                    2:2.2.0-113                                     amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                  1:1.6.7-6                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                         2.2.0-72                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                              1:2.2.0-1095                                    amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                            1:0.8.7-3                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation              1:2.2.0-33                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                        1:2.2.0-71                                      amd64        BigBlueButton record and playback
ii  bbb-red5                               1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-transcode-akka                     2.2.0-8                                         all          BigBlueButton Transcoder
ii  bbb-web                                1:2.2.0-148                                     amd64        BigBlueButton API
ii  bbb-webrtc-sfu                         1:2.2.0-108                                     amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                          1:2.2.0-5                                       amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                 7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                     7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                    7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                     7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                    7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                   7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                      7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                            0.2.1-1bbb1                                     amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                    7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                   7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                      7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library for image scaling and various conversions - runtime files

```

**Comment by burakguder** [comment]
/usr/local/bigbluebutton/core/lib/recordandplayback/generators/video.rb
changed as below

```
%w[-c:v libvpx-vp9 -b:v 400K -minrate 150K -maxrate 500K -crf 33 -quality realtime -speed 5 -tile-columns 2 -threads 4 -g 240 
             -c:a libopus -b:a 48K
             -f webm]
```

```
          %w[-c:v libx264 -crf 23 -threads 4 -preset ultrafast -g 240
             -c:a aac -b:a 64K
             -f mp4 -movflags faststart]

```

vim /usr/local/bigbluebutton/core/scripts/presentation.yml

-mp4  is activated

**Comment by burakguder** [comment]
lessons started now on the server. and ffmpeg processes started when the server was busy. 
There was no encode process when the server was idle
I want encoder operations to be done at night. But no action is taken at night and the queue is not processed.

this situation creates a serious problem. Do you have a suggestion?

![bbb-hata-4](https://user-images.githubusercontent.com/560147/102052690-85722980-3df7-11eb-8612-54c35f90cbe3.png)

**Comment by bilias** [comment]
I have this in all of my servers to only do processing at nights

/etc/systemd/system/bbb-record-core.timer.d/override.conf
[Timer]
#OnActiveSec=0
OnActiveSec=
OnUnitInactiveSec=
OnCalendar=21,22,23,00,01,02,03:*:00
Persistent=false

sudo systemctl daemon-reload
after the file creation

**Comment by burakguder** [comment]
I changed the encode profiles and made the format mp4. encode is now completed within the day

**Comment by ffdixon** [comment]
Thanks @bilias.  Added it to https://docs.bigbluebutton.org/2.2/customize.html#change-processing-time.

**Comment by bilias** [comment]
> Thanks @bilias. Added it to https://docs.bigbluebutton.org/2.2/customize.html#change-processing-time.

typo:
OnCalendar=21,22,23,00,01,02,03:*:00
between 11pm and 3am at night.

you should change either the calendar or the doc.

**Comment by ffdixon** [comment]
i'm not seeing the typo -- can you suggest the change to make them match.

**Comment by bilias** [comment]
Calendar starts at 21:00 and in document you say: between 11pm and 3am 

better change the document to day between 21:00 and 03:59

**Comment by ffdixon** [comment]
Thanks @bilias.  Made your suggested change to the docs.
