### ISSUE TITLE
BBB 2.2.31 - Build 1114 - TypeError: Cannot read property 'colorId' of null

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/bigbluebutton#11027]
HI BBB Team,

A new issue.
I don't know exactly why, but a exception in etherpad had to consequence to eject all the users...

user 1

```
Dec 16 15:08:13 bbb-host node[13368]: #033[32m[2020-12-16 15:08:13.980] [INFO] access - #033[39m[ENTER] Pad "434f4a37": Client Z1ICJRR5tjuIajAiAAAN with IP "x.x.x.x" entered the pad
Dec 16 15:08:13 bbb-host node[13368]: #033[31m[2020-12-16 15:08:13.985] [ERROR] console - #033[39m(node:13368) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'colorId' of null
Dec 16 15:08:13 bbb-host node[13368]:     at p.then.authorInfo (/usr/share/etherpad-lite/src/node/handler/PadMessageHandler.js:1199:37)
Dec 16 15:08:13 bbb-host node[13368]:     at <anonymous>
Dec 16 15:08:13 bbb-host node[13368]:     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
Dec 16 15:08:13 bbb-host node[13368]: #033[31m[2020-12-16 15:08:13.985] [ERROR] console - #033[39m(node:13368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Dec 16 15:08:13 bbb-host node[13368]: #033[31m[2020-12-16 15:08:13.985] [ERROR] console - #033[39m(node:13368) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
user 2

```

Dec 16 15:09:22 bbb-host node[13368]: #033[32m[2020-12-16 15:09:22.735] [INFO] access - #033[39m[ENTER] Pad "434f4a37": Client LpmRjpQ2kq2wQX7OAAAO with IP "y.y.y.y" entered the pad
Dec 16 15:09:22 bbb-host node[13368]: #033[31m[2020-12-16 15:09:22.739] [ERROR] console - #033[39m(node:13368) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'colorId' of null
Dec 16 15:09:22 bbb-host node[13368]:     at p.then.authorInfo (/usr/share/etherpad-lite/src/node/handler/PadMessageHandler.js:1199:37)
Dec 16 15:09:22 bbb-host node[13368]:     at <anonymous>
Dec 16 15:09:22 bbb-host node[13368]:     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
Dec 16 15:09:22 bbb-host node[13368]: #033[31m[2020-12-16 15:09:22.739] [ERROR] console - #033[39m(node:13368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
Dec 16 15:09:22 bbb-host node[13368]: #033[32m[2020-12-16 15:09:22.792] [INFO] ueberDB - #033[39mFlushed 2 values
```

**Comment by aguerson** [comment]
3 KMS activated

**Comment by basisbit** [comment]
Probably this problem: https://github.com/ether/etherpad-lite/issues/3612
Did you maybe change some styling or color settings previously and used new id values for those colors, but did not adjust all the translation files for it?

**Comment by aguerson** [comment]
I use the default BBB config.
I just adapt BBB to use stun turn server
I add a trunk SIP
I activated 3 KMS
I adapt Nginx conf like the last issue about html5 cache
I try to stay near from the origin to have a better support

I use BBB on a CT OpenVZ on Ubuntu 18.04 LTS

So if something is change about the colour, it is the global config, but not mine.
