### ISSUE TITLE
Determine minimal additions to bbb-libreoffice docker container to support Asian letters

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#11089]
**Describe the bug**
Since 2.3a, BBB does not convert Asian letters in .pptx file. 

**To Reproduce**
1. Upload a pptx file with Japanese, Korean, or Chinese letters
2. Only Asian letters are converted to white rectangles.

**Expected behavior**
Asian letters are displayed as well.

**Actual behavior**
Asian letters are displayed by white rectangles.

**Screenshots**
![asian](https://user-images.githubusercontent.com/45039819/103273642-26213580-4a03-11eb-8616-0843c282805f.jpg)

**Additional context**
The problem happens also in test23 server.
When uploading a PDF (which is converted from the pptx file by LibreOffice), all letters are displayed correctly.
BBB 2.2 does not have that problem.
Changing fonts does not help.
Either with locale Japanese or English I observed the same problem.

Would anybody suggest me which code to change?

**Comment by ffdixon** [comment]
The conversion process for libreoffice is now done inside a docker container.  After a bit of experimenting, on a 2.3 server we edited `/usr/share/bbb-libreoffice/docker` and removed the `--no-install-recommends` from `/usr/share/bbb-libreoffice/docker/Dockerfile`

```
RUN apt -y install --no-install-recommends libreoffice fonts-crosextra-carlito fonts-crosextra-caladea fonts-noto
```

Saved the updated `Dockerfile` and then rebuilt the docker image

```
# cd /usr/share/bbb-libreoffice
# docker build -t bbb-libreoffice docker/
```

and then restart the docker containers for libreoffice

```
# systemctl restart bbb-libreoffice@1.service bbb-libreoffice@2.service bbb-libreoffice@3.service bbb-libreoffice@4.service
```

Uploaded the attached test file and the Japanese characters displayed.

![image](https://user-images.githubusercontent.com/290351/103287605-4c21e800-49b9-11eb-82ad-cda325322e49.png)

[hello world.pptx](https://github.com/bigbluebutton/bigbluebutton/files/5750865/hello.world.pptx)

There is an increase in size for the docker container.  Before

```
# docker image list bbb-libreoffice
REPOSITORY        TAG       IMAGE ID       CREATED         SIZE
bbb-libreoffice   latest    f872c169793d   4 minutes ago   1.18GB
```

after

```
# docker image list bbb-libreoffice
REPOSITORY        TAG       IMAGE ID       CREATED         SIZE
bbb-libreoffice   latest    f872c169793d   4 minutes ago   2.52GB
```

The key would be to determine just the extra packages needed for libreoffice and add those to the Docker file and keep the  `--no-install-recommends`.

**Comment by hiroshisuga** [comment]
Hi @ffdixon , thanks for the fix. I have confirmed that it worked like a charm on one of my servers.
However, in another server the docker build command gave an error:

E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/o/openjdk-11/openjdk-11-jre-headless_11.0.8+10-1~deb10u1_amd64.deb  404  Not Found [IP: 151.101.110.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/l/llvm-toolchain-7/libllvm7_7.0.1-8_amd64.deb  404  Not Found [IP: 151.101.110.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/o/openjdk-11/openjdk-11-jre_11.0.8+10-1~deb10u1_amd64.deb  404  Not Found [IP: 151.101.110.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gupnp/libgupnp-1.0-4_1.0.3-3_amd64.deb  404  Not Found [IP: 151.101.110.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/libc/libcommons-compress-java/libcommons-compress-java_1.18-2_all.deb  404  Not Found [IP: 151.101.110.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt -y install libreoffice fonts-crosextra-carlito fonts-crosextra-caladea fonts-noto' returned a non-zero code: 100

Seems to be a temporary server problem. Thus, I modified the /usr/share/bbb-libreoffice/docker/Dockerfile as:
RUN apt -y install --no-install-recommends libreoffice fonts-crosextra-carlito fonts-crosextra-caladea fonts-noto fonts-noto-cjk
(just adding fonts-noto-cjk package)
This worked perfectly at least for three Asian languages.
The image file size is:
bbb-libreoffice   latest    9f7900465ca9   7 minutes ago   1.27GB

![cjk](https://user-images.githubusercontent.com/45039819/103293087-88ddf580-4a32-11eb-8f0f-ed62a88e857f.jpg)

**Comment by qdzmc** [comment]
something wrong
RUN apt -y install --no-install-recommends libreoffice fonts-crosextra-carlito fonts-crosextra-caladea fonts-noto fonts-noto-cjk


Get:194 Index of /debian buster/main amd64 libreoffice amd64 1:6.1.5-3+deb10u6 [78.1 kB]

**E: Failed to fetch http://deb.debian.org/debian/pool/main/s/systemd/systemd_241-7~deb10u4_amd64.deb 404 Not Found [IP: 151.101.38.132 80]**

**E: Failed to fetch http://deb.debian.org/debian/pool/main/s/systemd/systemd-sysv_241-7~deb10u4_amd64.deb 404 Not Found [IP: 151.101.38.132 80]**

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Fetched 241 MB in 27s (8867 kB/s)

The command '/bin/sh -c apt -y install --no-install-recommends libreoffice fonts-crosextra-carlito fonts-crosextra-caladea fonts-noto fonts-noto-cjk' returned a non-zero code: 100

dpkg: error processing package bbb-libreoffice-docker (--configure):

**Comment by qdzmc** [comment]
after change I cannt convert pptx file
[https://imgchr.com/i/ySKrcV](url)

bbb-web log：
2021-01-28T08:34:17.759+08:00 INFO  o.b.p.imp.Office2PdfPageConverter -  --analytics-- data={"filename":"安全班会.pptx","logCode":"office_doc_to_pdf","meetingId":"46ded18febc26f5c891b033642c4f13585397c49-1611793988242","message":"Converting Office doc to PDF.","presId":"bada3e4cebecbac03a2651fd483855f2ce7ce9b8-1611794046689"}
2021-01-28T08:34:19.770+08:00 ERROR o.b.p.imp.Office2PdfPageConverter -  --analytics-- data={"exception":{"detailMessage":"Could not establish connection to external office process","cause":{"detailMessage":"org.jodconverter.local.office.OfficeConnectionException: Connection failed: \u0027socket,host\u003d127.0.0.1,port\u003d8204,tcpNoDelay\u003d1\u0027; java.net.ConnectException: Connection refused (Connection refused)","cause":{"connectString":"socket,host\u003d127.0.0.1,port\u003d8204,tcpNoDelay\u003d1","detailMessage":"Connection failed: \u0027socket,host\u003d127.0.0.1,port\u003d8204,tcpNoDelay\u003d1\u0027; java.net.ConnectException: Connection refused (Connection refused)","cause":{"detailMessage":"java.net.ConnectException: Connection refused (Connection refused)","stackTrace":[],"suppressedExceptions":[]},"stackTrace":[],"suppressedExceptions":[]},"stackTrace":[],"suppressedExceptions":[]},"stackTrace":[],"suppressedExceptions":[]},"filename":"安全班会.pptx","logCode":"office_doc_to_pdf_failed_with_exception","meetingId":"46ded18febc26f5c891b033642c4f13585397c49-1611793988242","message":"Failed to convert Office doc to PDF.","presId":"bada3e4cebecbac03a2651fd483855f2ce7ce9b8-1611794046689"}
org.jodconverter.core.office.OfficeException: Could not establish connection to external office process
	at org.jodconverter.local.office.ExternalOfficeManager.connect(ExternalOfficeManager.java:149)
	at org.jodconverter.local.office.ExternalOfficeManager.execute(ExternalOfficeManager.java:158)
	at org.jodconverter.local.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:158)
	at org.jodconverter.core.job.AbstractConversionJob.execute(AbstractConversionJob.java:60)
	at org.bigbluebutton.presentation.imp.Office2PdfPageConverter.convert(Office2PdfPageConverter.java:67)
	at org.bigbluebutton.presentation.imp.OfficeToPdfConversionService.convertOfficeDocToPdf(OfficeToPdfConversionService.java:123)
	at org.bigbluebutton.presentation.imp.OfficeToPdfConversionService.convertOfficeToPdf(OfficeToPdfConversionService.java:71)
	at org.bigbluebutton.presentation.DocumentConversionServiceImp.processDocumentStart(DocumentConversionServiceImp.java:63)
	at org.bigbluebutton.presentation.DocumentConversionServiceImp.processDocument(DocumentConversionServiceImp.java:54)
	at org.bigbluebutton.presentation.DocumentConversionService$processDocument.call(Unknown Source)
	at org.bigbluebutton.web.services.PresentationService$_closure5$_closure16.doCall(PresentationService.groovy:85)
	at org.bigbluebutton.web.services.PresentationService$_closure5$_closure16.doCall(PresentationService.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods$2.run(DefaultGroovyMethods.java:15553)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: org.jodconverter.core.office.RetryTimeoutException: org.jodconverter.local.office.OfficeConnectionException: Connection failed: 'socket,host=127.0.0.1,port=8204,tcpNoDelay=1'; java.net.ConnectException: Connection refused (Connection refused)
	at org.jodconverter.core.office.AbstractRetryable.execute(AbstractRetryable.java:81)
	at org.jodconverter.local.office.ExternalOfficeManager.connect(ExternalOfficeManager.java:146)
	... 24 common frames omitted
Caused by: org.jodconverter.local.office.OfficeConnectionException: Connection failed: 'socket,host=127.0.0.1,port=8204,tcpNoDelay=1'; java.net.ConnectException: Connection refused (Connection refused)
	at org.jodconverter.local.office.OfficeConnection.connect(OfficeConnection.java:187)
	at org.jodconverter.local.office.ConnectRetryable.attempt(ConnectRetryable.java:68)
	at org.jodconverter.core.office.AbstractRetryable.execute(AbstractRetryable.java:75)
	... 25 common frames omitted
Caused by: com.sun.star.connection.NoConnectException: java.net.ConnectException: Connection refused (Connection refused)
	at com.sun.star.lib.connections.socket.socketConnector.connect(socketConnector.java:144)
	at com.sun.star.comp.connections.Connector.connect(Connector.java:119)
	at org.jodconverter.local.office.OfficeConnection.connect(OfficeConnection.java:113)
	... 27 common frames omitted
2021-01-28T08:34:19.773+08:00 WARN  o.b.p.i.OfficeToPdfConversionService -  --analytics-- data={"filename":"安全班会.pptx","logCode":"office_to_pdf_failed","meetingId":"46ded18febc26f5c891b033642c4f13585397c49-1611793988242","message":"Failed to convert /var/bigbluebutton/46ded18febc26f5c891b033642c4f13585397c49-1611793988242/46ded18febc26f5c891b033642c4f13585397c49-1611793988242/bada3e4cebecbac03a2651fd483855f2ce7ce9b8-1611794046689/bada3e4cebecbac03a2651fd483855f2ce7ce9b8-1611794046689.pptx to Pdf.","presId":"bada3e4cebecbac03a2651fd483855f2ce7ce9b8-1611794046689"}
