### ISSUE TITLE
BBB 2.3 and ibm-java80-jre - Failed to download presentation in bbb-web.log

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/bigbluebutton#11153]
Hi BBB Devs,
Happy new year !

OK guys, I installed bbb 2.3 on a fresh ubuntu 18.04 lts.
By default, in my situation bbb comes with ibm-java80-jre
and it is a bad thing. I get this kind of error in bbb-web.log
```
021-01-14T17:38:55.732Z ERROR o.b.p.PresentationUrlDownloadService - ExecutionException while saving presentation
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Received fatal alert: protocol_version
        at org.apache.http.concurrent.BasicFuture.getResult(BasicFuture.java:71)
        at org.apache.http.concurrent.BasicFuture.get(BasicFuture.java:84)
        at org.apache.http.impl.nio.client.FutureWrapper.get(FutureWrapper.java:70)
        at org.bigbluebutton.presentation.PresentationUrlDownloadService.savePresentation(PresentationUrlDownloadService.java:245)
        at org.bigbluebutton.presentation.PresentationUrlDownloadService$savePresentation.call(Unknown Source)
        at org.bigbluebutton.web.controllers.ApiController.downloadAndProcessDocument(ApiController.groovy:2152)
        at org.bigbluebutton.web.controllers.ApiController$downloadAndProcessDocument$0.callCurrent(Unknown Source)
...
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:820)
Caused by: javax.net.ssl.SSLException: Received fatal alert: protocol_version
        at com.ibm.jsse2.k.a(k.java:1)
        at com.ibm.jsse2.as.a(as.java:423)
        at com.ibm.jsse2.as.a(as.java:408)
        at com.ibm.jsse2.as.j(as.java:548)
        at com.ibm.jsse2.as.b(as.java:325)
        at com.ibm.jsse2.as.a(as.java:224)
        at com.ibm.jsse2.as.unwrap(as.java:418)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:5)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.doUnwrap(SSLIOSession.java:271)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:316)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:503)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        ... 1 common frames omitted
2021-01-14T17:38:55.736Z ERROR o.b.web.controllers.ApiController - Failed to download presentation=[https://hostname.domain/default.pdf], meeting=[xxxxx], fileName=[]
```
So I decided to help other people.

To correct this problem

```
apt-get install openjdk-8-jre
update-alternatives --config java
```

```
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      auto mode
  1            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode
  2            /usr/lib/jvm/java-ibm-x86_64-80/jre/bin/java     80        manual mode

Press <enter> to keep the current choice[*], or type selection number:
```

I had to select / set 0 in my case.

And now, no more problem with https and TLS 1.2 with java client with the presentation.

I hope it could help.

**Comment by basisbit** [comment]
Sorry, but where did you download your Ubuntu 18.06 install disk / drive image?

**Comment by aguerson** [comment]
@basisbit from OVZ CT ez package

**Comment by antobinary** [comment]
I will be closing this issue. Thank you for reporting what you encountered and how you resolved it.
In 2.4 we aim to switch to JVM 11 https://github.com/bigbluebutton/bigbluebutton/pull/12303
