### ISSUE TITLE
BBB 2.3-Alpha4 - Recordings are not being processed and shown

### ISSUE THREAD

**Issue by AK1912** [bigbluebutton/bigbluebutton#11184]
**Describe the bug**
After Recording a session it is not shown, neither in moodle nor in greenlight.
Please help!

**Actual behavior**

```
astra5203:/var/bigbluebutton/recording/raw# bbb-record --list

Internal MeetingID                                               Time                APVD APVDE RAS Slides Processed            Published           External MeetingID
------------------------------------------------------  ---------------------------- ---- ----- --- ------ -------------------- ------------------  -------------------
90d38e53127bd140f46e7bba4f13f8eb330e745c-1611143283916  Wed Jan 20 12:48:03 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1611142906497  Wed Jan 20 12:41:46 CET 2021  X                 12 
90d38e53127bd140f46e7bba4f13f8eb330e745c-1611142491439  Wed Jan 20 12:34:51 CET 2021  X                 12                                       
90d38e53127bd140f46e7bba4f13f8eb330e745c-1611141782045  Wed Jan 20 12:23:02 CET 2021  X                 12                                       
90d38e53127bd140f46e7bba4f13f8eb330e745c-1611141627851  Wed Jan 20 12:20:27 CET 2021  X                 12                                       
90d38e53127bd140f46e7bba4f13f8eb330e745c-1611141396019  Wed Jan 20 12:16:36 CET 2021  X                 12                                       
90d38e53127bd140f46e7bba4f13f8eb330e745c-1611141173594  Wed Jan 20 12:12:53 CET 2021  X                 12                                       
cc951939815cf831948a21b1cc815fae52a1b34e-1611139041256  Wed Jan 20 11:37:21 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1611138499193  Wed Jan 20 11:28:19 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1611138202182  Wed Jan 20 11:23:22 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1611138050393  Wed Jan 20 11:20:50 CET 2021  X                 12 
8528dda749559373dc4c7354b2aa53231d42da2c-1611134263411  Wed Jan 20 10:17:43 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1611132782379  Wed Jan 20 09:53:02 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1611131972755  Wed Jan 20 09:39:32 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1611131742961  Wed Jan 20 09:35:42 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1611126398799  Wed Jan 20 08:06:38 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1611126055029  Wed Jan 20 08:00:55 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1611124354972  Wed Jan 20 07:32:34 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1611078030035  Tue Jan 19 18:40:30 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1611064791846  Tue Jan 19 14:59:51 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1611064063894  Tue Jan 19 14:47:43 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1611062236648  Tue Jan 19 14:17:16 CET 2021  X                 12                                       
50318008b2abbbd19c072fe998b340ee978a7821-1611062065188  Tue Jan 19 14:14:25 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1611058902485  Tue Jan 19 13:21:42 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1611058670306  Tue Jan 19 13:17:50 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1611057768303  Tue Jan 19 13:02:48 CET 2021  X                 13                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1611051147864  Tue Jan 19 11:12:27 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1611045011076  Tue Jan 19 09:30:11 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1611044914721  Tue Jan 19 09:28:34 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1611040875722  Tue Jan 19 08:21:15 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1611039625464  Tue Jan 19 08:00:25 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1611039307718  Tue Jan 19 07:55:07 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1610989737071  Mon Jan 18 18:08:57 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1610977973639  Mon Jan 18 14:52:53 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1610976924604  Mon Jan 18 14:35:24 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1610975840007  Mon Jan 18 14:17:20 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1610975705469  Mon Jan 18 14:15:05 CET 2021  X                 12                                       
90d38e53127bd140f46e7bba4f13f8eb330e745c-1610975442984  Mon Jan 18 14:10:42 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1610975426768  Mon Jan 18 14:10:26 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1610975285527  Mon Jan 18 14:08:05 CET 2021  X                 12                                       
90d38e53127bd140f46e7bba4f13f8eb330e745c-1610972761706  Mon Jan 18 13:26:01 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1610969202329  Mon Jan 18 12:26:42 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1610967098795  Mon Jan 18 11:51:38 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1610966152907  Mon Jan 18 11:35:52 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1610965801424  Mon Jan 18 11:30:01 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1610964821593  Mon Jan 18 11:13:41 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1610958402234  Mon Jan 18 09:26:42 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1610953309886  Mon Jan 18 08:01:49 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1610953056649  Mon Jan 18 07:57:36 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1610952720859  Mon Jan 18 07:52:00 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1610952400817  Mon Jan 18 07:46:40 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1610892676193  Sun Jan 17 15:11:16 CET 2021  X                 12                                       
6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1610874962322  Sun Jan 17 10:16:02 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1610874757102  Sun Jan 17 10:12:37 CET 2021  X                 12                                       
784fa09a996c6d3e74e1a40561d08e1fe1619fad-1610872981362  Sun Jan 17 09:43:01 CET 2021  X                 12                                       
90d38e53127bd140f46e7bba4f13f8eb330e745c-1610836066513  Sat Jan 16 23:27:46 CET 2021  X                 12                                       
90d38e53127bd140f46e7bba4f13f8eb330e745c-1610834744628  Sat Jan 16 23:05:44 CET 2021  X                 12                                       
90d38e53127bd140f46e7bba4f13f8eb330e745c-1610834024093  Sat Jan 16 22:53:44 CET 2021  X                 12 
90d38e53127bd140f46e7bba4f13f8eb330e745c-1610833379185  Sat Jan 16 22:42:59 CET 2021  X                 12 
17f3ff8820987f3e3293a82df381605f32ae671b-1610833315085  Sat Jan 16 22:41:55 CET 2021  X                 12      
```

```
0 timers listed.
--
● bbb-rap-starter.service - BigBlueButton recording processing starter
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-starter.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-01-20 12:08:32 CET; 47min ago
 Main PID: 29028 (rap-starter.rb)
    Tasks: 2 (limit: 4915)
   CGroup: /bbb_record_core.slice/bbb-rap-starter.service
           └─29028 /usr/bin/ruby /usr/local/bigbluebutton/core/scripts/rap-starter.rb

Jan 20 12:23:26 astra5203 bbb-rap[29028]: Enqueuing job to archive {:meeting_id=>"90d38e53127bd140f46e7bba4f13f8eb330e745c-1611141782045", :break_timestamp=>nil}
Jan 20 12:23:26 astra5203 bbb-rap[29028]: Meeting 90d38e53127bd140f46e7bba4f13f8eb330e745c-1611141782045 had recording enabled, events will be handle…ing archive
Jan 20 12:26:49 astra5203 bbb-rap[29028]: Enqueuing job to archive {:meeting_id=>"90d38e53127bd140f46e7bba4f13f8eb330e745c-1611141782045", :break_timestamp=>nil}
Jan 20 12:35:19 astra5203 bbb-rap[29028]: Enqueuing job to archive {:meeting_id=>"90d38e53127bd140f46e7bba4f13f8eb330e745c-1611142491439", :break_timestamp=>nil}
Jan 20 12:35:19 astra5203 bbb-rap[29028]: Meeting 90d38e53127bd140f46e7bba4f13f8eb330e745c-1611142491439 had recording enabled, events will be handle…ing archive
Jan 20 12:41:25 astra5203 bbb-rap[29028]: Enqueuing job to archive {:meeting_id=>"6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1611138499193", :break_timestamp=>nil}
Jan 20 12:41:25 astra5203 bbb-rap[29028]: Meeting 6d0628adc2b545c5ad5ff8c9575f22dab0a84642-1611138499193 had recording enabled, events will be handle…ing archive
Jan 20 12:48:31 astra5203 bbb-rap[29028]: Enqueuing job to archive {:meeting_id=>"90d38e53127bd140f46e7bba4f13f8eb330e745c-1611143283916", :break_timestamp=>nil}
Jan 20 12:48:31 astra5203 bbb-rap[29028]: Meeting 90d38e53127bd140f46e7bba4f13f8eb330e745c-1611143283916 had recording enabled, events will be handle…ing archive
Jan 20 12:50:01 astra5203 bbb-rap[29028]: Enqueuing job to archive {:meeting_id=>"90d38e53127bd140f46e7bba4f13f8eb330e745c-1611143283916", :break_timestamp=>nil}

● bbb-rap-resque-worker.service - BigBlueButton resque worker for recordings
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-resque-worker.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
Hint: Some lines were ellipsized, use -l to show in full.
--
```

```
astra5203:/var/bigbluebutton/recording/raw# bbb-record -rebuild 90d38e53127bd140f46e7bba4f13f8eb330e745c-1611143283916
Marking for rebuild 90d38e53127bd140f46e7bba4f13f8eb330e745c-1611143283916
astra5203:/var/bigbluebutton/recording/raw# bbb-record -republish 90d38e53127bd140f46e7bba4f13f8eb330e745c-1611143283916
Marking for republish: 90d38e53127bd140f46e7bba4f13f8eb330e745c-1611143283916
Marking for republish 90d38e53127bd140f46e7bba4f13f8eb330e745c-1611143283916
Processed files for 90d38e53127bd140f46e7bba4f13f8eb330e745c-1611143283916 (presentation) do not exist, can't republish
Try rebuilding the recording instead.

```

**Comment by AK1912** [comment]
```
astra5203:~# bbb-record --debug
E, [2021-01-20T12:23:29.903697 #14571] ERROR -- : 
E, [2021-01-20T12:23:29.903764 #14571] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:104:in `each_line'
E, [2021-01-20T12:23:29.903778 #14571] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:104:in `block in execute'
E, [2021-01-20T12:23:29.903786 #14571] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:103:in `popen'
E, [2021-01-20T12:23:29.903794 #14571] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:103:in `execute'
E, [2021-01-20T12:23:29.903802 #14571] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:119:in `exec_ret'
E, [2021-01-20T12:23:29.903810 #14571] ERROR -- : ./rap-process-worker.rb:80:in `block (2 levels) in process_archived_meetings'
E, [2021-01-20T12:23:29.903817 #14571] ERROR -- : ./rap-process-worker.rb:56:in `each'
E, [2021-01-20T12:23:29.903826 #14571] ERROR -- : ./rap-process-worker.rb:56:in `block in process_archived_meetings'
E, [2021-01-20T12:23:29.903833 #14571] ERROR -- : ./rap-process-worker.rb:30:in `each'
E, [2021-01-20T12:23:29.903843 #14571] ERROR -- : ./rap-process-worker.rb:30:in `process_archived_meetings'
E, [2021-01-20T12:23:29.903851 #14571] ERROR -- : ./rap-process-worker.rb:155:in `<main>'

```

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by AK1912** [comment]
In my opinion this is a development related issue. I did a fresh install on two different servers and the same issue occurs on both.
