### ISSUE TITLE
2.3a8 broken install

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton#11673]
Using bbb-install to get latest 2.3 alpha on a fresh system the installation finishes with:

```
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    http://fqdn.server.tld/
#
# If your BigBlueButton server is behind a firewall, see FAQ.
```

The same server was running 2.2.latest before with no issue.

Okay, digging logs i get an error 500 for greenlight.
Looking in the .env shows the safe host is set as ip, also the hostname in the BBB_SERVER value.

Something seems to be broken in the install of alpha 8.

**Comment by ffdixon** [comment]
Hmm ... I've been testing the install and it's working here.  Can you paste the parameters you are using (and change the host/email) and we'll test again.

**Comment by lonesomewalker** [comment]
```
./bbb-install.sh -v bionic-230-dev -s fqdn.server.tld -e some@mail.tld -c fqdn.turnserver.tld:passfromturn -g
```

It is even not working with --setip manually :-|

**Comment by lonesomewalker** [comment]
The setip is showing:
```
+ grep -q SETSCHEDULER
+ '[' '!' -z '' ']'
+ '[' '!' -f /etc/systemd/system/bbb-apps-akka.service.d/override.conf ']'
+ mkdir -p /etc/systemd/system/bbb-apps-akka.service.d
+ cat
+ '[' '!' -f /etc/systemd/system/bbb-fsesl-akka.service.d/override.conf ']'
+ mkdir -p /etc/systemd/system/bbb-fsesl-akka.service.d
+ cat
+ '[' '!' -f /etc/systemd/system/bbb-transcode-akka.service.d/override.conf ']'
+ mkdir -p /etc/systemd/system/bbb-transcode-akka.service.d
+ cat
+ '[' '!' -z fqdn.server.tld ']'
+ bbb-conf --setip fqdn.server.tld
default
Assigning fqdn.server.tld for web application URL in /etc/bigbluebutton/bbb-web.properties
Assigning fqdn.server.tld for web application URL in /etc/bigbluebutton/bbb-apps-akka.conf
Assigning fqdn.server.tld for record and playback in /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml
Assigning fqdn.server.tld for playback of recordings:
Restarting the BigBlueButton 2.3.0-alpha8 ...
Stopping BigBlueButton
Warning: The unit file, source configuration file or drop-ins of bbb-apps-akka.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of bbb-fsesl-akka.service changed on disk. Run 'systemctl daemon-reload' to reload units.

Starting BigBlueButton
Warning: The unit file, source configuration file or drop-ins of bbb-apps-akka.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of bbb-fsesl-akka.service changed on disk. Run 'systemctl daemon-reload' to reload units.
+ systemctl show-environment
+ grep -q UTF-8
+ grep LANG=
+ bbb-conf --check
default

BigBlueButton Server 2.3.0-alpha8 (1799)
                    Kernel version: 4.15.0-135-generic
                      Distribution: Ubuntu 18.04.5 LTS (64-bit)
                            Memory: 132020 MB
                         CPU cores: 24

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: http://fqdn.server.tld
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: fqdn.server.tld
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: XXX.XXX.XXX.XXX
                   external_rtp_ip: XXX.XXX.XXX.XXX
                   external_sip_ip: XXX.XXX.XXX.XXX

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: XXX.XXX.XXX.XXX:5066
                       wss-binding: XXX.XXX.XXX.XXX:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: fqdn.server.tld
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb2~18.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: XXX.XXX.XXX.XXX
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: XXX.XXX.XXX.XXX
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: XXX.XXX.XXX.XXX
                    localIpAddress: XXX.XXX.XXX.XXX
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1482
                        kurentoUrl: wss://fqdn.server.tld/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun: fqdn.turnserver.de


# Potential problems described below

# Warning: No firewall detected.  Recommend using setting up a firewall for your server
#
#     https://docs.bigbluebutton.org/2.2/troubleshooting.html#freeswitch-using-default-stun-server
#

................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    http://fqdn.server.tld/
#
# If your BigBlueButton server is behind a firewall, see FAQ.
```

There are several issues which could be also addressed:
BBB uses HTTPS not http, so the servername should be displayed with https
Also, the help link should direct to 2.3 instead of 2.2 :-)

Any chance to deliver helpfull input for you? :)

**Comment by lonesomewalker** [comment]
Holy ...
Since i didn't find any issues in the logfiles, also the config didn't look strange to any of us technicians i just re-ran bbb-install script.

What should i say: seems to have fixed some things but we don't know what :-/

Nevertheless the above mentioned things with https instead http of the url could be fixed :-)

**Comment by hiroshisuga** [comment]
For http instead of https problem, #11656 might be a solution.

**Comment by lonesomewalker** [comment]
Correct! This was also messed up in this installation.

**Comment by lonesomewalker** [comment]
Again, after testing to upgrade another alpha version, the hostname gets replaced by ip address.

This can't be right.

**Comment by rasos** [comment]
Upgrading from BBB 2.3 alpha5 to alpha8 with `apt upgrade` and `bbb-conf -setip /bbb.domain.tld`  brings similar issue:
```
# Error: Could not connect to the configured hostname/IP address
#
#    http://bbb.domain.tld/
# Warning: Failed to verify STUN server at  3478 with command
```
Applying full install script again made it work.

**Comment by ffdixon** [comment]
Are you downloading the latest version of the `bbb-install.sh` script (via `wget`) when doing the upgrade?

**Comment by hiroshisuga** [comment]
For me this happened when upgrading by apt upgrade. Fixing it is easy, just manually changing http to https of bigbluebutton.web.serverURL in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties. I am pretty sure that this will be fixed in the next release which has already merged #11656.

**Comment by lonesomewalker** [comment]
yup, get's mirrored. Checked it with diff, correct version :-/

Since you are asking this, has there been recently any modifications for the alpha setup?

**Comment by ffdixon** [comment]
Probably the biggest change in 2.3-alpha-8 was the local override files.  We're trying to get away from each package upgrade overwriting user's settings.  See

  https://docs.bigbluebutton.org/dev/dev23.html#local-overrides-for-configuration-settings

**Comment by lonesomewalker** [comment]
Okay, we'll look into this a little bit more...

**Comment by lonesomewalker** [comment]
Can give a little update, starting debugging.

The URL /bigbluebutton/ and also /bigbluebutton/api/ fails on servers with these symptoms.

**Comment by lonesomewalker** [comment]
nginx logfile says:
```
2021/05/14 23:52:41 [error] 12705#12705: *12 connect() failed (111: Connection refused) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: bbb.domain.tld, request: "GET /bigbluebutton/ HTTP/1.1", upstream: "http://127.0.0.1:8090/bigbluebutton/", host: "bbb.domain.tld"
2021/05/14 23:52:41 [error] 12705#12705: *12 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: xxx.xxx.xxx.xxx, server: bbb.domain.tld, request: "GET /bigbluebutton/ HTTP/1.1", upstream: "http://127.0.0.1:8090/bigbluebutton/", host: "bbb.domain.tld"
```

which means, port 8090 is not responding...

This leads to bbb-web, and a netstat shows that there is really nothing listen to 8090.

However:

```systemctl status bbb-web```

says:

```
● bbb-web.service - BigBlueButton Web Application
   Loaded: loaded (/lib/systemd/system/bbb-web.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/bbb-web.service.d
           └─override.conf
   Active: active (running) since Fri 2021-05-14 23:52:10 CEST; 5min ago
 Main PID: 12950 (java)
    Tasks: 92 (limit: 9830)
   CGroup: /system.slice/bbb-web.service
           └─12950 java -Dgrails.env=prod -Dserver.address=127.0.0.1 -Dserver.port=8090 -Xms384m -Xmx384m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/bigbluebutton/diagnostics -cp WEB-INF/lib/*:/:WEB-INF/cl

May 14 23:52:17 bbb run-prod.sh[12950]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1281)
May 14 23:52:17 bbb run-prod.sh[12950]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
May 14 23:52:17 bbb run-prod.sh[12950]:         ... 38 common frames omitted
May 14 23:52:17 bbb run-prod.sh[12950]: Caused by: java.lang.IllegalArgumentException: Invalid boolean value [${authenticatedGuest}]
May 14 23:52:17 bbb run-prod.sh[12950]:         at org.springframework.beans.propertyeditors.CustomBooleanEditor.setAsText(CustomBooleanEditor.java:123)
May 14 23:52:17 bbb run-prod.sh[12950]:         at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:470)
May 14 23:52:17 bbb run-prod.sh[12950]:         at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:443)
May 14 23:52:17 bbb run-prod.sh[12950]:         at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:200)
May 14 23:52:17 bbb run-prod.sh[12950]:         at org.springframework.beans.AbstractNestablePropertyAccessor.convertIfNecessary(AbstractNestablePropertyAccessor.java:588)
May 14 23:52:17 bbb run-prod.sh[12950]:         ... 44 common frames omitted
```

/var/log/bigbluebutton/bbb-web.log says:
```
2021-05-15T00:01:41.922+02:00 INFO  org.bigbluebutton.web.Application - Starting Application on meeting with PID 15159 (/usr/share/bbb-web/WEB-INF/classes started by bigbluebutton in /usr/share/bbb-web)
2021-05-15T00:01:41.926+02:00 DEBUG org.bigbluebutton.web.Application - Running with Spring Boot v1.5.18.RELEASE, Spring v4.3.21.RELEASE
2021-05-15T00:01:41.926+02:00 INFO  org.bigbluebutton.web.Application - The following profiles are active: production
2021-05-15T00:01:43.403+02:00 INFO  o.b.w.services.turn.StunTurnService - Overlay stun/turn server config file /etc/bigbluebutton/turn-stun-servers.xml not found/readable, reading from default config file location
2021-05-15T00:01:46.034+02:00 INFO  o.b.api.HTML5LoadBalancingService - HTML5LoadBalancingService initialised
2021-05-15T00:01:46.044+02:00 INFO  o.b.a.m.ReceivedMessageHandler - Ready to handle messages from Redis pubsub!
2021-05-15T00:01:46.055+02:00 INFO  o.b.c.redis.RedisStorageService - Starting RedisStorageService with client name: clientName=BbbWeb
2021-05-15T00:01:46.602+02:00 INFO  io.lettuce.core.EpollProvider - Starting without optional epoll library
2021-05-15T00:01:46.603+02:00 INFO  io.lettuce.core.KqueueProvider - Starting without optional kqueue library
2021-05-15T00:01:46.700+02:00 INFO  o.b.c.redis.RedisStorageService - Connected to redis. clientName=BbbWeb
2021-05-15T00:01:46.710+02:00 INFO  o.b.c.redis.RedisStorageService - Connected to redis activated. clientName=BbbWeb
2021-05-15T00:01:47.354+02:00 INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
2021-05-15T00:01:47.445+02:00 INFO  o.b.c.redis.RedisStorageService - Starting RedisStorageService with client name: clientName=BbbWebRedisStore
2021-05-15T00:01:47.452+02:00 INFO  o.b.c.redis.RedisStorageService - Connected to redis. clientName=BbbWebRedisStore
2021-05-15T00:01:47.453+02:00 INFO  o.b.c.redis.RedisStorageService - Connected to redis activated. clientName=BbbWebRedisStore
2021-05-15T00:01:47.503+02:00 INFO  o.b.common2.redis.RedisPublisher - Connected to redis. clientName=BbbWebPub
2021-05-15T00:01:47.504+02:00 INFO  o.b.common2.redis.RedisPublisher - Connection to redis activated. clientName=BbbWebPub
2021-05-15T00:01:47.507+02:00 INFO  o.b.common2.redis.RedisPublisher - Connected to redis. clientName=BbbWebPub
2021-05-15T00:01:47.508+02:00 INFO  o.b.common2.redis.RedisPublisher - Connection to redis activated. clientName=BbbWebPub
2021-05-15T00:01:47.511+02:00 DEBUG o.b.api2.bus.MessageSenderActor - started (org.bigbluebutton.api2.bus.MessageSenderActor@706fae39)
2021-05-15T00:01:47.516+02:00 DEBUG o.b.a.m.OldMeetingMsgHdlrActor - started (org.bigbluebutton.api2.meeting.OldMeetingMsgHdlrActor@48fc9c47)
2021-05-15T00:01:47.524+02:00 DEBUG o.b.a.bus.MsgToAkkaAppsToJsonActor - started (org.bigbluebutton.api2.bus.MsgToAkkaAppsToJsonActor@150b5d47)
2021-05-15T00:01:47.532+02:00 DEBUG o.b.a.b.OldMessageJsonReceiverActor - started (org.bigbluebutton.api2.bus.OldMessageJsonReceiverActor@348258a4)
2021-05-15T00:01:47.536+02:00 DEBUG o.b.a.bus.ReceivedJsonMsgHdlrActor - started (org.bigbluebutton.api2.bus.ReceivedJsonMsgHdlrActor@5c957d02)
2021-05-15T00:01:47.551+02:00 INFO  o.b.a.e.r.WebRedisSubscriberActor - Connected to redis. clientName=BbbWebSub
2021-05-15T00:01:47.552+02:00 INFO  o.b.a.e.r.WebRedisSubscriberActor - Connection to redis activated. clientName=BbbWebSub
2021-05-15T00:01:47.557+02:00 DEBUG o.b.a.e.r.WebRedisSubscriberActor - started (org.bigbluebutton.api2.endpoint.redis.WebRedisSubscriberActor@25ed1233)
2021-05-15T00:01:47.562+02:00 INFO  o.b.p.i.PresentationConversionCompletionService - Ready to process presentation files!
2021-05-15T00:01:47.564+02:00 INFO  o.b.a.e.r.WebRedisSubscriberActor - Subscribed to pattern from-akka-apps-redis-channel
2021-05-15T00:01:47.618+02:00 INFO  o.b.c.redis.RedisStorageService - RedisStorageService Stopped
2021-05-15T00:01:47.648+02:00 ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'meetingService' defined in class path resource [spring/resources.xml]: Cannot resolve reference to bean 'paramsProcessorUtil' while setting bean property 'paramsProcessorUtil'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'paramsProcessorUtil' defined in class path resource [spring/resources.xml]: Initialization of bean failed; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Boolean' for property 'authenticatedGuest'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value [${authenticatedGuest}]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1534)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1281)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:84)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:393)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:380)
	at grails.boot.GrailsApp$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at org.bigbluebutton.web.Application.main(Application.groovy:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'paramsProcessorUtil' defined in class path resource [spring/resources.xml]: Initialization of bean failed; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Boolean' for property 'authenticatedGuest'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value [${authenticatedGuest}]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 32 common frames omitted
Caused by: org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Boolean' for property 'authenticatedGuest'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value [${authenticatedGuest}]
	at org.springframework.beans.AbstractNestablePropertyAccessor.convertIfNecessary(AbstractNestablePropertyAccessor.java:608)
	at org.springframework.beans.AbstractNestablePropertyAccessor.convertForProperty(AbstractNestablePropertyAccessor.java:615)
	at org.springframework.beans.BeanWrapperImpl.convertForProperty(BeanWrapperImpl.java:216)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.convertForProperty(AbstractAutowireCapableBeanFactory.java:1580)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1281)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
	... 38 common frames omitted
Caused by: java.lang.IllegalArgumentException: Invalid boolean value [${authenticatedGuest}]
	at org.springframework.beans.propertyeditors.CustomBooleanEditor.setAsText(CustomBooleanEditor.java:123)
	at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:470)
	at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:443)
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:200)
	at org.springframework.beans.AbstractNestablePropertyAccessor.convertIfNecessary(AbstractNestablePropertyAccessor.java:588)
	... 44 common frames omitted
```

which made me suspicious about ```Caused by: java.lang.IllegalArgumentException: Invalid boolean value [${authenticatedGuest}]```

Which finally leads to a missing parameter in bigbluebutton.properties.

So, in this case on a fresh 2.3.1 server i was able to solve that.
If anybody else has that issue, feel free to debug some missing parts yourself, this is a quick how-to for that ;-)

**Comment by antobinary** [comment]
@lonesomewalker looks like you were able to spot the issue in your latest comment. Nice! Thanks also for the detailed info on how you were able to debug this!

I will be closing this issue since we've had quite a few releases on 2.3.x since and from what I can tell this has not happened since. Please comment here if there's still an issue to look into and we can reopen.
