### ISSUE TITLE
2.3-beta-2: Sanity worker failed if no recording marks

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#11877]
**Describe the bug**
The recording processing in 2.3-beta-2 is throwing errors when encountering a recording with no start/stop recording marks..

**To Reproduce**
1. Open a browser and open the API demo demo10.jsp
2. Start a recorded meeting
3. Wait a few seconds, then end the meeting
4. The error appears in `bbb-record --watch` 

**Expected behavior**
No error.

**Actual behavior**
The following error occurs

```
# journalctl -u bbb-rap-resque-worker.service

Apr 04 11:16:02 droplet-9663 systemd[1]: Started BigBlueButton resque worker for recordings.
Apr 04 11:16:02 droplet-9663 sh[12915]: (in /usr/local/bigbluebutton/core)
Apr 04 11:19:18 droplet-9663 bbb-rap[15877]: Started worker archive for 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617535136163
Apr 04 11:19:18 droplet-9663 bbb-rap[15877]: Running archive worker for 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617535136163
Apr 04 11:19:18 droplet-9663 bbb-rap[15877]: Executing: ruby /usr/local/bigbluebutton/core/scripts/archive/archive.rb -m 6e35e3b2778883f5db637d7a5dba0a427f692e91-161
Apr 04 11:19:19 droplet-9663 bbb-rap[15877]: Success?: true
Apr 04 11:19:19 droplet-9663 bbb-rap[15877]: Process exited? true
Apr 04 11:19:19 droplet-9663 bbb-rap[15877]: Exit status: 0
Apr 04 11:19:19 droplet-9663 bbb-rap[15877]: Task: Getting external meeting id
Apr 04 11:19:19 droplet-9663 bbb-rap[15877]: Task: Getting meeting metadata
Apr 04 11:19:19 droplet-9663 bbb-rap[15877]: Task: Getting external meeting id
Apr 04 11:19:19 droplet-9663 bbb-rap[15877]: Task: Getting meeting metadata
Apr 04 11:19:19 droplet-9663 bbb-rap[15877]: Successfully archived 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617535136163
Apr 04 11:19:19 droplet-9663 bbb-rap[15877]: Ended worker archive for 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617535136163 with result true
Apr 04 11:19:19 droplet-9663 bbb-rap[15877]: Scheduling next step for archive
Apr 04 11:19:19 droplet-9663 bbb-rap[15877]: Enqueueing sanity worker with {:meeting_id=>"6e35e3b2778883f5db637d7a5dba0a427f692e91-1617535136163", :single_step=>fals
Apr 04 11:19:19 droplet-9663 bbb-rap[15877]: done: (Job{rap:archive} | BigBlueButton::Resque::ArchiveWorker | [{"meeting_id"=>"6e35e3b2778883f5db637d7a5dba0a427f692e
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: Started worker sanity for 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617535136163
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: Running sanity worker for 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617535136163
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: Task: Getting external meeting id
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: Task: Getting meeting metadata
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: Executing: ruby /usr/local/bigbluebutton/core/scripts/sanity/sanity.rb -m 6e35e3b2778883f5db637d7a5dba0a427f692e91-16175
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: ruby: warning: shebang line ending with \r may cause problems
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: Success?: true
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: Process exited? true
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: Exit status: 0
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: Task: Getting external meeting id
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: Task: Getting meeting metadata
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: Successfully sanity checked 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617535136163
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: Ended worker sanity for 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617535136163 with result false
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: Worker sanity for 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617535136163 failed with result false
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/local/bigbluebutton/core/lib/recordandplayback/workers/base_worker.rb:45:in `perform'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/local/bigbluebutton/core/lib/recordandplayback/workers/sanity_worker.rb:26:in `perform'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/local/bigbluebutton/core/lib/recordandplayback/workers/base_worker.rb:33:in `perform'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/job.rb:168:in `perform'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:308:in `perform'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:897:in `block in perform_with_fork'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:895:in `fork'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:895:in `perform_with_fork'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:264:in `work_one_job'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:238:in `block in work'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:235:in `loop'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:235:in `work'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/tasks.rb:20:in `block (2 levels) in <top (required)>'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `block in execute'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `each'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `execute'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/lib/ruby/vendor_ruby/rake/task.rb:213:in `block in invoke_with_call_chain'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/lib/ruby/vendor_ruby/rake/task.rb:193:in `invoke_with_call_chain'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/lib/ruby/vendor_ruby/rake/task.rb:182:in `invoke'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `invoke_task'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block (2 levels) in top_level'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `each'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block in top_level'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/lib/ruby/vendor_ruby/rake/application.rb:125:in `run_with_threads'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/lib/ruby/vendor_ruby/rake/application.rb:110:in `top_level'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/lib/ruby/vendor_ruby/rake/application.rb:83:in `block in run'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/lib/ruby/vendor_ruby/rake/application.rb:186:in `standard_exception_handling'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/lib/ruby/vendor_ruby/rake/application.rb:80:in `run'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: /usr/bin/rake:27:in `<main>'
Apr 04 11:19:19 droplet-9663 bbb-rap[15969]: (Job{rap:sanity} | BigBlueButton::Resque::SanityWorker | [{"meeting_id"=>"6e35e3b2778883f5db637d7a5dba0a427f692e91-16175

```

**Additional context**

**Comment by ffdixon** [comment]
Reported [here](https://groups.google.com/g/bigbluebutton-setup/c/dPK2-JRBhOM/m/q5tdCQ7yCQAJ) in bigbluebutton-setup.

**Comment by kepstin** [comment]
Do you have the sanity log output for this recording?

**Comment by ffdixon** [comment]
I did so and could not find any log for sanity worker.

```
# locate 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952 | grep log
/var/log/bigbluebutton/archive-6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952.log
```

You'll need to test this yourself on the latest build.  Looks like the sanity test returned `true`.

```
Apr 06 11:15:49 test-b3 bbb-rap[17105]: Started worker archive for 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952
Apr 06 11:15:49 test-b3 bbb-rap[17105]: Running archive worker for 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952
Apr 06 11:15:49 test-b3 bbb-rap[17105]: Executing: ruby /usr/local/bigbluebutton/core/scripts/archive/archive.rb -m 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952
Apr 06 11:15:50 test-b3 bbb-rap[17105]: Success?: true
Apr 06 11:15:50 test-b3 bbb-rap[17105]: Process exited? true
Apr 06 11:15:50 test-b3 bbb-rap[17105]: Exit status: 0
Apr 06 11:15:50 test-b3 bbb-rap[17105]: Task: Getting external meeting id
Apr 06 11:15:50 test-b3 bbb-rap[17105]: Task: Getting meeting metadata
Apr 06 11:15:50 test-b3 bbb-rap[17105]: Task: Getting external meeting id
Apr 06 11:15:50 test-b3 bbb-rap[17105]: Task: Getting meeting metadata
Apr 06 11:15:50 test-b3 bbb-rap[17105]: Successfully archived 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952
Apr 06 11:15:50 test-b3 bbb-rap[17105]: Ended worker archive for 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952 with result true
Apr 06 11:15:50 test-b3 bbb-rap[17105]: Scheduling next step for archive
Apr 06 11:15:50 test-b3 bbb-rap[17105]: Enqueueing sanity worker with {:meeting_id=>"6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952", :single_step=>false}
Apr 06 11:15:50 test-b3 bbb-rap[17105]: Pruning dead worker: test-b3:30058:rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
Apr 06 11:15:50 test-b3 bbb-rap[17105]: Pruning dead worker: test-b3:8108:rap:archive,rap:publish,rap:process,rap:sanity,rap:captions
Apr 06 11:15:50 test-b3 bbb-rap[17105]: done: (Job{rap:archive} | BigBlueButton::Resque::ArchiveWorker | [{"meeting_id"=>"6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952", "break_timestamp"=>nil}])
Apr 06 11:15:50 test-b3 bbb-rap[17140]: Started worker sanity for 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952
Apr 06 11:15:50 test-b3 bbb-rap[17140]: Running sanity worker for 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952
Apr 06 11:15:50 test-b3 bbb-rap[17140]: Task: Getting external meeting id
Apr 06 11:15:50 test-b3 bbb-rap[17140]: Task: Getting meeting metadata
Apr 06 11:15:50 test-b3 bbb-rap[17140]: Executing: ruby /usr/local/bigbluebutton/core/scripts/sanity/sanity.rb -m 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952
Apr 06 11:15:50 test-b3 bbb-rap[17140]: ruby: warning: shebang line ending with \r may cause problems
Apr 06 11:15:50 test-b3 bbb-rap[17140]: Success?: true
Apr 06 11:15:50 test-b3 bbb-rap[17140]: Process exited? true
Apr 06 11:15:50 test-b3 bbb-rap[17140]: Exit status: 0
Apr 06 11:15:50 test-b3 bbb-rap[17140]: Task: Getting external meeting id
Apr 06 11:15:50 test-b3 bbb-rap[17140]: Task: Getting meeting metadata
Apr 06 11:15:50 test-b3 bbb-rap[17140]: Successfully sanity checked 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952
Apr 06 11:15:50 test-b3 bbb-rap[17140]: Ended worker sanity for 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952 with result false
Apr 06 11:15:50 test-b3 bbb-rap[17140]: Worker sanity for 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952 failed with result false
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/local/bigbluebutton/core/lib/recordandplayback/workers/base_worker.rb:45:in `perform'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/local/bigbluebutton/core/lib/recordandplayback/workers/sanity_worker.rb:26:in `perform'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/local/bigbluebutton/core/lib/recordandplayback/workers/base_worker.rb:33:in `perform'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/job.rb:168:in `perform'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:308:in `perform'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:897:in `block in perform_with_fork'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:895:in `fork'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:895:in `perform_with_fork'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:264:in `work_one_job'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:238:in `block in work'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:235:in `loop'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:235:in `work'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/tasks.rb:20:in `block (2 levels) in <top (required)>'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `block in execute'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `each'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `execute'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/lib/ruby/vendor_ruby/rake/task.rb:213:in `block in invoke_with_call_chain'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/lib/ruby/vendor_ruby/rake/task.rb:193:in `invoke_with_call_chain'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/lib/ruby/vendor_ruby/rake/task.rb:182:in `invoke'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `invoke_task'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block (2 levels) in top_level'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `each'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block in top_level'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/lib/ruby/vendor_ruby/rake/application.rb:125:in `run_with_threads'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/lib/ruby/vendor_ruby/rake/application.rb:110:in `top_level'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/lib/ruby/vendor_ruby/rake/application.rb:83:in `block in run'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/lib/ruby/vendor_ruby/rake/application.rb:186:in `standard_exception_handling'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/lib/ruby/vendor_ruby/rake/application.rb:80:in `run'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: /usr/bin/rake:27:in `<main>'
Apr 06 11:15:50 test-b3 bbb-rap[17140]: (Job{rap:sanity} | BigBlueButton::Resque::SanityWorker | [{"meeting_id"=>"6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952", "single_step"=>false}]) failed: #<RuntimeError: Worker sanity for 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952 failed with result false>
```

**Comment by kepstin** [comment]
Sanity log is not per recording, there's a single log file `/var/log/bigbluebutton/sanity.log`

**Comment by ffdixon** [comment]
I still had the server running

```
# cat /var/log/bigbluebutton/sanity.log
# Logfile created on 2021-04-06 11:15:50 +0000 by logger.rb/61378
I, [2021-04-06T11:15:50.848873 #17143]  INFO -- : Starting sanity check for recording 6e35e3b2778883f5db637d7a5dba0a427f692e91-1617707727952
I, [2021-04-06T11:15:50.848903 #17143]  INFO -- : Checking events.xml
I, [2021-04-06T11:15:50.849265 #17143]  INFO -- : Repairing webcam videos
I, [2021-04-06T11:15:50.849304 #17143]  INFO -- : Repairing red5 serialized streams
I, [2021-04-06T11:15:50.849347 #17143]  INFO -- : Repairing deskshare videos
I, [2021-04-06T11:15:50.849367 #17143]  INFO -- : Repairing red5 serialized streams
I, [2021-04-06T11:15:50.849392 #17143]  INFO -- : Deleting keys
I, [2021-04-06T11:15:50.850899 #17143]  INFO -- : creating sanity done files
```

**Comment by kepstin** [comment]
So, after looking into the issue on this server, there are actually two separate problems:

1. Meetings with no recording marks shouldn't be processed, but are getting processed anyways.
2. The sanity check is returning an unexpected return code on recordings without recording marks.

I'm gonna need some help from @prlanzarin and folks who wrote the new queue system to figure out how to fix the first problem.

**Comment by pedrobmarin** [comment]
@kepstin I remember in the past touching something similar to 1. I made this change back then https://github.com/bigbluebutton/bigbluebutton/commit/44fc68c07cf3cc12253758b671e9b3d4d7125535#diff-bc1591fd8d430b953f5035291ed43e983457eb6c85ac6e54d6bdab6a5720f7b1

**Comment by kepstin** [comment]
@pedrobmarin that looks like it's in the wrong spot - the '.norecord' file is written by the archive script, so it should be checked for after the archive script runs, and block the sanity script from running.

**Comment by kepstin** [comment]
So it looks like the main here is that we're stopping the processing in the 'norecord' case by having the worker job fail, which causes some nasty error messages in the logs, and if someone's monitoring the resque failed jobs, they'll get a report there.

We need to be able to 'break' the recording processing in the norecord case such that it doesn't continue to the next job - but without causing a failed job to be reported.

We also need a way to manually trigger processing of a 'norecord' meeting.

**Comment by pedrobmarin** [comment]
It might be, but it's odd that such a common scenario only produced an erroneous state just now.

I'm trying to remember why I picked sanity and I think I just followed the post_archive logic.
