### ISSUE TITLE
OutOfMemory error

### ISSUE THREAD

**Issue by rmorenocampos** [bigbluebutton/bigbluebutton#12020]
**Describe the bug**
 bb-transcode-akka, bb-fsl-akka, red5 are closed by an OutofMemoryError in a random way, there are times when the server works normally and others not, seeing the memory status it is not even at 25% use

**To Reproduce**
I cant told to you how to reproduce it

**Expected behavior**

Access the rooms without problems
**Actual behavior**
We can login through greenlight, when those services begin to fail, we cannot access the created room or we simply cannot connect to the echo server, restarting these services

**Screenshots**
```
2021-04-14T12:10:07.368+02:00 INFO  o.b.f.v.f.a.CheckFreeswitchStatusCommand - ["UP 0 years, 0 days, 0 hours, 16 minutes, 1 second, 164 milliseconds, 910 microseconds","FreeSWITCH (Version 1.10.4-release git 133fc2c 2020-08-05 11:01:19Z 64bit) is ready","8 session(s) since startup","3 session(s) - peak 6, last 5min 3 ","0 session(s) per Sec out of max 30, peak 1, last 5min 0 ","1000 session(s) max","min idle cpu 0.00/92.93","Current Stack Size/Max 244K/244K"]
2021-04-14T12:10:32.673+02:00 ERROR akka.actor.ActorSystemImpl - exception on LARS’ timer thread
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1486)
	at java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1517)
	at java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1634)
	at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2414)
	at java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2648)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:24)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:328)
	at akka.actor.LightArrayRevolverScheduler$$anon$3.executeBucket$1(LightArrayRevolverScheduler.scala:279)
	at akka.actor.LightArrayRevolverScheduler$$anon$3.nextTick(LightArrayRevolverScheduler.scala:283)
	at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:235)
	at java.lang.Thread.run(Thread.java:748)
2021-04-14T12:10:32.674+02:00 INFO  akka.actor.ActorSystemImpl - starting new LARS thread
2021-04-14T12:10:32.674+02:00 ERROR akka.actor.ActorSystemImpl - LARS cannot start new thread, ship’s going down!
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:243)
	at java.lang.Thread.run(Thread.java:748)
2021-04-14T12:10:32.684+02:00 ERROR akka.actor.ActorSystemImpl - Uncaught error from thread [bigbluebutton-fsesl-system-scheduler-1]: unable to create new native thread, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[bigbluebutton-fsesl-system]
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1486)
	at java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1517)
	at java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1634)
	at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2414)
	at java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2648)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:24)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:328)
	at akka.actor.LightArrayRevolverScheduler$$anon$3.executeBucket$1(LightArrayRevolverScheduler.scala:279)
	at akka.actor.LightArrayRevolverScheduler$$anon$3.nextTick(LightArrayRevolverScheduler.scala:283)
	at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:235)
	at java.lang.Thread.run(Thread.java:748)
```

Error message from journalctl from bbb-fsel-akka 
```
abr 14 12:52:41 h2931082.stratoserver.net systemd[1]: bbb-fsesl-akka.service: Main process exited, code=exited, status=255/n/a
abr 14 12:52:41 h2931082.stratoserver.net systemd[1]: bbb-fsesl-akka.service: Unit entered failed state.
abr 14 12:52:41 h2931082.stratoserver.net systemd[1]: bbb-fsesl-akka.service: Failed with result 'exit-code'.
lines 300-324/324 (END)
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:24)
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverSched
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at akka.actor.LightArrayRevolverScheduler$$anon$3.executeBucket$1(LightArrayRevolverSche
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at akka.actor.LightArrayRevolverScheduler$$anon$3.nextTick(LightArrayRevolverScheduler.s
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at java.lang.Thread.run(Thread.java:748)
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]: 2021-04-14T12:52:41.210+02:00 ERROR akka.actor.ActorSystemImpl - exception on LARS’ timer thread
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]: java.lang.OutOfMemoryError: unable to create new native thread
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at java.lang.Thread.start0(Native Method)
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at java.lang.Thread.start(Thread.java:717)
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1486)
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1517)
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1634)
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2414)
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2648)
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:24)
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverSched
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at akka.actor.LightArrayRevolverScheduler$$anon$3.executeBucket$1(LightArrayRevolverSche
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at akka.actor.LightArrayRevolverScheduler$$anon$3.nextTick(LightArrayRevolverScheduler.s
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]:         at java.lang.Thread.run(Thread.java:748)
abr 14 12:52:41 h2931082.stratoserver.net bbb-fsesl-akka[2614]: 2021-04-14T12:52:41.226+02:00 INFO  akka.actor.ActorSystemImpl - starting new LARS thread
```

Stack trace from bbb-apps-akka

```
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]: 2021-04-14T12:53:52.124+02:00 INFO  akka.actor.ActorSystemImpl - starting new LARS thread
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]: Uncaught error from thread [bigbluebutton-apps-system-scheduler-1]: unable to create new native t
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]: java.lang.OutOfMemoryError: unable to create new native thread
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]:         at java.lang.Thread.start0(Native Method)
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]:         at java.lang.Thread.start(Thread.java:717)
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]:         at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1486)
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]:         at java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1517)
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]:         at java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1634)
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]:         at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2414)
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]:         at java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2648)
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]:         at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:24)
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]:         at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverSchedu
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]:         at akka.actor.LightArrayRevolverScheduler$$anon$3.executeBucket$1(LightArrayRevolverSched
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]:         at akka.actor.LightArrayRevolverScheduler$$anon$3.nextTick(LightArrayRevolverScheduler.sc
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]:         at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:2
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]:         at java.lang.Thread.run(Thread.java:748)
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]: 2021-04-14T12:53:52.133+02:00 ERROR akka.actor.ActorSystemImpl - LARS cannot start new thread, sh
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]: java.lang.OutOfMemoryError: unable to create new native thread
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]:         at java.lang.Thread.start0(Native Method)
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]:         at java.lang.Thread.start(Thread.java:717)
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]:         at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:2
abr 14 12:53:52 h2931082.stratoserver.net bbb-apps-akka[4407]:         at java.lang.Thread.run(Thread.java:748)
abr 14 12:53:52 h2931082.stratoserver.net systemd[1]: bbb-apps-akka.service: Main process exited, code=exited, status=255/n/a
abr 14 12:53:52 h2931082.stratoserver.net systemd[1]: bbb-apps-akka.service: Unit entered failed state.
abr 14 12:53:52 h2931082.stratoserver.net systemd[1]: bbb-apps-akka.service: Failed with result 'exit-code'.
```

bbb-transcode-akka stack trace from systemd

```
abr 14 13:05:53 h2931082.stratoserver.net bbb-transcode-akka[9380]: 13:05:53,875 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - This appender no longe
lines 233-281/307 91%
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at akka.actor.LightArrayRevolverScheduler$$anon$3.executeBucket$1(LightArrayRevolverScheduler
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at akka.actor.LightArrayRevolverScheduler$$anon$3.nextTick(LightArrayRevolverScheduler.scala:
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:235)
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at java.lang.Thread.run(Thread.java:748)
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]: 2021-04-14T13:04:50.583+02:00 INFO  akka.actor.ActorSystemImpl - starting new LARS thread
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]: 2021-04-14T13:04:50.589+02:00 ERROR akka.actor.ActorSystemImpl - LARS cannot start new thread, ship’s
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]: java.lang.OutOfMemoryError: unable to create new native thread
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at java.lang.Thread.start0(Native Method)
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at java.lang.Thread.start(Thread.java:717)
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:243)
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at java.lang.Thread.run(Thread.java:748)
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]: Uncaught error from thread [bigbluebutton-transcode-system-scheduler-1]: unable to create new native 
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]: java.lang.OutOfMemoryError: unable to create new native thread
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at java.lang.Thread.start0(Native Method)
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at java.lang.Thread.start(Thread.java:717)
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1486)
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1517)
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1634)
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at java.util.concurrent.ForkJoinPool.externalSubmit(ForkJoinPool.java:2367)
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2419)
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2648)
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:24)
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at akka.actor.LightArrayRevolverScheduler$$anon$3.executeBucket$1(LightArrayRevolverScheduler
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at akka.actor.LightArrayRevolverScheduler$$anon$3.nextTick(LightArrayRevolverScheduler.scala:
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:235)
abr 14 13:04:50 h2931082.stratoserver.net bbb-transcode-akka[8020]:         at java.lang.Thread.run(Thread.java:748)
abr 14 13:04:50 h2931082.stratoserver.net systemd[1]: bbb-transcode-akka.service: Main process exited, code=exited, status=255/n/a
abr 14 13:04:50 h2931082.stratoserver.net systemd[1]: bbb-transcode-akka.service: Unit entered failed state.
abr 14 13:04:50 h2931082.stratoserver.net systemd[1]: bbb-transcode-akka.service: Failed with result 'exit-code'.
```

**Additional context**
The machine has 4 cores and 8Gb of ram in cloud.

**Comment by pedrobmarin** [comment]
Hi @rmorenocampos ,

How much swap space you have configured on that machine? Another point that is interesting to mention is that BigBlueButton +v2.2 does not need bbb-akka-transcode nor red5 running as a service. v2.3 already removed them but if you believe they might be consuming too much from your setup you can turn them down.

**Comment by rmorenocampos** [comment]
@pedrobmarin 

Right now i have no swap space configured inside it. I'm going to try with the v2.3 in ubuntu 18.04, thank you
