### ISSUE TITLE
Meteor process fails on addConnectionStatus

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/bigbluebutton#12206]
**Describe the bug**
I just had an event affecting multiple nodes where all users simultaneously lost their connections at the same time. While that was most likely caused by a network issue, the bbb-html5 log showed the following error at the same time:

```
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]: Exception while invoking method 'addConnectionStatus' Error: Match error: Expected string, got undefined
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at check (packages/check/match.js:36:17)
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at MethodInvocation.addConnectionStatus (imports/api/connection-status/server/methods/addConnectionStatus.js:44:3)
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at packages/ddp-server/livedata_server.js:719:19
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at packages/ddp-server/livedata_server.js:717:46
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at packages/ddp-server/livedata_server.js:715:46
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at new Promise (<anonymous>)
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at packages/ddp-server/livedata_server.js:559:43
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]: Sanitized and reported to the client as: errorClass [Error]: Match failed [400]
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at errorClass.<anonymous> (packages/check/match.js:91:27)
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at new errorClass (packages/meteor.js:655:17)
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at check (packages/check/match.js:36:17)
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at MethodInvocation.addConnectionStatus (imports/api/connection-status/server/methods/addConnectionStatus.js:44:3)
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at packages/ddp-server/livedata_server.js:719:19
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at packages/ddp-server/livedata_server.js:717:46
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at packages/ddp-server/livedata_server.js:715:46
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at new Promise (<anonymous>)
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:     at packages/ddp-server/livedata_server.js:559:43 {
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:   isClientSafe: true,
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:   error: 400,
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:   reason: 'Match failed',
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:   details: undefined,
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:   message: 'Match failed [400]',
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]:   errorType: 'Meteor.Error'
Apr 29 13:40:57 <HOST> systemd_start_frontend.sh[55328]: }
```

**To Reproduce**
1. Unclear how to reproduce.

**Expected behavior**
Meteor exception correctly caught.

**Actual behavior**
Meteor errors out.

**Additional context**
Nodes run 2.3-RC2.

**Comment by antobinary** [comment]
This is most likely benign, not able to obtain meetingId or requesterId from the connection, but it's still good to look into. Thanks for reporting!

**Comment by ichdasich** [comment]
Heho,
yes, the system also seems to have been resillient against the error, i.e., operations continued normally; so this does not sound like some high prio thing. :-)
