### ISSUE TITLE
[2.3-alpha7, alpha8] Presentation Fails To Load/Possible 408/Loss of Presenter Rights

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#12387]
Very hard to re-create, you need to get this run condition, can take around 30 tries. Helps to use greenlight and end/start presentations quickly. Using WiFi is also easier to re-create this issue.

As attached below, the presentation fails to show and also the public chat icon will be missing.

Could be related to https://github.com/bigbluebutton/bigbluebutton/commit/eb601eef3e01671b6bfccbe8120d628fd3eaf89c
This commit landed in beta 1.
Cannot test because no beta packages available.
If someone can share bbb-apps-akka beta 1 package I can test.

![example](https://user-images.githubusercontent.com/970364/118398267-ce722680-b692-11eb-8f6f-4ab2e61702f7.png)

Upgrading to newer versions is not possible at this time because of UI changes from beta 2 onwards such as network indicator etc.

Reproducible on all browsers.

Logs:

```
sudo journalctl -fu bbb-html5-*

May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: User 'w_xfqu49jecvev' is trying to validate auth token for meeting '247998260ba93c7573ad9cb308d475383704a7b1-1621167841461' from connection 'g5qb8Jxzwh8tpipv5'
May 16 12:24:02 server systemd_start.sh[23433]: info: PendingAuths length [0]
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: PendingAuths length [1]
May 16 12:24:02 server systemd_start_frontend.sh[23476]: info: PendingAuths length [0]
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: Upserted {"meetingId":"247998260ba93c7573ad9cb308d475383704a7b1-1621167841461","userId":"w_xfqu49jecvev","connectionId":"g5qb8Jxzwh8tpipv5"} 2 in AuthTokenValidation
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: Created dummy user id=w_xfqu49jecvev token=1pt2qxtrtpuz meeting=247998260ba93c7573ad9cb308d475383704a7b1-1621167841461
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: Client connections add called {"logCode":"client_connections_add","extraInfo":{"sessionId":"247998260ba93c7573ad9cb308d475383704a7b1-1621167841461--w_xfqu49jecvev","connection":{"id":"g5qb8Jxzwh8tpipv5","clientAddress":"127.0.0.1","httpHeaders":{"host":"poolhtml5servers","user-agent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0","accept-language":"en-GB,en;q=0.5"}}}}
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: Meeting not found in connections: meetingId=247998260ba93c7573ad9cb308d475383704a7b1-1621167841461
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: Creating meeting in connections. meetingId=247998260ba93c7573ad9cb308d475383704a7b1-1621167841461
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: Adding new connection for sessionId=247998260ba93c7573ad9cb308d475383704a7b1-1621167841461--w_xfqu49jecvev connection=g5qb8Jxzwh8tpipv5
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: Creating connections poll for w_xfqu49jecvev
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: User= {"_id":"ZKrra5bYQQWssNsbJ","meetingId":"247998260ba93c7573ad9cb308d475383704a7b1-1621167841461","userId":"w_xfqu49jecvev","authToken":"1pt2qxtrtpuz","clientType":"HTML5","validated":null}
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: User='w_xfqu49jecvev' is joining meeting='247998260ba93c7573ad9cb308d475383704a7b1-1621167841461' authToken='1pt2qxtrtpuz'
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: Upserted {"meetingId":"247998260ba93c7573ad9cb308d475383704a7b1-1621167841461","userId":"w_xfqu49jecvev","connectionId":"g5qb8Jxzwh8tpipv5"} 3 in AuthTokenValidation
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: Validated auth token as true user=w_xfqu49jecvev meeting=247998260ba93c7573ad9cb308d475383704a7b1-1621167841461
May 16 12:24:02 server systemd_start.sh[23433]: info: Add voice user=w_xfqu49jecvev meeting=247998260ba93c7573ad9cb308d475383704a7b1-1621167841461
May 16 12:24:02 server systemd_start.sh[23433]: info: Upserted user id=w_xfqu49jecvev meeting=247998260ba93c7573ad9cb308d475383704a7b1-1621167841461
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: User 'w_xfqu49jecvev' is trying to validate auth token for meeting '247998260ba93c7573ad9cb308d475383704a7b1-1621167841461' from connection 'g5qb8Jxzwh8tpipv5'
May 16 12:24:02 server systemd_start_frontend.sh[23476]: info: PendingAuths length [0]
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: PendingAuths length [1]
May 16 12:24:02 server systemd_start.sh[23433]: info: Changed presenter=true id=w_xfqu49jecvev meeting=247998260ba93c7573ad9cb308d475383704a7b1-1621167841461 changedBy=w_xfqu49jecvev
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: Upserted {"meetingId":"247998260ba93c7573ad9cb308d475383704a7b1-1621167841461","userId":"w_xfqu49jecvev","connectionId":"g5qb8Jxzwh8tpipv5"} 2 in AuthTokenValidation
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: Client connections add called {"logCode":"client_connections_add","extraInfo":{"sessionId":"247998260ba93c7573ad9cb308d475383704a7b1-1621167841461--w_xfqu49jecvev","connection":{"id":"g5qb8Jxzwh8tpipv5","clientAddress":"127.0.0.1","httpHeaders":{"host":"poolhtml5servers","user-agent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0","accept-language":"en-GB,en;q=0.5"}}}}
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: Connection already exists for user. userId=w_xfqu49jecvev connectionId=g5qb8Jxzwh8tpipv5
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: User= {"_id":"ZKrra5bYQQWssNsbJ","meetingId":"247998260ba93c7573ad9cb308d475383704a7b1-1621167841461","userId":"w_xfqu49jecvev","authToken":"1pt2qxtrtpuz","clientType":"HTML5","validated":true,"approved":true,"inactivityCheck":false,"loginTime":1621167841777,"authed":true,"avatar":"","breakoutProps":{"isBreakoutUser":false,"parentId":"bbb-none"},"color":"#5e35b1","effectiveConnectionType":null,"emoji":"none","extId":"w_xfqu49jecvev","guest":false,"guestStatus":"ALLOW","intId":"w_xfqu49jecvev","locked":true,"loggedOut":false,"mobile":false,"name":"Staff","presenter":true,"responseDelay":0,"role":"MODERATOR","sortName":"staff"}
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: User='w_xfqu49jecvev' is joining meeting='247998260ba93c7573ad9cb308d475383704a7b1-1621167841461' authToken='1pt2qxtrtpuz'
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: Upserted {"meetingId":"247998260ba93c7573ad9cb308d475383704a7b1-1621167841461","userId":"w_xfqu49jecvev","connectionId":"g5qb8Jxzwh8tpipv5"} 3 in AuthTokenValidation
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: Validated auth token as true user=w_xfqu49jecvev meeting=247998260ba93c7573ad9cb308d475383704a7b1-1621167841461
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: Removing Annotations streamer object for meeting 247998260ba93c7573ad9cb308d475383704a7b1-1621167833593
May 16 12:24:02 server systemd_start_frontend.sh[23486]: info: Removing Cursor streamer object for meeting 247998260ba93c7573ad9cb308d475383704a7b1-1621167833593
May 16 12:24:02 server systemd_start_frontend.sh[23476]: info: Removing Annotations streamer object for meeting 247998260ba93c7573ad9cb308d475383704a7b1-1621167833593
May 16 12:24:02 server systemd_start_frontend.sh[23476]: info: Removing Cursor streamer object for meeting 247998260ba93c7573ad9cb308d475383704a7b1-1621167833593
May 16 12:24:03 server systemd_start.sh[23433]: error: PresenterAssignedEvtMsg: TypeError: Cannot destructure property 'currentPresenterId' of 'currentDefaultPodPresenter' as it is undefined.
May 16 12:24:03 server systemd_start.sh[23433]:     at EventEmitter.handlePresenterAssigned (imports/api/users/server/handlers/presenterAssigned.js:49:13)
May 16 12:24:03 server systemd_start.sh[23433]:     at EventEmitter.emitAsync (/usr/share/meteor/bundle/programs/server/npm/node_modules/eventemitter2/lib/eventemitter2.js:463:31)
May 16 12:24:03 server systemd_start.sh[23433]:     at MeetingMessageQueue.handleTask (imports/startup/server/redis.js:96:10)
May 16 12:24:03 server systemd_start.sh[23433]:     at PowerQueue.runTask (packages/cfs_power-queue.js:596:14)
May 16 12:24:03 server systemd_start.sh[23433]:     at PowerQueue.updateThrottleUp (packages/cfs_power-queue.js:402:12)
May 16 12:24:03 server systemd_start.sh[23433]:     at PowerQueue.next (packages/cfs_power-queue.js:451:10)
May 16 12:24:03 server systemd_start.sh[23433]:     at packages/cfs_power-queue.js:565:12
May 16 12:24:03 server systemd_start.sh[23433]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
May 16 12:24:03 server systemd_start.sh[23433]:     at packages/meteor.js:550:25
May 16 12:24:03 server systemd_start.sh[23433]:     at runWithEnvironment (packages/meteor.js:1286:24)
May 16 12:24:03 server systemd_start.sh[23433]: info: PendingAuths length [0]
May 16 12:24:03 server systemd_start_frontend.sh[23486]: info: Publishing Note for 247998260ba93c7573ad9cb308d475383704a7b1-1621167841461 w_xfqu49jecvev
May 16 12:24:03 server systemd_start_frontend.sh[23486]: info: Publishing connection status for 247998260ba93c7573ad9cb308d475383704a7b1-1621167841461 w_xfqu49jecvev
May 16 12:24:06 server systemd_start.sh[23433]: info: Updated presentation conversion status=SUPPORTED_DOCUMENT id=00b87a5c705d00ee775aa4432933f4f9f52a1b92-1621167841478 meeting=247998260ba93c7573ad9cb308d475383704a7b1-1621167841461
May 16 12:24:07 server systemd_start.sh[23433]: info: Set downloadable status on presentation {00b87a5c705d00ee775aa4432933f4f9f52a1b92-1621167841478 in meeting {247998260ba93c7573ad9cb308d475383704a7b1-1621167841461}
May 16 12:24:08 server systemd_start.sh[23433]: info: Added slide position id=00b87a5c705d00ee775aa4432933f4f9f52a1b92-1621167841478/10 pod=DEFAULT_PRESENTATION_POD presentation=00b87a5c705d00ee775aa4432933f4f9f52a1b92-1621167841478
May 16 12:24:08 server systemd_start.sh[23433]: info: Added slide position id=00b87a5c705d00ee775aa4432933f4f9f52a1b92-1621167841478/13 pod=DEFAULT_PRESENTATION_POD presentation=00b87a5c705d00ee775aa4432933f4f9f52a1b92-1621167841478
```

**Comment by mk-hs** [comment]
We're on stable 2.3.1 by now. You can update via the install script, just run it again on Ubuntu 18.04.

**Comment by aogilvie** [comment]
I can confirm this is fixed with beta1 akka-apps package.

So far, we cannot update to 2.3.1 as we have the following blockers:
- work to remove network indicator icon thing
- work to remove raise hand button
- work to remove the "touch palm tool thing"
- patch errors with bbb-conf specifically `--setip`

...and that's what we found on the first day of testing.

We will get to 2.3.1 eventually, but our use-case for BBB is stricter than most (or maybe people care less). 

To be honest, I've said this before, but our users (and i am sure the community would agree if there was more outreach on this) would much rather have
a) bug fixes or
b) real features like slide thumbnails for the presenter

instead of niche stuff that is not configurable.

**Comment by prlanzarin** [comment]
> work to remove network indicator icon thing

The network indicator **is configurable** and **can** be toggled off.

**Comment by aogilvie** [comment]
Thanks, can you tell us what the flag is? So far:

```
    enableNetworkInformation: false
```

```
networkMonitoring:
  enableNetworkMonitoring: false
```

Do not hide the icon.

**Comment by prlanzarin** [comment]
That's a flag tethered to an old code section that will be removed in the future.

The flag you're looking for is:
https://github.com/bigbluebutton/bigbluebutton/blob/e078e77e842537814ebb4e8211b49357f83a196e/bigbluebutton-html5/private/config/settings.yml#L456
