### ISSUE TITLE
Unable to publish Recording after upgrading from 2.2 to 2.3.4

### ISSUE THREAD

**Issue by reeddyy** [bigbluebutton/bigbluebutton#12627]
Hi, recently I have upgraded BBB 2.2 to 2.3.4 on Ubuntu 18.04 via the bbb-install script. Apart from the recording issue, everything else works fine. I have tried installing BBB using the bbb-install script several times but still end up the same issue. All the most recent recordings (1 min & less) after the upgrade are not able to publish.

Below are some of the checks done.

sudo bbb-conf --status - https://i.ibb.co/3sH2F2C/status.jpg
sudo bbb-conf --check - https://i.ibb.co/vm7F9TC/check.jpg

sudo bbb-record --watch - https://i.ibb.co/sbvn6YG/2021-06-19-16-34-57.jpg

sudo journalctl -f -u bbb-rap-archive-worker.service - https://i.ibb.co/8xYxT2M/2021-06-19-16-37-56a.jpg
`$ sudo journalctl -f -u bbb-rap-archive-worker.service
-- Logs begin at Fri 2021-06-18 17:46:37 +08. --
Jun 18 18:28:12 ip-172-31-37-219 rap-archive-worker.rb[4810]:         from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1063:in `find'
Jun 18 18:28:12 ip-172-31-37-219 rap-archive-worker.rb[4810]:         from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1063:in `find_by_path'
Jun 18 18:28:12 ip-172-31-37-219 rap-archive-worker.rb[4810]:         from /usr/lib/ruby/2.5.0/rubygems.rb:213:in `try_activate'
Jun 18 18:28:12 ip-172-31-37-219 rap-archive-worker.rb[4810]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
Jun 18 18:28:12 ip-172-31-37-219 rap-archive-worker.rb[4810]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
Jun 18 18:28:12 ip-172-31-37-219 rap-archive-worker.rb[4810]:         from /usr/local/bigbluebutton/core/lib/recordandplayback.rb:28:in `<top (required)>'
Jun 18 18:28:12 ip-172-31-37-219 rap-archive-worker.rb[4810]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Jun 18 18:28:12 ip-172-31-37-219 rap-archive-worker.rb[4810]:         from /usr/local/bigbluebutton/core/scripts/rap-archive-worker.rb:21:in `<main>'
Jun 18 18:28:12 ip-172-31-37-219 systemd[1]: bbb-rap-archive-worker.service: Main process exited, code=exited, status=1/FAILURE
Jun 18 18:28:12 ip-172-31-37-219 systemd[1]: bbb-rap-archive-worker.service: Failed with result 'exit-code'.
`

sudo journalctl -f -u bbb-rap-sanity-worker.service - no results
sudo journalctl -f -u bbb-rap-process-worker.service - no results
sudo journalctl -f -u bbb-rap-publish-worker.service - no results
sudo journalctl -f -u bbb-rap-events-worker.service - no results

/var/log/bigbluebutton/bbb-rap-worker.log - https://i.ibb.co/kcLPLMw/b.jpg

I also notice that meetingID folder in the raw directory (/var/bigbluebutton/recording/raw/153984ac11b69544e84a7cc0c74949fea115b1c1-1624082583250) after upgrade are all empty.

When i tried to rebuild, it shows me this
`$ sudo bbb-record --rebuild 153984ac11b69544e84a7cc0c74949fea115b1c1-1624082583250
Marking for rebuild 153984ac11b69544e84a7cc0c74949fea115b1c1-1624082583250
Enqueing sanity worker with {:single_step=>false, :meeting_id=>"153984ac11b69544e84a7cc0c74949fea115b1c1-1624082583250"}`

I hope someone can help me out on this.

**Comment by EmmyGraugans** [comment]
> Hi, recently I have upgraded BBB 2.2 to 2.3.4 on Ubuntu 18.04 via the bbb-install script. Apart from the recording issue, everything else works fine.

In that case, and assuming you did indeed *upgrade* and not a clean install, you got further than could be expected, considering that the upgrade-path from 2.2 on 16.04 directly to 2.3 on 18.04 is not supported at all... See https://docs.bigbluebutton.org/2.3/install.html#upgrading-from-bigbluebutton-22

Someone managed to pull it off and wrote about it here: https://www.mynaparrot.com/en/blog/180-how-to-upgrade-bigbluebutton-2-2-to-2-3-ubuntu-16-04-to-18-04 maybe you can use something of what he wrote.

Basic principle: purge everything that contains bbb or kurento or freeswitch in the package name and remove all directories related to that, and then reinstall bbb. Good luck.

**Comment by BackfischHunter** [comment]
Same issue when upgrading from 2.2 to 2.3.
I also purged everything according to the guide.
Everything works fine except the creation of new recordings.

bbb-rap-worker.log is empty, so I have no clue.
It is stuck on the first step of the RAS procedure in bbb-record --watch
rebuilding a single recording does not work since the raw files don't exist.
The newest raw file under /var/bigbluebutton/recording/raw is from before the update.

Any ideas?

**Comment by Mittler1** [comment]
I had the same problem but with a fresh install. I've tried a lot of things and in the end it worked, so I can't be 100% sure which of the adjustments worked out in the end.

First I added `keepEvents=true`  to the `/etc/bigbluebutton/bbb-web.properties` overwrite file.

Then I tried to reinstall bbb-record-core: `sudo apt-get install --reinstall bbb-record-core`
Errors have appeared in the output and I noticed that something was wrong with ruby and/or rubygems. So I tried to fix ruby and rubygems. In the end I simply installed ruby 2.7 and rubygems via rvm (Ruby Version Manager).

Then I got errors about the gems `absolute_time` and `ffi`, which could be fixed with `gem pristine absolute_time --version 1.0.0` and `gem pristine ffi --version 1.12.1`.

After all that, the reinstallation of bbb-record-core worked fine. I restarted the record service with `systemctl restart bbb_record_core.slice`.

Seems to work now. No idea, if the upgrade to ruby 2.7 is really necessary, but the pristination of the two gems could be the trick.

So before you try this ruby stuff, check if you too see an error on the output of `sudo apt-get install --reinstall bbb-record-core`

**Comment by BackfischHunter** [comment]
Thanks @Mittler1 
bbb-rap-archive-worker.service is finally running again.

I checked the logs with 
`sudo journalctl -f -u bbb-rap-starter.service`
and it revealed that some gems were missing.
I had to install them with sudo, otherwise it would not work. Like:
`sudo gem install resque`
then restart with `systemctl restart bbb-rap-starter.service` and check again.



Unfortunately I am still stuck, there is no X anymore under RAS.
`sudo journalctl -f -u bbb-rap-resque-worker.service` says the service is restarting 50000 times, is that normal?
bbb-rap-worker.log is still empty. 
Raw files seem to exist, because I can rebuild them. But it just says:
`Enqueing sanity worker with {:single_step=>false, :meeting_id=>"<id>"}`
Any clue?

**Comment by BackfischHunter** [comment]
I solved it for my setup.
`journalctl -u bbb-rap-resque-worker.service` revealed that multiple log files in /var/log/bigbluebutton had root as the owner, it should be bigbluebutton instead. Also `/usr/lib/systemd/system/bbb-rap-resque-worker.service`  just didn't work on the enqueued jobs.
I had to change the content of that file to this, so it could work:
```
[Unit]
Description=BigBlueButton resque worker for recordings

[Service]
Type=simple
Environment=QUEUE=*
Environment=COUNT=1
ExecStart=/bin/sh -c '/usr/bin/rake -f ../Rakefile resque:work >> /var/log/bigbluebutton/bbb-rap-worker.log'
WorkingDirectory=/usr/local/bigbluebutton/core/scripts
# Environment=VVERBOSE=1
User=bigbluebutton
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target

```
Then run 
`systemctl daemon-reload`
`sudo systemctl restart bbb-rap-resque-worker.service`
It's finally processing recordings and got so much faster in BBB 2.3,

**Comment by hostbbb** [comment]
did you update your 16.04 2.2 to 18.04 and then install 2.3?
think there were a number of permission changes in systemd to make it more secure for 2.3

**Comment by BackfischHunter** [comment]
@hostbbb If  you asked me, yes I did. I followed this guide:
 https://www.mynaparrot.com/en/blog/180-how-to-upgrade-bigbluebutton-2-2-to-2-3-ubuntu-16-04-to-18-04

**Comment by hostbbb** [comment]
so looks like any user updating ubuntu on existing, then updating bbb will probaby run into the issue.   
thanks for documenting how you solved.

**Comment by gestshb** [comment]
> I solved it for my setup. `journalctl -u bbb-rap-resque-worker.service` revealed that multiple log files in /var/log/bigbluebutton had root as the owner, it should be bigbluebutton instead. Also `/usr/lib/systemd/system/bbb-rap-resque-worker.service` just didn't work on the enqueued jobs. I had to change the content of that file to this, so it could work:
> 
> ```
> [Unit]
> Description=BigBlueButton resque worker for recordings
> 
> [Service]
> Type=simple
> Environment=QUEUE=*
> Environment=COUNT=1
> ExecStart=/bin/sh -c '/usr/bin/rake -f ../Rakefile resque:work >> /var/log/bigbluebutton/bbb-rap-worker.log'
> WorkingDirectory=/usr/local/bigbluebutton/core/scripts
> # Environment=VVERBOSE=1
> User=bigbluebutton
> Restart=always
> RestartSec=3
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> Then run `systemctl daemon-reload` `sudo systemctl restart bbb-rap-resque-worker.service` It's finally processing recordings and got so much faster in BBB 2.3,

Thanks you it s work

**Comment by antobinary** [comment]
We don't recommend upgrading the server for migrating from BBB 2.2 to 2.3 or 2.4 (there's a substantial jump in OS version). Glad to hear you were able to resolve the issues following that guide. We still recommend setting up a new server and migrating the recordings
