### ISSUE TITLE
HTML5 server crashed

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#12648]
**Describe the bug**

Received the following ticket.

"
Below for an incident that occurred this afternoon at about 1:12pm ET today, resolved around 1:20pm ET

The BBB classroom seemed to crash for all of us at the same time, leaving us with a blank, dark blue screen (i.e. the background of the app), and an attempt to rejoin took us to the same screen. The session didn't seem to have ended.
"

From syslog, I see this exception.

2021-06-21T17:13:43.409823+00:00 BBB-2 systemd_start_frontend.sh[5480]: #033[31merror#033[39m: Exception while invoking method addUserSettings Error: Match error: Expected string, got undefined
2021-06-21T17:13:43.410038+00:00 BBB-2 systemd_start_frontend.sh[5480]:     at check (packages/check/match.js:36:17)
2021-06-21T17:13:43.410091+00:00 BBB-2 systemd_start_frontend.sh[5480]:     at MethodInvocation.addUserSettings (imports/api/users-settings/server/methods/addUserSettings.js:89:5)
2021-06-21T17:13:43.410130+00:00 BBB-2 systemd_start_frontend.sh[5480]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
2021-06-21T17:13:43.410169+00:00 BBB-2 systemd_start_frontend.sh[5480]:     at packages/ddp-server/livedata_server.js:719:19
2021-06-21T17:13:43.410200+00:00 BBB-2 systemd_start_frontend.sh[5480]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-06-21T17:13:43.410237+00:00 BBB-2 systemd_start_frontend.sh[5480]:     at packages/ddp-server/livedata_server.js:717:46
2021-06-21T17:13:43.410278+00:00 BBB-2 systemd_start_frontend.sh[5480]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
2021-06-21T17:13:43.410310+00:00 BBB-2 systemd_start_frontend.sh[5480]:     at packages/ddp-server/livedata_server.js:715:46
2021-06-21T17:13:43.410345+00:00 BBB-2 systemd_start_frontend.sh[5480]:     at new Promise (<anonymous>)
2021-06-21T17:13:43.410379+00:00 BBB-2 systemd_start_frontend.sh[5480]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
2021-06-21T17:13:43.410416+00:00 BBB-2 systemd_start_frontend.sh[5480]:     at packages/ddp-server/livedata_server.js:559:43
2021-06-21T17:13:43.415504+00:00 BBB-2 systemd_start_frontend.sh[5480]: #033[32minfo#033[39m: Upserted {"meetingId":"338867c4f8751a6ad7f67759dc44ebf851231e8a-1624293831510","userId":"w_k4u3jz2nm1ld","connectionId":"uenAdsWff9aAMWCN5"} 2 in AuthTokenValidation
2021-06-21T17:13:43.415660+00:00 BBB-2 systemd_start_frontend.sh[5480]: #033[32minfo#033[39m: User 'w_k4u3jz2nm1ld' is trying to validate auth token for meeting '338867c4f8751a6ad7f67759dc44ebf851231e8a-1624293831510' from connection 'uenAdsWff9aAMWCN5'

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.3.3 (1767)

**Comment by itum** [comment]
Hello
I have same problem that you desrcribed here.
![pbbb](https://user-images.githubusercontent.com/5459694/123436688-1f573200-d5e4-11eb-9567-4cdc8272247f.JPG)
![صصصص](https://user-images.githubusercontent.com/5459694/123436727-2b42f400-d5e4-11eb-83d7-741ffaff0a55.JPG)
![problm](https://user-images.githubusercontent.com/5459694/123436772-38f87980-d5e4-11eb-90e9-1195838f54ba.JPG)
![prb2](https://user-images.githubusercontent.com/5459694/123436929-634a3700-d5e4-11eb-91b4-fd6a1ec12b61.jpeg)

The problem was that the number of users reached more than 40 users on BigBlueButton 2.3.4 (latest version) and when rendering public chats, users crashed and the browser gave an error message.
This was our first experience of using 60 users at the same time and it was constantly crashing and we felt that it was not stable at all.
Our dedicated server specifications:
RAM: 16 GB
CPU: 32 cores
Hard drive: 250 GB ssd
ubunto 18.04
