### ISSUE TITLE
Not running:  tomcat8 or grails Error on fresh installatoin

### ISSUE THREAD

**Issue by mojtaba82** [bigbluebutton/bigbluebutton#13337]
**Describe the bug**

**Installation type**
bbb-install.sh

**Firewall and IP address type**
Is your server behind a NAT or firewall? Does your BBB server have its own IPv4 addres?

**Console output**
after fresh installation i have this 
Not running:  tomcat8 or grails
 Error: Could not connect to the configured hostname/IP address
**Additional context**
in /var/log/bigbluebutton/bbb-web.log i have this error
`2021-09-29T22:43:26.189Z ERROR o.s.boot.SpringApplication - Application startup failed
java.lang.IllegalStateException: Cannot load configuration class: org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:404)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:249)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:283)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:127)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124)                                              at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:84)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:393)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:380)
        at grails.boot.GrailsApp$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
        at org.bigbluebutton.web.Application.main(Application.groovy:8)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: java.lang.ExceptionInInitializerError: null
        at org.springframework.context.annotation.ConfigurationClassEnhancer.newEnhancer(ConfigurationClassEnhancer.java:122)
        at org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(ConfigurationClassEnhancer.java:110)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:394)
        ... 25 common frames omitted
Caused by: org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @764669a7
        at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:464)
        at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:336)
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
        at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)                                                                                                   at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
        at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
        at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
        at org.springframework.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221)
        at org.springframework.cglib.core.KeyFactory.create(KeyFactory.java:174)
        at org.springframework.cglib.core.KeyFactory.create(KeyFactory.java:153)
        at org.springframework.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73)
        ... 28 common frames omitted
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @764669a7
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at org.springframework.cglib.core.ReflectUtils$1.run(ReflectUtils.java:61)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.springframework.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:52)
        at org.springframework.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:243)
        at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
        at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
        ... 40 common frames omitted`

**Comment by mojtaba82** [comment]
ubuntu version is
output of #cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"

**Comment by mojtaba82** [comment]
How can I resolve this issue?

**Comment by MrCapitalist** [comment]
Hi @ffdixon and other BigBlueButton development team.

I have this error too from yesterday

I used bbb-install on a fresh ubuntu 18.04 and I have 502 bad gateway in `https://myaddress.com/bigbluebutton/api` error and 

```
Server Error
Invalid BigBlueButton Endpoint and Secret
```
in the Greenlight after login into the panel!

**bb-conf --status:**
```
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
bbb-html5-backend@1 ———► [✔ - active]
bbb-html5-backend@2 ———► [✔ - active]
bbb-html5-frontend@1 ——► [✔ - active]
bbb-html5-frontend@2 ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✘ - activating]
```

**bbb-conf --check**
```
# Potential problems described below
# Not running:  tomcat8 or grails
```

I reinstall my OS 3 times and install BigBlueButton but it doesn't resolve my problem

**Comment by MrCapitalist** [comment]
I set up 3 other servers with different IPs now and again encountered this error on all of them.

@ffdixon, @antobinary, @pedrobmarin
Please check the bbb-install shell script. I'm waiting for your support.

Thanks a lot

**Comment by mojtaba82** [comment]
@MrCapitalist Do you find any solution?
please contact me mojtaba.baghban@gmail.com

**Comment by MrCapitalist** [comment]
> @MrCapitalist Do you find any solution? please contact me [mojtaba.baghban@gmail.com](mailto:mojtaba.baghban@gmail.com)

Unfortunately not yet

**Comment by arpitpitchvantage** [comment]
We are also having the same issue since yesterday after making customization through git, which re-deploys the complete set-up.

**Comment by ffdixon** [comment]
Can you try installing again -- just pushed an [update](https://github.com/bigbluebutton/bbb-install/commit/2cf126606abe5a4b2295e1f833ac31ddcbe93767) to ensure Java 1.8 is installed.  Let us know if the install now works.

**Comment by MrCapitalist** [comment]
> Can you try installing again -- just pushed an [update](https://github.com/bigbluebutton/bbb-install/commit/2cf126606abe5a4b2295e1f833ac31ddcbe93767) to ensure Java 1.8 is installed. Let us know if the install now works.

Thanks, man. Your change was worked! My problem solved

**Comment by mojtaba82** [comment]
> Can you try installing again -- just pushed an [update](https://github.com/bigbluebutton/bbb-install/commit/2cf126606abe5a4b2295e1f833ac31ddcbe93767) to ensure Java 1.8 is installed. Let us know if the install now works.

Thanks a lot. Problem solved
