### ISSUE TITLE
Screenshare is not captured in recording

### ISSUE THREAD

**Issue by vinodprakash** [bigbluebutton/bigbluebutton#13356]
**Describe the bug**
Screenshare is not captured in recording. Only audio is captured when I do screenshare

**To Reproduce**
1. Start a new Meeting
2. Click on 'Start Recording'
3. Share your screen with 'Entire screen' option
4. Click on 'Pause Recording'
5. End the meeting

**Expected behavior**
Proper recording with shared screen and audio content

**Actual behavior**
Recording available only with audio content

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 2.3.14

``` 
sudo bbb-conf --check


BigBlueButton Server 2.3.14 (2469)
                    Kernel version: 4.15.0-144-generic
                      Distribution: Ubuntu 18.04.6 LTS (64-bit)
                            Memory: 8167 MB
                         CPU cores: 4

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb.example.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: bbb.example.com
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: <IP>
                   external_rtp_ip: <IP>
                   external_sip_ip: <IP>

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: <IP>:5066
                       wss-binding: <IP>:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.example.com
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb2~18.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: <IP>
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: <IP>
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: <IP>
                    localIpAddress: <IP>
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1845
                        kurentoUrl: wss://bbb.example.com/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun: stun.l.google.com:19302

/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini (STUN Server)
                              stun: 172.217.212.127:19302


# Potential problems described below

#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

```
I see bbb-red5 package is not available post installation

``` 
dpkg -l | grep bbb

ii  bbb-apps-akka                        2.3.0-103                                 all          BigBlueButton Apps (Akka)
ii  bbb-config                           1:2.3.0-94                                amd64        BigBlueButton configuration utilities
ii  bbb-demo                             1:2.3.0-9                                 amd64        BigBlueButton API demos
ii  bbb-etherpad                         1:2.3.0-51                                amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                  2:2.3.0-27                                amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                1:1.6.7-3                                 amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                       2.3.0-55                                  all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                            1:2.3.0-1845                              amd64        The HTML5 components for BigBlueButton
ii  bbb-libreoffice-docker               1:2.3.0-56                                amd64        BigBlueButton setup for LibreOffice running in docker
ii  bbb-mkclean                          1:0.8.7-4                                 amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback                         1:2.3.0-20                                amd64        BigBlueButton playback
ii  bbb-playback-notes                   1:2.3.0-4                                 amd64        BigBluebutton playback of notes
ii  bbb-playback-podcast                 1:2.3.0-3                                 amd64        BigBluebutton playback in podcast
ii  bbb-playback-presentation            1:2.3.0-13                                amd64        BigBluebutton playback of presentation
ii  bbb-playback-screenshare             1:2.3.0-5                                 amd64        BigBluebutton playback of screenshare
ii  bbb-record-core                      1:2.3.0-37                                amd64        BigBlueButton record and playback
ii  bbb-web                              1:2.3.0-95                                amd64        BigBlueButton API
ii  bbb-webrtc-sfu                       1:2.3.0-36                                amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                        1:2.3.0-7                                 amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                               7:4.2.4-1ubuntu0.1bbb2~18.04              amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                   7:4.2.4-1ubuntu0.1bbb2~18.04              amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                  7:4.2.4-1ubuntu0.1bbb2~18.04              amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                   7:4.2.4-1ubuntu0.1bbb2~18.04              amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                  7:4.2.4-1ubuntu0.1bbb2~18.04              amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                 7:4.2.4-1ubuntu0.1bbb2~18.04              amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                    7:4.2.4-1ubuntu0.1bbb2~18.04              amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                          0.2.1-1bbb1                               amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                  7:4.2.4-1ubuntu0.1bbb2~18.04              amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                 7:4.2.4-1ubuntu0.1bbb2~18.04              amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                    7:4.2.4-1ubuntu0.1bbb2~18.04              amd64        FFmpeg library for image scaling and various conversions - runtime files
```

```
sudo bbb-conf --status

nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
tomcat8 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
kurento-media-server-8888  [✔ - active]
kurento-media-server-8889  [✔ - active]
kurento-media-server-8890  [✔ - active]
bbb-html5-backend@1 ———► [✔ - active]
bbb-html5-backend@2 ———► [✔ - active]
bbb-html5-frontend@1 ——► [✔ - active]
bbb-html5-frontend@2 ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
```

**Comment by vinodprakash** [comment]
bigbluebutton screenshare log file of a recorded meeting with screenshared

```
I, [2021-09-30T10:52:00.195339 #20071]  INFO -- : Reading source audio information
D, [2021-09-30T10:52:00.195357 #20071] DEBUG -- :   /var/bigbluebutton/recording/raw/cad408069b44ae450382f1b2789777a7d4c6572f-1632909860517/audio/cad408069b44ae450382f1b2789777a7d4c6572f-1632909860517-423045872.opus
D, [2021-09-30T10:52:00.214396 #20071] DEBUG -- :     format: ogg, codec: opus
D, [2021-09-30T10:52:00.214454 #20071] DEBUG -- :     sample rate: 48000, duration: 63000
I, [2021-09-30T10:52:00.214516 #20071]  INFO -- : Generating ffmpeg command
I, [2021-09-30T10:52:00.214538 #20071]  INFO -- :   Using input /var/bigbluebutton/recording/raw/cad408069b44ae450382f1b2789777a7d4c6572f-1632909860517/audio/cad408069b44ae450382f1b2789777a7d4c6572f-1632909860517-423045872.opus
D, [2021-09-30T10:52:00.214572 #20071] DEBUG -- :   ffmpeg filter_complex_script:
D, [2021-09-30T10:52:00.214589 #20071] DEBUG -- : [0]aresample=async=1000,aformat=sample_fmts=s16:sample_rates=48000:channel_layouts=stereo,apad,asetpts=PTS-STARTPTS,atrim=end=53.874
I, [2021-09-30T10:52:00.214688 #20071]  INFO -- : Running audio processing...
I, [2021-09-30T10:52:00.214769 #20071]  INFO -- : Executing: ffmpeg -y -v warning -nostats -max_error_rate 1.0 -ss 5.437 -c:a libopus -i /var/bigbluebutton/recording/raw/cad408069b44ae450382f1b2789777a7d4c6572f-1632909860517/audio/cad408069b44ae450382f1b2789777a7d4c6572f-1632909860517-423045872.opus -filter_complex_script /var/bigbluebutton/recording/process/screenshare/cad408069b44ae450382f1b2789777a7d4c6572f-1632909860517/audio.filter -vn -c:a libvorbis -q:a 2 -f ogg /var/bigbluebutton/recording/process/screenshare/cad408069b44ae450382f1b2789777a7d4c6572f-1632909860517/audio.ogg
I, [2021-09-30T10:52:01.372610 #20071]  INFO -- : Success?: true
I, [2021-09-30T10:52:01.372714 #20071]  INFO -- : Process exited? true
I, [2021-09-30T10:52:01.372731 #20071]  INFO -- : Exit status: 0
I, [2021-09-30T10:52:01.372747 #20071]  INFO -- : Rendering video
I, [2021-09-30T10:52:01.372789 #20071]  INFO -- : Pre-processing EDL
I, [2021-09-30T10:52:01.372811 #20071]  INFO -- : Reading source video information
D, [2021-09-30T10:52:01.372826 #20071] DEBUG -- : EDL Dump:
D, [2021-09-30T10:52:01.372838 #20071] DEBUG -- : ---
D, [2021-09-30T10:52:01.372848 #20071] DEBUG -- :   Timestamp: 0
D, [2021-09-30T10:52:01.372858 #20071] DEBUG -- :   Video Areas:
D, [2021-09-30T10:52:01.372878 #20071] DEBUG -- :     webcam
D, [2021-09-30T10:52:01.372896 #20071] DEBUG -- :     deskshare
D, [2021-09-30T10:52:01.372908 #20071] DEBUG -- : ---
D, [2021-09-30T10:52:01.372919 #20071] DEBUG -- :   Timestamp: 53874
D, [2021-09-30T10:52:01.372929 #20071] DEBUG -- :   Video Areas:
I, [2021-09-30T10:52:01.372939 #20071]  INFO -- : Compositing cuts
I, [2021-09-30T10:52:01.372976 #20071]  INFO -- :   Cut start time 0, duration 53874
D, [2021-09-30T10:52:01.372991 #20071] DEBUG -- :   Laying out 0 videos in deskshare
D, [2021-09-30T10:52:01.373002 #20071] DEBUG -- :   Laying out 0 videos in webcam
I, [2021-09-30T10:52:01.373072 #20071]  INFO -- : Executing: ffmpeg -y -v warning -nostats -max_error_rate 1.0 -filter_complex color\=c\=white:s\=1280x720:r\=,trim\=end\=53.874 -an -codec libx264 -preset veryfast -crf 30 -force_key_frames expr:gte\(t,n_forced\*10\) -pix_fmt yuv420p -r '' /var/bigbluebutton/recording/process/screenshare/cad408069b44ae450382f1b2789777a7d4c6572f-1632909860517/video_0.mp4
I, [2021-09-30T10:52:01.389208 #20071]  INFO -- : [color @ 0x5615db006000] Unable to parse option value "" as video rate
I, [2021-09-30T10:52:01.389315 #20071]  INFO -- :     Last message repeated 1 times
I, [2021-09-30T10:52:01.389329 #20071]  INFO -- : [color @ 0x5615db006000] Error setting option r to value .
I, [2021-09-30T10:52:01.389339 #20071]  INFO -- : [Parsed_color_0 @ 0x5615db005f00] Error applying options to the filter.
I, [2021-09-30T10:52:01.389349 #20071]  INFO -- : [AVFilterGraph @ 0x5615db005c40] Error initializing filter 'color' with args 'c=white:s=1280x720:r='
I, [2021-09-30T10:52:01.389360 #20071]  INFO -- : Error initializing complex filters.
I, [2021-09-30T10:52:01.389369 #20071]  INFO -- : Invalid argument
I, [2021-09-30T10:52:01.391057 #20071]  INFO -- : Success?: false
I, [2021-09-30T10:52:01.391103 #20071]  INFO -- : Process exited? true
I, [2021-09-30T10:52:01.391116 #20071]  INFO -- : Exit status: 1
E, [2021-09-30T10:52:01.391167 #20071] ERROR -- : ffmpeg failed, exit code 1
E, [2021-09-30T10:52:01.391206 #20071] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/edl/video.rb:561:in `composite_cut'
E, [2021-09-30T10:52:01.391225 #20071] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/edl/video.rb:261:in `block in render'
E, [2021-09-30T10:52:01.391241 #20071] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/edl/video.rb:255:in `each'
E, [2021-09-30T10:52:01.391256 #20071] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/edl/video.rb:255:in `render'
E, [2021-09-30T10:52:01.391272 #20071] ERROR -- : /usr/local/bigbluebutton/core/scripts/process/screenshare.rb:136:in `<main>'
```

**Comment by hostbbb** [comment]
are you using the default presentation format.  Or did you install the screenshare recording package?  A couple of people have commented that a param is missing in yml with screenshare.

**Comment by vinodprakash** [comment]
I have installed the screenshare package and configured in the yml file also as per the documentation

**Comment by jgribonvald** [comment]
Hi should we make a pull request to add this framerate option automatically and avoid the problem ?
