### ISSUE TITLE
Webcams randomly do not work (error: [mcs-core] TODO => Uncaught exception TypeError: Cannot read property 'ua' of undefined)

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#13385]
Most webcams have started to be displayed as black screens, some are displayed OK, randomly, the same webcam may be shown properly to some clients and at the same time can be shown as a black screen to other clients.

bbb-webrtc-sfu deb package is of version 1:2.4.0-14

Restarting kurento-media-server.service and bbb-webrtc-sfu.service did not help.

From `journalctl -u bbb-webrtc-sfu`:
```
error: [mcs-core] TODO => Uncaught exception TypeError: Cannot read property 'ua' of undefined
at Freeswitch._handleStopTalking (/usr/local/bigbluebutton/bbb-webrtc-sfu/lib/mcs-core/lib/adapters/freeswitch/freeswitch.js:118:55)
at EslWrapper.emit (events.js:314:20)Oat EslWrapper.EventEmitter.emit (domain.js:483:12)
at EslWrapper._onCustomEvent (/usr/local/bigbluebutton/bbb-webrtc-sfu/lib/mcs-core/lib/adapters/freeswitch/esl-wrapper.js:355:16)
at module.exports.EventEmitter.emit (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/eventemitter2/lib/eventemitter2.js:388:22)
at module.exports.Connection._onEvent (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/modesl/lib/esl/Connection.js:795:10)
at module.exports.EventEmitter.emit (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/eventemitter2/lib/eventemitter2.js:388:22)
at module.exports.Parser._parseEvent (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/modesl/lib/esl/Parser.js:208:10)
at module.exports.Parser._parseBody (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/modesl/lib/esl/Parser.js:100:10)
at module.exports.Parser._parseHeaders (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/modesl/lib/esl/Parser.js:76:37)

```

syslog is being continiosly spammed with it.

CPU is overloaded with freeswitch:
![image](https://user-images.githubusercontent.com/15802528/135764077-2ff56855-f94c-4a06-96d9-7a95e5896a42.png)

Firewall is working.
```
# /opt/freeswitch/bin/fs_cli -p $(xmlstarlet sel -t -m 'configuration/settings/param[@name="password"]' -v @value /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml)
<...>
> show channels
<...>
85cdda6c-3ae3-445e-bdff-56987807afd4,inbound,2021-10-03 19:49:51,1633279791,sofia/external/w_vdobu7bpukwy_1-bbbID-Ivan Ivanov@hostname,CS_EXECUTE,w_vdobu7bpukwy_1-bbbID-Ivan Ivanov,w_vdobu7bpukwy_1-bbbID-Ivan Ivanov,ip_address_1,echo78025,conference,78025@cdquality,XML,default,L16,48000,768000,opus,48000,0,srtp:dtls:AES_CM_128_HMAC_SHA1_80,hostname,,,,ACTIVE,,,,,,,w_vdobu7bpukwy_1-bbbID-Ivan Ivanov,w_vdobu7bpukwy_1-bbbID-Ivan Ivanov,ip_address_1,echo78025,XML,public
<...>
```
There is nothing interesting in the freeswitch log.

On the client from the browser console when seing black screens instead of webcams:
```
[20:00:18:0690] ERROR: clientLogger: Camera VIEWER failed. Reconnecting. https://hostname/html5client/cb58656….js?meteor_js_resource=true:348:578854
```
![image](https://user-images.githubusercontent.com/15802528/135764037-3d327681-7952-4b50-997e-dc3e5dd3d252.png)

**Comment by mikhailnov** [comment]
not only _handleStopTalking, but e.g.:
```
error: [mcs-core] TODO => Uncaught exception TypeError: Cannot read property 'ua' of undefined
at Freeswitch._handleMuted (/usr/local/bigbluebutton/bbb-webrtc-sfu/lib/mcs-core/lib/adapters/freeswitch/freeswitch.js:198:55)
at EslWrapper.emit (events.js:314:20)
at EslWrapper.EventEmitter.emit (domain.js:483:12)
at EslWrapper._onCustomEvent (/usr/local/bigbluebutton/bbb-webrtc-sfu/lib/mcs-core/lib/adapters/freeswitch/esl-wrapper.js:366:16)
at module.exports.EventEmitter.emit (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/eventemitter2/lib/eventemitter2.js:388:22)
at module.exports.Connection._onEvent (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/modesl/lib/esl/Connection.js:795:10)
at module.exports.EventEmitter.emit (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/eventemitter2/lib/eventemitter2.js:388:22)
at module.exports.Parser._parseEvent (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/modesl/lib/esl/Parser.js:208:10)
at module.exports.Parser._parseBody (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/modesl/lib/esl/Parser.js:100:10)
at module.exports.Parser._parseHeaders (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/modesl/lib/esl/Parser.js:76:37)
```

**Comment by mikhailnov** [comment]
```
error: [mcs-kurento-adapter] Stack trace for error 2210 | MEDIA_CONNECT_ERROR -> errorStack=Error: Media elements do not share pipeline
at /usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-client/lib/KurentoClient.js:365:24
at Object.dispatchCallback [as callback] (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-jsonrpc/lib/index.js:546:9)
at processResponse (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-jsonrpc/lib/index.js:667:15)
at RpcBuilder.decode (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-jsonrpc/lib/index.js:723:5)
at Stream.transportMessage (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-jsonrpc/lib/index.js:208:10)
at Stream.emit (events.js:314:20)
at Stream.EventEmitter.emit (domain.js:483:12)
at drain (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/through/index.js:36:16)
at Stream.stream.queue.stream.push (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/through/index.js:45:5)
at WebsocketStream.onMessage (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/websocket-stream/index.js:45:15)
Oct 03 20:17:17 hostname bbb-webrtc-sfu[67104]: 2021-10-03T17:17:17.186Z - error: [mcs-media-session] Stack trace for error 2200 | MEDIA_GENERIC_ERROR -> errorStack=TypeError: Cannot read property 'id' of undefined
at /usr/local/bigbluebutton/bbb-webrtc-sfu/lib/mcs-core/lib/model/sdp-session.js:339:35
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
Oct 03 20:17:17 hostname bbb-webrtc-sfu[67104]: 2021-10-03T17:17:17.193Z - error: [mcs-media] Failed to run underlying _connect procedure due to MEDIA_CONNECT_ERROR sourceId=divine-dream-Cthh5mc, sourceAdapterElementId=1589eab3-b90b-4006-b783-d5811ac1fbf1_kurento.MediaPipeline/65cf3425-4520-42ba-a409-c1ca92d54a4c_kurento.WebRtcEndpoint/dark-glade-N6hL~Tb, sinkId=frosty-sun-KlpY9h~, sinkAdapterElementId=c4cb2b1d-5e16-48fa-ae52-124f1a15b689_kurento.MediaPipeline/fcabd945-1aa0-46b3-b2aa-729516d2c5dc_kurento.WebRtcEndpoint/dark-glade-N6hL~Tb, connectionType=VIDEO, code=2210, type=CONNECT_ERROR, details=Media elements do not share pipeline, stackWasLogged=true
Oct 03 20:17:17 hostname bbb-webrtc-sfu[67104]: 2021-10-03T17:17:17.194Z - info: [mcs-kurento-adapter] Adapter elements to be connected {"sourceId":"1589eab3-b90b-4006-b783-d5811ac1fbf1_kurento.MediaPipeline/65cf3425-4520-42ba-a409-c1ca92d54a4c_kurento.WebRtcEndpoint/dark-glade-N6hL~Tb","sinkId":"c4cb2b1d-5e16-48fa-ae52-124f1a15b689_kurento.MediaPipeline/fcabd945-1aa0-46b3-b2aa-729516d2c5dc_kurento.WebRtcEndpoint/dark-glade-N6hL~Tb","connectionType":"VIDEO"}
```

**Comment by PhMemmel** [comment]
If the resources of your system are maxed out like that you can't expect the system to work without any issues anymore. It is recommended to keep the CPU load below 80% for the system to work well. Your problem is likely just the fact that your server cannot handle that many users.

**Comment by mikhailnov** [comment]
> If the resources of your system are maxed out like that you can't expect the system to work without any issues anymore. It is recommended to keep the CPU load below 80% for the system to work well. Your problem is likely just the fact that your server cannot handle that many users.

I am pretty sure that CPU spike is abnormal, it sometimes happens with that number of users and sometimes does not.
But sound quality did not regress, so the server was not very much overloaded.
It does not explain why this problem happened.

**Comment by prlanzarin** [comment]
> TODO => Uncaught exception TypeError: Cannot read property 'ua' of undefined

Unrelated (and not a problem even though it's ugly). And it's a byproduct of restarting webrtc-sfu in the midst of a running instance.

> error: [mcs-kurento-adapter] Stack trace for error 2210 | MEDIA_CONNECT_ERROR -> errorStack=Error: Media elements do not share pipeline

This one's interesting, though. Are you running a multiple Kurento setup? Do you have any non standard configs applied to webrtc-sfu (different balancing strategy, more than three KMSs, using H.264, [...])?


Moreover, what PhMemmel said: your server is overloaded. Audio quality not being _visibly_ affected doesn't mean a server isn't overloaded. If there's something Kurento doesn't like and strives to make a ruckus about is an overloaded server, even if overloads are _frequent spikes_.

**Comment by mikhailnov** [comment]
@prlanzarin 

>  Are you running a multiple Kurento setup?

No, not yet

> Do you have any non standard configs applied to webrtc-sfu (different balancing strategy, more than three KMSs, using H.264, [...])?

No, only bitrates of webcams are decreased in Kurento.

> Audio quality not being visibly affected doesn't mean a server isn't overloaded

Well, it means that CPU queue is not overloaded that high that Freeswitch does not have time to process all packets. But, if I remember corretly, Freeswitch is running with a high CPU priority, but Kurento and bbb-webrtc-sfu do not.

The problem is that overloading looks more like a bug than expected behaviour. Freeswitch was the main condumer of the CPU. Most attendees had both webcams and microphones turned on. Sound processing must not load the CPU much more than processing video.

**Comment by mikhailnov** [comment]
Running multiple Kurento instances - 3 instead of one, as bigbluebutton docs suggests - seems a strange idea to me. I would better run an instance of kurento per bigbluebutton session and would apply cgroup limitings by systemd to ensure that a kurento instance that performs a CPU usage spike does not overload the whole server.
