### ISSUE TITLE
Can't run puppeteer tests

### ISSUE THREAD

**Issue by BrentBaccala** [bigbluebutton/bigbluebutton#13614]
**Describe the bug**
Looks like its trying to run Firefox, I'm thinking it needs a PUPPETEER_EXECUTABLE_PATH argument, but I don't know what to give it.

**To Reproduce**
1. git clone bigbluebutton
2. npm install
3. cp .env-template to .env and get it right
4. ./run.sh -t audio in bigbluebutton-tests/puppeteer
**Expected behavior**
The puppeteer tests run

**Actual behavior**
```
console.log
    31-Oct-2021 13:26:43  Error: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
        at ChromeLauncher.launch (/home/baccala/src/bigbluebutton-upstream/bigbluebutton-tests/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:79:23)
        at Audio.init (/home/baccala/src/bigbluebutton-upstream/bigbluebutton-tests/puppeteer/core/page.js:53:24)
        at Object.<anonymous> (/home/baccala/src/bigbluebutton-upstream/bigbluebutton-tests/puppeteer/audio/audio.obj.js:20:7)

      at Audio.logger (core/page.js:406:15)

  console.log
    31-Oct-2021 13:26:43  TypeError: Cannot read property 'waitForSelector' of undefined
        at Audio.waitForSelector (/home/baccala/src/bigbluebutton-upstream/bigbluebutton-tests/puppeteer/core/page.js:418:21)
        at Audio.waitAndClick (/home/baccala/src/bigbluebutton-upstream/bigbluebutton-tests/puppeteer/core/page.js:322:16)
        at Object.joinAudio (/home/baccala/src/bigbluebutton-upstream/bigbluebutton-tests/puppeteer/audio/util.js:6:14)
        at Audio.test (/home/baccala/src/bigbluebutton-upstream/bigbluebutton-tests/puppeteer/audio/audio.js:10:17)
        at Object.<anonymous> (/home/baccala/src/bigbluebutton-upstream/bigbluebutton-tests/puppeteer/audio/audio.obj.js:22:29)

      at Audio.logger (core/page.js:406:15)

  console.log
    31-Oct-2021 13:26:44  begin of  joinWithMicrophone

      at Audio.logger (core/page.js:406:15)
```
then when I google around I find this: https://github.com/mrafiqk/html-pdf-node/issues/9

so I try this:

```
baccala@osito:~/src/bigbluebutton-upstream/bigbluebutton-tests/puppeteer$ PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome ./run.sh -t audio
Test is starting in 5 seconds...
 Test has started.
/home/baccala/src/bigbluebutton-upstream/bigbluebutton-tests/puppeteer
  console.log
    31-Oct-2021 13:29:27  begin of  joinWithListenOnly

      at Audio.logger (core/page.js:406:15)

  console.log
    31-Oct-2021 13:29:28  Error: Tried to use PUPPETEER_EXECUTABLE_PATH env variable to launch browser but did not find any executable at: /usr/bin/google-chrome
        at ChromeLauncher.launch (/home/baccala/src/bigbluebutton-upstream/bigbluebutton-tests/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:79:23)
        at Audio.init (/home/baccala/src/bigbluebutton-upstream/bigbluebutton-tests/puppeteer/core/page.js:53:24)
        at Object.<anonymous> (/home/baccala/src/bigbluebutton-upstream/bigbluebutton-tests/puppeteer/audio/audio.obj.js:20:7)

      at Audio.logger (core/page.js:406:15)


```

**Comment by BrentBaccala** [comment]
I've gotten it working.  The main thing I was missing was `PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser`

Should this be required?  It isn't in the test suite's README.md

**Comment by ffdixon** [comment]
Hi Brent -- it looks like it should be there.  If you could send a pull request to fix (and anything else you think needs updating in the docs), that would be welcome!

**Comment by BrentBaccala** [comment]
Fred - are you suggesting that we should use `PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser` and this should be added to the documentation?

Using this solution runs the chromium browser on the host running the test suite, i.e, not in a docker container and not headless.  `./run.sh` must be run from a shell with an X11 display available.

Is this the desired behavior?

**Comment by BrentBaccala** [comment]
I don't think this is the expected behavior.

I've built a different virtual machine where the Puppeteer has a built-in Chromium web browser that runs when I don't specify `PUPPETEER_EXECUTABLE_PATH` but it doesn't have all its shared libraries until I 'apt install' more stuff.

**Comment by ffdixon** [comment]
I'll let some of the testing guys respond to your questions.

**Comment by MaximKhlobystov** [comment]
Hello Brent,
Using `PUPPETEER_EXECUTABLE_PATH` is definitely not desired. That would run it from the binary. Avoiding that is one of the main Puppeteer advantages for us, so the default Puppeteer configuration is supposed to be used.

**Comment by MaximKhlobystov** [comment]
It may be a bug in Puppeteer. What environment and operating system are you using?

**Comment by MaximKhlobystov** [comment]
We'll close this environment-specific issue. Our main development focus shifted to Playwright tests. We'll keep an eye on how they run in various environments to spot potential issues in the future.
