### ISSUE TITLE
bbb-html5-backend@2 failed

### ISSUE THREAD

**Issue by vahidajorloo** [bigbluebutton/bigbluebutton#13959]
my bbb server is very slow and i dont know its greenlight or bbb itself that causing problem , when i run `bbb-conf --status` the `bbb-html5-backend@2 `status is failed. below is the output of `systemctl status bbb-html5-backend@2` , what should i do to solve this?

```
systemctl status bbb-html5-backend@2
● bbb-html5-backend@2.service - BigBlueButton HTML5 service, backend instance 2
   Loaded: loaded (/usr/lib/systemd/system/bbb-html5-backend@.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2021-12-21 06:49:58 UTC; 17min ago
  Process: 6025 ExecStart=/usr/share/meteor/bundle/systemd_start.sh 2 $BACKEND_NODEJS_ROLE (code=exited, status=1/FAILURE)
 Main PID: 6025 (code=exited, status=1/FAILURE)

Dec 21 06:49:58 tehranserver systemd_start.sh[6025]:  {"allowDefaultLogoutUrl":true,"allowFullscreen":true,"allowLogout":true,"allowUserLookup":false,"appName":"BigBlueButton H
Dec 21 06:49:58 tehranserver systemd_start.sh[6025]: error: uncaughtException: listen EADDRINUSE: address already in use 127.0.0.1:3000
Dec 21 06:49:58 tehranserver systemd_start.sh[6025]: Error: listen EADDRINUSE: address already in use 127.0.0.1:3000
Dec 21 06:49:58 tehranserver systemd_start.sh[6025]:     at Server.setupListenHandle [as _listen2] (net.js:1309:16)
Dec 21 06:49:58 tehranserver systemd_start.sh[6025]:     at listenInCluster (net.js:1357:12)
Dec 21 06:49:58 tehranserver systemd_start.sh[6025]:     at doListen (net.js:1496:7)
Dec 21 06:49:58 tehranserver systemd_start.sh[6025]:     at processTicksAndRejections (internal/process/task_queues.js:85:21) {"date":"Tue Dec 21 2021 06:49:58 GMT+0000 (Coordi
Dec 21 06:49:58 tehranserver systemd_start.sh[6025]: error: uncaughtException: Error: listen EADDRINUSE: address already in use 127.0.0.1:3000
Dec 21 06:49:58 tehranserver systemd[1]: bbb-html5-backend@2.service: Main process exited, code=exited, status=1/FAILURE
Dec 21 06:49:58 tehranserver systemd[1]: bbb-html5-backend@2.service: Failed with result 'exit-code'.
lines 1-16/16 (END)

```

im runing bbb 2.3.15 on a powerful server and its not about resources

**Comment by antobinary** [comment]
Hi @vahidajorloo 

> `Error: listen EADDRINUSE: address already in use 127.0.0.1:3000`

I typically see similar error if I am running bbb-html5 manually (dev env `npm start`) and then restart BBB (or just bbb-html5 service).

Please post the result of `sudo bbb-conf --status` if this remains an issue after you confirm there's no `npm start` in another terminal and after a bbb restart
