### ISSUE TITLE
bbb 2.3 - bbb-playback-screenshare: workflow in error

### ISSUE THREAD

**Issue by jgribonvald** [bigbluebutton/bigbluebutton#14018]
**Describe the bug**
The screenshare process fail and it doesn't produce any element of the process.

#### The logs:
in file `/var/log/bigbluebutton/screenshare/process-{a_private_id}.log`
```
I, [2022-01-07T10:25:19.414827 #48950]  INFO -- : Executing: ffmpeg -y -v warning -nostats -max_error_rate 1.0 -filter_complex color\=c\=white:s\=1280x720:r\=,trim\=end\=20.669 -an -codec libx264 -preset veryfast -crf 30 -force_key_frames expr:gte\(t,n_forced\*10\) -pix_fmt yuv420p -r '' /var/bigbluebutton/recording/process/screenshare/{a private id}/video_0.mp4
I, [2022-01-07T10:25:19.429845 #48950]  INFO -- : [color @ 0x56488a983000] Unable to parse option value "" as video rate
I, [2022-01-07T10:25:19.429889 #48950]  INFO -- :     Last message repeated 1 times
I, [2022-01-07T10:25:19.429901 #48950]  INFO -- : [color @ 0x56488a983000] Error setting option r to value .
I, [2022-01-07T10:25:19.429912 #48950]  INFO -- : [Parsed_color_0 @ 0x56488a982f00] Error applying options to the filter.
I, [2022-01-07T10:25:19.429927 #48950]  INFO -- : [AVFilterGraph @ 0x56488a982c40] Error initializing filter 'color' with args 'c=white:s=1280x720:r='
I, [2022-01-07T10:25:19.429937 #48950]  INFO -- : Error initializing complex filters.
I, [2022-01-07T10:25:19.429946 #48950]  INFO -- : Invalid argument
I, [2022-01-07T10:25:19.430997 #48950]  INFO -- : Success?: false
I, [2022-01-07T10:25:19.431016 #48950]  INFO -- : Process exited? true
I, [2022-01-07T10:25:19.431028 #48950]  INFO -- : Exit status: 1
E, [2022-01-07T10:25:19.431090 #48950] ERROR -- : ffmpeg failed, exit code 1
E, [2022-01-07T10:25:19.431111 #48950] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/edl/video.rb:561:in `composite_cut'
E, [2022-01-07T10:25:19.431122 #48950] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/edl/video.rb:261:in `block in render'
E, [2022-01-07T10:25:19.431131 #48950] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/edl/video.rb:255:in `each'
E, [2022-01-07T10:25:19.431149 #48950] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/edl/video.rb:255:in `render'
E, [2022-01-07T10:25:19.431153 #48950] ERROR -- : /usr/local/bigbluebutton/core/scripts/process/screenshare.rb:136:in `<main>'
```

**Configuration**

#### BBB package:
```
$ sudo bbb-conf --version

BigBlueButton Server 2.3.17 (2537)

ii  bbb-apps-akka                          2.3.0-108                                       all          BigBlueButton Apps (Akka)
ii  bbb-config                             1:2.3.0-102                                     amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                           1:2.3.0-53                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                    2:2.3.0-32                                      amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                  1:1.6.7-3                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                         2.3.0-59                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                              1:2.3.0-1865                                    amd64        The HTML5 components for BigBlueButton
ii  bbb-libreoffice-docker                 1:2.3.0-60                                      amd64        BigBlueButton setup for LibreOffice running in docker
ii  bbb-mkclean                            1:0.8.7-4                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback                           1:2.3.0-23                                      amd64        BigBlueButton playback
ii  bbb-playback-notes                     1:2.3.0-4                                       amd64        BigBluebutton playback of notes
ii  bbb-playback-podcast                   1:2.3.0-3                                       amd64        BigBluebutton playback in podcast
ii  bbb-playback-presentation              1:2.3.0-13                                      amd64        BigBluebutton playback of presentation
ii  bbb-playback-screenshare               1:2.3.0-5                                       amd64        BigBluebutton playback of screenshare
ii  bbb-record-core                        1:2.3.0-38                                      amd64        BigBlueButton record and playback
ii  bbb-web                                1:2.3.0-103                                     amd64        BigBlueButton API
ii  bbb-webrtc-sfu                         1:2.3.0-44                                      amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                          1:2.3.0-7                                       amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                 7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                     7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                    7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                     7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                    7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                   7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                      7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                            0.2.1-1bbb1                                     amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                    7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                   7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                      7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg library for image scaling and various conversions - runtime files
```

**Comment by jgribonvald** [comment]
Sorry it's a duplicate of #13356
