### ISSUE TITLE
Some recordings are not published by BBB

### ISSUE THREAD

**Issue by invokablegmbh** [bigbluebutton/bigbluebutton#14151]
On some of our production servers running 2.4.1 we sometimes see the following error.

**Describe the bug**
Some recordings will fail the publishing process in BBB.

**To Reproduce**
We cannot reproduce this behaviour. All of our tests (doing polls while recording etc.) were processed successfully.

**Expected behavior**
Recordings should be converted and published successfully.

**Actual behavior**
Recordings will stay in "processed" state and a file "RECORDINGID.failed" will be created inside the /var/bigbluebutton/recording/status/published folder.
Logs provided below.

**We isolated one of these production servers for the next 48 hours. So we can provide more info in case it is needed.**

**Logs**
_Meeting-IDs / Recording-IDs were masked at the end._

```
I, [2022-01-19T22:53:47.041557 #151233]  INFO -- : Success?: true
I, [2022-01-19T22:53:47.041599 #151233]  INFO -- : Process exited? true
I, [2022-01-19T22:53:47.041614 #151233]  INFO -- : Exit status: 0
I, [2022-01-19T22:53:47.041735 #151233]  INFO -- : Draw 65 Shape 65 Type poll_result from 500.0 to  undo
I, [2022-01-19T22:53:47.041882 #151233]  INFO -- : Executing: utils/gen_poll_svg -i /var/bigbluebutton/recording/process/presentation/b76b520a37d539e9ef94b8cXXXXBLANKEDXXXX-1642626336066/poll_result65.json -w 544 -h 60 -n 1 -o /var/bigbluebutton/recording/process/presentation/b76b520a37d539e9ef94b8cXXXXBLANKEDXXXX-1642626336066/presentation/d2d9a672040fbde2a47a10bXXXXBLANKEDXXXX-1642626336070/poll_result65.svg
I, [2022-01-19T22:53:47.099002 #151233]  INFO -- : Success?: true
I, [2022-01-19T22:53:47.099062 #151233]  INFO -- : Process exited? true
I, [2022-01-19T22:53:47.099075 #151233]  INFO -- : Exit status: 0
I, [2022-01-19T22:53:47.099200 #151233]  INFO -- : Draw 66 Shape 66 Type poll_result from 561.1 to  undo
I, [2022-01-19T22:53:47.099317 #151233]  INFO -- : Executing: utils/gen_poll_svg -i /var/bigbluebutton/recording/process/presentation/b76b520a37d539e9ef94b8cXXXXBLANKEDXXXX-1642626336066/poll_result66.json -w 544 -h 60 -n 1 -o /var/bigbluebutton/recording/process/presentation/b76b520a37d539e9ef94b8cXXXXBLANKEDXXXX-1642626336066/presentation/d2d9a672040fbde2a47a10bXXXXBLANKEDXXXX-1642626336070/poll_result66.svg
I, [2022-01-19T22:53:47.156364 #151233]  INFO -- : Success?: true
I, [2022-01-19T22:53:47.156410 #151233]  INFO -- : Process exited? true
I, [2022-01-19T22:53:47.156437 #151233]  INFO -- : Exit status: 0
I, [2022-01-19T22:53:47.156558 #151233]  INFO -- : Draw 67 Shape 67 Type poll_result from 602.8 to  undo
I, [2022-01-19T22:53:47.156667 #151233]  INFO -- : Executing: utils/gen_poll_svg -i /var/bigbluebutton/recording/process/presentation/b76b520a37d539e9ef94b8cXXXXBLANKEDXXXX-1642626336066/poll_result67.json -w 544 -h 60 -n 1 -o /var/bigbluebutton/recording/process/presentation/b76b520a37d539e9ef94b8cXXXXBLANKEDXXXX-1642626336066/presentation/d2d9a672040fbde2a47a10bXXXXBLANKEDXXXX-1642626336070/poll_result67.svg
I, [2022-01-19T22:53:47.213477 #151233]  INFO -- : Success?: true
I, [2022-01-19T22:53:47.213528 #151233]  INFO -- : Process exited? true
I, [2022-01-19T22:53:47.213551 #151233]  INFO -- : Exit status: 0
I, [2022-01-19T22:53:47.213665 #151233]  INFO -- : Draw 68 Shape 68 Type poll_result from 733.4 to  undo
I, [2022-01-19T22:53:47.214850 #151233]  INFO -- : Executing: utils/gen_poll_svg -i /var/bigbluebutton/recording/process/presentation/b76b520a37d539e9ef94b8cXXXXBLANKEDXXXX-1642626336066/poll_result68.json -w 544 -h 0 -n 0 -o /var/bigbluebutton/recording/process/presentation/b76b520a37d539e9ef94b8cXXXXBLANKEDXXXX-1642626336066/presentation/d2d9a672040fbde2a47a10bXXXXBLANKEDXXXX-1642626336070/poll_result68.svg
I, [2022-01-19T22:53:47.307334 #151233]  INFO -- : Traceback (most recent call last):
I, [2022-01-19T22:53:47.307649 #151233]  INFO -- :   File "utils/gen_poll_svg", line 243, in <module>
I, [2022-01-19T22:53:47.307666 #151233]  INFO -- :     main()
I, [2022-01-19T22:53:47.307677 #151233]  INFO -- :   File "utils/gen_poll_svg", line 238, in main
I, [2022-01-19T22:53:47.307686 #151233]  INFO -- :     args.output, args.num_responders, args.width, args.height, poll_data
I, [2022-01-19T22:53:47.307697 #151233]  INFO -- :   File "utils/gen_poll_svg", line 118, in draw_poll_result
I, [2022-01-19T22:53:47.307705 #151233]  INFO -- :     bar_height = (height - POLL_VPADDING) / len(poll_data) - POLL_VPADDING
I, [2022-01-19T22:53:47.307714 #151233]  INFO -- : ZeroDivisionError: float division by zero
I, [2022-01-19T22:53:47.321354 #151233]  INFO -- : Success?: false
I, [2022-01-19T22:53:47.321403 #151233]  INFO -- : Process exited? true
I, [2022-01-19T22:53:47.321414 #151233]  INFO -- : Exit status: 1
E, [2022-01-19T22:53:47.321440 #151233] ERROR -- : Failed to generate poll svg
E, [2022-01-19T22:53:47.321463 #151233] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:380:in `svg_render_shape_poll'
E, [2022-01-19T22:53:47.321479 #151233] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:421:in `svg_render_shape'
E, [2022-01-19T22:53:47.321486 #151233] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:468:in `block in svg_render_image'
E, [2022-01-19T22:53:47.321493 #151233] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:467:in `each'
E, [2022-01-19T22:53:47.321500 #151233] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:467:in `svg_render_image'
E, [2022-01-19T22:53:47.321507 #151233] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:1045:in `processPresentation'
E, [2022-01-19T22:53:47.321514 #151233] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:1411:in `<main>'
E, [2022-01-19T22:53:47.321529 #151233] ERROR -- : exit
E, [2022-01-19T22:53:47.321540 #151233] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:1451:in `exit'
E, [2022-01-19T22:53:47.321547 #151233] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:1451:in `rescue in <main>'
E, [2022-01-19T22:53:47.321553 #151233] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:1273:in `<main>'
```

The file /var/bigbluebutton/recording/process/presentation/b76b520a37d539e9ef94b8cXXXXBLANKEDXXXX-1642626336066/poll_result68.json just contains a "[]".

**Comment by antobinary** [comment]
Hmm, I think I was able to reproduce this.

If I am in a recordable meeting, start recording, create poll of type `User Response` and publish it with no responses, my recording will not process.

**Comment by invokablegmbh** [comment]
Hi! Thanks - and great news you found a bug!

I checked the events.xml and saw that the user did loads of polls (of different types). Without writing a script and parsing the XML I would not be able to verify whether there is a poll without answers. Unfortunately I do not have that much time today. Maybe I can write a script next week.

Or do you have any other clues how to find out whether there was a poll without any answer?

**Comment by invokablegmbh** [comment]
Issue seems to be solved in newest release of bbb. Closing & a big thanks!
