### ISSUE TITLE
[2.4] Client crashes on meeting end

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#14267]
**Describe the bug**

If a meeting is ended via the `End meeting` action, the client crashes instead of being redirected to the end view (feedback view, etc)

**To Reproduce**
1. Join a meeting
2. End the meeting via Settings -> End meeting -> Yes
3. Client crashes

**Expected behavior**

No crash, proper end view is shown.

**Actual behavior**
Client crashes, blue screen.

**BBB version:**

Branch v2.4.x-release HEAD @ fc5d727

**Desktop (please complete the following information):**

n/a

**Smartphone (please complete the following information):**

n/a

**Additional context**

Stack trace from a "prod" env:
```
TypeError: Cannot read properties of undefined (reading 'changed')
    at a.removeItem (a79b79763f20f318a4c70b6ab8373a0fa61b0581.js:375:1467257)
    at new I (a79b79763f20f318a4c70b6ab8373a0fa61b0581.js:375:1000955)
    at Fi (a79b79763f20f318a4c70b6ab8373a0fa61b0581.js:61:50413)
    at ol (a79b79763f20f318a4c70b6ab8373a0fa61b0581.js:61:67849)
    at Ss (a79b79763f20f318a4c70b6ab8373a0fa61b0581.js:61:105807)
    at Us (a79b79763f20f318a4c70b6ab8373a0fa61b0581.js:61:97613)
    at Ws (a79b79763f20f318a4c70b6ab8373a0fa61b0581.js:61:97538)
    at Rs (a79b79763f20f318a4c70b6ab8373a0fa61b0581.js:61:94463)
    at a79b79763f20f318a4c70b6ab8373a0fa61b0581.js:61:46070
    at n.unstable_runWithPriority (a79b79763f20f318a4c70b6ab8373a0fa61b0581.js:79:3854)
```

Stack trace from a dev env:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'changed')
    at StorageTracker.removeItem (app.js:83891:33)
    at new MeetingEnded (app.js:58466:13)
    at constructClassInstance (modules.js:20145:18)
    at updateClassComponent (modules.js:24365:5)
    at beginWork (modules.js:25885:16)
    at HTMLUnknownElement.callCallback (modules.js:7453:14)
    at Object.invokeGuardedCallbackDev (modules.js:7502:16)
    at invokeGuardedCallback (modules.js:7557:31)
    at beginWork$1 (modules.js:30468:7)
    at performUnitOfWork (modules.js:29419:12)
modules.js?hash=664c6ac7d85e27e59a0e729c45c4867dc12fa590:26792 The above error occurred in the <MeetingEnded> component:
    in MeetingEnded (created by Context.Consumer)
    in injectIntl(MeetingEnded) (created by Base)
    in Base (created by Context.Consumer)
    in Unknown
    in ContextProvider
    in Unknown (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent
    in IntlProvider (created by IntlStartup)
    in IntlStartup (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent
    in Subscriptions (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent
    in AuthenticatedHandler
    in JoinHandler
    in ChatContextProvider (created by ContextProvidersComponent)
    in GroupChatContextProvider (created by ContextProvidersComponent)
    in UsersContextProvider (created by ContextProvidersComponent)
    in ContextProvidersComponent

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

**Comment by antobinary** [comment]
Nice catch! Phew!
