### ISSUE TITLE
Exception while invoking method userUnshareWebcam

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/bigbluebutton#14308]
**Describe the bug**
On a machine with mediasoup, bbb-html5-frontends throws the following exception in our logs intermittently:

```
error: Exception while invoking method userUnshareWebcam Error: Match error: Expected string, got undefined
    at check (packages/check/match.js:36:17)
    at MethodInvocation.userUnshareWebcam (imports/api/video-streams/server/methods/userUnshareWebcam.js:14:5)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)
    at packages/ddp-server/livedata_server.js:769:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/ddp-server/livedata_server.js:767:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/ddp-server/livedata_server.js:765:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:739:23)
    at packages/ddp-server/livedata_server.js:603:43
```
It's not happening often, but at least 5 times per day and frontend thread. I was unsuccessful at reproducing this at will.

**BBB version:**

BigBlueButton Server 2.4.2

**Prelim. Analysis**

The crash seems to occur at:
```
check(meetingId, String);
```

because meetingId is undefined. This is a result from

```
const { meetingId, requesterUserId } = extractCredentials(this.userId);
```

where in turn

```
export const extractCredentials = (credentials) => {
  if (!credentials) return {};
```

so likely the `credentials` argument is undefined/null already. Did not yet have time to dig deeper than this.

Regardless, this should be fixed. Also, what is the severity of this crash? Will it impact all users on that frontend?

**Comment by prlanzarin** [comment]
> Regardless, this should be fixed. Also, what is the severity of this crash? Will it impact all users on that frontend?

Severity should be low because this _shouldn't_ be a crash since the error is wrapped into a try-catch for that reason (and the log error you're seeing comes from the catch clause).

Have you confirmed the service actually _crashes_ or does is it just the exception that's thrown (the expected behavior)?

**Comment by danimo** [comment]
No just logged. I cannot correlate this to a crash. But why would it occur anyway?

**Comment by prlanzarin** [comment]
> No just logged. I cannot correlate this to a crash. But why would it occur anyway?


Probably just a race condition between a client disconnection and the client-side camera cleanup condition (that method is triggered by a client call and is specifically bound to some browser unload/offline events). I've not delved further so there might be a different reason. Has happened for a while (at least 2.2), benign AFAIK. 

That was one of the reason all client methods were wrapped with try-catches in 2.3 as far as I remember (it can happen with basically any method depending on how the client calls it).

**Comment by yashodhank** [comment]
**BBB version:**
BigBlueButton Server 2.5.8

I see these in my `/var/log/syslog`
```
Dec 17 13:00:22 bbb systemd_start_frontend.sh[36589]: 2022-12-17T07:30:22.302Z frontend-1 [#033[31merror#033[39m] : Exception while invoking method userUnshareWebcam Error: Match error: Expected string, got undefined
Dec 17 13:00:22 bbb systemd_start_frontend.sh[36589]: 2022-12-17T07:30:22.302Z frontend-3 [#033[31merror#033[39m] : Exception while invoking method userUnshareWebcam Error: Match error: Expected string, got undefined
Dec 17 13:00:22 bbb systemd_start_frontend.sh[36589]: 2022-12-17T07:30:22.311Z frontend-4 [#033[31merror#033[39m] : Exception while invoking method userUnshareWebcam Error: Match error: Expected string, got undefined
Dec 17 13:00:22 bbb systemd_start_frontend.sh[36589]: 2022-12-17T07:30:22.311Z frontend-2 [#033[31merror#033[39m] : Exception while invoking method userUnshareWebcam Error: Match error: Expected string, got undefined
Dec 17 13:00:22 bbb systemd_start_frontend.sh[36589]: 2022-12-17T07:30:22.320Z frontend-3 [#033[31merror#033[39m] : Exception while invoking method userUnshareWebcam Error: Match error: Expected string, got undefined
Dec 17 13:00:22 bbb systemd_start_frontend.sh[36589]: 2022-12-17T07:30:22.329Z frontend-4 [#033[31merror#033[39m] : Exception while invoking method userUnshareWebcam Error: Match error: Expected string, got undefined
Dec 17 13:00:22 bbb systemd_start_frontend.sh[36589]: 2022-12-17T07:30:22.329Z frontend-4 [#033[31merror#033[39m] : Exception while invoking method userUnshareWebcam Error: Match error: Expected string, got undefined
Dec 17 13:00:22 bbb systemd_start_frontend.sh[36589]: 2022-12-17T07:30:22.330Z frontend-4 [#033[31merror#033[39m] : Exception while invoking method userUnshareWebcam Error: Match error: Expected string, got undefined
Dec 17 13:00:22 bbb systemd_start_frontend.sh[36589]: 2022-12-17T07:30:22.330Z frontend-4 [#033[31merror#033[39m] : Exception while invoking method userUnshareWebcam Error: Match error: Expected string, got undefined
Dec 17 13:00:22 bbb systemd_start_frontend.sh[36589]: 2022-12-17T07:30:22.338Z frontend-4 [#033[31merror#033[39m] : Exception while invoking method userUnshareWebcam Error: Match error: Expected string, got undefined
Dec 17 13:00:22 bbb systemd_start_frontend.sh[36589]: 2022-12-17T07:30:22.338Z frontend-4 [#033[31merror#033[39m] : Exception while invoking method userUnshareWebcam Error: Match error: Expected string, got undefined
```

**Comment by eric-it6** [comment]
The same here with BBB 2.5.12:
```
Feb 23 09:52:55 hostname systemd_start_frontend.sh[132724]: 2023-02-23T08:52:55.089Z frontend-1 [#033[31merror#033[39m] : Exception while invoking method userUnshareWebcam Error: Match error: Expected string, got undefined
Feb 23 09:52:55 hostname systemd_start_frontend.sh[132724]:     at check (packages/check/match.js:36:17)
Feb 23 09:52:55 hostname systemd_start_frontend.sh[132724]:     at MethodInvocation.userUnshareWebcam (imports/api/video-streams/server/methods/userUnshareWebcam.js:14:5)
Feb 23 09:52:55 hostname systemd_start_frontend.sh[132724]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1902:12)
Feb 23 09:52:55 hostname systemd_start_frontend.sh[132724]:     at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:772:38)
Feb 23 09:52:55 hostname systemd_start_frontend.sh[132724]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
Feb 23 09:52:55 hostname systemd_start_frontend.sh[132724]:     at packages/ddp-server/livedata_server.js:791:46
Feb 23 09:52:55 hostname systemd_start_frontend.sh[132724]:     at new Promise (<anonymous>)
Feb 23 09:52:55 hostname systemd_start_frontend.sh[132724]:     at Session.method (packages/ddp-server/livedata_server.js:739:23)
Feb 23 09:52:55 hostname systemd_start_frontend.sh[132724]:     at packages/ddp-server/livedata_server.js:603:43
```
