### ISSUE TITLE
Dial-in users are not removed from participants list

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#14969]
**Describe the bug**
Telephone (dial-in) participants are not hidden when they have left the conference.

**To Reproduce**
1. Start a meeting on a server with a correct dial-in support
2. Join the meeting with a web user with full audio
3. Call into the conference via phone number (i.e. dial in)
4. hang up on the phone

**Expected behavior**
The phone user should no longer be part of the meeting after a few seconds.

**Actual behavior**
The participants list entry never disappears.

**Screenshots**
TODO

**BBB version:**
BigBlueButton Server 2.50-beta.2

**Additional context**
2.5.0-alpha.4 had this working correctly according to the reporter.
First reported in https://groups.google.com/g/bigbluebutton-dev/c/XXpSHfxjhKQ

**Comment by schrd** [comment]
I can verify this on a build of commit a8619fda20 (a bit newer than rc1). In MongoDB there are 3 entries in the `voiceCallStates` collection although there were only 1 browser user and one phone user since the start of the server:

~~~
rs0:PRIMARY> db.voiceCallStates.find()
{ "_id" : "nFYE3iLucuufvBR6x", "clientSession" : "1", "meetingId" : "10af2fbee3aa11ed489e38f0034d9cc8512a5188-1652094576313", "userId" : "w_8nkua7pw4xzm", "callState" : "IN_CONFERENCE", "voiceConf" : "01197" }
{ "_id" : "ctLMtsEEKR5FtfY8i", "clientSession" : "0", "meetingId" : "10af2fbee3aa11ed489e38f0034d9cc8512a5188-1652094576313", "userId" : "v_4", "callState" : "IN_CONFERENCE", "voiceConf" : "01197" }
{ "_id" : "qXXpjr9aSaBJKGrz2", "clientSession" : "0", "meetingId" : "10af2fbee3aa11ed489e38f0034d9cc8512a5188-1652094576313", "userId" : "", "callState" : "CALL_ENDED", "voiceConf" : "01197" }
~~~

The last one with the empty userId seems a bit suspicious. In the system journal I got these messages:

~~~
May 09 13:11:30 bbb systemd_start_frontend.sh[237195]:     at check (packages/check/match.js:36:17)
May 09 13:11:30 bbb systemd_start_frontend.sh[237195]:     at removeUser (imports/api/users/server/modifiers/removeUser.js:30:3)
May 09 13:11:30 bbb systemd_start_frontend.sh[237195]:     at EventEmitter.handleVoiceUpdate (imports/api/voice-users/server/handlers/leftVoiceUser.js:25:45)
May 09 13:11:30 bbb systemd_start_frontend.sh[237195]:     at EventEmitter.emitAsync (/usr/share/meteor/bundle/programs/server/npm/node_modules/eventemitter2/lib/eventemitter2.js:463:31)
May 09 13:11:30 bbb systemd_start_frontend.sh[237195]:     at MeetingMessageQueue.handleTask (imports/startup/server/redis.js:117:10)
May 09 13:11:30 bbb systemd_start_frontend.sh[237195]:     at imports/startup/server/redis.js:129:28
May 09 13:11:30 bbb systemd_start_frontend.sh[237195]:     at Queue.start (/usr/share/meteor/bundle/programs/server/npm/node_modules/queue/index.js:145:17)
May 09 13:11:30 bbb systemd_start_frontend.sh[237195]:     at Queue.<computed> [as push] (/usr/share/meteor/bundle/programs/server/npm/node_modules/queue/index.js:59:12)
May 09 13:11:30 bbb systemd_start_frontend.sh[237195]:     at MeetingMessageQueue.add (imports/startup/server/redis.js:128:16)
May 09 13:11:30 bbb systemd_start_frontend.sh[237195]:     at RedisPubSub.handleMessage (imports/startup/server/redis.js:283:61)
May 09 13:11:30 bbb systemd_start_frontend.sh[237195]:     at runWithEnvironment (packages/meteor.js:1320:24)
May 09 13:11:31 bbb systemd_start.sh[237232]: error: UserLeftVoiceConfToClientEvtMsg: Error: Match error: Expected string, got undefined
May 09 13:11:31 bbb systemd_start.sh[237232]:     at check (packages/check/match.js:36:17)
May 09 13:11:31 bbb systemd_start.sh[237232]:     at removeUser (imports/api/users/server/modifiers/removeUser.js:30:3)
May 09 13:11:31 bbb systemd_start.sh[237232]:     at EventEmitter.handleVoiceUpdate (imports/api/voice-users/server/handlers/leftVoiceUser.js:25:45)
May 09 13:11:31 bbb systemd_start.sh[237232]:     at EventEmitter.emitAsync (/usr/share/meteor/bundle/programs/server/npm/node_modules/eventemitter2/lib/eventemitter2.js:463:31)
May 09 13:11:31 bbb systemd_start.sh[237232]:     at MeetingMessageQueue.handleTask (imports/startup/server/redis.js:117:10)
May 09 13:11:31 bbb systemd_start.sh[237232]:     at imports/startup/server/redis.js:129:28
May 09 13:11:31 bbb systemd_start.sh[237232]:     at Queue.start (/usr/share/meteor/bundle/programs/server/npm/node_modules/queue/index.js:145:17)
May 09 13:11:31 bbb systemd_start.sh[237232]:     at Queue.<computed> [as push] (/usr/share/meteor/bundle/programs/server/npm/node_modules/queue/index.js:59:12)
May 09 13:11:31 bbb systemd_start.sh[237232]:     at MeetingMessageQueue.add (imports/startup/server/redis.js:128:16)
May 09 13:11:31 bbb systemd_start.sh[237232]:     at RedisPubSub.handleMessage (imports/startup/server/redis.js:330:63)
May 09 13:11:31 bbb systemd_start.sh[237232]:     at runWithEnvironment (packages/meteor.js:1320:24)
~~~

**Comment by antobinary** [comment]
Thank you for these logs and the confirmation @schrd !

**Comment by Proman-bbb** [comment]
what can i do to Fix it..?

**Comment by hostbbb** [comment]
@Proman-bbb - 2.5 is a early beta release, probably not suitable to field in production quite yet.  Looks like the fix will need to be evaluated by the core team.  @scrd was able to debug why its happening so thats great.   So if you need production bbb move to the 2.4.x branch.
