### ISSUE TITLE
[2.5] Some slides of presentation not selectable if image is embedded

### ISSUE THREAD

**Issue by timm2k** [bigbluebutton/bigbluebutton#15209]
**Describe the bug**
One of our professors has presentations with embedded JPEGs on slides which are not selectable by the whiteboard.
*Next* button has no action if a slide with embedded JPEG is next one. I can use page selector to jump over this silde.

**To Reproduce**
1. Start meeting as presenter
2. Upload presentation [presenation_example_1.pdf](https://github.com/bigbluebutton/bigbluebutton/files/8938594/presenation_example_1.pdf)
3. try to went thougt the presentation
4. See *error*

**Expected behavior**
All slides of presentation are shown by whiteboard.

**Actual behavior**
Slides with embedded JPEGs are not shown by whiteboard as with BBB 2.4.

**BBB version:**
`BigBlueButton Server 2.5.1 (3020)`

**Additional context**
An error message for each broken slide is thrown to journalctl:
```
Jun 20 06:32:20 bbbt01 systemd_start.sh[41133]: (node:41133) UnhandledPromiseRejectionWarning: Error: Match error: Expected string, got number in field content
Jun 20 06:32:20 bbbt01 systemd_start.sh[41133]:     at check (packages/check/match.js:36:17)
Jun 20 06:32:20 bbbt01 systemd_start.sh[41133]:     at addSlide (imports/api/slides/server/modifiers/addSlide.js:49:3)
Jun 20 06:32:20 bbbt01 systemd_start.sh[41133]:     at imports/api/presentations/server/modifiers/addPresentation.js:26:5
Jun 20 06:32:20 bbbt01 systemd_start.sh[41133]:     at /usr/share/meteor/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Jun 20 06:32:20 bbbt01 systemd_start.sh[41133]: (node:41133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 549)
```

Kind regards
Timm

**Comment by timm2k** [comment]
Hi @mvasylenko 

I can confirm the fix.
Thanks a lot! :+1: 

If someone needs this immedeatly, run `sed -i -e "/request\.data;/s/data;/data\.toString();/" /usr/share/meteor/bundle/programs/server/app/app.js` and `bbb-conf --restart` (if no useres are connected).

Kind regards
Timm
