### ISSUE TITLE
2.5.x - records is not published: Possible GEM error

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/bigbluebutton#15528]
fresh installed server records processed but not published

bbb-conf --check :
```
# Potential problems described below

#
# Warning: found 'Nil' message in recording processing logs.  Possible GEM errors
#
#  https://github.com/bigbluebutton/bigbluebutton/issues/14287
#
root@vc:~# journalctl -u bbb-rap-* | grep -q 'Nil'
```
I checked all required in /usr/local/bigbluebutton/core/scripts/publish/presentation.rb gems present in folder /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems

 journalctl -u bbb-rap-*
```
Aug 13 15:16:58 conf2 bbb-rap[139381]: Started worker publish for 4ccf4495b1f529642ee8e15d266fb8a5f697742f-1660403780906
Aug 13 15:16:58 conf2 bbb-rap[139381]: Running publish worker for 4ccf4495b1f529642ee8e15d266fb8a5f697742f-1660403780906:presentation
Aug 13 15:16:58 conf2 bbb-rap[139381]: Task: Getting external meeting id
Aug 13 15:16:58 conf2 bbb-rap[139381]: Task: Getting meeting metadata
Aug 13 15:16:58 conf2 bbb-rap[139381]: Executing: ruby /usr/local/bigbluebutton/core/scripts/publish/presentation.rb -m 4ccf4495b1f529642ee8e15d266fb8a5f697742f-1660403780906-presentation
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:42:in `<main>': undefined method `merge' for nil:NilClass (NoMethodError)
Aug 13 15:16:59 conf2 bbb-rap[139381]: Success?: false
Aug 13 15:16:59 conf2 bbb-rap[139381]: Process exited? true
Aug 13 15:16:59 conf2 bbb-rap[139381]: Exit status: 1
Aug 13 15:16:59 conf2 bbb-rap[139381]: Couldn't find the metadata file at /var/bigbluebutton/published/presentation/4ccf4495b1f529642ee8e15d266fb8a5f697742f-1660403780906/metadata.xml
Aug 13 15:16:59 conf2 bbb-rap[139381]: Task: Getting external meeting id
Aug 13 15:16:59 conf2 bbb-rap[139381]: Task: Getting meeting metadata
Aug 13 15:16:59 conf2 bbb-rap[139381]: Publish format failed for 4ccf4495b1f529642ee8e15d266fb8a5f697742f-1660403780906:presentation
Aug 13 15:16:59 conf2 bbb-rap[139381]: Ended worker publish for 4ccf4495b1f529642ee8e15d266fb8a5f697742f-1660403780906 with result false
Aug 13 15:16:59 conf2 bbb-rap[139381]: Worker publish for 4ccf4495b1f529642ee8e15d266fb8a5f697742f-1660403780906 failed with result false
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/lib/recordandplayback/workers/base_worker.rb:56:in `perform'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/lib/recordandplayback/workers/publish_worker.rb:28:in `perform'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/lib/recordandplayback/workers/base_worker.rb:44:in `perform'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/job.rb:168:in `perform'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/worker.rb:308:in `perform'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/worker.rb:897:in `block in perform_with_fork'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/worker.rb:895:in `fork'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/worker.rb:895:in `perform_with_fork'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/worker.rb:264:in `work_one_job'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/worker.rb:238:in `block in work'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/worker.rb:235:in `loop'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/worker.rb:235:in `work'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/tasks.rb:20:in `block (2 levels) in <top (required)>'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/bin/rake:23:in `load'
Aug 13 15:16:59 conf2 bbb-rap[139381]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/bin/rake:23:in `<main>'
Aug 13 15:16:59 conf2 bbb-rap[139381]: (Job{rap:publish} | BigBlueButton::Resque::PublishWorker | [{"meeting_id"=>"4ccf4495b1f529642ee8e15d266fb8a5f697742f-1660403780906", "single_step"=>f>
Aug 13 15:16:59 conf2 bundle[73599]: Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.

```

gems in project folder:
```
absolute_time-1.0.0
activesupport-5.2.8
bbbevents-1.2.0
builder-3.2.4
concurrent-ruby-1.1.10
crass-1.0.6
fastimage-2.2.6
ffi-1.15.5
i18n-1.10.0
java_properties-0.0.4
journald-logger-3.1.0
journald-native-1.0.12
jwt-2.3.0
locale-2.1.3
loofah-2.18.0
mini_portile2-2.8.0
minitest-5.14.4
mono_logger-1.1.1
multi_json-1.15.0
mustermann-1.1.1
nokogiri-1.13.6-x86_64-linux
open4-1.3.4
optimist-3.0.1
racc-1.6.0
rack-2.2.3.1
rack-protection-2.2.0
rake-13.0.6
rb-inotify-0.10.1
redis-4.6.0
redis-namespace-1.8.2
resque-2.0.0
ruby2_keywords-0.0.5
rubyzip-2.3.2
sinatra-2.2.0
thread_safe-0.3.6
tilt-2.0.10
tzinfo-1.2.9
vegas-0.1.11
```
could not find any solution on the link https://github.com/bigbluebutton/bigbluebutton/issues/14287

**Comment by amg-web** [comment]
problem located.
I used override configs as described here: https://docs.bigbluebutton.org/admin/configuration-files.html#local-overrides-for-configuration-settings
/etc/bigbluebutton/recording/presentation.yml
```
video_formats:
- webm
- mp4
```
/etc/bigbluebutton/recording/recording.yml
```
playback_host: hostname.com
playback_protocol: https
```

not sure which of 2 is faulty

**Comment by mleocunha** [comment]
Same problem in two different machines in two very diverse settings. So I guess it is indeed a bug.

**Comment by Dennis1993** [comment]
@amg-web I've have the same problem and I added the video format **mp4** for my recordings, because we use iPads and no one can start the playback if no mp4 available. So the problem should be the **video format mp4**.

**Comment by VsDims** [comment]
solve:
sudo journalctl --vacuum-files=1
bbb-conf --restart
:)
