### ISSUE TITLE
How to fix error Error: Could not connect to the configured hostname/IP address

### ISSUE THREAD

**Issue by Yoshi257** [bigbluebutton/bigbluebutton#16064]
Hello guys,
my installation worked but now i get the following error:

```
# Potential problems described below
 # Not running:  tomcat9 or grails
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    http:/myserver.com/
#
# If your BigBlueButton server is behind a firewall, see FAQ.
```

Trying to open this URL with my Browser works perfect.

Output of the #sudo bbb-conf --check:

```
BigBlueButton Server 2.5.8 (3139)
                    Kernel version: 5.4.0-132-generic
                      Distribution: Ubuntu 20.04.5 LTS (64-bit)
                            Memory: 8148 MB
                         CPU cores: 4

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: http://myserver.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true
              defaultMeetingLayout: CUSTOM_LAYOUT

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: localhost
                              port: 80, [::]:80

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: xxx.xxx.xxx.xxx
                   external_rtp_ip: xxx.xxx.xxx.xxx
                   external_sip_ip: xxx.xxx.xxx.xxx

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: myserver.com
                 playback_protocol: http
                            ffmpeg: 4.2.7-0ubuntu0.1

/usr/share/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: xxx.xxx.xxx.xxx
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
/etc/bigbluebutton/bbb-webrtc-sfu/production.yml (Kurento SFU - override)
                        kurento.ip: xxx.xxx.xxx.xxx
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: xxx.xxx.xxx.xxx
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)
                             build: 2870
                        kurentoUrl: wss://myserver.com/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: false

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun: stun.l.google.com:19302
```

Output of #sudo bbb-conf --status:
```

nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
bbb-html5-backend@1 ———► [✔ - active]
bbb-html5-backend@2 ———► [✔ - active]
bbb-html5-frontend@1 ——► [✔ - active]
bbb-html5-frontend@2 ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
bbb-pads ——————————————► [✔ - active]
bbb-rap-caption-inbox —► [✔ - active]
bbb-rap-resque-worker —► [✔ - active]
bbb-rap-starter ———————► [✔ - active]
```

Considering the /var/log/nginx folder:
The bigbluebutton.access.log is empty, but the error.log (after trying to create a session one time):

```
2022/11/29 12:44:41 [error] 756#756: *84 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Unhandled curl error: Could not resolve host: api in /home/yoshi/bbb/vendo>
Stack trace:
#0 /home/yoshi/bbb/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php(115): BigBlueButton\BigBlueButton->processXmlResponse()
#1 /var/www/bigbluebutton-default/test/join-bbb.php(28): BigBlueButton\BigBlueButton->createMeeting()
#2 {main}
  thrown in /home/yoshi/bbb/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 487" while reading response header from upstream, client: 95.222.25.68, server: bbb.v220221118737>
```

Would be glad if you can help me with my problem.

Regards
Yoshi

**Comment by hostbbb** [comment]
you need to go to the google forums.  bigbluebutton-setup and ask questions. this is for software issues and reporting bugs, enhancements etc.

**Comment by Yoshi257** [comment]
k thx
