### ISSUE TITLE
Join issues 

### ISSUE THREAD

**Issue by Davka** [bigbluebutton/bigbluebutton#16452]
**Describe the bug**
We have a 2.5.11 here and certain users who are behind a restrictive firewall cannot join the meeting. 

There is no errors. The user is stuck in the echo test for a long time. Once through, the audio devices are not displayed.

Unfortunately I don't have an exceptions from the browser console.

In the server log I found

```
8508","logCode":"handle_enter_api","name":"XXXX","sessionToken":"rnxjfddddwef3qvt","description":"Handling ENTER API.","meetingid":"xxx1","userid":"xxx"}
Jan 11 09:00:37 server6 systemd_start_frontend.sh[5586]: 2023-01-11T08:00:37.231Z frontend-2 [#033[31merror#033[39m] : Exception while invoking method chatMessageBeforeJoinCounte
r Error: Match error: Expected string, got undefined
Jan 11 09:00:37 server6 systemd_start_frontend.sh[5586]:     at check (packages/check/match.js:36:17)
Jan 11 09:00:37 server6 systemd_start_frontend.sh[5586]:     at MethodInvocation.chatMessageBeforeJoinCounter (imports/api/group-chat-msg/server/methods/chatMessageBeforeJoinCoun
ter.js:16:5)
Jan 11 09:00:37 server6 systemd_start_frontend.sh[5586]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1902:12)
Jan 11 09:00:37 server6 systemd_start_frontend.sh[5586]:     at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:772:38)
Jan 11 09:00:37 server6 systemd_start_frontend.sh[5586]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
Jan 11 09:00:37 server6 systemd_start_frontend.sh[5586]:     at packages/ddp-server/livedata_server.js:791:46
Jan 11 09:00:37 server6 systemd_start_frontend.sh[5586]:     at new Promise (<anonymous>)
Jan 11 09:00:37 server6 systemd_start_frontend.sh[5586]:     at Session.method (packages/ddp-server/livedata_server.js:739:23)
Jan 11 09:00:37 server6 systemd_start_frontend.sh[5586]:     at packages/ddp-server/livedata_server.js:603:43
````

**To Reproduce**
I can't reproduce this yet

** Browser **

Microsoft Edge

**Comment by schrd** [comment]
I also see this kind stack trace from time to time (once a day per server or so). It is prepended by these log lines:

~~~
Jan 11 22:28:34 bbbserver systemd_start_frontend.sh[2468]: 2023-01-11T21:28:34.391Z frontend-3 [warn] : Publishing Polls was requested by unauth connection LmTRNBhpp55KChwjK
Jan 11 22:28:34 bbbserver systemd_start_frontend.sh[2468]: 2023-01-11T21:28:34.400Z frontend-3 [info] : Upserted {"meetingId":"xxxx","userId":"xxxxx","connectionId":"LmTRNBhpp55KChwjK"} 2 in AuthTokenValidation
Jan 11 22:28:34 bbbserver systemd_start_frontend.sh[2468]: 2023-01-11T21:28:34.401Z frontend-3 [info] : User 'xxxxx' is trying to validate auth token for meeting 'xxxx' from connection 'LmTRNBhpp55KChwjK'
~~~

I looked into the akka apps log and there were no events at that time. When I grepped for the meeting ID I saw that the meeting started hours before this log entry. It also ended hours before these log entries.

After the meeting ended the following log message appeared in the akka log:
~~~
2023-01-11T17:10:32.120+01:00 INFO  akka.actor.LocalActorRef - Message [org.bigbluebutton.core.running.MeetingActor$SyncVoiceUserStatusInternalMsg$] from Actor[akka://bigbluebutton-apps-system/user/bigbluebutton-actor/xxxx#-704966967] to Actor[akka://bigbluebutton-apps-system/user/bigbluebutton-actor/xxxx#-704966967] was not delivered. [3] dead letters encountered. If this is not an expected behavior then Actor[akka://bigbluebutton-apps-system/user/bigbluebutton-actor/xxxx#-704966967] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
~~~

The userid started joining as a guest user in the waiting room.

Hope this helps.
