### ISSUE TITLE
Local docs build contained cached content

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#17057]
**Describe the bug**
I was using `yarn install` and `yarn start` to work on the new docs.
`yarn build` reported broken links that had actually been fixed.

I looked at whether `yarn build` was using old files in the report. As a result I deleted `/build`, `/versioned_docs/`, `/versioned_sidebars/`.

This time I could not build at all.

```
anton@x:~/bbb26/bigbluebutton/docs$ yarn build
yarn run v1.22.19
warning package.json: No license field
$ docusaurus build

   ╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                       │
   │                                            Update available 2.2.0 → 2.3.1                                             │
   │                                                                                                                       │
   │                   To upgrade Docusaurus packages with the latest version, run the following command:                  │
   │     `yarn upgrade @docusaurus/core@latest @docusaurus/preset-classic@latest @docusaurus/module-type-aliases@latest`   │
   │                                                                                                                       │
   ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

[INFO] [en] Creating an optimized production build...
[ERROR] Loading of version failed for version 2.6
[ERROR] Unable to build website for locale en.
[ERROR] Error: Docs version "2.6" has no docs! At least one doc should exist at "versioned_docs/version-2.6".
    at loadVersionDocsBase (/home/anton/bbb26/bigbluebutton/docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:75:27)
    at async doLoadVersion (/home/anton/bbb26/bigbluebutton/docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:89:34)
    at async loadVersion (/home/anton/bbb26/bigbluebutton/docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:113:28)
    at async Promise.all (index 1)
    at async Object.loadContent (/home/anton/bbb26/bigbluebutton/docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:121:33)
    at async /home/anton/bbb26/bigbluebutton/docs/node_modules/@docusaurus/core/lib/server/plugins/index.js:35:25
    at async Promise.all (index 0)
    at async loadPlugins (/home/anton/bbb26/bigbluebutton/docs/node_modules/@docusaurus/core/lib/server/plugins/index.js:34:27)
    at async load (/home/anton/bbb26/bigbluebutton/docs/node_modules/@docusaurus/core/lib/server/index.js:76:58)
    at async buildLocale (/home/anton/bbb26/bigbluebutton/docs/node_modules/@docusaurus/core/lib/commands/build.js:84:19)
[INFO] Docusaurus version: 2.2.0
Node version: v16.19.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

What I had to do to overcome this was to **also delete versions.json** which had kept the expectations I have a local 2.6 build.
Following this with `yarn build` worked correctly.

**Questions**

Now,
Question 1) -- in order to avoid local cache wasting people's time, would it make sense to include the steps to remove `/build`, `/versioned_docs/`, `/versioned_sidebars/` and `versions.json` ?
Question 2) -- perhaps this would have been much easier to spot if `versions.json` was not blacklisted in `.gitignore`. If we were to commit this file and exclude it from `.gitignore`, I think deleting the dirs would have no negative consequences.
Comments welcome! cc @tibroc

**Comment by antobinary** [comment]
Never mind -- I just discovered `yarn clear` and another few in `package.json`. I will add a note in the docs to clear cache when starting out to avoid cache issues.
