### ISSUE TITLE
docusaurus start - It is not possible to use docs without any version. 

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#17321]
When trying to use docusaurus locally, specifically for the first time. Hit by @scouillard and now by me on a new branch.
`npm i; yarn clear; yarn build; yarn start` does not resolve it;

```
$ docusaurus start

   ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                                                                  │
   │                                                                  Update available 2.2.0 → 2.4.0                                                                  │
   │                                                                                                                                                                  │
   │                                         To upgrade Docusaurus packages with the latest version, run the following command:                                       │
   │     `yarn upgrade @docusaurus/core@latest @docusaurus/plugin-client-redirects@latest @docusaurus/preset-classic@latest @docusaurus/module-type-aliases@latest`   │
   │                                                                                                                                                                  │
   ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

[INFO] Starting the development server...
[ERROR] Error: It is not possible to use docs without any version. No version is included because you have requested to not include /home/anton/bbb26/bigbluebutton/docs/docs through "includeCurrentVersion: false", while the versions file is empty/non-existent.
    at readVersionNames (/home/anton/bbb26/bigbluebutton/docs/node_modules/@docusaurus/plugin-content-docs/lib/versions/files.js:95:15)
    at async readVersionsMetadata (/home/anton/bbb26/bigbluebutton/docs/node_modules/@docusaurus/plugin-content-docs/lib/versions/index.js:146:29)
    at async Object.pluginContentDocs [as plugin] (/home/anton/bbb26/bigbluebutton/docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:32:30)
    at async initializePlugin (/home/anton/bbb26/bigbluebutton/docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:83:32)
    at async Promise.all (index 0)
    at async initPlugins (/home/anton/bbb26/bigbluebutton/docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:91:21)
    at async loadPlugins (/home/anton/bbb26/bigbluebutton/docs/node_modules/@docusaurus/core/lib/server/plugins/index.js:26:21)
    at async load (/home/anton/bbb26/bigbluebutton/docs/node_modules/@docusaurus/core/lib/server/index.js:76:58)
    at async Command.start (/home/anton/bbb26/bigbluebutton/docs/node_modules/@docusaurus/core/lib/commands/start.js:42:19)
[INFO] Docusaurus version: 2.2.0
Node version: v16.19.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tibroc** [comment]
Have you tried `rm -r versioned_docs versioned_sidebars versions.json`?

**Comment by antobinary** [comment]
I have not had this happen the last year or so i several dev env setups (and others I know have been able to set up the env too)
