### ISSUE TITLE
[2.7.0rc2] bbb-html5 server exception during community test

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#18690]
**Describe the bug**
During todays community test I discovered the following exception in `bbb-html5*` journal:

~~~
Sep 01 14:11:35 bbbserver systemd_start_frontend.sh[239915]: 2023-09-01T12:11:35.936Z frontend-8 [error] : NotifyRoleInMeetingEvtMsg: TypeError: Cannot read property 'role' of undefined
Sep 01 14:11:35 bbbserver systemd_start_frontend.sh[239915]:     at EventEmitter.<anonymous> (imports/api/meetings/server/publishers.js:175:82)
Sep 01 14:11:35 bbbserver systemd_start_frontend.sh[239915]:     at EventEmitter.emit (events.js:412:35)
Sep 01 14:11:35 bbbserver systemd_start_frontend.sh[239915]:     at EventEmitter.emit (domain.js:475:12)
Sep 01 14:11:35 bbbserver systemd_start_frontend.sh[239915]:     at emitNotification (imports/api/meetings/server/modifiers/emitNotification.js:5:25)
Sep 01 14:11:35 bbbserver systemd_start_frontend.sh[239915]:     at EventEmitter.handleNotifyRoleInMeeting (imports/api/meetings/server/handlers/handleNotifyRoleInMeeting.js:14:10)
Sep 01 14:11:35 bbbserver systemd_start_frontend.sh[239915]:     at EventEmitter.emitAsync (/usr/share/meteor/bundle/programs/server/npm/node_modules/eventemitter2/lib/eventemitter2.js:1137:31)
Sep 01 14:11:35 bbbserver systemd_start_frontend.sh[239915]:     at MeetingMessageQueue.handleTask (imports/startup/server/redis.js:117:10)
Sep 01 14:11:35 bbbserver systemd_start_frontend.sh[239915]:     at imports/startup/server/redis.js:129:28
Sep 01 14:11:35 bbbserver systemd_start_frontend.sh[239915]:     at Queue.start (/usr/share/meteor/bundle/programs/server/npm/node_modules/queue/index.js:145:17)
Sep 01 14:11:35 bbbserver systemd_start_frontend.sh[239915]:     at Queue.<computed> [as push] (/usr/share/meteor/bundle/programs/server/npm/node_modules/queue/index.js:59:12)
Sep 01 14:11:35 bbbserver systemd_start_frontend.sh[239915]:     at MeetingMessageQueue.add (imports/startup/server/redis.js:128:16)
Sep 01 14:11:35 bbbserver systemd_start_frontend.sh[239915]:     at RedisPubSub.handleMessage (imports/startup/server/redis.js:289:61)
Sep 01 14:11:35 bbbserver systemd_start_frontend.sh[239915]:     at runWithEnvironment (packages/meteor.js:1486:24)
~~~

The message appeared at different frontends.

**To Reproduce**
Unfortunately I can't remember what we did when this one was triggered. Maybe it is related to #18689

**Comment by antobinary** [comment]
We've removed the frontends in BBB 3.0.
I will close this issue as we won't be fixing in 2.7. If there's something causing client crashes, let's report it, but unlikely that we'll patch this particular issue.
