### ISSUE TITLE
All recordings fail 

### ISSUE THREAD

**Issue by HumphRey123** [bigbluebutton/bigbluebutton#19012]
**Describe the bug**
recordings are not proceeded at BBB 2.7.x
I updated from BBB 2.6 over install script.

If I record a meeting, stop the recording, close the meeting, the meeting_id dir is shortly shown in /var/bigbluebutton/recording/raw/ , then I found the meeting_id in /var/bigbluebutton/recording/status/archived/ meeting_id.fail

 journalctl -u bbb-rap-resque-worker.service :

bbb-rap[337993]: Started worker archive for 0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842
Oct 27 11:36:08 meeting bbb-rap[337993]: Running archive worker for 0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842
Oct 27 11:36:08-meeting bbb-rap[337993]: Executing: ruby /usr/local/bigbluebutton/core/scripts/archive/archive.rb -m 0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842
Oct 27 11:36:08-meeting sudo[337998]: bigbluebutton : TTY=unknown ; PWD=/usr/local/bigbluebutton/core/scripts ; USER=root ; COMMAND=/usr/bin/bbb-record --delete 0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842
Oct 27 11:36:08-meeting sudo[337998]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 27 11:36:08-meeting bbb-rap[337993]: deleting: 0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842
Oct 27 11:36:08-meeting sudo[337998]: pam_unix(sudo:session): session closed for user root
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/scripts/archive/archive.rb:50:in `initialize': No such file or directory @ rb_sysopen - /var/bigbluebutton/recording/raw/0b6cd0825f8641dffdc083924f79eaaef471>
Oct 27 11:36:08-meeting bbb-rap[337993]:         from /usr/local/bigbluebutton/core/scripts/archive/archive.rb:50:in `open'
Oct 27 11:36:08-meeting bbb-rap[337993]:         from /usr/local/bigbluebutton/core/scripts/archive/archive.rb:50:in `archive_notes'
Oct 27 11:36:08-meeting bbb-rap[337993]:         from /usr/local/bigbluebutton/core/scripts/archive/archive.rb:244:in `<main>'
Oct 27 11:36:08-meeting bbb-rap[337993]: Success?: false
Oct 27 11:36:08-meeting bbb-rap[337993]: Process exited? true
Oct 27 11:36:08-meeting bbb-rap[337993]: Exit status: 1
Oct 27 11:36:08-meeting bbb-rap[337993]: Failed to archive 0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842
Oct 27 11:36:08-meeting bbb-rap[337993]: Ended worker archive for 0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842 with result false
Oct 27 11:36:08-meeting bbb-rap[337993]: Worker archive for 0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842 failed with result false
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/lib/recordandplayback/workers/base_worker.rb:56:in `perform'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/lib/recordandplayback/workers/archive_worker.rb:26:in `perform'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/lib/recordandplayback/workers/base_worker.rb:44:in `perform'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/job.rb:168:in `perform'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:322:in `perform'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:922:in `block in perform_with_fork'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:920:in `fork'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:920:in `perform_with_fork'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:278:in `work_one_job'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:249:in `block in work'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:246:in `loop'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:246:in `work'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/tasks.rb:20:in `block (2 levels) in <top (required)>'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/bin/rake:23:in `load'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/bin/rake:23:in `<main>'
Oct 27 11:36:08-meeting bbb-rap[337993]: (Job{rap:archive} | BigBlueButton::Resque::ArchiveWorker | [{"meeting_id"=>"0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842", "break_timestamp"=>nil}]) failed: #<RuntimeError: Work>

What is wrong here. Is this okay?: 
bbb-rap[337993]: Executing: ruby /usr/local/bigbluebutton/core/scripts/archive/archive.rb -m 0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842
sudo[337998]: bigbluebutton : TTY=unknown ; PWD=/usr/local/bigbluebutton/core/scripts ; USER=root ; COMMAND=/usr/bin/bbb-record --delete 0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842

bbb-record --list-recent
Internal MeetingID                                               Time                APVD APVDE RAS Slides Processed            Published           External MeetingID
------------------------------------------------------  ---------------------------- ---- ----- --- ------ -------------------- ------------------  -------------------
2e9f6d97455f3f2ec328e17d35b3d3c35bbbde1a-1698391647502  Fri 27 Oct 2023 07:27:27 AM UTC  X                  7 
2e9f6d97455f3f2ec328e17d35b3d3c35bbbde1a-1698305364121  Thu 26 Oct 2023 07:29:24 AM UTC  X                  7 

--
NEXT LEFT LAST PASSED UNIT ACTIVATES

0 timers listed.
--
● bbb-rap-starter.service - BigBlueButton recording processing starter
     Loaded: loaded (/lib/systemd/system/bbb-rap-starter.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-10-27 11:31:13 UTC; 43min ago
   Main PID: 337099 (rap-starter.rb)
      Tasks: 1 (limit: 28734)
     Memory: 35.1M
     CGroup: /bbb_record_core.slice/bbb-rap-starter.service
             └─337099 /usr/bin/ruby /usr/local/bigbluebutton/core/scripts/rap-starter.rb

Oct 27 11:31:13 meeting systemd[1]: Started BigBlueButton recording processing starter.
Oct 27 11:31:13 meeting bbb-rap[337099]: Setting up inotify watch on /var/bigbluebutton/recording/status/ended
Oct 27 11:31:13 meeting bbb-rap[337099]: Setting up inotify watch on /var/bigbluebutton/recording/status/archived
Oct 27 11:31:13-meeting bbb-rap[337099]: Setting up inotify watch on /var/bigbluebutton/recording/status/recorded
Oct 27 11:31:13 meeting bbb-rap[337099]: Waiting for new recordings...
Oct 27 11:36:06 meeting bbb-rap[337099]: Enqueuing job to archive {:meeting_id=>"0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842", :break_timestamp=>nil}

● bbb-rap-resque-worker.service - BigBlueButton resque worker for recordings
     Loaded: loaded (/lib/systemd/system/bbb-rap-resque-worker.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-10-27 11:32:56 UTC; 41min ago
   Main PID: 337420 (ruby2.7)
      Tasks: 10 (limit: 28734)
     Memory: 172.2M
     CGroup: /system.slice/bbb-rap-resque-worker.service
             ├─337420 ruby2.7 /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/bin/rake -f Rakefile resque:workers
             ├─337429 resque-2.6.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:capti
             ├─337430 resque-2.6.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:capti
             └─337431 resque-2.6.0: Waiting for rap:archive,rap:publish,rap:process,rap:sanity,rap:capti

Oct 27 11:36:08 -meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
Oct 27 11:36:08-meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
Oct 27 11:36:08 -meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
Oct 27 11:36:08 ameeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Oct 27 11:36:08 meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/bin/rake:23:in `load'
Oct 27 11:36:08 meeting bbb-rap[337993]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/bin/rake:23:in `<main>'
Oct 27 11:36:08 meeting bbb-rap[337993]: (Job{rap:archive} | BigBlueButton::Resque::ArchiveWorker | [{"meeting_id"=>"0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842", "break_timestamp"=>nil}]) failed: #… with result false>

Please help me

**Comment by HumphRey123** [comment]
Okay, there are no recording marks from freeswitch:
 /var/log/bigbluebutton/archive-0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842.log 
I, [2023-10-27T11:36:08.732139 #337994]  INFO -- : Executing: rsync -stv /var/freeswitch/meetings/0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842-164865640.opus /var/bigbluebutton/recording/raw/0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842/audio
I, [2023-10-27T11:36:08.734744 #337994]  INFO -- : 0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842-164865640.opus
I, [2023-10-27T11:36:08.739898 #337994]  INFO -- : 
I, [2023-10-27T11:36:08.739936 #337994]  INFO -- : sent 753,434 bytes  received 35 bytes  1,506,938.00 bytes/sec
I, [2023-10-27T11:36:08.739955 #337994]  INFO -- : total size is 753,115  speedup is 1.00
I, [2023-10-27T11:36:08.740242 #337994]  INFO -- : Success?: true
I, [2023-10-27T11:36:08.740269 #337994]  INFO -- : Process exited? true
I, [2023-10-27T11:36:08.740288 #337994]  INFO -- : Exit status: 0
I, [2023-10-27T11:36:08.740307 #337994]  INFO -- : There is no recording marks for 0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842, deleting the recording.
I, [2023-10-27T11:36:08.867142 #337994]  INFO -- : Archiving notes for 0b6cd0825f8641dffdc083924f79eaaef4718967-1698406409842

But why?

**Comment by HumphRey123** [comment]
Sorry, my fault ....
old config has overwritten archive.rb ...
