### ISSUE TITLE
Not being able to connect screenshare / invalid recordingId

### ISSUE THREAD

**Issue by Ithanil** [bigbluebutton/bigbluebutton#19085]
**Describe the bug**
I got the complaint from a user that she was unable to fully connect a screenshare within a particular BBB session (it would work fine in other ones). As I understood it, when pressing the button for screenshare the selection popup would appear, but then afterwards it would load forever with 3 dots appearing.

When investigating the issue in the logs I stumbled across the following message appearing repeatedly for that particular user in that session:

`2023-11-07T13:27:15+01:00 bbb-27-151 bbb-webrtc-sfu[687542]: {"cameraId":"w_hw5q0ccj7qxm_101f02d25b8d36d7dfce120ea7511e19534cbdf7a0412a0159be2ef3bcdea0f0","connectionId":"274dca14-11f1-45c3-b857-4c3e6b19c441","error":{"details":"Error: invalid recordingId","message":"Error: invalid recordingId","operation":"stopRecording","stack":"Error: Error: invalid recordingId\n    at MCSClient.stopRecording (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/mcs-js/lib/MCSClient.js:626:13)\n    at MCSAPIWrapper.stopRecording (/usr/local/bigbluebutton/bbb-webrtc-sfu/lib/base/MCSAPIWrapper.js:175:47)\n    at /usr/local/bigbluebutton/bbb-webrtc-sfu/lib/video/video.js:1157:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","type":"error"},"internalMeetingId":"1d429e7028311b8720b7e71763932eebe15fc98d-1699359643273","label":"video","level":"warn","mediaId":"88b13c5a-68a1-42ed-b402-db2069d98fe5","message":"stopRecordingFailed for ccd53e98-4486-4948-a5b8-6fd91c5f5571, stream 274dca14-11f1-45c3-b857-4c3e6b19c441w_hw5q0ccj7qxm_101f02d25b8d36d7dfce120ea7511e19534cbdf7a0412a0159be2ef3bcdea0f0-viewer","role":"viewer","roomId":"51210","sessionId":"w_8zosvgwx6qjz-w_hw5q0ccj7qxm_101f02d25b8d36d7dfce120ea7511e19534cbdf7a0412a0159be2ef3bcdea0f0-viewer","status":"MEDIA_STOPPING","streamName":"274dca14-11f1-45c3-b857-4c3e6b19c441w_hw5q0ccj7qxm_101f02d25b8d36d7dfce120ea7511e19534cbdf7a0412a0159be2ef3bcdea0f0-viewer","timestamp":"2023-11-07T12:27:15.204Z","userId":"w_8zosvgwx6qjz"}`

Apparently this message is not about screenshare, but about *stopping* the *video*. Indeed, in the logs it seems like she had ended her webcam before trying the screenshare.

That's all I can say about this particular case, but when looking more I found similar log messages appearing very frequently on all our BBB servers. I caught with "screenshare" instead of "video" as well:

`2023-11-07T23:33:05+01:00 bbb-26-55 bbb-webrtc-sfu[359207]: {"connectionId":"be8f5289-8857-4ab9-b916-bf671050b7a7","error":{"details":"Error: invalid recordingId","message":"Error: invalid recordingId","operation":"stopRecording","stack":"Error: Error: invalid recordingId\n    at MCSClient.stopRecording (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/mcs-js/lib/MCSClient.js:626:13)\n    at MCSAPIWrapper.stopRecording (/usr/local/bigbluebutton/bbb-webrtc-sfu/lib/base/MCSAPIWrapper.js:175:47)\n    at /usr/local/bigbluebutton/bbb-webrtc-sfu/lib/screenshare/screenshare.js:1448:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","type":"error"},"internalMeetingId":"5ca0977536e2f401dd477bbdc3b367f2582cde7b-1699390468194","label":"screenshare","level":"warn","mediaId":"85c7a43e-4aaa-4de8-a7f7-a2599139bec5","message":"stopRecordingFailed for 9c4ccff1-2e29-47cf-8974-25286ae93c53","role":"presenter","roomId":"96266","status":"MEDIA_STOPPING","timestamp":"2023-11-07T22:33:05.488Z","userId":"9c4ccff1-2e29-47cf-8974-25286ae93c53"}`

Do you have an idea what is going on or know more about this issue?

**To Reproduce**
Steps to reproduce the behavior (maybe):
1. Enter session, connect webcam
2. close webcam
3. try screenshare
4. See loading symbols forever

(can't reproduce it myself!)

**Desktop (please complete the following information):**
Reportedly, multiple browsers have been tried in that session.

**Comment by Ithanil** [comment]
@prlanzarin Hi, thanks for the quick response and the information regarding the logs.

Regarding the reported issue: First, I have got the problem report via a third party and no direct contact to the user. But for what I know the screen sharing did work for that user in the same environment, same time, but different meeting (and thus likely different server). It was reproducible by that user in the problematic meeting, even when trying a different browser. They did rule out connectivity issues.

I can't reproduce they issue myself though, even on that same server.

**Comment by Wladimir-N** [comment]
I have exactly the same problem, screen sharing stops working, and with similar messages in the log.
If I restart the service everything starts working, right in the same conference

`systemctl restart bbb-webrtc-sfu`

**Comment by hostbbb** [comment]
systemctl restart bbb-webrtc-sfu  this fixed screenshare,  but now cams dont connect :)

**Comment by hostbbb** [comment]
2.7.2 server running fine for 4 hours.

Screenshare fails for all meetings once error occurs...   

systemctl restart bbb-webrtc-sfu  fixes screenshare, but now cams don't connect and just show avatars:)

took bbb-conf --restart to fix everything.    i have full logs if needed.

**Comment by Wladimir-N** [comment]
I already caught the problem on 2.7.2

**Comment by amg-web** [comment]
Problem happens randomly on different server, I had to rebuild one as it was happened every day.
after rebuild 3 days fine now.

**Comment by amg-web** [comment]
@prlanzarin 
how to share logs with you without public?

> what do you mean by "rebuild"? Did you upgrade to latest v2.7.3?

it was 3 days ago, I reinstalled os.
I can send you logs from todays' reported server, How can I do it without public access?

**Comment by amg-web** [comment]
@prlanzarin 
after several seconds after meeting started i see following message in browser's console

`[17:37:33:0420] ERROR: clientLogger: Screen sharing will not reconnect M.handleConnectionTimeoutExpiry (https://s1.sense.org/html5client/11c7ff844f98e0e76abb1f715bdf2a2c52b2fdb6.js?meteor_js_resource=true:680:1603580)`

**Comment by Ithanil** [comment]
@Wladimir-N @hostbbb @amg-web Thanks everyone for tuning in and providing more insight / logs. @prlanzarin Excellent!

**Comment by anandchristudas** [comment]
Wow, nice finally someone was able to figure it out. We had the same issue when we installed 2.7 a few months back and had to move back to 2.6. I even reported the issue but was not able to give detailed info as we only have one production environment and didn't want to take any chance running 2.7. Hope you guys will release the patch with the next version of BBB.

**Comment by anandchristudas** [comment]
@prlanzarin I reported that in Google BBB group

**Comment by Ithanil** [comment]
@prlanzarin I would love to test the fix, but unfortunately I was never able to reproduce or even notice any issue myself. I've received only one report about this, at several thousand users daily. Anyway, many thanks for your effort and I'm really happy that this vague Github issue had such an outcome.

**Comment by ffdixon** [comment]
Thanks @Ithanil for reporting the issue in the first place -- much appreciated!

**Comment by Wladimir-N** [comment]
> Hi, this is the prelimary patch for those that want to test it https://github.com/bigbluebutton/bbb-webrtc-sfu/commit/c84e038a9dd77d3a45df1279c6a30703ecb72a6a.patch.
> 
> I'll tag it once I've done more testing.
> 
> Steps to apply:
> 
> * Copy the patch into a file (c84e038a9dd77d3a45df1279c6a30703ecb72a6a.patch), transfer it to a BBB server's home directory
> * $ cd /usr/local/bigbluebutton/bbb-webrtc-sfu
> * $ patch -p1 < ~/c84e038a9dd77d3a45df1279c6a30703ecb72a6a.patch
> * $ sudo systemctl restart bbb-webrtc-sfu
> 
> This only affects setups that run `recordFullDurationMedia=false`, which is the default. The envs I monitor use it set to `recordFullDurationMedia=true`. That's why I haven't hit that yet. Rationale for the issue is in the patch headers.

After a week of successful work, I applied the patch on the 13th, today it was reproduced again. It’s true that I’ll note that it eventually corrected itself. I mean, previously, if someone had a glitch with the demonstration, then as a result, until I restarted, the demonstration did not work for anyone, today it fixed itself and then the demonstrations continued to work after some time. Now I’m sinning that maybe the problem is that I applied the patch to bbb2.7.2, and not the last one. I'll try to update today.

**Comment by anandchristudas** [comment]
@prlanzarin I found my previous Google group post that I made on 24th Sept 2023. Posting it again here as someone else commented on it mentioning the same issue. He has posted his error logs in it, please check if it's the same issue that you have solved here. Thank you. 

My Google Group post link: https://groups.google.com/g/bigbluebutton-dev/c/la7g-Dsiig0/m/1zT_MRhFAAAJ?utm_medium=email&utm_source=footer

**Comment by anandchristudas** [comment]
> @prlanzarin I reported that in Google BBB group

@prlanzarin I found my previous Google group post that I made on 24th Sept 2023. Posting it again here as someone else commented on it mentioning the same issue. He has posted his error logs in it, please check if it's the same issue that you have solved here. Thank you.

My Google Group post link: https://groups.google.com/g/bigbluebutton-dev/c/la7g-Dsiig0/m/1zT_MRhFAAAJ?utm_medium=email&utm_source=footer
