### ISSUE TITLE
starting red5 manually spits out an exception

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1922]
Originally reported on Google Code with ID 1168

```
Running "sudo -u red5 ./red5.sh" shows the following exception on the console. Seems
like nothing serious as BigBlueButton still works. Maaybe the cause is we removed some
dirs that came with Red5 to clean it up a bit.

Adding logger context: sip to map for context: sip
[INFO] [main] org.apache.coyote.http11.Http11Protocol - Initializing Coyote HTTP/1.1
on http-0.0.0.0-5080
[INFO] [main] org.apache.coyote.http11.Http11Protocol - Starting Coyote HTTP/1.1 on
http-0.0.0.0-5080
[INFO] [main] org.red5.server.tomcat.TomcatLoader - Dedicated RTMPT server configuration
was not specified
Bootstrap complete
Exception in thread "Launcher:/" org.springframework.beans.factory.BeanDefinitionStoreException:
Could not resolve bean definition resource pattern [/WEB-INF/red5-*.xml]; nested exception
is java.io.FileNotFoundException: ServletContext resource [/WEB-INF/] cannot be resolved
to URL because it does not exist
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:190)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:149)
        at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:124)
        at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:93)
        at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130)
        at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:467)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:397)
        at org.red5.server.tomcat.TomcatLoader$1.run(TomcatLoader.java:577)
Caused by: java.io.FileNotFoundException: ServletContext resource [/WEB-INF/] cannot
be resolved to URL because it does not exist
        at org.springframework.web.context.support.ServletContextResource.getURL(ServletContextResource.java:131)
        at org.springframework.core.io.support.PathMatchingResourcePatternResolver.isJarResource(PathMatchingResourcePatternResolver.java:413)
        at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources(PathMatchingResourcePatternResolver.java:342)
        at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources(PathMatchingResourcePatternResolver.java:280)
        at org.springframework.context.support.AbstractApplicationContext.getResources(AbstractApplicationContext.java:1227)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:177)
        ... 7 more
[INFO] [Launcher:/live] org.springframework.beans.factory.config.PropertyPlaceholderConfigurer
- Loading properties file from ServletContext resource [/WEB-INF/red5-web.properties]


```

Reported by `ritzalam` on 2012-03-04 18:23:54

**Comment by ffdixon** [comment]
Tried it in the latest version of red5 packaged with BigBlueButton 1.1-beta and don't see these errors anymore.  Closing this issue.
