### ISSUE TITLE
After breakout rooms end, the whiteboard conversion for some rooms fails

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#19668]
**Describe the bug**
We're getting reports that whiteboard conversion in breakout rooms sometimes fails.  A report of the issue was here in the community

  https://groups.google.com/g/bigbluebutton-dev/c/13TLSwJLE5w/m/xMV_WvmEAAAJ

**Expected behavior**
Conversion of whiteboard slides in breakout rooms should always complete and return to the main room.

**Actual behavior**
It sometimes fails.

From the above forum link

```
Hello,
One of our developers noticed in the log files that the service 'bbb-export-annotations' is producing an error during conversion. We can reproduce this error, but not always. We don't know why.

Feb 22 13:11:51 DEV-BigBlueButton bbb-export-annotations[823]: 2024-02-22T13:11:51.844Z INFO         [presAnn Process Worker] Processing PDF for job 1fbfeac0af5207876a201fec1d2532ec21c7edd6-1708607324541-slides
Feb 22 13:11:51 DEV-BigBlueButton bbb-export-annotations[823]: 2024-02-22T13:11:51.863Z INFO         [presAnn Process Worker] Processing PDF for job 6eba6fa368842debb0eb87cfe25ebb809faf7963-1708607324541-slides
Feb 22 13:11:51 DEV-BigBlueButton bbb-export-annotations[823]: 2024-02-22T13:11:51.868Z INFO         [presAnn Process Worker] Processing PDF for job 2718150c9dd5fccad8adb55b974d80af61229a20-1708607324541-slides
Feb 22 13:11:51 DEV-BigBlueButton systemd_start_frontend.sh[1917]: 2024-02-22T13:11:51.889Z frontend-2 [info] : Updated clientNotResponding=true meetingId=1fbfeac0af5207876a201fec1d2532ec21c7edd6-1708607324541 userId=w_kq9bltg8vo35
Feb 22 13:11:51 DEV-BigBlueButton bbb-export-annotations[823]: node:internal/process/promises:288
Feb 22 13:11:51 DEV-BigBlueButton bbb-export-annotations[823]:             triggerUncaughtException(err, true /* fromPromise */);
Feb 22 13:11:51 DEV-BigBlueButton bbb-export-annotations[823]:             ^
Feb 22 13:11:51 DEV-BigBlueButton bbb-export-annotations[823]: TypeError [Error]: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
Feb 22 13:11:51 DEV-BigBlueButton bbb-export-annotations[823]:     at overlay_text (/usr/local/bigbluebutton/bbb-export-annotations/workers/process.js:706:41)
Feb 22 13:11:51 DEV-BigBlueButton bbb-export-annotations[823]:     at overlay_annotation (/usr/local/bigbluebutton/bbb-export-annotations/workers/process.js:754:7)
Feb 22 13:11:51 DEV-BigBlueButton bbb-export-annotations[823]:     at overlay_annotations (/usr/local/bigbluebutton/bbb-export-annotations/workers/process.js:780:11)
Feb 22 13:11:51 DEV-BigBlueButton bbb-export-annotations[823]:     at process_presentation_annotations (/usr/local/bigbluebutton/bbb-export-annotations/workers/process.js:849:5)
Feb 22 13:11:51 DEV-BigBlueButton bbb-export-annotations[823]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Feb 22 13:11:51 DEV-BigBlueButton bbb-export-annotations[823]: Node.js v18.19.1
Feb 22 13:11:52 DEV-BigBlueButton systemd_start_frontend.sh[1917]: 2024-02-22T13:11:52.315Z frontend-2 [info] : Updated clientNotResponding=true meetingId=6eba6fa368842debb0eb87cfe25ebb809faf7963-1708607324541 userId=w_lebf22y2ykwc
Feb 22 13:11:52 DEV-BigBlueButton systemd_start_frontend.sh[1913]: 2024-02-22T13:11:52.418Z frontend-1 [info] : Updated clientNotResponding=true meetingId=1fbfeac0af5207876a201fec1d2532ec21c7edd6-1708607324541 userId=w_3gnffjnn62cc
Feb 22 13:11:52 DEV-BigBlueButton systemd[1]: bbb-export-annotations.service: Main process exited, code=exited, status=1/FAILURE
Feb 22 13:11:52 DEV-BigBlueButton systemd[1]: bbb-export-annotations.service: Failed with result 'exit-code'.
Feb 22 13:11:52 DEV-BigBlueButton java[982]: 2024-02-22T13:11:52.707Z DEBUG o.b.web.controllers.ApiController - ApiController#getMeetings
Feb 22 13:11:52 DEV-BigBlueButton java[982]: 2024-02-22T13:11:52.707Z INFO  o.b.api.service.ValidationService - Validating getMeetings request with query string checksum=1bb412884e93f95b085d77b92b5eeee4914dfe15
Feb 22 13:11:52 DEV-BigBlueButton java[982]: 2024-02-22T13:11:52.707Z INFO  o.b.a.m.v.GetChecksumValidator - query string after checksum removed: []
Feb 22 13:11:52 DEV-BigBlueButton java[982]: 2024-02-22T13:11:52.707Z INFO  o.b.a.m.v.GetChecksumValidator - CHECKSUM=1bb412884e93f95b085d77b92b5eeee4914dfe15 length=40
Feb 22 13:11:52 DEV-BigBlueButton java[982]: 2024-02-22T13:11:52.707Z INFO  o.b.a.m.v.GetChecksumValidator - SHA1 1bb412884e93f95b085d77b92b5eeee4914dfe15
Feb 22 13:11:52 DEV-BigBlueButton systemd[1]: bbb-export-annotations.service: Scheduled restart job, restart counter is at 1.
Feb 22 13:11:52 DEV-BigBlueButton systemd[1]: Stopped BigBlueButton Export Annotations.
Feb 22 13:11:52 DEV-BigBlueButton systemd[1]: Started BigBlueButton Export Annotations.  

```

**Additional context**
Have received one other (verbal) report of this, so suspect it's happening to others.

**Comment by thuh-reflact** [comment]
We fixed that today in our local deployment.

What happens is that, the whole conversion process exits and does not continue when any element on any slide could not be     converted to an svg element and throws an error to the main process.

That happens always when tldraw library does not send the size of the created text element, which is caused by a user that does never blur a new created text element to the slide.

**Quickfix**

In:  /usr/local/bigbluebutton/bbb-export-annotations/workers/process.js  or https://github.com/bigbluebutton/bigbluebutton/blob/develop/bbb-export-annotations/workers/process.js

We changed the following:

```
function overlay_text(svg, annotation) {
  const [textBoxWidth, textBoxHeight] = annotation.size;

...
```

to

```
function overlay_text(svg, annotation) {
  if (annotation.size == null || annotation.size.length < 2) {
    return
  }
  const [textBoxWidth, textBoxHeight] = annotation.size;
...
```

And maybe its a good idea to prevent breaking the whole conversion process of all breakoutslides in general by changing

```
function overlay_annotation(svg, currentAnnotation) {
    switch (currentAnnotation.type) {
      case 'arrow':
        overlay_arrow(svg, currentAnnotation);
        break;
      case 'draw':
        overlay_draw(svg, currentAnnotation);
        break;
      case 'ellipse':
        overlay_ellipse(svg, currentAnnotation);
        break;
      case 'rectangle':
        overlay_rectangle(svg, currentAnnotation);
        break;
      case 'sticky':
        overlay_sticky(svg, currentAnnotation);
        break;
      case 'triangle':
        overlay_triangle(svg, currentAnnotation);
        break;
      case 'text':
        overlay_text(svg, currentAnnotation);
        break;
      default:
        logger.info(`Unknown annotation type ${currentAnnotation.type}.`);
    }
}
```
with a little try catch block like:

```
function overlay_annotation(svg, currentAnnotation) {
  try { // if something goes wrong, we don't want to stop the entire process
    switch (currentAnnotation.type) {
      case 'arrow':
        overlay_arrow(svg, currentAnnotation);
        break;
      case 'draw':
        overlay_draw(svg, currentAnnotation);
        break;
      case 'ellipse':
        overlay_ellipse(svg, currentAnnotation);
        break;
      case 'rectangle':
        overlay_rectangle(svg, currentAnnotation);
        break;
      case 'sticky':
        overlay_sticky(svg, currentAnnotation);
        break;
      case 'triangle':
        overlay_triangle(svg, currentAnnotation);
        break;
      case 'text':
        overlay_text(svg, currentAnnotation);
        break;
      default:
        logger.info(`Unknown annotation type ${currentAnnotation.type}.`);
    }
  } catch (error) {
    logger.warn("Failed to overlay annotation", { failedAnnotation: currentAnnotation, error: error });
  }
}
```

hope thats helps.

**Comment by thuh-reflact** [comment]
That would be great @danielpetri1 .

**Comment by thuh-reflact** [comment]
i think the main issue is located in tldraw which should alwas provide a valid size on creating text annotations.

**Comment by danielpetri1** [comment]
Just a brief follow-up as I'm trying to reproduce the issue:  what do you mean by the user never blurring a newly created text element? I am trying to reproduce the issue on a fresh 2.7 server. Thanks in advance!
