### ISSUE TITLE
Recordings will fail while archiving

### ISSUE THREAD

**Issue by bugeater17** [bigbluebutton/bigbluebutton#19874]
**Describe the bug**
Some recordings will fail while archiving (bigbluebutton 2.7.4).

**To Reproduce**
We cannot reproduce this behaviour. All of our tests (with camera, doing polls, camera as content, screenshare etc.) were processed successfully.

**Expected behavior**
Recordings should be converted and published successfully.

Actual behavior
Sometimes the recordings are failing while processing. I think that happend in archive.rb file. (see logs below)

**Log**
Here are two logs that both depend on different errors that leads to the result, that recordings are not processed correct. It seems that both occure in the archive.rb file. 
We've had a handfull of these errors in the last 7 days. In the meantime there have been thousends conferences that worked fine. 

```
${date}T${time}.133Z,"<30>1 ${date}T${time}.133007+01:00 ${serverId} systemd_start_frontend.sh 7407 - -  ${date}T${time}.132Z frontend-4 [#033[32minfo#033[39m] : Removing Cursor streamer object for meeting ${meetingId}-${timestamp}"
${date}T${time}.655Z,"<14>1 ${date}T${time}.655847+01:00 ${serverId} bbb-rap 142266 - -  Running archive worker for ${meetingId}-${timestamp}"
${date}T${time}.655Z,"<14>1 ${date}T${time}.655734+01:00 ${serverId} bbb-rap 142266 - -  Started worker archive for ${meetingId}-${timestamp}"
${date}T${time}.656Z,"<14>1 ${date}T${time}.656010+01:00 ${serverId} bbb-rap 142266 - -  Executing: ruby /usr/local/bigbluebutton/core/scripts/archive/archive.rb -m ${meetingId}-${timestamp}"
${date}T${time}.698Z,"<30>1 ${date}T${time}.698010+01:00 ${serverId} systemd_start_frontend.sh 7677 - -  ${date}T${time}.697Z frontend-5 [#033[32minfo#033[39m] : Updated clientNotResponding=true meetingId=${meetingId}-${timestamp} userId=xxxxxxxxxx"
${date}T${time}.711Z,"<14>1 ${date}T${time}.711995+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/lib/ruby/2.7.0/rubygems/version.rb:174:in `correct?'"
${date}T${time}.711Z,"<14>1 ${date}T${time}.711933+01:00 ${serverId} bbb-rap 142266 - -  /usr/lib/ruby/2.7.0/rubygems/deprecate.rb:27:in `skip': can't modify frozen #<Class:Gem::Deprecate>: Gem::Deprecate (FrozenError)"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712989+01:00 ${serverId} bbb-rap 142266 - -  Ended worker archive for ${meetingId}-${timestamp} with result false"
${date}T${time}.712Z,"<11>1 ${date}T${time}.712926+01:00 ${serverId} bbb-rap 142266 - -  Failed to archive ${meetingId}-${timestamp}"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712733+01:00 ${serverId} bbb-rap 142266 - -  Exit status: 1"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712707+01:00 ${serverId} bbb-rap 142266 - -  Process exited? true"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712680+01:00 ${serverId} bbb-rap 142266 - -  Success?: false"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712546+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712525+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712505+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712485+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712465+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712442+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712423+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler.rb:143:in `setup'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712399+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler.rb:195:in `definition'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712375+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:34:in `build'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712316+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/dsl.rb:13:in `evaluate'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712294+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/dsl.rb:234:in `to_definition'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712269+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/dsl.rb:234:in `new'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712245+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:83:in `initialize'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712225+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:83:in `new'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712205+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/lockfile_parser.rb:74:in `initialize'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712160+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/lockfile_parser.rb:74:in `each'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712136+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/lockfile_parser.rb:89:in `block in initialize'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712109+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/lockfile_parser.rb:169:in `parse_source'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712089+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/lockfile_parser.rb:220:in `parse_spec'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712069+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/lib/ruby/2.7.0/rubygems/version.rb:206:in `new'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712050+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/lib/ruby/2.7.0/rubygems/version.rb:206:in `new'"
${date}T${time}.712Z,"<14>1 ${date}T${time}.712023+01:00 ${serverId} bbb-rap 142266 - -  #011from /usr/lib/ruby/2.7.0/rubygems/version.rb:214:in `initialize'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713991+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713966+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713943+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713919+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713898+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713875+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713848+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713823+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713799+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713764+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713735+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713710+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713685+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713659+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713637+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713614+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713591+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713567+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/tasks.rb:20:in `block (2 levels) in <top (required)>'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713542+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:246:in `work'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713518+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:246:in `loop'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713493+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:249:in `block in work'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713468+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:278:in `work_one_job'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713442+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:920:in `perform_with_fork'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713414+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:920:in `fork'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713390+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:922:in `block in perform_with_fork'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713364+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:322:in `perform'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713339+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/job.rb:168:in `perform'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713312+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/lib/recordandplayback/workers/base_worker.rb:44:in `perform'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713247+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/lib/recordandplayback/workers/archive_worker.rb:26:in `perform'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713195+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/lib/recordandplayback/workers/base_worker.rb:56:in `perform'"
${date}T${time}.713Z,"<11>1 ${date}T${time}.713014+01:00 ${serverId} bbb-rap 142266 - -  Worker archive for ${meetingId}-${timestamp} failed with result false"
${date}T${time}.714Z,"<11>1 ${date}T${time}.714059+01:00 ${serverId} bbb-rap 142266 - -  (Job{rap:archive} | BigBlueButton::Resque::ArchiveWorker | [{""meeting_id""=>""${meetingId}-${timestamp}"", ""break_timestamp""=>nil}]) failed: #<RuntimeError: Worker archive for ${meetingId}-${timestamp} failed with result false>"
${date}T${time}.714Z,"<11>1 ${date}T${time}.714034+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/bin/rake:23:in `<main>'"
${date}T${time}.714Z,"<11>1 ${date}T${time}.714014+01:00 ${serverId} bbb-rap 142266 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/bin/rake:23:in `load'"


####################################################################################################################################################################################################################################


${date}T${time}.386Z,"<14>1 ${date}T${time}.386070+01:00 ${ServerId} bbb-rap 111801 - -  ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]"
${date}T${time}.386Z,"<14>1 ${date}T${time}.386051+01:00 ${ServerId} bbb-rap 111801 - -  7ffdc6469000-7ffdc646a000 r-xp 00000000 00:00 0                          [vdso]"
${date}T${time}.386Z,"<14>1 ${date}T${time}.386034+01:00 ${ServerId} bbb-rap 111801 - -  7ffdc6466000-7ffdc6469000 r--p 00000000 00:00 0                          [vvar]"
${date}T${time}.386Z,"<14>1 ${date}T${time}.386015+01:00 ${ServerId} bbb-rap 111801 - -  7ffdc5c35000-7ffdc6434000 rw-p 00000000 00:00 0                          [stack]"
${date}T${time}.458Z,"<11>1 ${date}T${time}.458994+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/tasks.rb:20:in `block (2 levels) in <top (required)>'"
${date}T${time}.458Z,"<11>1 ${date}T${time}.458973+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:246:in `work'"
${date}T${time}.458Z,"<11>1 ${date}T${time}.458955+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:246:in `loop'"
${date}T${time}.458Z,"<11>1 ${date}T${time}.458931+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:249:in `block in work'"
${date}T${time}.458Z,"<11>1 ${date}T${time}.458908+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:278:in `work_one_job'"
${date}T${time}.458Z,"<11>1 ${date}T${time}.458887+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:920:in `perform_with_fork'"
${date}T${time}.458Z,"<11>1 ${date}T${time}.458868+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:920:in `fork'"
${date}T${time}.458Z,"<11>1 ${date}T${time}.458851+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:922:in `block in perform_with_fork'"
${date}T${time}.458Z,"<11>1 ${date}T${time}.458834+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/worker.rb:322:in `perform'"
${date}T${time}.458Z,"<11>1 ${date}T${time}.458812+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.6.0/lib/resque/job.rb:168:in `perform'"
${date}T${time}.458Z,"<11>1 ${date}T${time}.458790+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/lib/recordandplayback/workers/base_worker.rb:44:in `perform'"
${date}T${time}.458Z,"<11>1 ${date}T${time}.458753+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/lib/recordandplayback/workers/archive_worker.rb:26:in `perform'"
${date}T${time}.458Z,"<11>1 ${date}T${time}.458735+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/lib/recordandplayback/workers/base_worker.rb:53:in `perform'"
${date}T${time}.458Z,"<11>1 ${date}T${time}.458713+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/lib/recordandplayback/workers/archive_worker.rb:40:in `block in perform'"
${date}T${time}.458Z,"<11>1 ${date}T${time}.458635+01:00 ${ServerId} bbb-rap 111801 - -  undefined method `zero?' for nil:NilClass"
${date}T${time}.458Z,"<14>1 ${date}T${time}.458308+01:00 ${ServerId} bbb-rap 111801 - -  Exit status:"
${date}T${time}.458Z,"<14>1 ${date}T${time}.458277+01:00 ${ServerId} bbb-rap 111801 - -  Process exited? false"
${date}T${time}.458Z,"<14>1 ${date}T${time}.458197+01:00 ${ServerId} bbb-rap 111801 - -  Success?:"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459385+01:00 ${ServerId} bbb-rap 111801 - -  (Job{rap:archive} | BigBlueButton::Resque::ArchiveWorker | [{""meeting_id""=>""${meetingId}-${timestamp}"", ""break_timestamp""=>nil}]) failed: #<NoMethodError: undefined method `zero?' for nil:NilClass>"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459363+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/bin/rake:23:in `<main>'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459344+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/bin/rake:23:in `load'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459321+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459298+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459283+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459267+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459251+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459237+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459223+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459207+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459193+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459179+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459165+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459148+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459129+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459106+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459082+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459064+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'"
${date}T${time}.459Z,"<11>1 ${date}T${time}.459015+01:00 ${ServerId} bbb-rap 111801 - -  /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'"
${date}T${time}.922Z,"<134>1 ${date}T${time}.922133+01:00 ${ServerId} 	 6209 - -   ${ip} [${date}:${time}.916] nginx_or_turn~ nginx-http2/localhost 4/0/5 390 -- 1/1/0/0/0 0/0 captured_user:P"
${date}T${time}.789Z,"<30>1 ${date}T${time}.789240+01:00 ${ServerId} bbb-apps-akka 7218 - -  ${date}T${time}.788+01:00 INFO  akka.actor.LocalActorRef - Message [org.bigbluebutton.core.running.MeetingActorAudit$AuditMonitorInternalMsg$] from Actor[akka://bigbluebutton-apps-system/user/bigbluebutton-actor/${meetingId}-${timestamp}/actorMonitor-${meetingId}-${timestamp}#-${timestamp}] to Actor[akka://bigbluebutton-apps-system/user/bigbluebutton-actor/${meetingId}-${timestamp}/actorMonitor-${meetingId}-${timestamp}#-${timestamp}] was not delivered. [12] dead letters encountered, of which 1 were not logged. The counter will be reset now. If this is not an expected behavior then Actor[akka://bigbluebutton-apps-system/user/bigbluebutton-actor/${meetingId}-${timestamp}/actorMonitor-${meetingId}-${timestamp}#-${timestamp}] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'."
${date}T${time}.790Z,"<30>1 ${date}T${time}.790965+01:00 ${ServerId} systemd_start_frontend.sh 7774 - -  ${date}T${time}.790Z frontend-2 [#033[32minfo#033[39m] : Removing Cursor streamer object for meeting ${meetingId}-${timestamp}"
${date}T${time}.790Z,"<30>1 ${date}T${time}.790898+01:00 ${ServerId} systemd_start_frontend.sh 7774 - -  ${date}T${time}.790Z frontend-2 [#033[32minfo#033[39m] : Removing Annotations streamer object for meeting ${meetingId}-${timestamp}"
${date}T${time}.791Z,"<30>1 ${date}T${time}.791347+01:00 ${ServerId} systemd_start_frontend.sh 7831 - -  ${date}T${time}.790Z frontend-6 [#033[32minfo#033[39m] : Removing Cursor streamer object for meeting ${meetingId}-${timestamp}"
```

**Comment by bugeater17** [comment]
We are testing now if it occurs under 2.6

**Comment by ffdixon** [comment]
You closed this as completed -- did you resolve the issue?

If you have a recording that fails to process, could you gzip the raw components of the recording and upload it as an attachment (or email it directly to ffdixon .at. bigbluebutton .dot.org)?

**Comment by bugeater17** [comment]
Hello Fred, 

thank you for your reply. 

Sorry it was not my plan to mark it as complete. I wanted to test this again under 2.7.6 before you search for the bug. 
I have several new informations about the problem:

1.) The error occures under bbb 2.7.6 too.
2.) The error occures in conferences with recordings as well as in conferences without recordings. The most time it occures in conferences without recordings. But we also have conferences where recrodings have been made.
3.) We can find the error with the following search term in the logs. May you can find this on your servers too:
 ```grep -E "\(Job\{rap:archive\} | BigBlueButton::Resque::ArchiveWorker \|.*failed"```

The error still occures just in a handful of conferences in a time where we had thousend conferences. 

Unfortunatly we can not provide data from our conferences due to privacy reasons. But we have seperated one server in which the error occured (in a conference without recording). Its a server with bigbluebutton 2.7.4. If you can give us instructions we can investigate the server and provide the technical information you need. 

Additional I have updated the logs above. I had cut the first example a little bit too early so that some parts of the error message was missing. May the appended part is helpfull.

**Comment by bugeater17** [comment]
Update:
We had one more case where a recording is lost. Now it happend on a server with bigbluebutton 2.7.6. So in 2.7.6 the error still occurs even in meetings with recordings.

**Comment by soheb-somani** [comment]
We are facing the same problem. 2 of our recordings were lost and couldn't be recovered because of this issue.

**Comment by ffdixon** [comment]
Hmmm ...

**Comment by germanocaumo** [comment]
@bugeater17 do you have the logs from `/var/log/bigbluebutton/archive-meetingid-timestamp.log` of one affected meeting? it should contain more useful info about the error

**Comment by bugeater17** [comment]
@germanocaumo Currently we have no logs from this files. 

But we have created a workaround. This workaround detects if a recording is created by freeswitch. If this is the case our plattform will be informed about it and keeps the server alive if there is a recording missing. Means, if the problem occurs again the server will be seperated by our plattfrom and we can investigate the problem.

**Comment by bugeater17** [comment]
Now I have saved a server with failed recording where we actually have a recording. There was no archive log for the meeting. I have tried to to rebuild this one and there have been a error in sanity.log which says: There is no events.xml. I think this depends on the failed archive script.

When I run bbb-conf --check I have got the following Information refering to the issu #14287: 
```
#
# Warning: found 'Nil' message in recording processing logs.  Possible GEM errors
#
#  https://github.com/bigbluebutton/bigbluebutton/issues/14287
#

```

I have recognized that the archive script is not executed again by rebuilding the recording. To reexecute the archive script I followed this instructions (maybe a issue that is in touch with ours?): 
https://github.com/bigbluebutton/bigbluebutton/issues/9175#issuecomment-1868276135

Now the archive script runs again. Rebuild the recording has done the rest and I was able to save the recording. This is fine for investigating the problem but it is not a real solution for the basic problem.

I hope you will be able to find the real error with this information. If you need more information for trouble shooting please do not hesitate to give me instructions to investigate the server. I will keep this one alife for some more days.
