### ISSUE TITLE
UserJoinedMeetingEvtMsg: TypeError: Cannot read property 'isBreakout' of undefined

### ISSUE THREAD

**Issue by fadgan** [bigbluebutton/bigbluebutton#20501]
Good afternoon,

Installed BBB 2.7 on Ubuntu 20.04. All runs fine.
Followed the docs for setting up the hmtl5 client alongside an already installed BBB.
Pulled the corresponding branch:
```

git status
On branch v2.7.x-release
Your branch is up to date with 'origin/v2.7.x-release'.
```

Stopped the packages version of hmtl5 as per the doc and started the pulled one with ` npm install` and `npm start`.

Using API mate to test. Meeting creation is SUCCESS from but when joining as a moderator or an attendee getting this error in the app log:
 
```
 [error] : UserJoinedMeetingEvtMsg: TypeError: Cannot read property 'isBreakout' of undefined
 at imports/api/users/server/modifiers/addUser.js:52:43
```
 
 and this is in the browser console:

` Uncaught TypeError: meeting.meetingProp is undefined`
 
As a result, the meeting room does not open: just a dark blue screen.

Any tips and help is highly appreciated.

Thank you.

Regards,
Fadai.

**Comment by fadgan** [comment]
Also noticed the following error when the the client side started:

`I20240617-14:25:09.420(0)? 2024-06-17T14:25:09.415Z [error] : MeetingCreatedEvtMsg: Error: Match error: Missing key 'allowPromoteGuestToModerator' in field usersProp
I20240617-14:25:09.421(0)?     at check (packages/check/match.js:36:17)
I20240617-14:25:09.422(0)?     at imports/api/meetings/server/modifiers/addMeeting.js:71:3
I20240617-14:25:09.422(0)?     at /home/bigbluebutton/.meteor/packages/promise/.0.12.2.1v51k7w.6dob++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20240617-14:25:09.422(0)?  => awaited here:
I20240617-14:25:09.422(0)?     at Function.Promise.await (/home/bigbluebutton/.meteor/packages/promise/.0.12.2.1v51k7w.6dob++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20240617-14:25:09.422(0)?     at imports/api/meetings/server/handlers/meetingCreation.js:9:15
I20240617-14:25:09.422(0)?     at /home/bigbluebutton/.meteor/packages/promise/.0.12.2.1v51k7w.6dob++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40 
I20240617-14:25:09.423(0)? 2024-06-17T14:25:09.416Z [error] : MeetingCreatedEvtMsg: Error: Match error: Missing key 'allowPromoteGuestToModerator' in field usersProp
I20240617-14:25:09.423(0)?     at check (packages/check/match.js:36:17)
I20240617-14:25:09.423(0)?     at imports/api/meetings/server/modifiers/addMeeting.js:71:3
I20240617-14:25:09.423(0)?     at /home/bigbluebutton/.meteor/packages/promise/.0.12.2.1v51k7w.6dob++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20240617-14:25:09.423(0)?  => awaited here:
I20240617-14:25:09.424(0)?     at Function.Promise.await (/home/bigbluebutton/.meteor/packages/promise/.0.12.2.1v51k7w.6dob++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20240617-14:25:09.424(0)?     at imports/api/meetings/server/handlers/meetingCreation.js:9:15
I20240617-14:25:09.424(0)?     at /home/bigbluebutton/.meteor/packages/promise/.0.12.2.1v51k7w.6dob++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40 `
