### ISSUE TITLE
some breakout rooms record publish failed with error: key not found: "SYSTEM"

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/bigbluebutton#21707]
some breakout rooms record publish failed with error:
```
I, [2024-11-19T05:51:56.193934 #484612]  INFO -- : Getting chat events
E, [2024-11-19T05:51:56.195856 #484612] ERROR -- : key not found: "SYSTEM"
E, [2024-11-19T05:51:56.195891 #484612] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/generators/events.rb:790:in `fetch'
E, [2024-11-19T05:51:56.195915 #484612] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/generators/events.rb:790:in `block in get_chat_events'
E, [2024-11-19T05:51:56.195922 #484612] ERROR -- : /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.15.6-x86_64-linux/lib/nokogiri/xml/node_set.rb:235:in `block in each'
E, [2024-11-19T05:51:56.195928 #484612] ERROR -- : /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.15.6-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `upto'
E, [2024-11-19T05:51:56.195935 #484612] ERROR -- : /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.15.6-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `each'
E, [2024-11-19T05:51:56.195941 #484612] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/generators/events.rb:771:in `get_chat_events'
E, [2024-11-19T05:51:56.195947 #484612] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:1101:in `block in process_chat_messages'
E, [2024-11-19T05:51:56.195953 #484612] ERROR -- : /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/builder-3.2.4/lib/builder/xmlbase.rb:176:in `_nested_structures'
E, [2024-11-19T05:51:56.195969 #484612] ERROR -- : /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/builder-3.2.4/lib/builder/xmlbase.rb:69:in `tag!'
E, [2024-11-19T05:51:56.195976 #484612] ERROR -- : /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/builder-3.2.4/lib/builder/xmlbase.rb:94:in `method_missing'
E, [2024-11-19T05:51:56.195982 #484612] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:1100:in `process_chat_messages'
E, [2024-11-19T05:51:56.195988 #484612] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:1424:in `<main>'
I, [2024-11-19T06:54:52.834729 #567022]  INFO -- : Setting recording dir
```

Actually there were 7 breakout rooms, and only 1 of them successfully published.
events.xml, publish and processing logs for one of the failed breakout room attached.
record related folders were not removed from  
/var/bigbluebutton/recording/raw/publish/presentation
/var/bigbluebutton/recording/raw/process/presentation

[publish-5510c4eadc5a9ae67598eb1c49795eb39e0152d6-1731376047659.log](https://github.com/user-attachments/files/17811491/publish-5510c4eadc5a9ae67598eb1c49795eb39e0152d6-1731376047659.log)
[process-5510c4eadc5a9ae67598eb1c49795eb39e0152d6-1731376047659.log](https://github.com/user-attachments/files/17811492/process-5510c4eadc5a9ae67598eb1c49795eb39e0152d6-1731376047659.log)
[events.zip](https://github.com/user-attachments/files/17811522/events.zip)

please inform if any additional logs required

**Comment by amg-web** [comment]
I think all 2.7 is affected maybe 2.6 too as I found lot of failed breakout rooms recording
```
root@virtualclass:~# bbb-record --check

** Potential problems described below **

#
# Warning: /var/log/bigbluebutton/bbb-rap-worker.log is missing.
#

#
# Warning: /var/log/bigbluebutton/post_process.log is missing.
#

#
# Warning: /var/log/bigbluebutton/bbb-recording-cleanup.log is missing.
#

root@virtualclass:~# bbb-conf --check

BigBlueButton Server 2.7.15 (794)
                    Kernel version: 5.4.0-200-generic
                      Distribution: Ubuntu 20.04.6 LTS (64-bit)
                            Memory: 32636 MB
                         CPU cores: 12

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://virtualclass.somedomain.com
                defaultGuestPolicy: ALWAYS_ACCEPT
              defaultMeetingLayout: CUSTOM_LAYOUT

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: virtualclass.somedomain.com
                              port: 
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 51.161.208.70
                   external_rtp_ip: 51.161.208.70
                   external_sip_ip: 51.161.208.70

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: 51.161.208.70:5066
                       wss-binding: 51.161.208.70:7443

UDP port ranges

                        FreeSWITCH: 16384-24576
                           kurento: 24577-32768
                    bbb-webrtc-sfu: 24577-32768
                    bbb-webrtc-recorder: 24577-32768

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: virtualclass.somedomain.com
                 playback_protocol: https
                            ffmpeg: 4.2.7-0ubuntu0.1

/usr/share/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 51.161.208.70
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (bbb-webrtc-sfu)
/etc/bigbluebutton/bbb-webrtc-sfu/production.yml (bbb-webrtc-sfu - override)
    mediasoup.webrtc.*.announcedIp: 51.161.208.70
  mediasoup.plainRtp.*.announcedIp: 51.161.208.70
                        kurento.ip: 51.161.208.70
                       kurento.url: ws://127.0.0.1:8888/kurento
                 freeswitch.sip_ip: 51.161.208.70
                  recordingAdapter: Kurento
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/etc/bbb-webrtc-recorder/bbb-webrtc-recorder.yml (bbb-webrtc-recorder)
/etc/bigbluebutton/bbb-webrtc-recorder.yml (bbb-webrtc-recorder - override)
               debug: false
               recorder.directory: /var/lib/bbb-webrtc-recorder

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)
                             build: 359
                        kurentoUrl: wss://virtualclass.somedomain.com/bbb-webrtc-sfu
            defaultFullAudioBridge: fullaudio
           defaultListenOnlyBridge: fullaudio
                    sipjsHackViaWs: true

/etc/bigbluebutton/turn-stun-servers.xml (STUN Server)
                              stun: turn-au.host.com


# Potential problems described below

root@virtualclass:~# 
```

**Comment by amg-web** [comment]
some more info, table of breakout rooms for same parent meeting.
all has same start timestamp
| id | end timestamp | processing result  |
|---|---|---|
| ce5b973ba86c04d42f60ae9fa7fa5e2a30bf6f35-1731376047659 | 1731377632529 | fail |
| 0dae8bb8dea1616df389b1181a01006fe8eadc10-1731376047659 | 1731377632524 | fail |
| 84aa355a8f42c64624c762744732d135b4bc486e-1731376047659 | 1731377632522 | fail |
| 3377a1cd3925ca5fd296fc397710576516c2de59-1731376047659 | 1731377632516 | success |
| 26a5496fae49d18ae838295d574fdd1b24298dee-1731376047659 | 1731377632511 | fail |
| 5510c4eadc5a9ae67598eb1c49795eb39e0152d6-1731376047659 | 1731377632508 | fail |
| 39a16051ca865aba3807945ea758dd4c7aaf4629-1731376047659 | 1731377632507 | fail |

**Comment by JohnKiller** [comment]
Just happened to me. It was a chat message sent by the API so in the events xml instead of having an user id, it had the text SYSTEM. I've replaced it with my id and then it exported correctly.

**Comment by JohnKiller** [comment]
please keep open, it's a real bug
