### ISSUE TITLE
Whiteboard shape causes recording actor to dies

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#21716]
**Describe the bug**
An exception occurs on the recording actor which causes it to die. Once the actor is dead, no events are saved into redis resulting in incomplete events.xml

Here is the exception.

```
2024-11-15T14:21:18.257Z INFO  o.b.c.redis.RedisStorageService - Starting RedisStorageService with client name: clientName=BbbAppsAkkaRecorder
2024-11-15T14:21:18.260Z ERROR akka.actor.OneForOneStrategy - null
scala.MatchError: null
        at org.bigbluebutton.core.record.events.AddTldrawShapeWhiteboardRecordEvent$AnyJsonFormat$.write(AddTldrawShapeWhiteboardRecordEvent.scala:33)
        at spray.json.RichAny.toJson(package.scala:44)
        at spray.json.CollectionFormats$$anon$1.$anonfun$write$1(CollectionFormats.scala:28)
        at scala.collection.immutable.List.map(List.scala:246)
        at spray.json.CollectionFormats$$anon$1.write(CollectionFormats.scala:28)
        at spray.json.CollectionFormats$$anon$1.write(CollectionFormats.scala:27)
        at org.bigbluebutton.core.record.events.AddTldrawShapeWhiteboardRecordEvent$AnyJsonFormat$.write(AddTldrawShapeWhiteboardRecordEvent.scala:38)
        at spray.json.RichAny.toJson(package.scala:44)
        at spray.json.CollectionFormats$$anon$3.$anonfun$write$3(CollectionFormats.scala:54)
        at scala.collection.StrictOptimizedMapOps.map(StrictOptimizedMapOps.scala:28)
        at scala.collection.StrictOptimizedMapOps.map$(StrictOptimizedMapOps.scala:27)
        at scala.collection.immutable.HashMap.map(HashMap.scala:39)
        at spray.json.CollectionFormats$$anon$3.write(CollectionFormats.scala:52)
        at spray.json.CollectionFormats$$anon$3.write(CollectionFormats.scala:50)
        at spray.json.RichAny.toJson(package.scala:44)
        at org.bigbluebutton.core.record.events.AddTldrawShapeWhiteboardRecordEvent.addAnnotation(AddTldrawShapeWhiteboardRecordEvent.scala:57)
        at org.bigbluebutton.endpoint.redis.RedisRecorderActor.$anonfun$handleSendWhiteboardAnnotationsEvtMsg$2(RedisRecorderActor.scala:309)
        at org.bigbluebutton.endpoint.redis.RedisRecorderActor.$anonfun$handleSendWhiteboardAnnotationsEvtMsg$2$adapted(RedisRecorderActor.scala:301)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
        at org.bigbluebutton.endpoint.redis.RedisRecorderActor.handleSendWhiteboardAnnotationsEvtMsg(RedisRecorderActor.scala:301)
        at org.bigbluebutton.endpoint.redis.RedisRecorderActor.org$bigbluebutton$endpoint$redis$RedisRecorderActor$$handleBbbCommonEnvCoreMsg(RedisRecorderActor.scala:78)
        at org.bigbluebutton.endpoint.redis.RedisRecorderActor$$anonfun$receive$1.applyOrElse(RedisRecorderActor.scala:55)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at org.bigbluebutton.endpoint.redis.RedisRecorderActor.aroundReceive(RedisRecorderActor.scala:35)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
        at akka.actor.ActorCell.invoke(ActorCell.scala:548)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2024-11-15T14:21:18.261Z DEBUG o.b.e.redis.RedisRecorderActor - restarting
2024-11-15T14:21:18.309Z INFO  o.b.c.redis.RedisStorageService - Connected to redis. clientName=BbbAppsAkkaRecorder
2024-11-15T14:21:18.310Z INFO  o.b.c.redis.RedisStorageService - Connected to redis activated. clientName=BbbAppsAkkaRecorder
2024-11-15T14:21:18.313Z DEBUG o.b.e.redis.RedisRecorderActor - restarted
```

**To Reproduce**
I haven't tried reproducing. We got reports that no recordings were being generated and when I investigated I saw this log. The events.xml is missing the events from akka-apps.

** See comment below on version and how to monitor **

**Comment by ritzalam** [comment]
This is the only the contents of events.xml 

```
<?xml version="1.0" encoding="UTF-8"?>
<recording meeting_id="0e391c19c135170b14f7181057f7dd0729b61509-1731688188064" bbb_version="2.6.1">
  <meeting id="0e391c19c135170b14f7181057f7dd0729b61509-1731688188064" externalId="--" name="sdsdsf 4.5" breakout="false"/>
  <metadata .../>
  <breakout/>
  <breakoutRooms/>
  <event timestamp="445291230" module="bbb-webrtc-sfu" eventname="StartWebRTCShareEvent">
    <userId>w_uyad8ntlwxxc</userId>
    <filename>/var/kurento/recordings/0e391c19c135170b14f7181057f7dd0729b61509-1731688188064/medium-w_uyad8ntlwxxc-1731688210377.webm</filename>
    <timestampUTC>1731688210395</timestampUTC>
    <meeting_id>0e391c19c135170b14f7181057f7dd0729b61509-1731688188064</meeting_id>
  </event>
  <event timestamp="445302123" module="bbb-webrtc-sfu" eventname="StartWebRTCDesktopShareEvent">
    <userId>w_uyad8ntlwxxc</userId>
    <filename>/var/kurento/screenshare/0e391c19c135170b14f7181057f7dd0729b61509-1731688188064/130352031-1731688221266.webm</filename>
    <timestampUTC>1731688221288</timestampUTC>
    <meeting_id>0e391c19c135170b14f7181057f7dd0729b61509-1731688188064</meeting_id>
  </event>
  <event timestamp="447971406" module="bbb-webrtc-sfu" eventname="StopWebRTCDesktopShareEvent">
    <userId>w_uyad8ntlwxxc</userId>
    <filename>/var/kurento/screenshare/0e391c19c135170b14f7181057f7dd0729b61509-1731688188064/130352031-1731688221266.webm</filename>
    <timestampUTC>1731690890571</timestampUTC>
    <meeting_id>0e391c19c135170b14f7181057f7dd0729b61509-1731688188064</meeting_id>
  </event>
  <event timestamp="448538260" module="bbb-webrtc-sfu" eventname="StopWebRTCShareEvent">
    <userId>w_uyad8ntlwxxc</userId>
    <filename>/var/kurento/recordings/0e391c19c135170b14f7181057f7dd0729b61509-1731688188064/medium-w_uyad8ntlwxxc-1731688210377.webm</filename>
    <timestampUTC>1731691457425</timestampUTC>
    <meeting_id>0e391c19c135170b14f7181057f7dd0729b61509-1731688188064</meeting_id>
  </event>
</recording>
```

**Comment by ritzalam** [comment]
Nothing. Here are the logs before the exception.

```
2024-11-15T14:21:17.079Z INFO  o.b.core.running.MeetingActor - Handling UserDisconnectedToGlobalAudio: meetingId=3578f6388b80b96811f1177e190eb2cc55b62c1f-1731678142872 userId=w_ttuiqweaef4l
2024-11-15T14:21:17.079Z INFO  o.b.core2.AnalyticsActor - -- analytics -- {"envelope":{"name":"UserDisconnectedFromGlobalAudioMsg","routing":{"voiceConf":"194899414"},"timestamp":1731680477078},"core":{"header":{"name":"UserDisconnectedFromGlobalAudioMsg","voiceConf":"194899414"},"body":{"userId":"w_ttuiqweaef4l","name":"SFU_NO_USERNAME"}}}
2024-11-15T14:21:17.079Z INFO  o.b.core2.AnalyticsActor - -- analytics -- {"envelope":{"name":"UserLeftVoiceConfToClientEvtMsg","routing":{"msgType":"BROADCAST_TO_MEETING","meetingId":"3578f6388b80b96811f1177e190eb2cc55b62c1f-1731678142872","userId":"w_ttuiqweaef4l"},"timestamp":1731680477079},"core":{"header":{"name":"UserLeftVoiceConfToClientEvtMsg","meetingId":"3578f6388b80b96811f1177e190eb2cc55b62c1f-1731678142872","userId":"w_ttuiqweaef4l"},"body":{"voiceConf":"194899414","intId":"w_ttuiqweaef4l","voiceUserId":"w_ttuiqweaef4l"}}}
2024-11-15T14:21:17.085Z INFO  o.b.core.running.MeetingActor - Received user left meeting. user w_ttuiqweaef4l meetingId=3578f6388b80b96811f1177e190eb2cc55b62c1f-1731678142872
2024-11-15T14:21:17.085Z INFO  o.b.core.running.MeetingActor - Setting user left flag. user w_ttuiqweaef4l meetingId=3578f6388b80b96811f1177e190eb2cc55b62c1f-1731678142872
2024-11-15T14:21:18.257Z INFO  o.b.c.redis.RedisStorageService - Starting RedisStorageService with client name: clientName=BbbAppsAkkaRecorder
2024-11-15T14:21:18.260Z ERROR akka.actor.OneForOneStrategy - null
scala.MatchError: null
        at org.bigbluebutton.core.record.events.AddTldrawShapeWhiteboardRecordEvent$AnyJsonFormat$.write(AddTldrawShapeWhiteboardRecordEvent.scala:33)
        at spray.json.RichAny.toJson(package.scala:44)
        at spray.json.CollectionFormats$$anon$1.$anonfun$write$1(CollectionFormats.scala:28)
        at scala.collection.immutable.List.map(List.scala:246)
        at spray.json.CollectionFormats$$anon$1.write(CollectionFormats.scala:28)
        at spray.json.CollectionFormats$$anon$1.write(CollectionFormats.scala:27)
        at org.bigbluebutton.core.record.events.AddTldrawShapeWhiteboardRecordEvent$AnyJsonFormat$.write(AddTldrawShapeWhiteboardRecordEvent.scala:38)
        at spray.json.RichAny.toJson(package.scala:44)
        at spray.json.CollectionFormats$$anon$3.$anonfun$write$3(CollectionFormats.scala:54)
        at scala.collection.StrictOptimizedMapOps.map(StrictOptimizedMapOps.scala:28)
        at scala.collection.StrictOptimizedMapOps.map$(StrictOptimizedMapOps.scala:27)
        at scala.collection.immutable.HashMap.map(HashMap.scala:39)
        at spray.json.CollectionFormats$$anon$3.write(CollectionFormats.scala:52)
        at spray.json.CollectionFormats$$anon$3.write(CollectionFormats.scala:50)
        at spray.json.RichAny.toJson(package.scala:44)
        at org.bigbluebutton.core.record.events.AddTldrawShapeWhiteboardRecordEvent.addAnnotation(AddTldrawShapeWhiteboardRecordEvent.scala:57)
        at org.bigbluebutton.endpoint.redis.RedisRecorderActor.$anonfun$handleSendWhiteboardAnnotationsEvtMsg$2(RedisRecorderActor.scala:309)
        at org.bigbluebutton.endpoint.redis.RedisRecorderActor.$anonfun$handleSendWhiteboardAnnotationsEvtMsg$2$adapted(RedisRecorderActor.scala:301)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
        at org.bigbluebutton.endpoint.redis.RedisRecorderActor.handleSendWhiteboardAnnotationsEvtMsg(RedisRecorderActor.scala:301)
        at org.bigbluebutton.endpoint.redis.RedisRecorderActor.org$bigbluebutton$endpoint$redis$RedisRecorderActor$$handleBbbCommonEnvCoreMsg(RedisRecorderActor.scala:78)
        at org.bigbluebutton.endpoint.redis.RedisRecorderActor$$anonfun$receive$1.applyOrElse(RedisRecorderActor.scala:55)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at org.bigbluebutton.endpoint.redis.RedisRecorderActor.aroundReceive(RedisRecorderActor.scala:35)
```

**Comment by ritzalam** [comment]
This is the last log from the recordingActor after several exception.

```
2024-11-15T14:23:43.519Z ERROR akka.actor.OneForOneStrategy - failed to create a child event loop
akka.actor.PostRestartException: akka://bigbluebutton-apps-system/user/redisRecorderActor: exception post restart (class scala.MatchError)
        at akka.actor.PostRestartException$.apply(Actor.scala:237)
        at akka.actor.dungeon.FaultHandling.$anonfun$finishRecreate$3(FaultHandling.scala:282)
        at akka.actor.dungeon.FaultHandling.$anonfun$finishRecreate$3$adapted(FaultHandling.scala:279)
        at akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1.applyOrElse(FaultHandling.scala:339)
        at akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1.applyOrElse(FaultHandling.scala:334)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
        at akka.actor.dungeon.FaultHandling.finishRecreate(FaultHandling.scala:279)
        at akka.actor.dungeon.FaultHandling.faultRecreate(FaultHandling.scala:101)
        at akka.actor.dungeon.FaultHandling.faultRecreate$(FaultHandling.scala:80)
        at akka.actor.ActorCell.faultRecreate(ActorCell.scala:411)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:517)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:536)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
        at akka.dispatch.Mailbox.run(Mailbox.scala:230)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedConstructorAccessor328.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at akka.util.Reflect$.instantiate(Reflect.scala:73)
        at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:101)
        at akka.actor.Props.newActor(Props.scala:226)
        at akka.actor.ActorCell.newActor(ActorCell.scala:616)
        at akka.actor.dungeon.FaultHandling.finishRecreate(FaultHandling.scala:266)
        ... 13 common frames omitted
Caused by: java.lang.IllegalStateException: failed to create a child event loop
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:60)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:49)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:69)
        at io.lettuce.core.resource.DefaultEventLoopGroupProvider.createEventLoopGroup(DefaultEventLoopGroupProvider.java:239)
        at io.lettuce.core.resource.DefaultEventLoopGroupProvider.doCreateEventLoopGroup(DefaultEventLoopGroupProvider.java:190)
        at io.lettuce.core.resource.DefaultEventLoopGroupProvider.getOrCreate(DefaultEventLoopGroupProvider.java:172)
        at io.lettuce.core.resource.DefaultEventLoopGroupProvider.allocate(DefaultEventLoopGroupProvider.java:113)
        at io.lettuce.core.AbstractRedisClient.lambda$getEventLoopGroup$0(AbstractRedisClient.java:305)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at io.lettuce.core.AbstractRedisClient.getEventLoopGroup(AbstractRedisClient.java:304)
        at io.lettuce.core.ConnectionBuilder.configureBootstrap(ConnectionBuilder.java:258)
        at io.lettuce.core.AbstractRedisClient.connectionBuilder(AbstractRedisClient.java:274)
```
