### ISSUE TITLE
Greenlight v3 don't respond on fresh installation - HTTP 500

### ISSUE THREAD

**Issue by Zvangi** [bigbluebutton/bigbluebutton#21797]
**Describe the bug**

I run few BBB instances on my servers. Recently tried to install one instance with BBB + Greenlight but greenlight was not responding after installation. I tried to install both BBBv3 and BBBv2 on fresh servers. Both version installed correctly. There was no errors after script finished running.

I can't access my greenlight installation at my domain. Getting straight HTTP 500 error.

**Installation type**

Commands used to install

Ubuntu 22.04

`wget -qO- https://raw.githubusercontent.com/bigbluebutton/bbb-install/refs/heads/v3.0.x-release/bbb-install.sh | bash -s -- -w -v jammy-300 -s bbb.mydomain.com -e info@myemail.com -g`

Ubuntu 20.04

`wget -qO- https://raw.githubusercontent.com/bigbluebutton/bbb-install/v2.7.x-release/bbb-install.sh | bash -s -- -w -v focal-270 -s bbb.mydomain.com -e info@myemail.com -g`

**Firewall and IP address type**

No firewall. My server has IPV4

**Console output**

 ```
greenlight-v3 is now installed and accessible on: https://mydomain.com/
bbb-install: To create Greenlight administrator account, see: https://docs.bigbl                                                                                                                                                             uebutton.org/greenlight/v3/install#creating-an-admin-account

BigBlueButton Server 2.7.15 (786)
                    Kernel version: 5.4.0-200-generic
                      Distribution: Ubuntu 20.04.6 LTS (64-bit)
                            Memory: 16380 MB
                         CPU cores: 8

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://mydomain.com
                defaultGuestPolicy: ALWAYS_ACCEPT
              defaultMeetingLayout: CUSTOM_LAYOUT

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: mydomain.com
                              port: 80, [::]:80127.0.0.1:82 http2 proxy_protocol                                                                                                                                                             , [::1]:82 http2127.0.0.1:81 proxy_protocol, [::1]:81

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: ipv4.ipv4.ipv4.ipv4
                   external_rtp_ip: ipv4.ipv4.ipv4.ipv4
                   external_sip_ip: ipv4.ipv4.ipv4.ipv4

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: ipv4.ipv4.ipv4.ipv4:5066
                       wss-binding: ipv4.ipv4.ipv4.ipv4:7443

UDP port ranges

                        FreeSWITCH: 16384-24576
                           kurento: 24577-32768
                    bbb-webrtc-sfu: 24577-32768
                    bbb-webrtc-recorder: 24577-32768

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: mydomain.com
                 playback_protocol: https
                            ffmpeg: 4.2.7-0ubuntu0.1

/usr/share/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: ipv4.ipv4.ipv4.ipv4
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (bbb-webrtc-sfu)
/etc/bigbluebutton/bbb-webrtc-sfu/production.yml (bbb-webrtc-sfu - override)
    mediasoup.webrtc.*.announcedIp: ipv4.ipv4.ipv4.ipv4
  mediasoup.plainRtp.*.announcedIp: ipv4.ipv4.ipv4.ipv4
                        kurento.ip: ipv4.ipv4.ipv4.ipv4
                       kurento.url: ws://127.0.0.1:8888/kurento
                 freeswitch.sip_ip: ipv4.ipv4.ipv4.ipv4
                  recordingAdapter: Kurento
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/etc/bbb-webrtc-recorder/bbb-webrtc-recorder.yml (bbb-webrtc-recorder)
/etc/bigbluebutton/bbb-webrtc-recorder.yml (bbb-webrtc-recorder - override)
               debug: false
               recorder.directory: /var/lib/bbb-webrtc-recorder

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 c                                                                                                                                                             lient)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)
                             build: 359
                        kurentoUrl: wss://mydomain.com/bbb-webrtc-sfu
            defaultFullAudioBridge: fullaudio
           defaultListenOnlyBridge: fullaudio
                    sipjsHackViaWs: true


# Potential problems described below

```
**Additional context**

I tried creating an administrator account. Got this error;

```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "roles" does not exist (ActiveRecord::StatementInvalid)
LINE 10:  WHERE a.attrelid = '"roles"'::regclass
                             ^
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `exec'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `block (2 levels) in query'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:1027:in `block in with_raw_connection'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:999:in `with_raw_connection'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:18:in `block in query'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:1142:in `log'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:17:in `query'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:1074:in `column_definitions'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:109:in `columns'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:346:in `block in columns'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:345:in `fetch'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:345:in `columns'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:354:in `block in columns_hash'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:353:in `fetch'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:353:in `columns_hash'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:58:in `columns_hash'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:188:in `columns_hash'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/model_schema.rb:622:in `load_schema!'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/attributes.rb:264:in `load_schema!'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/encryption/encryptable_record.rb:127:in `load_schema!'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/model_schema.rb:567:in `block in load_schema'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/model_schema.rb:564:in `synchronize'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/model_schema.rb:564:in `load_schema'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/model_schema.rb:425:in `columns_hash'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/core.rb:293:in `block in find_by'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/core.rb:262:in `each'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/core.rb:262:in `each_with_object'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/core.rb:262:in `find_by'
/usr/src/app/lib/tasks/user.rake:71:in `check_role!'
/usr/src/app/lib/tasks/user.rake:32:in `block (2 levels) in <main>'
/usr/src/app/lib/tasks/admin.rake:31:in `block (2 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'

Caused by:
PG::UndefinedTable: ERROR:  relation "roles" does not exist (PG::UndefinedTable)
LINE 10:  WHERE a.attrelid = '"roles"'::regclass
                             ^
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `exec'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `block (2 levels) in query'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:1027:in `block in with_raw_connection'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:999:in `with_raw_connection'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:18:in `block in query'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:1142:in `log'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:17:in `query'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:1074:in `column_definitions'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:109:in `columns'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:346:in `block in columns'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:345:in `fetch'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:345:in `columns'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:354:in `block in columns_hash'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:353:in `fetch'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:353:in `columns_hash'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:58:in `columns_hash'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/schema_cache.rb:188:in `columns_hash'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/model_schema.rb:622:in `load_schema!'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/attributes.rb:264:in `load_schema!'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/encryption/encryptable_record.rb:127:in `load_schema!'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/model_schema.rb:567:in `block in load_schema'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/model_schema.rb:564:in `synchronize'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/model_schema.rb:564:in `load_schema'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/model_schema.rb:425:in `columns_hash'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/core.rb:293:in `block in find_by'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/core.rb:262:in `each'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/core.rb:262:in `each_with_object'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/core.rb:262:in `find_by'
/usr/src/app/lib/tasks/user.rake:71:in `check_role!'
/usr/src/app/lib/tasks/user.rake:32:in `block (2 levels) in <main>'
/usr/src/app/lib/tasks/admin.rake:31:in `block (2 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
Tasks: TOP => user:create
(See full trace by running task with --trace)
```

My docker logs greenlight-v3 result;

```
[0b8cd86e-79f1-4e0c-80ca-d1c9bb64cacd]     22:     <!-- Open Graph Attributes -->
[0b8cd86e-79f1-4e0c-80ca-d1c9bb64cacd]     23:     <meta property="og:title" content="<%= page_title %>" />
[0b8cd86e-79f1-4e0c-80ca-d1c9bb64cacd]     24:     <meta property="og:description" content="<%= t('opengraph.description') %>" />
[0b8cd86e-79f1-4e0c-80ca-d1c9bb64cacd]     25:     <meta property="og:image" content="<%= branding_image %>" />
[0b8cd86e-79f1-4e0c-80ca-d1c9bb64cacd]     26:
[0b8cd86e-79f1-4e0c-80ca-d1c9bb64cacd]     27:     <%= csrf_meta_tags %>
[0b8cd86e-79f1-4e0c-80ca-d1c9bb64cacd]     28:     <%= csp_meta_tag %>
[0b8cd86e-79f1-4e0c-80ca-d1c9bb64cacd]
I, [2024-12-01T04:23:48.481536 #1]  INFO -- : [07702856-fcc4-44de-a629-5acfaba7346a] method=GET path=/ format=html controller=ComponentsController action=index status=500 allocations=450 duration=1.23 view=0.00 db=0.59 time=2024-12-01 04:23:48 UTC host=greenlight
F, [2024-12-01T04:23:48.481848 #1] FATAL -- : [07702856-fcc4-44de-a629-5acfaba7346a]
[07702856-fcc4-44de-a629-5acfaba7346a] ActionView::Template::Error (PG::UndefinedTable: ERROR:  relation "site_settings" does not exist
LINE 10:  WHERE a.attrelid = '"site_settings"'::regclass
```

**Comment by Zvangi** [comment]
Added the issue to greenlight issues. We can remove this post if it's misplaced.

**Comment by edisnezir** [comment]
the same for me with 2.7 version.

ERROR:  relation "site_settings" does not exist

**Comment by virtualized-human** [comment]
also had this issue. the comment above fixed it.

**Comment by Zvangi** [comment]
In case someone needs more info about this:

https://github.com/bigbluebutton/greenlight/issues/5969

**Comment by farhatahmad** [comment]
Fixed in the latest release https://github.com/bigbluebutton/greenlight/releases/tag/release-3.4.3
