### ISSUE TITLE
Deskshare Java applet showed some errors upon shutdown

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2466]
Originally reported on Google Code with ID 1714

```
The following errors appeared in the Java Console when the deskshare was stopped:

Exception in thread "pool-1-thread-1" java.lang.IllegalMonitorStateException 
at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(Unknown Source) 
at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(Unknown Source) 
at java.util.concurrent.locks.ReentrantLock.unlock(Unknown Source) 
at java.util.concurrent.LinkedBlockingQueue.take(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
at java.lang.Thread.run(Unknown Source) 
Exception in thread "pool-2-thread-1" java.lang.IllegalMonitorStateException 
at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(Unknown Source) 
at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(Unknown Source) 
at java.util.concurrent.locks.ReentrantLock.unlock(Unknown Source) 
at java.util.concurrent.LinkedBlockingQueue.take(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
at java.lang.Thread.run(Unknown Source) 
Exception in thread "pool-4-thread-1" java.lang.IllegalMonitorStateException 
at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(Unknown Source) 
at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(Unknown Source) 
at java.util.concurrent.locks.ReentrantLock.unlock(Unknown Source) 
at java.util.concurrent.LinkedBlockingQueue.take(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
at java.lang.Thread.run(Unknown Source) 
Exception in thread "pool-5-thread-1" java.lang.IllegalMonitorStateException 
at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(Unknown Source) 
at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(Unknown Source) 
at java.util.concurrent.locks.ReentrantLock.unlock(Unknown Source) 
at java.util.concurrent.LinkedBlockingQueue.take(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
at java.lang.Thread.run(Unknown Source)

```

Reported by `ritzalam` on 2014-01-27 16:53:40

**Comment by ffdixon** [comment]
Closing this issue as it is no longer relevant since shifting desktop sharing to launching outside the borwser.  See http://docs.bigbluebutton.org/1.1/overview.html#faster-desktop-sharing
