### ISSUE TITLE
If redis is stopped, tomcat can loop and run out of memory

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2467]
Originally reported on Google Code with ID 1715

```
If redis is stopped, and tomcat is still running, then the tomcat code has the errors
below. 
We need the bigbluebutton servlet to terminate cleanly in this case, since tomcat is
running other applications.

2012-02-10 15:10:11,484 INFO [org.bigbluebutton.api.MeetingService] - <Cleaning up
expired meetings> 
Exception in thread "pool-20-thread-1" redis.clients.jedis.exceptions.JedisConnectionException:
It seems like server has closed the connection. 
at redis.clients.util.RedisInputStream.readLine(RedisInputStream.java:91) 
at redis.clients.jedis.Protocol.processMultiBulkReply(Protocol.java:110) 
at redis.clients.jedis.Protocol.process(Protocol.java:63) 
at redis.clients.jedis.Protocol.read(Protocol.java:122) 
at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:196) 
at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:88) 
at redis.clients.jedis.JedisPubSub.proceedWithPatterns(JedisPubSub.java:76) 
at redis.clients.jedis.Jedis.psubscribe(Jedis.java:1988) 
at org.bigbluebutton.api.messaging.RedisMessagingService$1.run(RedisMessagingService.java:81)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)

at java.lang.Thread.run(Thread.java:636) 
2012-02-10 15:11:11,484 INFO [org.bigbluebutton.api.MeetingService] - <Cleaning up
expired meetings> 
2012-02-10 15:12:11,484 INFO [org.bigbluebutton.api.MeetingService] - <Cleaning up
expired meetings> 
Feb 10, 2012 3:12:28 PM org.apache.catalina.startup.HostConfig checkResources 
INFO: Reloading context [/bigbluebutton] 
2012-02-10 15:12:28,105 DEBUG [net.sf.ehcache.store.DiskStore] - <Spool Thread interrupted.>

2012-02-10 15:12:28,105 DEBUG [net.sf.ehcache.store.DiskStore] - <Deleting file org.jsecurity.realm.text.PropertiesRealm-0-accounts.data>

2012-02-10 15:12:28,197 INFO [org.codehaus.groovy.grails.web.context.GrailsContextLoader]
- <Destroying Spring parent WebApplicationContext Root WebApplicationContext> 
Feb 10, 2012 3:12:28 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads

SEVERE: A web application appears to have started a thread named [Thread-95] but has
failed to stop it. This is very likely to create a memory leak. 
Feb 10, 2012 3:12:28 PM org.apache.catalina.loader.WebappClassLoader clearReferencesStopTimerThread

SEVERE: A web application appears to have started a TimerThread named [bbb-api-cleanup]
via the java.util.Timer API but has failed to stop it. To prevent a memory leak, the
timer (and hence the associated thread) has been forcibly cancelled. 
Feb 10, 2012 3:12:28 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads

SEVERE: A web application appears to have started a thread named [pool-22-thread-1]
but has failed to stop it. This is very likely to create a memory leak. 
Feb 10, 2012 3:12:28 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads

SEVERE: A web application appears to have started a thread named [pool-20-thread-2]
but has failed to stop it. This is very likely to create a memory leak. 
Feb 10, 2012 3:12:28 PM org.apache.catalina.loader.WebappClassLoader clearThreadLocalMap

SEVERE: A web application created a ThreadLocal with key of type [org.codehaus.groovy.runtime.GroovyCategorySupport.MyThreadLocal]
(value [org.codehaus.groovy.runtime.GroovyCategorySupport$MyThreadLocal@c39bb3]) and
a value of type [java.lang.ref.SoftReference] (value [java.lang.ref.SoftReference@233666])
but failed to remove it when the web application was stopped. To prevent a memory leak,
the ThreadLocal has been forcibly removed. 
Feb 10, 2012 3:12:28 PM org.apache.catalina.loader.WebappClassLoader clearThreadLocalMap

SEVERE: A web application created a ThreadLocal with key of type [org.codehaus.groovy.runtime.GroovyCategorySupport.MyThreadLocal]
(value [org.codehaus.groovy.runtime.GroovyCategorySupport$MyThreadLocal@c39bb3]) and
a value of type [java.lang.ref.SoftReference] (value [java.lang.ref.SoftReference@1c88890])
but failed to remove it when the web application was stopped. To prevent a memory leak,
the ThreadLocal has been forcibly removed. 
Feb 10, 2012 3:12:28 PM org.apache.catalina.loader.WebappClassLoader clearThreadLocalMap

SEVERE: A web application created a ThreadLocal with key of type [org.jsecurity.util.ThreadContext$1]
(value [org.jsecurity.util.ThreadContext$1@7dcdd5]) and a value of type [java.util.HashMap]
(value [{}]) but failed to remove it when the web application was stopped. To prevent
a memory leak, the ThreadLocal has been forcibly removed. 
SEVERE: A web application created a ThreadLocal with key of type [org.jsecurity.util.ThreadContext$1]
(value [org.jsecurity.util.ThreadContext$1@7dcdd5]) and a value of type [java.util.HashMap]
(value [{org.jsecurity.util.ThreadContext_SECURITY_MANAGER_KEY=org.jsecurity.web.DefaultWebSecurityManager@ca0a76,
org.jsecurity.util.ThreadContext_SUBJECT_KEY=org.jsecurity.subject.DelegatingSubject@7507f4,
javax.servlet.ServletRequest_JSECURITY_THREAD_CONTEXT_KEY=org.jsecurity.web.servlet.JSecurityHttpServletRequest@15d58b9,
org.jsecurity.util.ThreadContext_INET_ADDRESS_KEY=/127.0.0.1, javax.servlet.ServletResponse_JSECURITY_THREAD_CONTEXT_KEY=org.apache.catalina.connector.ResponseFacade@16be089}])
but failed to remove it when the web application was stopped. To prevent a memory leak,
the ThreadLocal has been forcibly removed. 
log4j:ERROR LogMananger.repositorySelector was null likely due to error in class reloading,
using NOPLoggerRepository. 
Exception in thread "ContainerBackgroundProcessor[StandardEngine[Catalina]]" java.lang.OutOfMemoryError:
PermGen space 
javax.servlet.ServletException: Servlet execution threw an exception 
Exception in thread "http-8080-4" Exception in thread "http-9443-6" java.lang.OutOfMemoryError:
PermGen space

```

Reported by `ritzalam` on 2014-01-27 16:57:54

**Comment by ffdixon** [comment]
@GhaziTriki is this still an issue with 2.2?

**Comment by GhaziTriki** [comment]
@ffdixon Can you assign me this issue? I will test it. We replaced `jedis` by `lettuce` and I think we have a correct reconnection policy now.

**Comment by GhaziTriki** [comment]
@ffdixon I stopped `redis-server` and left all the other service running for 18 hours. I observer that JVM application kept retrying to connect to redis without reporting any expcetion. This issue can be closed.
