### ISSUE TITLE
using 'configToken' with a non-existent file results in null pointer exception in Grails

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#3165]
The user is displayed a generic green Grails error page.

Exception:
```
2016-06-03 19:00:15,073Z DEBUG grails.app.controllers.org.bigbluebutton.web.controllers.ApiController  - ApiController#join
2016-06-03 19:00:15,074Z INFO  grails.app.controllers.org.bigbluebutton.web.controllers.ApiController  - Retrieving meeting 6f38ed6f70802cec8c761b6efd568f2349df2b25
2016-06-03 19:00:15,078Z ERROR org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver  - NullPointerException occurred when processing request: [GET] /bigbluebutton/api/join
Cannot get property 'config' on null object. Stacktrace follows:
java.lang.NullPointerException: Cannot get property 'config' on null object
        at org.bigbluebutton.web.controllers.ApiController$_closure3.doCall(ApiController.groovy:365)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:200)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by hostbbb** [comment]
Fyi - Issue #2960 reported the same thing.

**Comment by jfederico** [comment]
What should be the response for this exception?, an error message or to load the default config.xml?
