### ISSUE TITLE
Installation for ubuntu 14 - 64 bits issue

### ISSUE THREAD

**Issue by johnfelipe** [bigbluebutton/bigbluebutton#3221]
All log is in here

https://gist.github.com/johnfelipe/74c1d11294c0e3f73e744f42af633453

this is errors:

	Traceback (most recent call last):
	  File "/usr/lib/update-notifier/package-data-downloader", line 239, in process_download_requests
		dest_file = urllib.urlretrieve(files[i])[0]
	  File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
		return _urlopener.retrieve(url, filename, reporthook, data)
	  File "/usr/lib/python2.7/urllib.py", line 240, in retrieve
		fp = self.open(url, data)
	  File "/usr/lib/python2.7/urllib.py", line 208, in open
		return getattr(self, name)(url)
	  File "/usr/lib/python2.7/urllib.py", line 359, in open_http
		return self.http_error(url, fp, errcode, errmsg, headers)
	  File "/usr/lib/python2.7/urllib.py", line 372, in http_error
		result = method(url, fp, errcode, errmsg, headers)
	  File "/usr/lib/python2.7/urllib.py", line 665, in http_error_301
		return self.http_error_302(url, fp, errcode, errmsg, headers, data)
	  File "/usr/lib/python2.7/urllib.py", line 635, in http_error_302
		data)
	  File "/usr/lib/python2.7/urllib.py", line 661, in redirect_internal
		return self.open(newurl)
	  File "/usr/lib/python2.7/urllib.py", line 208, in open
		return getattr(self, name)(url)
	  File "/usr/lib/python2.7/urllib.py", line 359, in open_http
		return self.http_error(url, fp, errcode, errmsg, headers)
	  File "/usr/lib/python2.7/urllib.py", line 372, in http_error
		result = method(url, fp, errcode, errmsg, headers)
	  File "/usr/lib/python2.7/urllib.py", line 635, in http_error_302
		data)
	  File "/usr/lib/python2.7/urllib.py", line 661, in redirect_internal
		return self.open(newurl)
	  File "/usr/lib/python2.7/urllib.py", line 208, in open
		return getattr(self, name)(url)
	  File "/usr/lib/python2.7/urllib.py", line 345, in open_http
		h.endheaders(data)
	  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
		self._send_output(message_body)
	  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
		self.send(msg)
	  File "/usr/lib/python2.7/httplib.py", line 797, in send
		self.connect()
	  File "/usr/lib/python2.7/httplib.py", line 778, in connect
		self.timeout, self.source_address)
	  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
		raise err
	IOError: [Errno socket error] timed out

and

	Installing RDoc documentation for bundler-1.12.5...
	Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
	installing your bundle as root will break this application for all non-root
	users on this machine.
	Fetching gem metadata from http://rubygems.org/
	Fetching version metadata from http://rubygems.org/
	Resolving dependencies...
	Rubygems 1.8.23 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.

and for last

	Setting up bbb-web (1.0.0-1ubuntu98) ...
	 * Stopping Tomcat servlet engine tomcat7                                [ OK ]
	 * no JDK or JRE found - please set JAVA_HOME
	dpkg: error processing package bbb-web (--configure):
	 subprocess installed post-installation script returned error exit status 1
	Setting up bbb-playback-presentation (1.0.0-1ubuntu22) ...
	dpkg: dependency problems prevent configuration of bbb-config:
	 bbb-config depends on bbb-web; however:
	  Package bbb-web is not configured yet.

	dpkg: error processing package bbb-config (--configure):
	 dependency problems - leaving unconfigured
	dpkg: dependency problems prevent configuration of bigbluebutton:
	 bigbluebutton depends on bbb-config; however:
	  Package bbb-config is not configured yet.

	dpkg: error processing package bigbluebutton (--configure):
	 dependency problems - leaving unconfigured
	Setting up odbcinst1debian2:amd64 (2.2.14p2-5ubuntu5) ...
	Setting up unixodbc (2.2.14p2-5ubuntu5) ...
	Setting up bbb-freeswitch (1.0.0-1ubuntu48) ...
	No apport report written because the error message indicates its a followup error from a previous failure.
							  No apport report written because the error message indicates its a followup error from a previous failure.
														adduser: Warning: The home directory `/opt/freeswitch' does not belong to the user you are currently creating.
	Adding user `freeswitch' to group `audio' ...
	Adding user freeswitch to group audio
	Done.
	25430 Backgrounding.
	Setting up odbcinst (2.2.14p2-5ubuntu5) ...
	Processing triggers for ureadahead (0.100.0-16) ...
	Setting up bbb-apps-sip (1.0.0-1ubuntu23) ...
	Processing triggers for libc-bin (2.19-0ubuntu6.9) ...
	Errors were encountered while processing:
	 bbb-web
	 bbb-config
	 bigbluebutton
	E: Sub-process /usr/bin/dpkg returned an error code (1)

How solved all?

**Comment by hostbbb** [comment]
Usually means locales are not correctly.  http://docs.bigbluebutton.org/install/install.html#before-you-install

Make sure these are done.

In addition to ensuring your server meets the above requirements, there are a few more checks. First, the locale of the server must be en_US.UTF-8. To verify , enter the following command

$ cat /etc/default/locale
LANG="en_US.UTF-8"

**Comment by ffdixon** [comment]
Hi John,

Can we get you to post this to our bigbluebutton-setup mailing list.  We'll handle all installation/configuration issues there.

   https://groups.google.com/forum/#!forum/bigbluebutton-setup

If we see an error in BigBlueButton itself, we'll open an issue to track it here.
