### ISSUE TITLE
Updating secret does not works

### ISSUE THREAD

**Issue by dvapelnik** [bigbluebutton/bigbluebutton#3305]
I wrote
`# bbb-conf --setsecret <my-new-secret-key>`
The secret key has been changed:
```
# cat /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties | grep security
securitySalt=<my-new-secret-key>
```
But I cant use API because response has error: `You did not pass the checksum security check`.
I set up default salt (secret) from clean installed software. It works. OK.
But new salt (secret) not used.
Is it bug?

`bbb-conf --check` with new salt (updated on demo config too)
```
# bbb-conf --check

BigBlueButton Server 1.0.0 (1017)
                    Kernel version: 4.2.0-41-generic
                      Distribution: Ubuntu 14.04.4 LTS (64-bit)
                            Memory: 7982 MB

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
  		Port test (tunnel): 193.243.159.108
                              Red5: 193.243.159.108
              useWebrtcIfAvailable: true

/opt/freeswitch/conf/sip_profiles/external.xml (FreeSWITCH)
                    websocket port: 5066
                    WebRTC enabled: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: <SERVER_IP>
                              port: 80
                    bbb-client dir: /var/www/bigbluebutton

/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties (bbb-web)
                      bbb-web host: <SERVER_IP>

/var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp (API demos)
                               url: <SERVER_IP>

/usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
                  voice conference: FreeSWITCH
                     capture video: true
                   capture desktop: true

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback host: <SERVER_IP>


** Potential problems described below **
# Warning: The API demos are installed and accessible from:
#
#    http://193.243.159.108/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    sudo apt-get purge bbb-demo
```
Demo not works with updated secret on config:
```
Error: getJoinURL() failed
checksumError: You did not pass the checksum security check
These API demos use the BigBlueButton API. The source code for these demos is available here.
```

**Comment by ffdixon** [comment]
You need to manually change the shared secret for the API examples at

  /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp

**Comment by dvapelnik** [comment]
@ffdixon it has been changed manually. I can't use API from another my services not demo. It looks like old secret still used by server

**Comment by ffdixon** [comment]
Check the shared secret in bbb-web so it matches what shared secret you are using on the API calls

   http://docs.bigbluebutton.org/support/faq.html#where-is-the-shared-secret-located

**Comment by dvapelnik** [comment]
From http://docs.bigbluebutton.org/support/faq.html#where-is-the-shared-secret-located

> You’ll find the shared secret (salt) in the file
> 
>    `/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties`
> Look for the line
> 
>    `beans.dynamicConferenceService.securitySalt=<value_of_salt>`
> This is the security salt used for enabling 3rd party plug-ins and external applications to access your BigBlueButton server through it’s API.

I wrote on topic:
```
# cat /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties | grep security
securitySalt=<my-new-secret-key>
```
It looks like secret key has been changed correctly but looks like the old secret key slill used by server

What i doing wrong?

**Comment by ffdixon** [comment]
Can you make the shared secret in the API examples match the shared secret in bigbluebutton.properties, restart your server, and see if you can login.

**Comment by dvapelnik** [comment]
Should I restart server (tomcat-webserver or server as machine) after updating secret key?
OK, I will restart tomcat webserver and check it tomorrow
I will wrote reply

**Comment by dvapelnik** [comment]
BBB needs restart `tomcat7` web-server after changing shared secret key but `java.lang.NullPointerException` has been threw on creating first meeting after restart
```
java.lang.NullPointerException
	at org.apache.jsp.demo1_jsp.getJoinURL(demo1_jsp.java:223)
	at org.apache.jsp.demo1_jsp._jspService(demo1_jsp.java:1279)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ffdixon** [comment]
See

  http://docs.bigbluebutton.org/support/faq.html#using-the-api-examples-i-get-a-javalangnullpointerexception-when-trying-to-join-a-room

**Comment by dvapelnik** [comment]
Thx for reply @ffdixon
