### ISSUE TITLE
Red5 unable to bind port 8081

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#3375]
Hey guys!

We were making some tests over here with FS 1.6 and noticed that mod_verto uses the same 8081 port Red5 uses. This happens with you guys too?

Caught this on bbb-apps console:
```
[ERROR] [main] org.red5.net.websocket.WebSocketTransport - Exception occurred during resolve / bind
java.io.IOException: Error while binding on /0.0.0.0:8081
original message : Address already in use
	at org.apache.mina.transport.socket.nio.NioSocketAcceptor.open(NioSocketAcceptor.java:238) ~[mina-core-2.0.9.jar:na]
	at org.apache.mina.transport.socket.nio.NioSocketAcceptor.open(NioSocketAcceptor.java:51) ~[mina-core-2.0.9.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoAcceptor.registerHandles(AbstractPollingIoAcceptor.java:583) ~[mina-core-2.0.9.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoAcceptor.access$400(AbstractPollingIoAcceptor.java:71) ~[mina-core-2.0.9.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoAcceptor$Acceptor.run(AbstractPollingIoAcceptor.java:457) ~[mina-core-2.0.9.jar:na]
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) ~[mina-core-2.0.9.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_111]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_111]

```

**Comment by ritzalam** [comment]
You can comment out the websocket plugin in red5/conf/jee-container.xml
