### ISSUE TITLE
? in chat breaks recording playback.

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#3670]
http://demo.bigbluebutton.org/playback/presentation/0.9.0/playback.html?meetingId=6e35e3b2778883f5db637d7a5dba0a427f692e91-1487342648576

Happened on server, and reproduced on demo.

playback.js:348 Loading audio
playback.js:453 ==Loading acorn media player 
jquery.min.js:2 Uncaught Error: Syntax error, unrecognized expression: this is a test ?
    at Function.bc.error (http://demo.bigbluebutton.org/playback/presentation/0.9.0/lib/jquery.min.js:2:59146)
    at bh (http://demo.bigbluebutton.org/playback/presentation/0.9.0/lib/jquery.min.js:2:46728)
    at bp (http://demo.bigbluebutton.org/playback/presentation/0.9.0/lib/jquery.min.js:2:49139)
    at bp (http://demo.bigbluebutton.org/playback/presentation/0.9.0/lib/jquery.min.js:2:60556)
    at Function.bc [as find] (http://demo.bigbluebutton.org/playback/presentation/0.9.0/lib/jquery.min.js:2:45807)
    at init.find (http://demo.bigbluebutton.org/playback/presentation/0.9.0/lib/jquery.min.js:2:61546)
    at init (http://demo.bigbluebutton.org/playback/presentation/0.9.0/lib/jquery.min.js:2:10553)
    at p (http://demo.bigbluebutton.org/playback/presentation/0.9.0/lib/jquery.min.js:2:9336)
    at init.Popcorn.plugin.options.start.elem (http://demo.bigbluebutton.org/playback/presentation/0.9.0/lib/popcorn.chattimeline.js:66:8)
    at init.d.p.(anonymous function).t.(anonymous function) [as chattimeline] (http://demo.bigbluebutton.org/playback/presentation/0.9.0/lib/popcorn-

**Comment by kepstin** [comment]
Verified that with e782709 link targets still work correctly, and messages with question marks are parsed properly: http://demo.bigbluebutton.org/playback/presentation/0.9.0/playback.html?meetingId=6e35e3b2778883f5db637d7a5dba0a427f692e91-1488383076977
