### ISSUE TITLE
NumberFormatException Exception thrown when parsing metadata.xml 

### ISSUE THREAD

**Issue by adnanel** [bigbluebutton/bigbluebutton#4541]
Version used: latest (BigBlueButton Version 2.0.0-beta)

When using the following API url:
`https://my-domain-com/bigbluebutton/api/getRecordings?meetingID=49afac146a9dfaeead1a667294063afbf27bd2a2-1110-9367&checksum=***********`

The metadata.xml gets parsed and works most of the time. BUT when parsing a file which has the following value for the <raw_size> tag: 4181308972

The parser fails to read the value and no meetings are found. 
When the value is manually changed to a smaller value it works, so I assume it's an overflow issue.

The full stacktrace is given below
```
2017-10-20 14:35:09,136+02:00 INFO  org.bigbluebutton.api2.util.RecMetaXmlHelper  - Exception while saving /var/bigbluebutton/published/presentation/91ad71b290c547fc0adc9e3f345ffd07c494dd65-1507961061531/metadata.xml
2017-10-20 14:35:09,137+02:00 INFO  org.bigbluebutton.api2.util.RecMetaXmlHelper  - Exception details: {}
java.lang.NumberFormatException: For input string: "4181308972"
	at org.bigbluebutton.api2.util.RecMetaXmlHelper.getRecordingMetadata(RecMetaXmlHelper.scala:72)
	at org.bigbluebutton.api.util.RecordingMetadataReaderHelper.getRecordingMetadata(RecordingMetadataReaderHelper.java:25)
	at org.bigbluebutton.api.RecordingService.getRecordingMetadata(RecordingService.java:105)
	at org.bigbluebutton.api.RecordingService.getRecordingsMetadata(RecordingService.java:86)
	at org.bigbluebutton.api.RecordingService.getRecordings2x(RecordingService.java:98)
	at org.bigbluebutton.api.MeetingService.getRecordings2x(MeetingService.java:327)
	at org.bigbluebutton.web.controllers.ApiController$_closure17.doCall(ApiController.groovy:1555)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

A fix for this would be awesome as we're using this BBB version in production (even though it's beta, i know)

**Comment by kepstin** [comment]
This is a problem with BBB web, it's probably parsing the value as a 32bit number, but in this case it's too big, >4gb.

**Comment by ritzalam** [comment]
Hi @adnanel 

Can you please verify that this fixes your issue?

Thanks.

**Comment by ffdixon** [comment]
@adnael, as Richard said, we have pushed out an update that has this fix, see

  https://groups.google.com/d/msg/bigbluebutton-dev/xq3_fmWf5zY/sdF5hrhXCAAJ

If you could update your server, very interested to hear if this item is fixed for you.

**Comment by adnanel** [comment]
Hello all,
Thanks for the quick response, we will update on friday night just in case we break something, we'll have more time to fix on the weekend.
I'll post back as soon as we test it out.

**Comment by adnanel** [comment]
The issue is fixed now, thanks!

**Comment by ffdixon** [comment]
Great -- thanks for helping us find the issue and test it's fix.
