### ISSUE TITLE
requesterUserId is null on subscribe for `current-user`

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#4747]
```
Error: Match error: Expected string, got null
I20171129-11:49:32.362(-5)?     at exports.check (packages/check.js:56:15)
I20171129-11:49:32.362(-5)?     at [object Object]._handler (imports/api/users/server/publishers.js:12:3)
```
in the Terminal on user join/refresh

https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/bigbluebutton-html5/imports/api/users/server/publishers.js#L13

**Comment by antobinary** [comment]
I tend to see it when my current user is redirected to an error screen (410 for example)

**Comment by antobinary** [comment]
Obsolete
