### ISSUE TITLE
HTML5 Video on HTML5 client - a npm dependency nightmare

### ISSUE THREAD

**Issue by danionescu2007** [bigbluebutton/bigbluebutton#4958]
I am trying (hard) to test the HTML5 video using the lab guide  at http://docs.bigbluebutton.org/labs/html5-video.html on the HTML5 client 2.x. So far, using the nodejs 6.x indicated in the instructions did not work when trying to install npm dependencies. Using nodejs 6.3.1 installed from sources, got me where I could install all the npm dependencies. However, when running the server with `./start.sh` I get errors which prevent startup:
```
> bbb-html5-video-kurento-bridge@1.0.0 postinstall /home/dan/dev-6.3.1/bigbluebutton/labs/kurento-html5-video
> npm start


> bbb-html5-video-kurento-bridge@1.0.0 start /home/dan/dev-6.3.1/bigbluebutton/labs/kurento-html5-video
> nodejs server.js

 [*] Running bbb-html5 kurento video service.
[[[[[ ~/dev-6.3.1/bigbluebutton/bigbluebutton-html5 ]]]]]

=> Started proxy.
=> Meteor 1.6.0.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.
=> Errors prevented startup:

   While loading plugin `minifyStdJS` from package `standard-minifier-js`:
   vm.js:24:10: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
   at Object.exports.createScript (vm.js:24:10)
   at /tools/fs/files.js:1161:34
   at Function.time (/tools/tool-env/profile.js:305:10)
   at Object.files.runJavaScript (/tools/fs/files.js:1099:18)
   at /tools/isobuild/bundler.js:1783:15
   at Array.forEach (native)
   at Function._.each._.forEach (/home/dan/.meteor/packages/meteor-tool/.1.4.4_5.1d6c9qg.9ky5++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
   at JsImage.load (/tools/isobuild/bundler.js:1696:7)
   at /tools/isobuild/isopack.js:536:16
   at /tools/utils/buildmessage.js:359:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at /tools/isobuild/isopack.js:526:20
   at Function._.each._.forEach (/home/dan/.meteor/packages/meteor-tool/.1.4.4_5.1d6c9qg.9ky5++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
   at [object Object].ensurePluginsInitialized (/tools/isobuild/isopack.js:514:7)
   at /tools/isobuild/compiler.js:382:16
   at Array.forEach (native)
   at /tools/isobuild/compiler.js:381:26
   at /tools/utils/buildmessage.js:359:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at /tools/isobuild/compiler.js:377:16
   at /tools/isobuild/compiler.js:184:28
   at Object.withCache (/tools/fs/files.js:1652:12)
   at /tools/isobuild/compiler.js:183:11
   at Array.forEach (native)
   at Function._.each._.forEach (/home/dan/.meteor/packages/meteor-tool/.1.4.4_5.1d6c9qg.9ky5++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
   at Object.compile (/tools/isobuild/compiler.js:178:5)
   at /tools/isobuild/bundler.js:2738:24
   at /tools/utils/buildmessage.js:271:13
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:264:29
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:262:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:253:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.capture (/tools/utils/buildmessage.js:252:19)
   at bundle (/tools/isobuild/bundler.js:2681:31)
   at /tools/isobuild/bundler.js:2628:32
   at Object.withCache (/tools/fs/files.js:1652:12)
   at Object.exports.bundle (/tools/isobuild/bundler.js:2628:16)
   at /tools/runners/run-app.js:588:36
   at Function.run (/tools/tool-env/profile.js:490:12)
   at bundleApp (/tools/runners/run-app.js:587:34)
   at [object Object]._.extend._runOnce (/tools/runners/run-app.js:631:35)
   at [object Object]._.extend._fiber (/tools/runners/run-app.js:890:28)
   at /tools/runners/run-app.js:417:12


=> Your application has errors. Waiting for file change.
```

Using nodejs 6.x and installing most of the npm dependencies one at a time by specifying versions to comply with the requested versions, managed to install the deps but I also get this error when I do `./start.sh`:
```
> bbb-html5-video-kurento-bridge@1.0.0 postinstall /home/dan/dev-6.3.1/bigbluebutton/labs/kurento-html5-video
> npm start


> bbb-html5-video-kurento-bridge@1.0.0 start /home/dan/dev-6.3.1/bigbluebutton/labs/kurento-html5-video
> nodejs server.js

 [*] Running bbb-html5 kurento video service.
[[[[[ ~/dev-6.3.1/bigbluebutton/bigbluebutton-html5 ]]]]]

=> Started proxy.
WARNING: version mismatch for node-sass; installed version is 4.5.3, but version 3.x is required by nathantreid:css-modules)
WARNING: version mismatch for node-sass; installed version is 4.5.3, but version 3.x is required by nathantreid:css-modules)

/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Processing Step: SCSS compilation
Unable to compile /home/dan/dev-6.3.1/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/test/fixtures/include-path/lib/vars.scss
Line: NaN, Column: undefined
TypeError: Cannot read property 'renderSync' of undefined

/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
=> Errors prevented startup:

   While processing files with nathantreid:css-modules (for target web.browser):
   error: Can't load npm module 'node-sass' from packages/modules-runtime.js. Check your Npm.depends().
   packages/mss/scss-processor.js:112:20: Cannot read property 'renderSync' of undefined
   at ScssProcessor._transpile (packages/mss/scss-processor.js:112:20)
   at ScssProcessor._process (packages/mss/scss-processor.js:62:37)
   at ScssProcessor.process (packages/mss/scss-processor.js:44:12)
   at CssModulesBuildPlugin._preprocessFile (packages/mss/css-modules-build-plugin.js:229:30)
   at CssModulesBuildPlugin.compileOneFile (packages/mss/css-modules-build-plugin.js:141:10)
   at packages/caching-compiler/multi-file-caching-compiler.js:115:45
   at packages/caching-compiler/multi-file-caching-compiler.js:97:11
   at /home/dan/.meteor/packages/nathantreid_css-modules/.2.4.0.3h9ik6++os+web.browser+web.cordova/plugin.mss.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
   at replenish (/home/dan/.meteor/packages/nathantreid_css-modules/.2.4.0.3h9ik6++os+web.browser+web.cordova/plugin.mss.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
   at /home/dan/.meteor/packages/nathantreid_css-modules/.2.4.0.3h9ik6++os+web.browser+web.cordova/plugin.mss.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:328:15
   at Object.async.forEachLimit.async.eachLimit (/home/dan/.meteor/packages/nathantreid_css-modules/.2.4.0.3h9ik6++os+web.browser+web.cordova/plugin.mss.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:221:35)
   at CssModulesBuildPlugin.processFilesForTarget (packages/caching-compiler/multi-file-caching-compiler.js:95:11)
   at CssModulesBuildPlugin.processFilesForTarget (packages/mss/css-modules-build-plugin.js:58:5)


=> Your application has errors. Waiting for file change.
=> A patch (Meteor 1.4.4.5) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.
```
It seems that something is still not right.

Could someone help me out of this npm dependency nightmare :)

**Comment by ffdixon** [comment]
Got your request ... we're take a closer look.

**Comment by danionescu2007** [comment]
Could someone tell which configuration is verified to be working in terms of versions: os, nodejs, npm, meteor etc?
This would be the quickest way to get to have a working instance in my environment.

Thank you!
Regards,
Dan

**Comment by ffdixon** [comment]
The HTML5 video is under active development and we're getting close to finishing another sprint.  If you can wait a few days, we should have some updated documentation and packages for you to try out.

We'll post a follow-up to this issue when ready.

**Comment by danionescu2007** [comment]
Thank you for your reply. I will gladly wait.

Regards,
Dan

**Comment by danionescu2007** [comment]
Hello @ffdixon !
Any good news on the new release?
Thank you!
Regards,
Dan

**Comment by ffdixon** [comment]
We recently merged in the support for video in HTML5 client -- it's still in development (read: it many not work consistently), but the core pieces are in place.  We're using Kurento for the back-end server.

As a result, we've removed this page

   http://docs.bigbluebutton.org/labs/html5-video.html

as the steps were for 1.1 and are now out-of-date.  We now provide Kurento as part of the BigBlueButton packages (you don't need to install it separately).

If you follow the steps at

  http://docs.bigbluebutton.org/html/html5-install.html#1-install-mongdb-and-nodejs

(and note we are now using node 8.x), you'll have BigBlueButton 2.0-beta running with the (near) latest development build of BigBlueButton HTML5 client.  We're running this build on https://test.bigbluebutton.org).  Here we are doing a quick test of sharing webcam

![video](https://user-images.githubusercontent.com/290351/35364097-4c5cac48-013b-11e8-8830-af020417ba1a.gif)

**Comment by danionescu2007** [comment]
Thank you for your kind help!

**Comment by ffdixon** [comment]
Closing this issue.  Going forward, we've also created a one-line install script that you can setup BigBlueButton with SSL + HTML5 on an new server that has a fully qualified domain name.  See:  https://github.com/bigbluebutton/bbb-install
