### ISSUE TITLE
Fix GuestApprovedEvtMsg message handler

### ISSUE THREAD

**Issue by OZhurbenko** [bigbluebutton/bigbluebutton#5123]
Currently Meteor throws an exception on user join:

```
Match error: Expected boolean, got undefined
     at exports.check (packages/check.js:55:15)
     at EventEmitter.handleGuestsWaitingForApproval (imports/api/users/server/handlers/guestApproved.js:12:3)
     at EventEmitter.emitAsync (/home/firstuser/dev/bigbluebutton/bigbluebutton-html5/node_modules/eventemitter2/lib/eventemitter2.js:461:31)
     at MettingMessageQueue.handleTask (imports/startup/server/redis.js:80:10)
     at PowerQueue.runTask (packages/cfs_power-queue.js:596:14)
     at PowerQueue.updateThrottleUp (packages/cfs_power-queue.js:402:12)
     at PowerQueue.next (packages/cfs_power-queue.js:451:10)
     at PowerQueue._autoStartTasks (packages/cfs_power-queue.js:356:14)
     at PowerQueue.add (packages/cfs_power-queue.js:381:10)
     at MettingMessageQueue.add (imports/startup/server/redis.js:89:23)
```

**Comment by antobinary** [comment]
Done in #5851
