### ISSUE TITLE
Start/stop Flash webcam triggers error on html5 log

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5690]
`info: REDIS: UserBroadcastCamStartedEvtMsg: Error: Match error: Failed Match.Where validation`

**Comment by antobinary** [comment]
```systemd_start.sh[31956]: info: REDIS: {"header":{"name":"UserBroadcastCamStartedEvtMsg","meetingId":"9b88ea4a9e966fd53743d2d5f1914b2242494aaa-1529324793144","userId":"w_hffnvjs4zaaa"},"body":{"userId":"w_hffnvjs4zaaa","stream":"medium-w_hffnvjs4zaaa-1529325124409-recorded"}} emitted
systemd_start.sh[31956]: info: REDIS: UserBroadcastCamStartedEvtMsg: Error: Match error: Failed Match.Where validation
systemd_start.sh[31956]:     at exports.check (packages/check.js:55:15)
systemd_start.sh[31956]:     at EventEmitter.handleUserSharedHtml5Webcam (imports/api/video/server/handlers/userSharedHtml5Webcam.js:16:3)
systemd_start.sh[31956]:     at EventEmitter.emitAsync (/usr/share/meteor/bundle/programs/server/npm/node_modules/eventemitter2/lib/eventemitter2.js:461:31)
systemd_start.sh[31956]:     at MettingMessageQueue.handleTask (imports/startup/server/redis.js:84:10)
systemd_start.sh[31956]:     at PowerQueue.runTask (packages/cfs_power-queue.js:596:14)
systemd_start.sh[31956]:     at PowerQueue.updateThrottleUp (packages/cfs_power-queue.js:402:12)
systemd_start.sh[31956]:     at PowerQueue.next (packages/cfs_power-queue.js:451:10)
systemd_start.sh[31956]:     at PowerQueue._autoStartTasks (packages/cfs_power-queue.js:356:14)
systemd_start.sh[31956]:     at PowerQueue.add (packages/cfs_power-queue.js:381:10)
systemd_start.sh[31956]:     at MettingMessageQueue.add (imports/startup/server/redis.js:93:23)
systemd_start.sh[31956]: info: REDIS: UserBroadcastCamStartedEvtMsg completed sync
```
