### ISSUE TITLE
HTML5 shutting down (redis exiting)

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6419]
Users are receiving a 404 error when trying to join the HTML5 client.  A first analysis suggests redis is shutting down.

From `journalctl -u bbb-html5`

~~~
Dec 12 06:04:50 ip-172-31-85-42 systemd_start.sh[22487]: info: REDIS: CheckAlivePongSysMsg skipped
Dec 12 06:04:58 ip-172-31-85-42 systemd_start.sh[22487]: error: uncaughtException: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 date=Wed Dec 12 2018 06:04:58 GMT+0000 (UTC), pid=22714, uid=0, gid=0, cwd=/usr/share/meteor/bundle/programs/server, execPath=/usr/share/node-v8.9.4-linux-x64/bin/node, version=v8.9.4, argv=[/usr/share/node-v8.9.4-linux-x64/bin/node, /usr/share/meteor/bundle/main.js, program.json], rss=129695744, heapTotal=56209408, heapUsed=50697256, external=24747145, loadavg=[0.11328125, 0.03955078125, 0.0078125], uptime=479434
Dec 12 06:04:58 ip-172-31-85-42 systemd_start.sh[22487]: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
Dec 12 06:04:58 ip-172-31-85-42 systemd_start.sh[22487]:     at Object._errnoException (util.js:1022:11)
Dec 12 06:04:58 ip-172-31-85-42 systemd_start.sh[22487]:     at _exceptionWithHostPort (util.js:1044:20)
Dec 12 06:04:58 ip-172-31-85-42 systemd_start.sh[22487]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
Dec 12 06:04:58 ip-172-31-85-42 systemd[1]: bbb-html5.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 06:04:58 ip-172-31-85-42 systemd[1]: bbb-html5.service: Unit entered failed state.
Dec 12 06:04:58 ip-172-31-85-42 systemd[1]: bbb-html5.service: Failed with result 'exit-code'.
~~~

And from `/var/log/redis/redis-server.log` at the same moment

~~~
root@ip-172-31-85-42:/var/log/redis# cat redis-server.log
22227:signal-handler (1544594698) Received SIGTERM scheduling shutdown...
22227:signal-handler (1544594698) Received SIGTERM scheduling shutdown...
22227:M 12 Dec 06:04:58.139 # User requested shutdown...
22227:M 12 Dec 06:04:58.139 * Saving the final RDB snapshot before exiting.
22227:M 12 Dec 06:04:58.143 * DB saved on disk
22227:M 12 Dec 06:04:58.143 * Removing the pid file.
~~~

Posted in 

  https://groups.google.com/d/msg/bigbluebutton-dev/xb-XOweFEpA/EfdcTfs3DwAJ

**Comment by antobinary** [comment]
Merge into https://github.com/bigbluebutton/bigbluebutton/issues/7799
