### ISSUE TITLE
BigBlueButton coturn Issue no access to ScreenSharing or Cam

### ISSUE THREAD

**Issue by Ada201922** [bigbluebutton/bigbluebutton#6926]
I want to implement BigBlueButton in my local network, some of those networks are protected with firewalls and it is not possible to enable all the ports that are required because of security reasons. So i thought I install coturn and followed your instructions on the website. Now that everything is installed everything on my network seems to be working fine, yet when I try to connect from a different local Network I can logIn, see Presentation yet when it comes to sharing or useing the ScreenSharing or the Webcam option. They stay stuck on the loading screen with the two arrows that rotate, without Error Messages on the website.  

The bbb-conf ---check -> does not indicate any problems 
** Potential problems described below **

# Warning: The API demos are installed and accessible from:
#
#    https://192.168.38.94/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

# Warning: The client self check is installed and accessible from:
#
#    https://192.168.38.94/check

  -- Exceptions found in /var/lib/tomcat7/logs/ --
/var/lib/tomcat7/logs/catalina.2019-03-07.log:java.net.BindException: Address already in use (Bind failed) <null>:8080
/var/lib/tomcat7/logs/catalina.2019-03-07.log:Caused by: java.net.BindException: Address already in use (Bind failed)
/var/lib/tomcat7/logs/catalina.2019-03-07.log:org.apache.catalina.LifecycleException: Failed to initialize component [Connector[HTTP/1.1-8080]]
/var/lib/tomcat7/logs/catalina.2019-03-07.log:Caused by: org.apache.catalina.LifecycleException: Protocol handler initialization failed
/var/lib/tomcat7/logs/catalina.2019-03-07.log:Caused by: java.net.BindException: Address already in use (Bind failed) <null>:8080
/var/lib/tomcat7/logs/catalina.2019-03-07.log:Caused by: java.net.BindException: Address already in use (Bind failed)
/var/lib/tomcat7/logs/catalina.2019-03-07.log:java.io.IOException: Invalid keystore format
/var/lib/tomcat7/logs/catalina.2019-03-07.log:org.apache.catalina.LifecycleException: Failed to initialize component [Connector[HTTP/1.1-8443]]
/var/lib/tomcat7/logs/catalina.2019-03-07.log:Caused by: org.apache.catalina.LifecycleException: Protocol handler initialization failed
/var/lib/tomcat7/logs/catalina.2019-03-07.log:Caused by: java.io.IOException: Invalid keystore format
/var/lib/tomcat7/logs/catalina.2019-03-07.log:java.net.BindException: Address already in use (Bind failed)
/var/lib/tomcat7/logs/catalina.2019-03-07.log:java.lang.IllegalStateException
/var/lib/tomcat7/logs/catalina.2019-03-07.log:INFO: Illegal access: this web application instance has been stopped already.  Could not load akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedExceptio
n$1.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
/var/lib/tomcat7/logs/catalina.2019-03-07.log:java.lang.IllegalStateException
/var/lib/tomcat7/logs/catalina.2019-03-07.log:  at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException(FaultHandling.scala:298)
/var/lib/tomcat7/logs/catalina.2019-03-07.log:  at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException$(FaultHandling.scala:298)
/var/lib/tomcat7/logs/catalina.2019-03-07.log:  at akka.actor.ActorCell.handleNonFatalOrInterruptedException(ActorCell.scala:362)
/var/lib/tomcat7/logs/catalina.2019-03-07.log:java.lang.IllegalStateException
/var/lib/tomcat7/logs/catalina.2019-03-07.log:  at akka.actor.ActorSystemImpl$$anon$2.uncaughtException(ActorSystem.scala:665)
/var/lib/tomcat7/logs/catalina.2019-03-07.log:java.io.IOException: Invalid keystore format
/var/lib/tomcat7/logs/catalina.2019-03-07.log:org.apache.catalina.LifecycleException: Failed to initialize component [Connector[HTTP/1.1-8443]]
/var/lib/tomcat7/logs/catalina.2019-03-07.log:Caused by: org.apache.catalina.LifecycleException: Protocol handler initialization failed

and the bbb-web.log gives me:
root@ubuntu:/home/kali# tail -fn 200 /var/log/bigbluebutton/bbb-web.log 
2019-03-07T13:49:07.027+01:00 INFO  org.bigbluebutton.web.services.callback.CallbackUrlService  - Starting callback url service.
2019-03-07T13:49:07.029+01:00 INFO  org.bigbluebutton.api.MeetingService  - Starting Meeting Service.
2019-03-07T13:49:08.408+01:00 INFO  org.bigbluebutton.web.services.callback.CallbackUrlService  - Stopping callback url service.
2019-03-07T13:49:08.522+01:00 ERROR org.bigbluebutton.presentation.imp.OfficeToPdfConversionService  - Could not stop Office Manager
org.jodconverter.office.OfficeException: Could not get the process exit code
	at org.jodconverter.office.OfficeProcess.getExitCode(OfficeProcess.java:206)
	at org.jodconverter.office.ManagedOfficeProcess.doEnsureProcessExited(ManagedOfficeProcess.java:80)
	at org.jodconverter.office.ManagedOfficeProcess.doStopProcess(ManagedOfficeProcess.java:135)
	at org.jodconverter.office.ManagedOfficeProcess.access$000(ManagedOfficeProcess.java:40)
	at org.jodconverter.office.ManagedOfficeProcess$5.call(ManagedOfficeProcess.java:302)
	at org.jodconverter.office.ManagedOfficeProcess$5.call(ManagedOfficeProcess.java:298)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.jodconverter.office.ExitCodeRetryable.attempt(ExitCodeRetryable.java:43)
	at org.jodconverter.office.Retryable.execute(Retryable.java:69)
	at org.jodconverter.office.ExitCodeRetryable.execute(ExitCodeRetryable.java:23)
	at org.jodconverter.office.Retryable.execute(Retryable.java:48)
	at org.jodconverter.office.ExitCodeRetryable.execute(ExitCodeRetryable.java:23)
	at org.jodconverter.office.OfficeProcess.getExitCode(OfficeProcess.java:201)
	... 9 more
2019-03-07T13:54:10.975+01:00 INFO  org.bigbluebutton.api.messaging.ReceivedMessageHandler  - Ready to handle messages from Redis pubsub!
2019-03-07T13:54:11.948+01:00 DEBUG org.bigbluebutton.api2.BbbWebApiGWApp  - *********** meetingManagerChannel = FOOOOOOOOO
2019-03-07T13:54:12.128+01:00 DEBUG org.bigbluebutton.api2.bus.MessageSenderActor  - started (org.bigbluebutton.api2.bus.MessageSenderActor@7ebd53a2)
2019-03-07T13:54:12.139+01:00 DEBUG org.bigbluebutton.api2.meeting.OldMeetingMsgHdlrActor  - started (org.bigbluebutton.api2.meeting.OldMeetingMsgHdlrActor@258b702f)
2019-03-07T13:54:12.161+01:00 DEBUG org.bigbluebutton.api2.bus.MsgToAkkaAppsToJsonActor  - started (org.bigbluebutton.api2.bus.MsgToAkkaAppsToJsonActor@1954e338)
2019-03-07T13:54:12.190+01:00 DEBUG org.bigbluebutton.api2.bus.OldMessageJsonReceiverActor  - started (org.bigbluebutton.api2.bus.OldMessageJsonReceiverActor@45a68d50)
2019-03-07T13:54:12.190+01:00 DEBUG org.bigbluebutton.api2.bus.ReceivedJsonMsgHdlrActor  - started (org.bigbluebutton.api2.bus.ReceivedJsonMsgHdlrActor@45f4436c)
2019-03-07T13:54:12.193+01:00 INFO  org.bigbluebutton.api2.endpoint.redis.AppsRedisSubscriberActor  - Connect to /127.0.0.1:6379
2019-03-07T13:54:12.204+01:00 DEBUG org.bigbluebutton.api2.endpoint.redis.AppsRedisSubscriberActor  - started (org.bigbluebutton.api2.endpoint.redis.AppsRedisSubscriberActor@7a6c25cc)
2019-03-07T13:54:12.237+01:00 DEBUG org.bigbluebutton.api2.endpoint.redis.AppsRedisSubscriberActor  - now watched by Actor[akka://bbb-web-common/system/IO-TCP/selectors/$a/1#286797040]
2019-03-07T13:54:12.270+01:00 INFO  org.bigbluebutton.api2.endpoint.redis.AppsRedisSubscriberActor  - Connected to localhost/127.0.0.1:6379
2019-03-07T13:54:15.590+01:00 INFO  org.bigbluebutton.web.services.callback.CallbackUrlService  - Starting callback url service.
2019-03-07T13:54:15.592+01:00 INFO  org.bigbluebutton.api.MeetingService  - Starting Meeting Service.

These are the only Error Messages that I get. Im running the BBB /webrtc etc with the coturn on the same server, could that have anyhing to do with it? 
Thank you.

**Comment by matiasilva** [comment]
No follow up in a year. Closing for now but feel free to follow up at https://groups.google.com/forum/#!forum/bigbluebutton-setup.
