### ISSUE TITLE
page counting question

### ISSUE THREAD

**Issue by gittester2017** [bigbluebutton/bigbluebutton#7336]

**Comment by gittester2017** [comment]
Hi Gurus,

I try to deploy release 2.2-beta5 on ubuntu server 16.04 vmware
only nginx tomcat demo html5client bbb-apps-akka bbb-web and libreoffice5.1.6.2 installed and running without docker。
But default pdf is not loaded（convert success）, it seams couting page failed!
new files can not be uploaded too!
I guess something wrong with nuprocess stdout, but how to fix it?

2019-05-01T22:28:32.266-07:00 INFO  o.b.p.DocumentConversionServiceImp -  --analytics-- data={"current":true,"filename":"default.pdf","logCode":"presentation_conversion_start","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1556774906871","message":"Start presentation conversion.","podId":"DEFAULT_PRESENTATION_POD","presId":"d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1556774907141"}
2019-05-01T22:28:32.275-07:00 INFO  o.b.p.SupportedDocumentFilter - Received supported file /var/bigbluebutton/183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1556774906871/183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1556774906871/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1556774907141/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1556774907141.pdf
2019-05-01T22:28:32.332-07:00 ERROR o.b.p.h.PdfPageCounterHandler - pages counting string:
2019-05-01T22:28:32.334-07:00 ERROR o.b.p.h.PdfPageCounterHandler - Exception counting images
java.lang.IllegalStateException: No match found
	at java.util.regex.Matcher.group(Matcher.java:536)
	at org.bigbluebutton.presentation.handlers.PdfPageCounterHandler.numberOfPages(PdfPageCounterHandler.java:44)
	at org.bigbluebutton.presentation.imp.PdfPageCounter.countNumberOfPages(PdfPageCounter.java:55)
	at org.bigbluebutton.presentation.imp.PageCounterService.countPages(PageCounterService.java:74)
	at org.bigbluebutton.presentation.imp.PageCounterService.determineNumberOfPages(PageCounterService.java:37)
	at org.bigbluebutton.presentation.imp.PdfToSwfSlidesGenerationService.determineNumberOfPages(PdfToSwfSlidesGenerationService.java:95)
	at org.bigbluebutton.presentation.imp.PdfToSwfSlidesGenerationService.generateSlides(PdfToSwfSlidesGenerationService.java:69)
	at org.bigbluebutton.presentation.DocumentConversionServiceImp.processDocument(DocumentConversionServiceImp.java:72)
	at org.bigbluebutton.presentation.DocumentConversionService$processDocument.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at org.bigbluebutton.web.services.PresentationService$_closure5$_closure16.doCall(PresentationService.groovy:85)
	at org.bigbluebutton.web.services.PresentationService$_closure5$_closure16.doCall(PresentationService.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods$2.run(DefaultGroovyMethods.java:15553)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
2019-05-01T22:28:32.334-07:00 ERROR o.b.presentation.imp.PdfPageCounter - number of pages:0
2019-05-01T22:28:32.335-07:00 ERROR o.b.p.i.PdfToSwfSlidesGenerationService -  --analytics-- data={"filename":"default.pdf","logCode":"determine_num_pages_failed","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1556774906871","message":"Failed to determine number of pages.","podId":"DEFAULT_PRESENTATION_POD","presId":"d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1556774907141"}
org.bigbluebutton.presentation.imp.CountingPageException: Exception while trying to determine number of pages.
	at org.bigbluebutton.presentation.imp.PageCounterService.isNumberOfPagesValid(PageCounterService.java:49)
	at org.bigbluebutton.presentation.imp.PageCounterService.determineNumberOfPages(PageCounterService.java:42)
	at org.bigbluebutton.presentation.imp.PdfToSwfSlidesGenerationService.determineNumberOfPages(PdfToSwfSlidesGenerationService.java:95)
	at org.bigbluebutton.presentation.imp.PdfToSwfSlidesGenerationService.generateSlides(PdfToSwfSlidesGenerationService.java:69)
	at org.bigbluebutton.presentation.DocumentConversionServiceImp.processDocument(DocumentConversionServiceImp.java:72)
	at org.bigbluebutton.presentation.DocumentConversionService$processDocument.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at org.bigbluebutton.web.services.PresentationService$_closure5$_closure16.doCall(PresentationService.groovy:85)
	at org.bigbluebutton.web.services.PresentationService$_closure5$_closure16.doCall(PresentationService.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods$2.run(DefaultGroovyMethods.java:15553)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
2019-05-01T22:28:32.338-07:00 INFO  o.b.p.DocumentConversionServiceImp -  --analytics-- data={"current":true,"filename":"default.pdf","logCode":"presentation_conversion_end","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1556774906871","message":"End presentation conversion.","podId":"DEFAULT_PRESENTATION_POD","presId":"d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1556774907141"}

Thanks.
Best Regards.

**Comment by GhaziTriki** [comment]
Thank you @gittester2017 we have never faced this issue for `default.pdf`. Could check if the file des exist in `/var/bigbluebutton/183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1556774906871/183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1556774906871/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1556774907141/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1556774907141.pdf`?

**Comment by gittester2017** [comment]
yes,it exists

so, I think it's successfully converted?

**Comment by riteshmaddala** [comment]
Hi,

I am also facing this issue. Do we have any resolution.

Not sure, but I guess this started when I changed default url to my Hostname.

Thanks

**Comment by odairmario** [comment]
hi, i upgraded bbb with `apt upgrade` and i have this problem, any solution?

**Comment by riteshmaddala** [comment]
@odairmario 

Hi,

The fix is to update the Hostname after you upgrade the project.

Follow below steps -

1.Check the default.pdf file present under /var/www/bigbluebutton-default/ 

2. If present then open /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties and change bigbluebutton.web.serverURL to your IP or hostname.

Thanks

**Comment by matiasilva** [comment]
Also note this issue was opened for the beta release. If you face any further issues, please post your topic to https://groups.google.com/forum/#!forum/bigbluebutton-setup. Thanks.

**Comment by edlerd** [comment]
Hello,

I have the same problem running latest 2.2.32 on my second host. It might have appeared after the update, not 100% sure the issue did not exist before though.

The serverURL is set correctly as bbb2.mydomain.
The default.pdf is present on the location mentioned above.

Any ideas welcome!

`2021-02-26T11:17:21.487+01:00 INFO  o.b.p.DocumentConversionServiceImp -  --analytics-- data={"current":true,"filename":"default.pdf","logCode":"presentation_conversion_start","authzToken":"preupload-download-authz-token","meetingId":"4cb70a321ea86be14bede7c4c9e1140f57215ad1-1614334636334","message":"Start presentation conversion.","podId":"DEFAULT_PRESENTATION_POD","presId":"d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1614334636345"}
2021-02-26T11:17:21.487+01:00 INFO  o.b.p.SupportedDocumentFilter - Received supported file /var/bigbluebutton/4cb70a321ea86be14bede7c4c9e1140f57215ad1-1614334636334/4cb70a321ea86be14bede7c4c9e1140f57215ad1-1614334636334/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1614334636345/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1614334636345.pdf
2021-02-26T11:17:21.535+01:00 ERROR o.b.p.h.PdfPageCounterHandler - Exception counting images
java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Matcher.java:536)
        at org.bigbluebutton.presentation.handlers.PdfPageCounterHandler.numberOfPages(PdfPageCounterHandler.java:42)
        at org.bigbluebutton.presentation.imp.PdfPageCounter.countNumberOfPages(PdfPageCounter.java:55)
        at org.bigbluebutton.presentation.imp.PageCounterService.countPages(PageCounterService.java:74)
        at org.bigbluebutton.presentation.imp.PageCounterService.determineNumberOfPages(PageCounterService.java:37)
        at org.bigbluebutton.presentation.imp.PresentationFileProcessor.determineNumberOfPages(PresentationFileProcessor.java:152)
        at org.bigbluebutton.presentation.imp.PresentationFileProcessor.processUploadedPresentation(PresentationFileProcessor.java:81)
        at org.bigbluebutton.presentation.imp.PresentationFileProcessor.access$000(PresentationFileProcessor.java:22)
        at org.bigbluebutton.presentation.imp.PresentationFileProcessor$1.run(PresentationFileProcessor.java:64)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`
