### ISSUE TITLE
Disabling swfSlidesRequired causes presentation recordings to not process

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7427]
In the latest build of BigBlueButton 2.2-beta, setting

~~~
#----------------------------------------------------
# Conversion of the presentation slides to SWF to be
# used in the Flash client
swfSlidesRequired=false
~~~

in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties` causes an error in the `process/presentation.rb` for presentation playback format.

When it tries to process the archive file, it throws

~~~
I, [2019-05-11T17:49:42.420744 #24818]  INFO -- : Found pdf file for presentation /var/bigbluebutton/recording/process/presentation/183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1557596835766/temp/183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1557596835766/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1557596836339/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1557596836339.pdf
E, [2019-05-11T17:49:42.420843 #24818] ERROR -- : unknown file type: /var/bigbluebutton/recording/process/presentation/183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1557596835766/temp/183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1557596835766/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1557596836339/thumbnails
E, [2019-05-11T17:49:42.420871 #24818] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1387:in `copy'
E, [2019-05-11T17:49:42.420903 #24818] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:472:in `block in copy_entry'
E, [2019-05-11T17:49:42.420912 #24818] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1498:in `wrap_traverse'
E, [2019-05-11T17:49:42.420919 #24818] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:469:in `copy_entry'
E, [2019-05-11T17:49:42.420927 #24818] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:444:in `block in cp_r'
E, [2019-05-11T17:49:42.420934 #24818] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
E, [2019-05-11T17:49:42.420942 #24818] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
E, [2019-05-11T17:49:42.420949 #24818] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
E, [2019-05-11T17:49:42.420956 #24818] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:443:in `cp_r'
~~~

 It looks like it's using the .swf files to count the number of slides.  Need to refactor this so it uses a different method that does not depend on the SWF slides.

**Comment by GhaziTriki** [comment]
The recording `process` step fails with error because it tries to copy the `thumbnails` directory which is not created when `swfSlidesRequired=false`. It also raises another issue, when `swfSlidesRequired=false` we have no thumbnails for recording playback.

**Comment by GhaziTriki** [comment]
Should be fixed by #7447

**Comment by GhaziTriki** [comment]
@ffdixon Can this issue be closed?

**Comment by ffdixon** [comment]
Closing this issue as it related to the Flash client.
