### ISSUE TITLE
Screen sharing not working - error 2001

### ISSUE THREAD

**Issue by rcitdept** [bigbluebutton/bigbluebutton#7829]
I'm interested in using BigBlueButton mainly for the screen sharing component, but am having some trouble getting it to work reliably. The server is hosted as a virtual machine with a private IP address. We have a wildcard certificate and hostname setup for it.

If I create a room and attempt to share my screen, I do see the dropdown from Firefox asking me to select which screen/window to share. I select "Entire screen" and click Allow but after that the screen share doesn't replace the whiteboard as normal.

Using the HTML5 client. The computer is a Windows 10 machine running Firefox 68.0.1. I'm connecting via OpenVPN in order to get to the server's private IP (hosted at datacenter) address from my home Internet connection.

In the log file named "/var/log/bbb-webrtc-sfu/bbb-webrtc-sfu.log.2019-07-23" I can see the following set of lines generated after clicking "Allow" to share my entire screen.

```
{"level":"info","message":"[WebsocketConnectionManager] New connection with id [ 2 ]","timestamp":"2019-07-23T16:18:46.688Z"}
{"level":"info","message":"RecordingStatusReply for userId w_qxhfpkrprfup is true","timestamp":"2019-07-23T16:18:50.521Z"}
{"level":"info","message":"[screenshare] Starting session 95475-send","timestamp":"2019-07-23T16:18:50.524Z"}
{"level":"info","message":"[mcs-controller] Join room => 95475 as SFU","timestamp":"2019-07-23T16:18:50.526Z"}
{"level":"info","message":"[mcs-controller] Creating new room with ID 95475","timestamp":"2019-07-23T16:18:50.527Z"}
{"level":"info","message":"[mcs-controller] Creating a new SFU user at room 95475","timestamp":"2019-07-23T16:18:50.528Z"}
{"level":"info","message":"[mcs-controller] Resolving user little-pond-jpyheiw","timestamp":"2019-07-23T16:18:50.528Z"}
{"level":"info","message":"[screenshare] MCS Join for 2 returned little-pond-jpyheiw","timestamp":"2019-07-23T16:18:50.528Z"}
{"level":"info","message":"[mcs-controller] Publish from user little-pond-jpyheiw to room 95475","timestamp":"2019-07-23T16:18:50.530Z"}
{"level":"info","message":"[mcs-controller] Fetched user little-pond-jpyheiw","timestamp":"2019-07-23T16:18:50.530Z"}
{"level":"info","message":"[mcs-sfu-user] Added new SDP session dawn-leaf-CEyWGxA to user little-pond-jpyheiw","timestamp":"2019-07-23T16:18:50.535Z"}
{"level":"info","message":"[mcs-sfu-user] Stopping session => dawn-leaf-CEyWGxA","timestamp":"2019-07-23T16:18:50.536Z"}
{"error":{"type":"error","code":2001,"message":"MEDIA_SERVER_OFFLINE","operation":"publish"},"level":"error","message":"[mcs-router] Reject operation publish with","timestamp":"2019-07-23T16:18:50.537Z"}
{"error":{"type":"error","code":2001,"message":"MEDIA_SERVER_OFFLINE","operation":"publish"},"level":"error","message":"[mcs-api] Reject operation publish with","timestamp":"2019-07-23T16:18:50.537Z"}
{"type":"error","code":2001,"message":"[screenshare] MCS publish returned error =>","operation":"publish","level":"error","timestamp":"2019-07-23T16:18:50.537Z"}
```

bbb-conf --check output:
```
root@bbb:/var/log/bbb-webrtc-sfu# bbb-conf --check

BigBlueButton Server 2.2.0-beta-16 (1251)
                    Kernel version: 4.4.0-154-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 6110 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb.rainierconnect.net
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: bbb.rainierconnect.net
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://bbb.rainierconnect.net
                              red5: bbb.rainierconnect.net
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 172.18.5.55
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.rainierconnect.net
                 playback_protocol: https
                            ffmpeg: 4.1.3-0york1~16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 172.18.5.55

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 172.18.5.55
                       kurento.url: ws://bbb.rainierconnect.net:8888/kurento
                    localIpAddress: 172.18.5.55
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 592
                        kurentoUrl: wss://bbb.rainierconnect.net/bbb-webrtc-sfu
                  enableListenOnly: true


** Potential problems described below **
```

bbb-conf --status output:

```
root@bbb:/var/log/bbb-webrtc-sfu# bbb-conf --status
red5 ——————————————————► [✔ - active]
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
```

**Comment by ffdixon** [comment]
> If I create a room and attempt to share my screen, I do see the dropdown from Firefox asking me to select which screen/window to share. I select "Entire screen" and click Allow but after that the screen share doesn't replace the whiteboard as normal.

Can you do a quick test against

  https://test.bigbluebutton.org/

and let us know if that works for you there.

**Comment by prlanzarin** [comment]
```
{"error":{"type":"error","code":2001,"message":"MEDIA_SERVER_OFFLINE","operation":"publish"},"level":"error","message":"[mcs-router] Reject operation publish with","timestamp":"2019-07-23T16:18:50.537Z"}
```
means bbb-webrtc-sfu couldn't connect to the media server for some reason. Kurento is up, so I'll guess this is either a misconfig in `kurento.url`, 8888 port block or a problem in the restart procedure.

Try these two:
`telnet bbb.rainierconnect.net 8888`
and, afterwards, sudo systemctl restart bbb-webrtc-sfu.

See if the problem persists.

**Comment by rcitdept** [comment]
Thank you for the quick replies!

I was able to share my screen at https://test.bigbluebutton.org without issue.

Telnet to port 8888 from my client machine appears to have worked. Using the Windows telnet client, it didn't appear to timeout and went to a black screen.

Restarting the service allowed me to start sharing the screen OK.

It appears that after restarting the whole BBB server, it was back to its original state. I saw these lines in `journalctl -u bbb-webrtc-sfu --no-pager`:
```
Jul 23 11:14:52 bbb bbb-webrtc-sfu[1748]: 2019-07-23T18:14:52.457Z - info: [app] MCS Server is initializing ...
Jul 23 11:14:52 bbb bbb-webrtc-sfu[1748]: 2019-07-23T18:14:52.472Z - info: [app] MCS Server is ready to receive connections
Jul 23 11:14:52 bbb bbb-webrtc-sfu[1748]: reconnect to server 0 100 undefined
Jul 23 11:14:52 bbb bbb-webrtc-sfu[1748]: reconnect to server 1 100 undefined
Jul 23 11:14:52 bbb bbb-webrtc-sfu[1748]: reconnect to server 2 200 undefined
Jul 23 11:14:53 bbb bbb-webrtc-sfu[1748]: reconnect to server 3 300 undefined
Jul 23 11:14:53 bbb bbb-webrtc-sfu[1748]: 2019-07-23T18:14:53.384Z - info: [sfu-mcs-api] Connecting to MCS at ws://localhost:3010/mcs
Jul 23 11:14:53 bbb bbb-webrtc-sfu[1748]: 2019-07-23T18:14:53.388Z - info: [sfu-mcs-api] Connecting to MCS at ws://localhost:3010/mcs
Jul 23 11:14:53 bbb bbb-webrtc-sfu[1748]: 2019-07-23T18:14:53.393Z - info: [sfu-mcs-api] Connected to MCS
Jul 23 11:14:53 bbb bbb-webrtc-sfu[1748]: 2019-07-23T18:14:53.394Z - info: [sfu-mcs-api] Connecting to MCS at ws://localhost:3010/mcs
Jul 23 11:14:53 bbb bbb-webrtc-sfu[1748]: 2019-07-23T18:14:53.396Z - info: [sfu-mcs-api] Connected to MCS
Jul 23 11:14:53 bbb bbb-webrtc-sfu[1748]: 2019-07-23T18:14:53.400Z - info: [sfu-mcs-api] Connected to MCS
Jul 23 11:14:53 bbb bbb-webrtc-sfu[1748]: reconnect to server 4 500 undefined
Jul 23 11:14:53 bbb bbb-webrtc-sfu[1748]: 2019-07-23T18:14:53.723Z - error: [mcs-balancer] Failed to connect to candidate host url=ws://bbb.rainierconnect.net:8888/kurento, ip=172.18.5.55
```

After getting the service restarted I was doing some more testing with my colleagues. I found out that from my home computer (behind OpenVPN) I could share my screen and they could see it no problem. If one of them shared their screens however, only I could not see it (just saw spinning white arrows in place of whiteboard indefinitely).

I was checking the output of Firefox's `about:webrtc` page and noticed that when sharing my screen, I can see a successful ICE connection between my VPN IP (172.16.253.3) and the Bigbluebutton server (172.18.5.55). But if I view the log for a session where I'm viewing another person's screen, only my local LAN IP (192.168.0.2) is seen trying to connect to BBB. Is there a setting within BBB that could fix this?

Here is the log output from bbb-webrtc-sfu when I can't view someone else's screen and just see the spinning white arrows:
```
{"mediaSessionId":"rough-grass-Aam_Syv","mediaId":"rough-grass-Aam_Syv","state":{"name":"MediaFlowOutStateChange","details":"NOT_FLOWING"},"elementId":"f43e2740-41d4-456b-b017-93a746ca25c2_kurento.MediaPipeline/ed3a017b-bc43-46c7-aff0-845e8a16bb5b_kurento.WebRtcEndpoint","level":"info","message":"[mcs-media-session] Media bitter-paper-PR6V1Ob media state event","timestamp":"2019-07-23T18:34:23.994Z"}
{"name":"MediaFlowOutStateChange","details":"NOT_FLOWING","level":"info","message":"[screenshare] WebRTC session with media rough-grass-Aam_Syv received state","timestamp":"2019-07-23T18:34:23.996Z"}
{"level":"warn","message":"[screenshare] TODO WebRTC source NOT_FLOWING in meeting 16322","timestamp":"2019-07-23T18:34:23.997Z"}
{"mediaSessionId":"bold-fire-LedWIDN","mediaId":"bold-fire-LedWIDN","state":{"name":"MediaFlowInStateChange","details":"NOT_FLOWING"},"elementId":"f43e2740-41d4-456b-b017-93a746ca25c2_kurento.MediaPipeline/fa1728c8-ae3f-4b55-9b70-9795a27275bc_kurento.RecorderEndpoint","level":"info","message":"[mcs-media-session] Media nameless-violet-kELWRAY media state event","timestamp":"2019-07-23T18:34:24.182Z"}
{"level":"info","message":"[screenshare] Recording status for rec bold-fire-LedWIDN for screenshare at c3fc7019e7b0a7211ca25df034aac066ad2cdf51-1563906469101 is MediaFlowInStateChange { name: 'MediaFlowInStateChange', details: 'NOT_FLOWING' } NOT_FLOWING","timestamp":"2019-07-23T18:34:24.182Z"}
{"mediaSessionId":"solitary-firefly-5DZ9Age","mediaId":"solitary-firefly-5DZ9Age","state":{"name":"MediaFlowInStateChange","details":"NOT_FLOWING"},"elementId":"f43e2740-41d4-456b-b017-93a746ca25c2_kurento.MediaPipeline/66d84405-f293-40c1-9d93-43c4a14c8ca1_kurento.WebRtcEndpoint","level":"info","message":"[mcs-media-session] Media small-wave-KCwihjx media state event","timestamp":"2019-07-23T18:34:25.349Z"}
{"name":"MediaFlowInStateChange","details":"NOT_FLOWING","level":"info","message":"[screenshare] WebRTC session with media solitary-firefly-5DZ9Age received state","timestamp":"2019-07-23T18:34:25.351Z"}
{"level":"warn","message":"[screenshare] TODO WebRTC source NOT_FLOWING in meeting 16322","timestamp":"2019-07-23T18:34:25.352Z"}
{"mediaSessionId":"bitter-shape-vsULZUy","mediaId":"bitter-shape-vsULZUy","state":{"name":"MediaFlowInStateChange","details":"NOT_FLOWING"},"elementId":"f43e2740-41d4-456b-b017-93a746ca25c2_kurento.MediaPipeline/c17557bc-c62e-430f-98d3-8945da098f17_kurento.WebRtcEndpoint","level":"info","message":"[mcs-media-session] Media holy-voice-UnT5Ayq media state event","timestamp":"2019-07-23T18:34:25.353Z"}
{"name":"MediaFlowInStateChange","details":"NOT_FLOWING","level":"info","message":"[screenshare] WebRTC session with media bitter-shape-vsULZUy received state","timestamp":"2019-07-23T18:34:25.355Z"}
{"level":"warn","message":"[screenshare] TODO WebRTC source NOT_FLOWING in meeting 16322","timestamp":"2019-07-23T18:34:25.355Z"}
{"mediaSessionId":"dark-leaf-oeDyNyy","mediaId":"dark-leaf-oeDyNyy","state":{"name":"MediaFlowInStateChange","details":"NOT_FLOWING"},"elementId":"f43e2740-41d4-456b-b017-93a746ca25c2_kurento.MediaPipeline/9127c96f-9c73-4b8a-a8b3-7d2bd3a55ad9_kurento.WebRtcEndpoint","level":"info","message":"[mcs-media-session] Media throbbing-hill-5K~xLey media state event","timestamp":"2019-07-23T18:34:25.656Z"}
{"name":"MediaFlowInStateChange","details":"NOT_FLOWING","level":"info","message":"[screenshare] WebRTC session with media dark-leaf-oeDyNyy received state","timestamp":"2019-07-23T18:34:25.658Z"}
{"level":"warn","message":"[screenshare] TODO WebRTC source NOT_FLOWING in meeting 16322","timestamp":"2019-07-23T18:34:25.658Z"}
{"level":"info","message":"[WebsocketConnectionManager] New connection with id [ 6 ]","timestamp":"2019-07-23T18:34:27.882Z"}
{"level":"info","message":"[screenshare] Starting session 16322-recv","timestamp":"2019-07-23T18:34:27.917Z"}
{"level":"info","message":"[screenshare] Starting viewer w_rnwlevdxb1f5 for voiceBridge 16322","timestamp":"2019-07-23T18:34:27.917Z"}
{"level":"info","message":"[mcs-controller] Subscribe from user divine-wildflower-n7_IDbq to source rough-grass-Aam_Syv","timestamp":"2019-07-23T18:34:27.918Z"}
{"level":"info","message":"[mcs-controller] Fetched user divine-wildflower-n7_IDbq","timestamp":"2019-07-23T18:34:27.918Z"}
{"level":"info","message":"[mcs-sfu-user] Added new SDP session late-wave-H1TrihY to user divine-wildflower-n7_IDbq","timestamp":"2019-07-23T18:34:27.921Z"}
{"level":"info","message":"[mcs-balancer] Chosen host is twilight-wave-mLSjtKc ws://bbb.rainierconnect.net:8888/kurento 172.18.5.55 4 2","timestamp":"2019-07-23T18:34:27.922Z"}
{"level":"info","message":"[mcs-kurento-adapter] Pipeline for 16322 at host twilight-wave-mLSjtKc  already exists.","timestamp":"2019-07-23T18:34:27.923Z"}
{"level":"info","message":"[mcs-kurento-adapter] Created [WebRtcEndpoint] media element: f43e2740-41d4-456b-b017-93a746ca25c2_kurento.MediaPipeline/f83c7eb3-6ce5-49cd-b9e9-04fa6b9fd2a9_kurento.WebRtcEndpoint","timestamp":"2019-07-23T18:34:27.927Z"}
{"level":"info","message":"[mcs-sdp-media] New session with options WebRtcEndpoint","timestamp":"2019-07-23T18:34:27.975Z"}
{"video":5,"level":"info","message":"[mcs-balancer] Host twilight-wave-mLSjtKc streams incremented { audio: 2 }","timestamp":"2019-07-23T18:34:27.978Z"}
{"level":"info","message":"[mcs-media] New media session restless-morning-hVhHm~1 in room 16322 started with media server endpoint f43e2740-41d4-456b-b017-93a746ca25c2_kurento.MediaPipeline/f83c7eb3-6ce5-49cd-b9e9-04fa6b9fd2a9_kurento.WebRtcEndpoint","timestamp":"2019-07-23T18:34:27.978Z"}
{"level":"info","message":"[mcs-kurento-adapter] Gathering ICE candidates for f43e2740-41d4-456b-b017-93a746ca25c2_kurento.MediaPipeline/f83c7eb3-6ce5-49cd-b9e9-04fa6b9fd2a9_kurento.WebRtcEndpoint","timestamp":"2019-07-23T18:34:27.980Z"}
{"level":"info","message":"[screenshare] MCS subscribe returned for user divine-wildflower-n7_IDbq returned late-wave-H1TrihY at userId w_rnwlevdxb1f5","timestamp":"2019-07-23T18:34:27.984Z"}
{"level":"info","message":"[ScreenshareManager] Sending startResponse to peer 16322 for connection","timestamp":"2019-07-23T18:34:27.984Z"}
{"level":"info","message":"[mcs-kurento-adapter] Triggered ICE gathering for f43e2740-41d4-456b-b017-93a746ca25c2_kurento.MediaPipeline/f83c7eb3-6ce5-49cd-b9e9-04fa6b9fd2a9_kurento.WebRtcEndpoint","timestamp":"2019-07-23T18:34:27.996Z"}
{"level":"error","message":"[mcs-core] Unhandled exception { Error: Error adding candidate\n    at /usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-client/lib/KurentoClient.js:361:24\n    at Object.dispatchCallback [as callback] (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-client/node_modules/kurento-jsonrpc/lib/index.js:614:9)\n    at processResponse (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-client/node_modules/kurento-jsonrpc/lib/index.js:745:15)\n    at RpcBuilder.decode (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-client/node_modules/kurento-jsonrpc/lib/index.js:806:5)\n    at Stream.transportMessage (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-client/node_modules/kurento-jsonrpc/lib/index.js:225:10)\n    at emitOne (events.js:116:13)\n    at Stream.emit (events.js:211:7)\n    at drain (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/through/index.js:36:16)\n    at Stream.stream.queue.stream.push (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/through/index.js:45:5)\n    at WebsocketStream.onMessage (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/websocket-stream/index.js:45:15)\n    at WebSocket.onMessage (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:355:18)\n    at emitTwo (events.js:126:13)\n    at WebSocket.emit (events.js:214:7)\n    at Receiver.self._receiver.ontext (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:682:10)\n    at Receiver.finish (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:391:14)\n    at Receiver.expectHandler (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:378:31)\n  code: 2020,\n  data: { type: 'ICE_ADD_CANDIDATE_ERROR' },\n  details: 'Error adding candidate' } Promise {\n  <rejected> { Error: Error adding candidate\n    at /usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-client/lib/KurentoClient.js:361:24\n    at Object.dispatchCallback [as callback] (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-client/node_modules/kurento-jsonrpc/lib/index.js:614:9)\n    at processResponse (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-client/node_modules/kurento-jsonrpc/lib/index.js:745:15)\n    at RpcBuilder.decode (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-client/node_modules/kurento-jsonrpc/lib/index.js:806:5)\n    at Stream.transportMessage (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-client/node_modules/kurento-jsonrpc/lib/index.js:225:10)\n    at emitOne (events.js:116:13)\n    at Stream.emit (events.js:211:7)\n    at drain (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/through/index.js:36:16)\n    at Stream.stream.queue.stream.push (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/through/index.js:45:5)\n    at WebsocketStream.onMessage (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/websocket-stream/index.js:45:15)\n    at WebSocket.onMessage (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:355:18)\n    at emitTwo (events.js:126:13)\n    at WebSocket.emit (events.js:214:7)\n    at Receiver.self._receiver.ontext (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:682:10)\n    at Receiver.finish (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:391:14)\n    at Receiver.expectHandler (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:378:31)\n  code: 2020,\n  data: { type: 'ICE_ADD_CANDIDATE_ERROR' },\n  details: 'Error adding candidate' } }","timestamp":"2019-07-23T18:34:28.176Z"}
{"mediaSessionId":"rough-grass-Aam_Syv","mediaId":"rough-grass-Aam_Syv","state":{"name":"MediaFlowOutStateChange","details":"FLOWING"},"elementId":"f43e2740-41d4-456b-b017-93a746ca25c2_kurento.MediaPipeline/ed3a017b-bc43-46c7-aff0-845e8a16bb5b_kurento.WebRtcEndpoint","level":"info","message":"[mcs-media-session] Media bitter-paper-PR6V1Ob media state event","timestamp":"2019-07-23T18:34:30.462Z"}
{"name":"MediaFlowOutStateChange","details":"FLOWING","level":"info","message":"[screenshare] WebRTC session with media rough-grass-Aam_Syv received state","timestamp":"2019-07-23T18:34:30.463Z"}
{"level":"info","message":"[screenshare] Recording status for rec bold-fire-LedWIDN for screenshare at c3fc7019e7b0a7211ca25df034aac066ad2cdf51-1563906469101 is MediaFlowInStateChange { name: 'MediaFlowInStateChange', details: 'FLOWING' } FLOWING","timestamp":"2019-07-23T18:34:30.464Z"}
{"name":"MediaFlowInStateChange","details":"FLOWING","level":"info","message":"[screenshare] WebRTC session with media solitary-firefly-5DZ9Age received state","timestamp":"2019-07-23T18:34:30.465Z"}
{"mediaSessionId":"bold-fire-LedWIDN","mediaId":"bold-fire-LedWIDN","state":{"name":"MediaFlowInStateChange","details":"FLOWING"},"elementId":"f43e2740-41d4-456b-b017-93a746ca25c2_kurento.MediaPipeline/fa1728c8-ae3f-4b55-9b70-9795a27275bc_kurento.RecorderEndpoint","level":"info","message":"[mcs-media-session] Media nameless-violet-kELWRAY media state event","timestamp":"2019-07-23T18:34:30.463Z"}
{"mediaSessionId":"solitary-firefly-5DZ9Age","mediaId":"solitary-firefly-5DZ9Age","state":{"name":"MediaFlowInStateChange","details":"FLOWING"},"elementId":"f43e2740-41d4-456b-b017-93a746ca25c2_kurento.MediaPipeline/66d84405-f293-40c1-9d93-43c4a14c8ca1_kurento.WebRtcEndpoint","level":"info","message":"[mcs-media-session] Media small-wave-KCwihjx media state event","timestamp":"2019-07-23T18:34:30.464Z"}
{"name":"MediaFlowInStateChange","details":"FLOWING","level":"info","message":"[screenshare] WebRTC session with media bitter-shape-vsULZUy received state","timestamp":"2019-07-23T18:34:30.466Z"}
{"mediaSessionId":"bitter-shape-vsULZUy","mediaId":"bitter-shape-vsULZUy","state":{"name":"MediaFlowInStateChange","details":"FLOWING"},"elementId":"f43e2740-41d4-456b-b017-93a746ca25c2_kurento.MediaPipeline/c17557bc-c62e-430f-98d3-8945da098f17_kurento.WebRtcEndpoint","level":"info","message":"[mcs-media-session] Media holy-voice-UnT5Ayq media state event","timestamp":"2019-07-23T18:34:30.466Z"}
{"mediaSessionId":"dark-leaf-oeDyNyy","mediaId":"dark-leaf-oeDyNyy","state":{"name":"MediaFlowInStateChange","details":"FLOWING"},"elementId":"f43e2740-41d4-456b-b017-93a746ca25c2_kurento.MediaPipeline/9127c96f-9c73-4b8a-a8b3-7d2bd3a55ad9_kurento.WebRtcEndpoint","level":"info","message":"[mcs-media-session] Media throbbing-hill-5K~xLey media state event","timestamp":"2019-07-23T18:34:30.477Z"}
{"name":"MediaFlowInStateChange","details":"FLOWING","level":"info","message":"[screenshare] WebRTC session with media dark-leaf-oeDyNyy received state","timestamp":"2019-07-23T18:34:30.485Z"}
```

![view-fail](https://user-images.githubusercontent.com/53231234/61740453-86f30b80-ad43-11e9-8ab5-edf37a40ed20.png)
![host-success](https://user-images.githubusercontent.com/53231234/61740456-878ba200-ad43-11e9-84b2-b65ff248c07c.png)

**Comment by dymitar** [comment]
The same error applies to webcam sharing. 
After restarting the bbb-webrtc-sfu (systemctl restart bbb-webrtc-sfu) the sharing is working.
After restarting the complete system with bbb-conf --restart it stops again.

BigBlueButton Server 2.2.0-beta-18 (1285)

**Comment by rcitdept** [comment]
We are no longer using a VPN to connect to the server and our issue has gone away.

**Comment by mcfilib** [comment]
sorry to resurrect this issue but i'm trying to get screensharing working reliably and not having much luck. i've tried visiting https://test.bigbluebutton.org and, after enabling allowing screen sharing with the relevant dialogue, in the console i get the following errors:

```
[12:44:45:0661] ERROR: clientLogger: WebRTC peer constructor for screenshare (presenter) failed due to The object can not be found here. https://test.bigbluebutton.org/html5client/compatibility/kurento-extension.js?v=837:465:19

[12:44:45:0663] ERROR: clientLogger: Screenshare presenter failed when trying to start due to NotFoundError https://test.bigbluebutton.org/html5client/ff674e169b89da17bfbcb3cf00b91c4e6aaec27f.js?meteor_js_resource=true:125:1134118

[12:44:45:0664] ERROR: clientLogger: Default error handler for screenshare https://test.bigbluebutton.org/html5client/ff674e169b89da17bfbcb3cf00b91c4e6aaec27f.js?meteor_js_resource=true:125:412571
```

I’ve tried starting firefox in safe mode to rule it out being a problem being with one of my extensions blocking something critical. unlike op, i am not connecting using a vpn.
 
@ffdixon @prlanzarin would you like me to open a new issue to track this?

**Comment by blackie333** [comment]
Hello, I have similar problem with screen sharing on client Windows PCs connected via OpenVPN client.
The BBB server version is 2.2.0-rc-2 (1613), on local network there are no problems, all is working fine.
On client PC connected remotely via OpenVPN connect Voice is working but I can't share screen (any type) from the client PCs.
Any advice where to look for error?
Thanks in advance

**Comment by mcfilib** [comment]
this issue is specific to firefox. unless your issue is too, please consider opening a separate issue.
