### ISSUE TITLE
"screenshare" recording format no longer works

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#7867]
It looks like some changes were made to the recordandplayback libraries which the screenshare recording format has not been updated for.

An example log:
```I, [2019-07-31T17:50:54.380718 #30680]  INFO -- : Reading basic recording information
I, [2019-07-31T17:50:54.381520 #30680]  INFO -- : Generating video events list
E, [2019-07-31T17:50:54.381582 #30680] ERROR -- : wrong number of arguments (given 1, expected 2)
E, [2019-07-31T17:50:54.381597 #30680] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/generators/events.rb:104:in `create_webcam_edl'
E, [2019-07-31T17:50:54.381605 #30680] ERROR -- : process/screenshare.rb:88:in `<main>'
```

**Comment by ritzalam** [comment]
The method `def self.create_webcam_edl(events, archive_dir)` but `screenshare.rb` calls it with 
`webcam_edl = BigBlueButton::Events.create_webcam_edl(raw_archive_dir)`

**Comment by GhaziTriki** [comment]
@ffdixon I think this one is good to be closed.
