### ISSUE TITLE
 Audio-recorded lesson error without audio!

### ISSUE THREAD

**Issue by mmhospedagem** [bigbluebutton/bigbluebutton#8213]
I have a problem! We are recording classes but all are running out of sound! Video only! We don't know how to solve anyone know how?

Video demo https://new.bbb.fitref.online/playback/presentation/2.0/playback.html?meetingId=dcb5320c04ca3466001920b1330ca1eb44ccfae8-1571091660193

We are using google chromer, already tested with opera, mozilla and etc.

**Comment by GhaziTriki** [comment]
The same issue happened on productions servers for severals meeting yesterday. A `bbb-conf --check` shows this:

```
# Potential problems described below
# The following properties in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties have no value:
#     defaultWelcomeMessageFooter

# Error: Found text in freeswitch.log:
#
#    Thread ended for mod_event_socket
#
# FreeSWITCH may not be responding to requests on port 8021 (event socket layer)
# and users may have errors joining audio.
#
```

**Comment by GhaziTriki** [comment]
It happened after a hard reboot of the server.

In akka-fsesl logs I noticed this 

```
2020-01-14T09:40:49.779+03:00 ERROR o.b.f.v.f.ConnectionManager - Failed to connect to ESL
2020-01-14T09:40:54.770+03:00 INFO  o.b.f.v.f.ConnectionManager - Attempting to connect to FreeSWITCH ESL
2020-01-14T09:40:54.777+03:00 WARN  o.f.esl.client.inbound.Client - Failed to connect to [127.0.0.1:8021]
2020-01-14T09:40:54.778+03:00 WARN  o.f.esl.client.inbound.Client -   * reason: {}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.connect(NioClientSocketPipelineSink.java:401)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processSelectedKeys(NioClientSocketPipelineSink.java:370)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:292)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The server has IPv6 enabled.

The file `/opt/freeswitch/conf/autoload_configs/cat event_socket.conf.xml` has the following content

```xml
<configuration name="event_socket.conf" description="Socket Client">
  <settings>
    <param name="nat-map" value="false"/>
    <param name="listen-ip" value="::"/>
    <param name="listen-port" value="8021"/>
    <param name="password" value="ClueCon"/>
    <!--<param name="apply-inbound-acl" value="loopback.auto"/>-->
    <!--<param name="stop-on-bind-error" value="true"/>-->
  </settings>
</configuration>
```

@hostbbb is underlying the fact that `listen-ip` should be set to the local IP address `127.0.0.1`. Not sure if it makes any sense?

**Comment by ritzalam** [comment]
The `<param name="listen-ip" value="::"/>`  is ok. That's what we have on demo server.

Did akka-fsesl fail to connect? The logs show only one attempt. It should continue to try to connect forever. Maybe it did connect but the messages aren't getting sent to FS. We have seen this issue but can't reproduce. We have to restart akka-fsesl to get it to work. We're suspecting a thread died or deadlocked. This happens when FS crashes and akka-fsesl attempts to reconnect.

**Comment by ritzalam** [comment]
TO check if FS crashed, check for `/opt/freeswitch/core` file.

**Comment by prlanzarin** [comment]
Closing (stale). Re-open if there's still an issue to track here, but I personally haven't seen this happen in a _long_ time.
