### ISSUE TITLE
Disk full because of recordings : recording KO

### ISSUE THREAD

**Issue by ljoets** [bigbluebutton/bigbluebutton#8850]
Hi,

In installed BBB and GreenLight with the install script on a Proxmox VM with a 32G disk.

After some use, I added a second disk and move recordings that disk as described here : https://docs.bigbluebutton.org/2.2/customize.html#move-recordings-to-a-different-partition

But last night, mys first disk was full. I discovered that most of used space was in /var/lib/kurento/recordings/

I successfully resized this first disk to 64G, but should I move /var/lib/kurento/recordings to another disk too as for /var/bigbluebutton/ ?

Thanks

**Comment by ljoets** [comment]
Since my full disk problem, `bbb-record --debug` shows me errors (examples :)
```
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-03-20T18:20:31.243325 #11288] ERROR -- : SIGTERM
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-03-20T18:20:31.244048 #11288] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in `each_line'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-03-20T18:20:31.244127 #11288] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in `block in exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-03-20T18:20:31.244192 #11288] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:122:in `popen'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-03-20T18:20:31.244240 #11288] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:122:in `exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-03-20T18:20:31.244300 #11288] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:81:in `block (2 levels) in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-03-20T18:20:31.244347 #11288] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:57:in `each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-03-20T18:20:31.244412 #11288] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:57:in `block in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-03-20T18:20:31.244492 #11288] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:31:in `each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-03-20T18:20:31.244557 #11288] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:31:in `process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-03-20T18:20:31.244626 #11288] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:156:in `<main>'
```

```
   -- Ingest and Processing: found recorded meeting but no archive files-- 
  /var/bigbluebutton/recording/status/recorded/01748a2f4c5943c0750ecd1b7b9117d94e2f4455-1584954419631.done
  /var/bigbluebutton/recording/status/recorded/01748a2f4c5943c0750ecd1b7b9117d94e2f4455-1584958978554.done
  /var/bigbluebutton/recording/status/recorded/0912b6dd897f9f0d0d47b7b2996972e95b211d04-1584951822274.done
  /var/bigbluebutton/recording/status/recorded/0f92d90d1a1261bd9afe2c5a4ccda574d9d78619-1585046338937.done
  /var/bigbluebutton/recording/status/recorded/1d74bb1d7e572e2cb515448900fa0a51f9d875d4-1585055697390.done
```
How can I clean it without loosing valid records ?

Thanks

**Comment by ljoets** [comment]
Hum...
At the end of `bbb-record --watch` I can see : 
```
--
NEXT LEFT LAST PASSED UNIT                  ACTIVATES
n/a  n/a  n/a  n/a    bbb-record-core.timer bbb-record-core.target

1 timers listed.
--
● bbb-rap-archive-worker.service - BigBlueButton recording and playback archive worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-archive-worker.service; static; vendor preset: enabled)
   Active: inactive (dead)

● bbb-rap-sanity-worker.service - BigBlueButton recording and playback sanity check worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-sanity-worker.service; static; vendor preset: enabled)
   Active: inactive (dead)

● bbb-rap-process-worker.service - BigBlueButton recording and playback process worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-process-worker.service; static; vendor preset: enabled)
   Active: inactive (dead)

● bbb-rap-publish-worker.service - BigBlueButton recording and playback publish worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-publish-worker.service; static; vendor preset: enabled)
   Active: inactive (dead)
--
```
Should I kill something ?

**Comment by someone-somenet-org** [comment]
The `bbb-record --list/watch` output is fine - imho should be split into 2 additional commands, but whatever.

Have you looked into `/etc/cron.daily/bigbluebutton`?

They have imho not really good defaults in there, but the cleaner seems to work, just reduce the history days to 1 and try running it manually.
If that wont solve it, you have likely a too active server for your storage-capacity

**Comment by ljoets** [comment]
I restarted my VM
No room running.
I recorded seconds in a test room, and closing the room.
Room appears in `bbb-record --watch` but stuck with a "X _ _" on "R A S" column

If I `bbb-rebuild` thas `specific meeting_id` I obtain an error : 
```
Marking for rebuild 8dbb0d77c9a14bae7fff9dae847ff499c94ccf17-1585150640323
Raw files for 8dbb0d77c9a14bae7fff9dae847ff499c94ccf17-1585150640323 do not exist, can't rebuild
```

**Comment by ljoets** [comment]
I solved my problem by :
1. stopping BBB
1. removing records that have no raw data (some of records in date of the fulldisk problem)
1. starting BBB

**Comment by alialic** [comment]
Hi, i have a problem, for all session found recorded meeting but no archive files.

**Comment by matiasilva** [comment]
Please submit your request for support to the mailing lists!
