### ISSUE TITLE
Blank events - Error to process recording.

### ISSUE THREAD

**Issue by rriscado** [bigbluebutton/bigbluebutton#8863]
I, [2020-03-24T18:27:41.065308 #14816]  INFO -- : Performing post-processing step 0
I, [2020-03-24T18:27:41.076629 #14816]  INFO -- : Executing: mkclean --quiet /var/bigbluebutton/recording/process/presentation/410c9de48c8a110075ab0f545203faf2fde58d99-1583878929147/audio.encode.webm /var/bigbluebutton/recording/process/presentation/410c9de48c8a110075ab0f545203faf2fde58d99-1583878929147/audio.pp0.webm
I, [2020-03-24T18:32:52.302785 #14816]  INFO -- : The MinCache element at -1 is not part of profile 'webm', skipping
I, [2020-03-24T18:32:52.302928 #14816]  INFO -- : The TrackTimecodeScale element at -1 is not part of profile 'webm', skipping
I, [2020-03-24T18:32:52.302964 #14816]  INFO -- : The MaxBlockAdditionID element at -1 is not part of profile 'webm', skipping
I, [2020-03-24T18:32:52.302991 #14816]  INFO -- : The CodecDecodeAll element at -1 is not part of profile 'webm', skipping
I, [2020-03-24T18:38:16.242710 #14816]  INFO -- : Exit status: 0
I, [2020-03-24T18:38:16.343290 #14816]  INFO -- : Task: Getting presentations from events
I, [2020-03-24T18:38:16.496368 #14816]  INFO -- : Task: Getting meeting metadata
I, [2020-03-24T18:38:16.564124 #14816]  INFO -- : Created an updated metadata.xml with start_time and end_time
I, [2020-03-24T18:38:16.564202 #14816]  INFO -- : Generating closed captions
I, [2020-03-24T18:38:16.564227 #14816]  INFO -- : Executing: utils/gen_webvtt -i /var/bigbluebutton/recording/raw/410c9de48c8a110075ab0f545203faf2fde58d99-1583878929147 -o /var/bigbluebutton/recording/process/presentation/410c9de48c8a110075ab0f545203faf2fde58d99-1583878929147
I, [2020-03-24T18:38:16.781930 #14816]  INFO -- : INFO:__main__:Reading recording events file
I, [2020-03-24T18:38:16.934778 #14816]  INFO -- : Traceback (most recent call last):
I, [2020-03-24T18:38:16.934887 #14816]  INFO -- :   File "utils/gen_webvtt", line 409, in <module>
I, [2020-03-24T18:38:16.934919 #14816]  INFO -- :     events = parse_events(rawdir)
I, [2020-03-24T18:38:16.934945 #14816]  INFO -- :   File "utils/gen_webvtt", line 356, in parse_events
I, [2020-03-24T18:38:16.934970 #14816]  INFO -- :     timestamp = int(element.attrib['timestamp'])
I, [2020-03-24T18:38:16.934996 #14816]  INFO -- : ValueError: invalid literal for int() with base 10: ''
I, [2020-03-24T18:38:16.957937 #14816]  INFO -- : Exit status: 1
E, [2020-03-24T18:38:16.958024 #14816] ERROR -- : Generating closed caption files failed
E, [2020-03-24T18:38:16.958050 #14816] ERROR -- : process/presentation.rb:204:in `<main>'

**Comment by rriscado** [comment]
The events.xml file contains many blank lines. After removing these lines, the process was finished.

Why are these blank lines in the events.xml file?

  <event timestamp="" module="" eventname=""/>
  <event timestamp="" module="" eventname=""/>
  <event timestamp="" module="" eventname=""/>
  <event timestamp="" module="" eventname=""/>
  <event timestamp="" module="" eventname=""/>
  <event timestamp="" module="" eventname=""/>
  <event timestamp="" module="" eventname=""/>
  <event timestamp="" module="" eventname=""/>
  <event timestamp="" module="" eventname=""/>
  <event timestamp="" module="" eventname=""/>
  <event timestamp="" module="" eventname=""/>
  <event timestamp="" module="" eventname=""/>
  <event timestamp="" module="" eventname=""/>
  <event timestamp="" module="" eventname=""/>
  <event timestamp="" module="" eventname=""/>
  <event timestamp="" module="" eventname=""/>
  <event timestamp="" module="" eventname=""/>

**Comment by rriscado** [comment]
In archive log file, we have this INFO.

`I, [2020-04-04T13:12:00.069104 #32089]  INFO -- : Reordered event timestamp= module= eventname= by 1 positions
I, [2020-04-04T13:12:00.069171 #32089]  INFO -- : Reordered event timestamp= module= eventname= by 1 positions
I, [2020-04-04T13:12:00.069236 #32089]  INFO -- : Reordered event timestamp= module= eventname= by 1 positions
I, [2020-04-04T13:12:00.069319 #32089]  INFO -- : Reordered event timestamp= module= eventname= by 1 positions
I, [2020-04-04T13:12:00.069385 #32089]  INFO -- : Reordered event timestamp= module= eventname= by 1 positions
I, [2020-04-04T13:12:00.069448 #32089]  INFO -- : Reordered event timestamp= module= eventname= by 1 positions
I, [2020-04-04T13:12:00.069511 #32089]  INFO -- : Reordered event timestamp= module= eventname= by 1 positions
I, [2020-04-04T13:12:00.069585 #32089]  INFO -- : Reordered event timestamp= module= eventname= by 1 positions
I, [2020-04-04T13:12:00.069652 #32089]  INFO -- : Reordered event timestamp= module= eventname= by 1 positions
`

**Comment by rriscado** [comment]
This problem occurs when recording for a very long class!
