### ISSUE TITLE
Directory not empty @ dir_s_rmdir - /var/bigbluebutton/recording/publish/presentation

### ISSUE THREAD

**Issue by jibon57** [bigbluebutton/bigbluebutton#9062]
**Describe the bug**
I am using NFS to map `/var/bigbluebutton` direcotry. Everything is working fine but no callback on `meta_bbb-recording-ready-url`. So, I have started looking the log file & found this error:
`/var/log/bigbluebutton/presentation/publish-f7cd82f40b1bd4a558358ef03352811d82a07dde-1586785807015.log`
```
# Logfile created on 2020-04-13 12:20:18 -0500 by logger.rb/v1.2.7
I, [2020-04-13T12:20:18.623590 #15556]  INFO -- : Setting recording dir
I, [2020-04-13T12:20:18.623622 #15556]  INFO -- : Setting process dir
I, [2020-04-13T12:20:18.623640 #15556]  INFO -- : setting publish dir
I, [2020-04-13T12:20:18.623655 #15556]  INFO -- : setting playback url info
I, [2020-04-13T12:20:18.623668 #15556]  INFO -- : setting target dir
I, [2020-04-13T12:20:18.623693 #15556]  INFO -- : Making dir target_dir
I, [2020-04-13T12:20:18.662967 #15556]  INFO -- : Making dir package_dir
I, [2020-04-13T12:20:18.680084 #15556]  INFO -- : Making video dir
I, [2020-04-13T12:20:18.696600 #15556]  INFO -- : Made video dir - copying: /var/bigbluebutton/recording/process/presentation/f7cd82f40b1bd4a558358ef03352811d82a07dde-1586785807015/webcams.mp4 to -> /var/bigbluebutton/recording/publish/presentation/f7cd82f40b1bd4a558358ef03352811d82a07dde-1586785807015/f7cd82f40b1bd4a558358ef03352811d82a07dde-1586785807015/video
I, [2020-04-13T12:20:18.847321 #15556]  INFO -- : Copied .mp4 file
I, [2020-04-13T12:20:18.847469 #15556]  INFO -- : Copying caption files
I, [2020-04-13T12:20:18.904127 #15556]  INFO -- : Could not copy deskshares.webm: file doesn't exist
I, [2020-04-13T12:20:18.963065 #15556]  INFO -- : Getting start and stop rec button events
I, [2020-04-13T12:20:18.963109 #15556]  INFO -- : Getting record status events
I, [2020-04-13T12:20:18.963334 #15556]  INFO -- : Matching record events
I, [2020-04-13T12:20:18.963365 #15556]  INFO -- : Getting start and stop rec button events
I, [2020-04-13T12:20:18.963381 #15556]  INFO -- : Getting record status events
I, [2020-04-13T12:20:18.963637 #15556]  INFO -- : Matching record events
I, [2020-04-13T12:20:18.963891 #15556]  INFO -- : Creating metadata.xml
I, [2020-04-13T12:20:19.047796 #15556]  INFO -- : Copied metadata.xml file
I, [2020-04-13T12:20:19.048306 #15556]  INFO -- : Task: Getting from events the presentation to be used for preview
I, [2020-04-13T12:20:19.104430 #15556]  INFO -- : Added playback to metadata.xml
I, [2020-04-13T12:20:19.104479 #15556]  INFO -- : Generating xml for slides and chat
I, [2020-04-13T12:20:19.104730 #15556]  INFO -- : Processing chat events
I, [2020-04-13T12:20:19.105431 #15556]  INFO -- : Presentation  Slide 0 Deskshare false
W, [2020-04-13T12:20:19.105632 #15556]  WARN -- : Missing image file /var/bigbluebutton/recording/process/presentation/f7cd82f40b1bd4a558358ef03352811d82a07dde-1586785807015/presentation/logo.png!
I, [2020-04-13T12:20:19.107182 #15556]  INFO -- : Executing: convert -size 1600x1200 xc:transparent -background transparent -quality 90 +dither -depth 8 -colors 256 /var/bigbluebutton/recording/process/presentation/f7cd82f40b1bd4a558358ef03352811d82a07dde-1586785807015/presentation/logo.png
I, [2020-04-13T12:20:19.264544 #15556]  INFO -- : Success?: true
I, [2020-04-13T12:20:19.264606 #15556]  INFO -- : Process exited? true
I, [2020-04-13T12:20:19.264628 #15556]  INFO -- : Exit status: 0
I, [2020-04-13T12:20:19.265695 #15556]  INFO -- : Image size is 1600x1200
I, [2020-04-13T12:20:19.265740 #15556]  INFO -- : Panzoom: 0.0 0.0 100.0 100.0 (1600x1200)
I, [2020-04-13T12:20:19.265767 #15556]  INFO -- : Cursor: visible false, -1.0 -1.0 (1600x1200)
I, [2020-04-13T12:20:19.265967 #15556]  INFO -- : Presentation  Slide 0 is never shown (duration rounds to 0)
I, [2020-04-13T12:20:19.265990 #15556]  INFO -- : Presentation c4678fcdc2bc5b49dbc7b30656266f958a7b16d2-1586785807066 Slide 0 Deskshare false
I, [2020-04-13T12:20:19.266373 #15556]  INFO -- : Image size is 1600x900
I, [2020-04-13T12:20:19.266408 #15556]  INFO -- : Panzoom: not emitting, duration rounds to 0
I, [2020-04-13T12:20:19.266427 #15556]  INFO -- : Panzoom: 0.0 0.0 100.0 100.0 (1600x900)
I, [2020-04-13T12:20:19.266448 #15556]  INFO -- : Cursor: not emitting, duration rounds to 0
I, [2020-04-13T12:20:19.266463 #15556]  INFO -- : Cursor: visible false, -1.0 -1.0 (1600x900)
I, [2020-04-13T12:20:19.266534 #15556]  INFO -- : Cursor: skipping, no changes
I, [2020-04-13T12:20:19.266612 #15556]  INFO -- : Cursor: skipping, no changes
I, [2020-04-13T12:20:19.266681 #15556]  INFO -- : Cursor: skipping, no changes
I, [2020-04-13T12:20:19.266819 #15556]  INFO -- : Cursor: not emitting, duration rounds to 0
I, [2020-04-13T12:20:19.266855 #15556]  INFO -- : Cursor: visible true, 49.21225229899088 30.18963849103009 (1600x900)
I, [2020-04-13T12:20:19.266965 #15556]  INFO -- : Cursor: not emitting, duration rounds to 0
I, [2020-04-13T12:20:19.266991 #15556]  INFO -- : Cursor: visible true, 49.43107604980469 27.272061948423033 (1600x900)
I, [2020-04-13T12:20:19.267090 #15556]  INFO -- : Cursor: not emitting, duration rounds to 0
I, [2020-04-13T12:20:19.267115 #15556]  INFO -- : Cursor: visible true, 50.96280415852864 17.935812208387585 (1600x900)
I, [2020-04-13T12:20:19.267249 #15556]  INFO -- : Cursor: not emitting, duration rounds to 0
I, [2020-04-13T12:20:19.267273 #15556]  INFO -- : Cursor: visible false, -57.680530548095696 -18.825677942346644 (1600x900)
I, [2020-04-13T12:20:19.267386 #15556]  INFO -- : Cursor: not emitting, duration rounds to 0
I, [2020-04-13T12:20:19.267610 #15556]  INFO -- : Cursor: visible true, 14.310722351074217 62.08849871600116 (1600x900)
I, [2020-04-13T12:20:19.267778 #15556]  INFO -- : Cursor 0.14311 0.62088 at 0.0
I, [2020-04-13T12:20:19.267828 #15556]  INFO -- : Cursor: visible true, 14.310722351074217 61.699490017361114 (1600x900)
I, [2020-04-13T12:20:19.267996 #15556]  INFO -- : Cursor 0.14311 0.61699 at 0.3
I, [2020-04-13T12:20:19.268027 #15556]  INFO -- : Cursor: visible true, 20.0 49.05664514612268 (1600x900)
I, [2020-04-13T12:20:19.268166 #15556]  INFO -- : Cursor: not emitting, duration rounds to 0
I, [2020-04-13T12:20:19.268194 #15556]  INFO -- : Cursor: visible true, 43.085339864095054 17.157791985405815 (1600x900)
I, [2020-04-13T12:20:19.268312 #15556]  INFO -- : Cursor 0.43085 0.17158 at 0.4
I, [2020-04-13T12:20:19.268346 #15556]  INFO -- : Cursor: visible true, 53.26039632161458 7.043517783836083 (1600x900)
I, [2020-04-13T12:20:19.268499 #15556]  INFO -- : Cursor: not emitting, duration rounds to 0
I, [2020-04-13T12:20:19.268526 #15556]  INFO -- : Cursor: visible true, 60.04376729329427 1.9863820959020544 (1600x900)
I, [2020-04-13T12:20:19.268730 #15556]  INFO -- : Cursor 0.60044 0.01986 at 0.5
I, [2020-04-13T12:20:19.268763 #15556]  INFO -- : Cursor: visible true, 60.04376729329427 1.7918777465820312 (1600x900)
I, [2020-04-13T12:20:19.268866 #15556]  INFO -- : Cursor: not emitting, duration rounds to 0
I, [2020-04-13T12:20:19.268892 #15556]  INFO -- : Cursor: visible false, -57.680530548095696 -18.825677942346644 (1600x900)
I, [2020-04-13T12:20:19.269070 #15556]  INFO -- : Cursor -1.0 -1.0 at 0.7
I, [2020-04-13T12:20:19.269103 #15556]  INFO -- : Cursor: visible true, 99.64988708496094 7.043517783836083 (1600x900)
I, [2020-04-13T12:20:19.269202 #15556]  INFO -- : Cursor: not emitting, duration rounds to 0
I, [2020-04-13T12:20:19.269227 #15556]  INFO -- : Cursor: visible false, -57.680530548095696 -18.825677942346644 (1600x900)
I, [2020-04-13T12:20:19.269344 #15556]  INFO -- : Cursor -1.0 -1.0 at 1.5
I, [2020-04-13T12:20:19.269437 #15556]  INFO -- : Cursor: visible true, 90.78774770100911 27.466566297743057 (1600x900)
I, [2020-04-13T12:20:19.269546 #15556]  INFO -- : Cursor: not emitting, duration rounds to 0
I, [2020-04-13T12:20:19.269570 #15556]  INFO -- : Cursor: visible false, -57.680530548095696 -18.825677942346644 (1600x900)
I, [2020-04-13T12:20:19.269719 #15556]  INFO -- : Cursor -1.0 -1.0 at 5.1
I, [2020-04-13T12:20:19.269751 #15556]  INFO -- : Cursor: visible true, 16.71772638956706 58.97641217267072 (1600x900)
I, [2020-04-13T12:20:19.269779 #15556]  INFO -- : Image 1: Presentation c4678fcdc2bc5b49dbc7b30656266f958a7b16d2-1586785807066 Slide 0 Deskshare false from 0.0 to 6.0
I, [2020-04-13T12:20:19.270008 #15556]  INFO -- : Panzoom viewbox -0.0 -0.0 1600.0 900.0 at 0.0
I, [2020-04-13T12:20:19.270042 #15556]  INFO -- : Cursor: not emitting, duration rounds to 0
I, [2020-04-13T12:20:19.449306 #15556]  INFO -- : Processing deskshare events
I, [2020-04-13T12:20:19.449813 #15556]  INFO -- : Task: Getting stop DESKSHARE events
I, [2020-04-13T12:20:19.449966 #15556]  INFO -- : Task: Matching the start and stop deskshare events
I, [2020-04-13T12:20:19.566390 #15556]  INFO -- : Copying files to package dir
I, [2020-04-13T12:20:20.997246 #15556]  INFO -- : Copied files to package dir
I, [2020-04-13T12:20:20.997304 #15556]  INFO -- : Publishing slides
I, [2020-04-13T12:20:22.889418 #15556]  INFO -- : Finished publishing script presentation.rb successfully.
I, [2020-04-13T12:20:22.889484 #15556]  INFO -- : Removing processed files. /var/bigbluebutton/recording/process/presentation/f7cd82f40b1bd4a558358ef03352811d82a07dde-1586785807015
I, [2020-04-13T12:20:24.698528 #15556]  INFO -- : Removing published files. /var/bigbluebutton/recording/process/presentation/f7cd82f40b1bd4a558358ef03352811d82a07dde-1586785807015
E, [2020-04-13T12:20:25.380308 #15556] ERROR -- : Directory not empty @ dir_s_rmdir - /var/bigbluebutton/recording/publish/presentation/f7cd82f40b1bd4a558358ef03352811d82a07dde-1586785807015/f7cd82f40b1bd4a558358ef03352811d82a07dde-1586785807015
E, [2020-04-13T12:20:25.380364 #15556] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1445:in `rmdir'
E, [2020-04-13T12:20:25.380382 #15556] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1445:in `block in remove_dir1'
E, [2020-04-13T12:20:25.380396 #15556] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1456:in `platform_support'
E, [2020-04-13T12:20:25.380408 #15556] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1444:in `remove_dir1'
E, [2020-04-13T12:20:25.380420 #15556] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1437:in `remove'
E, [2020-04-13T12:20:25.380432 #15556] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:779:in `block in remove_entry'
E, [2020-04-13T12:20:25.380444 #15556] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1494:in `postorder_traverse'
E, [2020-04-13T12:20:25.380457 #15556] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:777:in `remove_entry'
E, [2020-04-13T12:20:25.380469 #15556] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:635:in `block in rm_r'
E, [2020-04-13T12:20:25.380481 #15556] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:631:in `each'
E, [2020-04-13T12:20:25.380493 #15556] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:631:in `rm_r'
E, [2020-04-13T12:20:25.380505 #15556] ERROR -- : publish/presentation.rb:1377:in `<main>'
E, [2020-04-13T12:20:25.380529 #15556] ERROR -- : exit
E, [2020-04-13T12:20:25.380552 #15556] ERROR -- : publish/presentation.rb:1383:in `exit'
E, [2020-04-13T12:20:25.380566 #15556] ERROR -- : publish/presentation.rb:1383:in `rescue in <main>'
E, [2020-04-13T12:20:25.380578 #15556] ERROR -- : publish/presentation.rb:1203:in `<main>'
```

**To Reproduce**
This is happening if I am using NFS otherwise fine. More [details](https://groups.google.com/forum/#!topic/bigbluebutton-dev/9cvOSGOqBE4)

Any idea how to resolve this? Thanks in advance.

**Comment by jibon57** [comment]
OK, I did following changes for `/usr/local/bigbluebutton/core/scripts/publish/presentation.rb`

line 1374:
```
#FileUtils.rm_r(Dir.glob("#{$process_dir}/*"))
system "rm -rf #{$process_dir}/*"
```
line 1378
```
#FileUtils.rm_r(Dir.glob("#{target_dir}/*"))
system "rm -rf #{$target_dir}/*"
```
Now it's working fine. There may be better solution.

**Comment by jibon57** [comment]
OK, I have changed like this for `/usr/local/bigbluebutton/core/scripts/publish/presentation.rb`

line 1374
```
#FileUtils.rm_r("#{$process_dir}/*")
system "rm -rf #{$process_dir}"
```

line 1378
```
#FileUtils.rm_r("#{target_dir}/*")
system "rm -rf #{$target_dir}"
```
Now seems like working. There should be better way.

**Comment by int03** [comment]
> OK, I have changed like this for `/usr/local/bigbluebutton/core/scripts/publish/presentation.rb`
> 
> line 1374
> 
> ```
> #FileUtils.rm_r(Dir.glob("#{$process_dir}/*"))
> system "rm -rf #{$process_dir}"
> ```
> 
> line 1378
> 
> ```
> #FileUtils.rm_r(Dir.glob("#{target_dir}/*"))
> system "rm -rf #{$target_dir}"
> ```
> 
> Now seems like working. There should be better way.

you can change it to FileUtils.rm_r**f**(Dir.glob("#{$process_dir}/*"))

**Comment by jibon57** [comment]
@int03 thanks it's working too. Sorry, I don't have experience on `ruby`

**Comment by matiasilva** [comment]
Should be solved with the latest PR guys. Wait for the minor release or patch it in yourselves to test. Closing for now.

**Comment by defnull** [comment]
I saw `Directory not empty @ dir_s_rmdir - /var/bigbluebutton/recording/publish/presentation/40b7957f6698c9deccb12ac267a782690502e60f-1596274929474/40b7957f6698c9deccb12ac267a782690502e60f-1596274929474` now, with the newest version of BBB. is there a regression?

**Comment by defnull** [comment]
Please re-open this issue, it is not fixed.

**Comment by caijian76** [comment]
I have the same Error ,But it's Random occurrence

**Comment by prlanzarin** [comment]
Fixed by https://github.com/bigbluebutton/bigbluebutton/pull/10984
