### ISSUE TITLE
Error uploading big files with via API (java.lang.OutOfMemoryError: Java heap space)

### ISSUE THREAD

**Issue by davidrojo** [bigbluebutton/bigbluebutton#9092]
**Describe the bug**
I am having an issue uploading presentation files via create meeting api. The issue comes when uploading big files, like 20Mb files. These files works ok when uploading them via de BBB frontend,  but no when uploading via API.

I receive the following error from the API.

`HTTP Status 500 – Internal Server Error`

I've increased the `client_body_size` for the api endpoint, and looking into `/var/log/bigbluebutton/bbb-web.log` I see that this is an error related with the Java Heap memory

```
2020-04-15T13:23:32.296+02:00 ERROR o.g.w.e.GrailsExceptionResolver - OutOfMemoryError occurred when processing request: [POST] /bigbluebutton/api/create
Java heap space. Stacktrace follows:
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:982)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

So the question is how to increase Java Heap Size for the api.

**Comment by jibon57** [comment]
The maximum file size will be 2MB if you want to use API. 
http://docs.bigbluebutton.org/dev/api.html#pre-upload-slides

**Comment by davidrojo** [comment]
Hi @jibon57, editing the file `/etc/bigbluebutton/nginx/web.nginx` and adding in `location /bigbluebutton` the line `client_max_body_size 50m;` allows you to upload files bigger than 2Mb. As it says in the link the 2Mb limit is "by default" http://docs.bigbluebutton.org/2.2/customize.html#increase-the-file-size-for-an-uploaded-presentation

Without adding the `client_max_body_size` in `location /bigbluebutton`, I receive the error "Entity too large" but adding it I can upload files of 15Mb correctly. Bigger files or some certain pdf files throws the OutOfMemoryError resulting in a Internal server error.

**Comment by matiasilva** [comment]
Can you try upgrading to the latest version of BBB and see if this issue persists?

**Comment by Ezanor** [comment]
Hi, Yesterday i encountered exactly the same problem pre-uploading large pdf files, resulted in java OutOfMemoryError. (Using bbb 2.2.17)

So i decided to build my own bbb-web to find where the problem is.
Landed in : https://github.com/bigbluebutton/bigbluebutton/blob/82930ad4bd14045a9a7e7b1dea65237415b4e953/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy

Removed the log that log the entire pdf :
`log.debug "Request body: \n" + requestBody;`
And now i have no more the issue, it works.

I don't think we need to log all files that are uploaded via API.

**Comment by weberhofer** [comment]
In case it's needed for debugging purposes, I'd recomment to use this line to dramatically reduce the memory used for large files:
```java
if (log.isDebugEnabled())
{
    log.debug "Request body: \n" + requestBody;
}

**Comment by matiasilva** [comment]
@Ezanor could you submit a pull request with your proposed changes?
