### ISSUE TITLE
Weird presentationName value in SharePresentationEvent events.xml tag

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#9214]
**Describe the bug**
The original file name with additional characters is place in the `presentationName` instead of the generated presentation.

**To Reproduce**
1. Upload two presentations one in docx and the other one in pptx when the meetings starts.

**Expected behavior**
The recorded meeting should process.

**Actual behavior**
Recording processing fails.

**Logs**

The recordings fails with the following logs.

```ruby
W, [2020-04-22T12:16:44.761258 #29417]  WARN -- : Could not find pdf file for presentation Chapter 5.pptx161
E, [2020-04-22T12:16:44.761365 #29417] ERROR -- : unknown file type: /var/bigbluebutton/recording/process/presentation/17ac28605c1bb24effd8140dcd28aebc08661782-1587275479284/temp/17ac28605c1bb24effd8140dcd28aebc08661782-1587275479284/presentation/Chapter 5.pptx161/thumbnails
E, [2020-04-22T12:16:44.761393 #29417] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1387:in `copy'
E, [2020-04-22T12:16:44.761404 #29417] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:472:in `block in copy_entry'
E, [2020-04-22T12:16:44.761412 #29417] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1498:in `wrap_traverse'
E, [2020-04-22T12:16:44.761419 #29417] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:469:in `copy_entry'
E, [2020-04-22T12:16:44.761427 #29417] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:444:in `block in cp_r'
E, [2020-04-22T12:16:44.761433 #29417] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
E, [2020-04-22T12:16:44.761440 #29417] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
E, [2020-04-22T12:16:44.761446 #29417] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
E, [2020-04-22T12:16:44.761452 #29417] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:443:in `cp_r'
E, [2020-04-22T12:16:44.761459 #29417] ERROR -- : process/presentation.rb:198:in `block in <main>'
E, [2020-04-22T12:16:44.761465 #29417] ERROR -- : process/presentation.rb:153:in `each'
E, [2020-04-22T12:16:44.761471 #29417] ERROR -- : process/presentation.rb:153:in `<main>'
```

**Additional context**

The event in the events.xml

```xml
  <event timestamp="3379701761" module="PRESENTATION" eventname="SharePresentationEvent">
    <timestampUTC>1587275898274</timestampUTC>
    <presentationName>Chapter 5.pptx161</presentationName>
    <podId>DEFAULT_PRESENTATION_POD</podId>
    <share>true</share>
    <date>2020-04-19T08:58:18.274+03</date>
  </event>
```

While it should be 

```xml
  <event timestamp="3379701761" module="PRESENTATION" eventname="SharePresentationEvent">
    <timestampUTC>1587275898274</timestampUTC>
    <presentationName>0b55c351a2a21bc6ee7954ab6c9bf82262676305-1587275571213</presentationName>
    <podId>DEFAULT_PRESENTATION_POD</podId>
    <share>true</share>
    <date>2020-04-19T08:58:18.274+03</date>
  </event>
```

Assumptions: 
- The file looks like to have been uploaded twice.
- Some redis inconsistency?

**Comment by pedrobmarin** [comment]
@fcecagno we had a similar problem, right?

**Comment by fcecagno** [comment]
Yes, but it's been a while. We couldn't figure out why it was happening, and I believe it's no longer an issue.

This is the code we used to fix the recordings:
```ruby
# encoding: UTF-8

require 'nokogiri'
require 'fileutils'
require 'optimist'

opts = Optimist::options do
  opt :record_id, "recordID to process", :type => :string, :required => true
end

record_id = opts[:record_id]
events_xml = "/var/bigbluebutton/recording/raw/#{record_id}/events.xml"
if ! File.exists? events_xml
  puts "Cannot fix #{record_id} because raw isn't available any more"
  exit 1
end

data = []
modified = false

doc = Nokogiri::XML(File.open(events_xml)) { |x| x.noblanks }
doc.xpath("/recording/event[@module='PRESENTATION' and ( @eventname='SharePresentationEvent' or @eventname='ConversionCompletedEvent' )]").each do |event|
  event_name = event.at_xpath("@eventname").text
  presentation_name_node = event.at_xpath("presentationName")
  presentation_name = presentation_name_node.text
  case event_name
  when "ConversionCompletedEvent"
    original_filename = event.at_xpath("originalFilename").text
    data << {
      :original_filename => original_filename,
      :presentation_name => presentation_name
    }
  when "SharePresentationEvent"
    match = /^\w+-\d+$/.match presentation_name
    next if ! match.nil?

    puts
    puts "ID #{record_id}, current presentation_name: #{presentation_name}"
    candidate = data.select{ |item| presentation_name.start_with? item[:original_filename] }.first
    if candidate.nil?
      puts "  Cannot find a suitable candidate"
    else
      puts "  Candidate original filename: #{candidate[:original_filename]}"
      puts "  New presentation name: #{candidate[:presentation_name]}"
      modified = true
      presentation_name_node.content = candidate[:presentation_name]
    end
  end
end

if modified
  FileUtils.cp events_xml, "#{events_xml}.orig" if ! File.exists? "#{events_xml}.orig"
  xml_file = File.new(events_xml, "w")
  xml_file.write(doc.to_xml(:indent => 2))
  xml_file.close

  puts "Rebuilding #{record_id}"
  FileUtils.rm_rf "/var/bigbluebutton/recording/process/presentation/#{record_id}"
  FileUtils.rm_rf "/var/bigbluebutton/recording/publish/presentation/#{record_id}"
  FileUtils.rm_f "/var/bigbluebutton/recording/status/processed/#{record_id}-presentation.fail"
end
```
