### ISSUE TITLE
Authentication timeout error after reboot

### ISSUE THREAD

**Issue by TheJJ** [bigbluebutton/bigbluebutton#9400]
Hi!

Authentication of the html5-client fails after the bbb-node was rebooted.

The authentication attempt waits one minute, then timeouts. The user is presented "401 Unauthorized".

Issuing `bbb-conf --restart` fixes the problem! Meetings work just fine after that (until the next reboot).

Browser log (Firefox 75):
```
[22:32:41:0384]  WARN: clientLogger: Call to userChangedLocalSettings failed because Meteor is not connected https://node8.bbb.lolschool.edu/html5client/c86276c602f80e1c39e9064918149b6eade2642d.js?meteor_js_resource=true:121:1111148 c86276c602f80e1c39e9064918149b6eade2642d.js:9:342209
[22:32:42:0209] DEBUG: clientLogger: Initial connection status change. status: connecting, connected: false https://node8.bbb.lolschool.edu/html5client/c86276c602f80e1c39e9064918149b6eade2642d.js?meteor_js_resource=true:121:996508 c86276c602f80e1c39e9064918149b6eade2642d.js:9:342209
uncaught exception: Call to userChangedLocalSettings failed because Meteor is not connected
[22:32:42:0483] DEBUG: clientLogger: Initial connection status change. status: connected, connected: true https://node8.bbb.lolschool.edu/html5client/c86276c602f80e1c39e9064918149b6eade2642d.js?meteor_js_resource=true:121:996508 c86276c602f80e1c39e9064918149b6eade2642d.js:9:342209
[22:32:42:0483]  INFO: clientLogger: Connection to Meteor took 0.28s https://node8.bbb.lolschool.edu/html5client/c86276c602f80e1c39e9064918149b6eade2642d.js?meteor_js_resource=true:121:996679 c86276c602f80e1c39e9064918149b6eade2642d.js:9:342209
[22:32:42:0564]  INFO: clientLogger: Log information about the client https://node8.bbb.lolschool.edu/html5client/c86276c602f80e1c39e9064918149b6eade2642d.js?meteor_js_resource=true:121:997850 c86276c602f80e1c39e9064918149b6eade2642d.js:9:342209
[22:32:42:0566]  INFO: clientLogger: User successfully went through main.joinRouteHandler https://node8.bbb.lolschool.edu/html5client/c86276c602f80e1c39e9064918149b6eade2642d.js?meteor_js_resource=true:121:998555 c86276c602f80e1c39e9064918149b6eade2642d.js:9:342209
[22:32:42:0573]  INFO: clientLogger: re-send validateAuthToken for delayed authentication https://node8.bbb.lolschool.edu/html5client/c86276c602f80e1c39e9064918149b6eade2642d.js?meteor_js_resource=true:121:1125579 c86276c602f80e1c39e9064918149b6eade2642d.js:9:342209
[22:33:42:0582] ERROR: clientLogger: Encountered error while trying to authenticate https://node8.bbb.lolschool.edu/html5client/c86276c602f80e1c39e9064918149b6eade2642d.js?meteor_js_resource=true:121:964357 c86276c602f80e1c39e9064918149b6eade2642d.js:9:342209
[22:33:42:0604] ERROR: clientLogger: User could not log in HTML5, hit 401 https://node8.bbb.lolschool.edu/html5client/c86276c602f80e1c39e9064918149b6eade2642d.js?meteor_js_resource=true:121:1167136 c86276c602f80e1c39e9064918149b6eade2642d.js:9:342209
[22:33:42:0624] XHR GET https://node8.bbb.lolschool.edu/html5client/locale?locale=en-US&init=true
[HTTP/2 200 OK 155ms]
[22:33:42:0849]  WARN: clientLogger: Call to userChangedLocalSettings failed because Meteor is not connected https://node8.bbb.lolschool.edu/html5client/c86276c602f80e1c39e9064918149b6eade2642d.js?meteor_js_resource=true:121:1111148 c86276c602f80e1c39e9064918149b6eade2642d.js:9:342209
[22:33:42:0857] ERROR: clientLogger: User could not log in HTML5, hit 401 https://node8.bbb.lolschool.edu/html5client/c86276c602f80e1c39e9064918149b6eade2642d.js?meteor_js_resource=true:121:1167136 c86276c602f80e1c39e9064918149b6eade2642d.js:9:342209
uncaught exception: Call to userChangedLocalSettings failed because Meteor is not connected
```

Server log (`bbb-html5.service`):
```
May 03 22:32:42 bbbnodeserver systemd_start.sh[2108]: warn: {"logCode":"was_not_provided","logDescription":"Call to userChangedLocalSettings failed because Meteor is not connected","connectionId":"D4KdY33Myu8cXtWLp","e
xtraInfo":{"validUser":"notFound"},"userInfo":{}}
May 03 22:32:42 bbbnodeserver systemd_start.sh[2108]: info: {"logCode":"was_not_provided","logDescription":"Connection to Meteor took 0.28s","connectionId":"D4KdY33Myu8cXtWLp","extraInfo":{"validUser":"notFound"},"user
Info":{}}
May 03 22:32:42 bbbnodeserver systemd_start.sh[2108]: info: {"logCode":"joinhandler_component_clientinfo","logDescription":"Log information about the client","connectionId":"D4KdY33Myu8cXtWLp","extraInfo":{"clientInfo"
:{"language":"en-US","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0","screenSize":{"width":1707,"height":960},"windowSize":{"width":1303,"height":854},"bbbVersion":2.2,"location"
:"https://node8.bbb.lolschool.edu/html5client/join?sessionToken=t5pskff0wmgdnjpq"},"validUser":"notFound"},"userInfo":{"sessionToken":"t5pskff0wmgdnjpq","meetingId":"asdfmeetingidcensoredasdfasdf0-158853795
9442","requesterUserId":"w_pnyyyyyyyyyk","fullname":"rofl","confname":"lol conference","externUserID":"gl-imxxxxxxxxy","uniqueClientSession":null}}
May 03 22:32:42 bbbnodeserver systemd_start.sh[2108]: info: {"logCode":"joinhandler_component_joinroutehandler_success","logDescription":"User successfully went through main.joinRouteHandler","connectionId":"D4KdY33Myu
8cXtWLp","extraInfo":{"response":{"returncode":"SUCCESS","fullname":"rofl","confname":"lol conference","meetingID":"asdfmeetingidcensoredasdfasdf0-1588537959442","externMeetingID":"snipsnap","externUserID":"gl-imxxxxxxxxy","internalUserID":"w_pnyyyyyyyyyk","authToken":"qvsnvnoir7cm","role":"MODERATOR","guest":false,"guestStatus":"ALLOW","conference":"asdfmeetingidcensoredasdfasdf0-1588537959442","room":"asdfmeetingidcensoredasdfasdf0-1588537959442","voicebridge":"51690","dialnumber":"613-555-1234","webvoiceconf":"51690","mode":"LIVE","record":"true","isBreakout"
:false,"logoutTimer":0,"allowStartStopRecording":true,"welcome":"snip","modOnlyMessage":"snip","customLogoURL":"","customCopyright":"","muteOnStart":false,"allowModsToUnmuteUsers":false,"logoutUrl":"https://bbb.lolschool.edu/jon-xxx-yyy/logout","defaultLayout":"NOLAYOUT","avatarURL":"https://node8.bbb.lolschool.edu/client/avatar.png","breakoutRooms":{"enabled":true,"record":false,"privateChatEnabled":true},"customdata":[],"metadata":[{"bbb-origin-version":"v2"},{"bbb-origin-server-name":"bbb.lolschool.edu"},{"bbb-origin":"Greenlight"},{"gl-listed":"false"}]},"validUser":"notFound"},"userInfo":{"sessionToken":"t5pskff0wmgdnjpq","meetingId":"asdfmeetingidcensoredasdfasdf0-1588537959442","requesterUserId":"w_pnyyyyyyyyyk","fullname":"rofl","confname":"lol conference","exter
May 03 22:32:42 bbbnodeserver systemd_start.sh[2108]: nUserID":"gl-imxxxxxxxxy","uniqueClientSession":null}}
May 03 22:32:42 bbbnodeserver systemd_start.sh[2108]: info: User 'w_pnyyyyyyyyyk' is trying to validate auth token for meeting 'asdfmeetingidcensoredasdfasdf0-1588537959442' from connection 'D4KdY33Myu8cXtWLp'
May 03 22:32:42 bbbnodeserver systemd_start.sh[2108]: info: {"logCode":"auth_service_resend_validateauthtoken","logDescription":"re-send validateAuthToken for delayed authentication","connectionId":"D4KdY33Myu8cXtWLp","extraInfo":{"validUser":"notFound"},"userInfo":{"sessionToken":"t5pskff0wmgdnjpq","meetingId":"asdfmeetingidcensoredasdfasdf0-1588537959442","requesterUserId":"w_pnyyyyyyyyyk","fullname":"rofl","confname":"lol conference","externUserID":"gl-imxxxxxxxxy","uniqueClientSession":null}}
May 03 22:32:42 bbbnodeserver systemd_start.sh[2108]: info: User 'w_pnyyyyyyyyyk' is trying to validate auth token for meeting 'asdfmeetingidcensoredasdfasdf0-1588537959442' from connection 'D4KdY33Myu8cXtWLp'
May 03 22:33:42 bbbnodeserver systemd_start.sh[2108]: error: {"logCode":"authenticatedhandlercomponent_setreason","logDescription":"Encountered error while trying to authenticate","connectionId":"D4KdY33Myu8cXtWLp","extraInfo":{"reason":{"error":401,"description":"Authentication timeout."},"validUser":"notFound"},"userInfo":{"sessionToken":"t5pskff0wmgdnjpq","meetingId":"asdfmeetingidcensoredasdfasdf0-1588537959442","requesterUserId":"w_pnyyyyyyyyyk","fullname":"rofl","confname":"lol conference","externUserID":"gl-imxxxxxxxxy","uniqueClientSession":null}}
May 03 22:33:42 bbbnodeserver systemd_start.sh[2108]: error: {"logCode":"startup_client_usercouldnotlogin_error","logDescription":"User could not log in HTML5, hit 401","connectionId":"D4KdY33Myu8cXtWLp","extraInfo":{"validUser":"notFound"},"userInfo":{"sessionToken":"t5pskff0wmgdnjpq","meetingId":"asdfmeetingidcensoredasdfasdf0-1588537959442","requesterUserId":"w_pnyyyyyyyyyk","fullname":"rofl","confname":"lol conference","externUserID":"gl-imxxxxxxxxy","uniqueClientSession":null}}
May 03 22:33:42 bbbnodeserver systemd_start.sh[2108]: warn: 'Could not process locale en_US:Error: Unknown asset: locales/en_US.json
```

The important part seems to be this:
```
"extraInfo":{"reason":{"error":401,"description":"Authentication timeout."} ...
```

**BBB version:**
* 2.2.9
* also happened on 2.2.6

**Comment by bruno-berchielli** [comment]
I'm also getting this error.

**Comment by flyinghuman** [comment]
here the same error using greenlight.

**Comment by TheJJ** [comment]
This still happens on 2.2.19, and I've figured out one reason now: `bbb-apps-akka.service` fails to connect to redis because it's out of file descriptors.

```
Jun 25 12:47:36 kischt bbb-apps-akka[92263]: 2020-06-25T12:47:36.483+02:00 INFO  o.b.c.redis.RedisStorageService - Connected to redis. clientName=BbbAppsAkkaRecorder
Jun 25 12:47:36 kischt bbb-apps-akka[92263]: 2020-06-25T12:47:36.485+02:00 INFO  o.b.c.redis.RedisStorageService - Connected to redis activated. clientName=BbbAppsAkkaRecorder
Jun 25 12:47:36 kischt bbb-apps-akka[92263]: 2020-06-25T12:47:36.486+02:00 DEBUG o.b.e.redis.RedisRecorderActor - started (org.bigbluebutton.endpoint.redis.RedisRecorderActor@518bca45)
Jun 25 12:47:36 kischt bbb-apps-akka[92263]: 2020-06-25T12:47:36.495+02:00 DEBUG o.b.c.p.s.ReceivedJsonMsgHandlerActor - started (org.bigbluebutton.core.pubsub.senders.ReceivedJsonMsgHandlerActor@257c9218)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]: 2020-06-25T12:47:38.770+02:00 ERROR akka.actor.OneForOneStrategy - failed to create a child event loop
Jun 25 12:47:38 kischt bbb-apps-akka[92263]: akka.actor.ActorInitializationException: akka://bigbluebutton-apps-system/user/redis-subscriber: exception during creation
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at akka.actor.ActorInitializationException$.apply(Actor.scala:193)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at akka.actor.ActorCell.create(ActorCell.scala:669)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at akka.dispatch.Mailbox.run(Mailbox.scala:224)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]: Caused by: java.lang.reflect.InvocationTargetException: null
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at akka.util.Reflect$.instantiate(Reflect.scala:66)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at akka.actor.Props.newActor(Props.scala:212)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at akka.actor.ActorCell.newActor(ActorCell.scala:624)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at akka.actor.ActorCell.create(ActorCell.scala:650)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         ... 9 common frames omitted
Jun 25 12:47:38 kischt bbb-apps-akka[92263]: Caused by: java.lang.IllegalStateException: failed to create a child event loop
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.lettuce.core.resource.DefaultEventLoopGroupProvider.createEventLoopGroup(DefaultEventLoopGroupProvider.java:145)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.lettuce.core.resource.DefaultEventLoopGroupProvider.getOrCreate(DefaultEventLoopGroupProvider.java:116)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.lettuce.core.resource.DefaultEventLoopGroupProvider.allocate(DefaultEventLoopGroupProvider.java:65)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.lettuce.core.AbstractRedisClient.getEventLoopGroup(AbstractRedisClient.java:187)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.lettuce.core.AbstractRedisClient.channelType(AbstractRedisClient.java:173)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.lettuce.core.RedisClient.connectStatefulAsync(RedisClient.java:304)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.lettuce.core.RedisClient.connectPubSubAsync(RedisClient.java:434)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.lettuce.core.RedisClient.connectPubSub(RedisClient.java:355)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at org.bigbluebutton.common2.redis.RedisSubscriberProvider.<init>(RedisSubscriberProvider.scala:34)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at org.bigbluebutton.endpoint.redis.AppsRedisSubscriberActor.<init>(AkkaAppsRedisSubscriberActor.scala:42)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         ... 18 common frames omitted
Jun 25 12:47:38 kischt bbb-apps-akka[92263]: Caused by: io.netty.channel.ChannelException: failed to open a new selector
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:168)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:142)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         ... 34 common frames omitted
Jun 25 12:47:38 kischt bbb-apps-akka[92263]: Caused by: java.io.IOException: Too many open files
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at sun.nio.ch.EPollArrayWrapper.epollCreate(Native Method)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at sun.nio.ch.EPollArrayWrapper.<init>(EPollArrayWrapper.java:130)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:69)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:166)
Jun 25 12:47:38 kischt bbb-apps-akka[92263]:         ... 38 common frames omitted
```



After overriding the fdlimit with `/etc/systemd/system/bbb-apps-akka.service.d/override.conf`:
```
[Service]
LimitNOFILE=
LimitNOFILE=262144
```

And running `bbb-conf --restart`, the session creation worked again worked.

The server has **128 cores**. I'd be glad if the BBB core team optimized the software more for scalability even with big single nodes. The fdlimits should be increased by default (and also more ressource optimizations e.g. for room joins >100).

**Comment by TheJJ** [comment]
Another hint towards the problem: After a reboot, the problem persists, even though the fdlimit is increased. It seems there's a startup race condition in `bbb-apps-akka` and it can't connect to redis.

To fix this properly, `bbb-apps-akka` should try to reconnect instead of hang in this non-connected but running state!

```
Jun 25 14:44:24 kischt bbb-apps-akka[2267]: 2020-06-25T14:44:24.500+02:00 DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
Jun 25 14:44:24 kischt bbb-apps-akka[2267]: 2020-06-25T14:44:24.501+02:00 DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
Jun 25 14:44:24 kischt bbb-apps-akka[2267]: 2020-06-25T14:44:24.501+02:00 DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
Jun 25 14:44:24 kischt bbb-apps-akka[2267]: 2020-06-25T14:44:24.528+02:00 DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
Jun 25 14:44:24 kischt bbb-apps-akka[2267]: 2020-06-25T14:44:24.529+02:00 DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
Jun 25 14:44:24 kischt bbb-apps-akka[2267]: 2020-06-25T14:44:24.529+02:00 DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
Jun 25 14:44:24 kischt bbb-apps-akka[2267]: 2020-06-25T14:44:24.529+02:00 DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
Jun 25 14:44:24 kischt bbb-apps-akka[2267]: 2020-06-25T14:44:24.538+02:00 DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
Jun 25 14:44:24 kischt bbb-apps-akka[2267]: 2020-06-25T14:44:24.538+02:00 DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
Jun 25 14:44:24 kischt bbb-apps-akka[2267]: 2020-06-25T14:44:24.538+02:00 DEBUG i.n.u.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@1ba56384
Jun 25 14:44:24 kischt bbb-apps-akka[2267]: Exception in thread "main" io.lettuce.core.RedisConnectionException: Unable to connect to 127.0.0.1:6379
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:234)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at io.lettuce.core.RedisClient.connectPubSub(RedisClient.java:355)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at org.bigbluebutton.common2.redis.RedisPublisher.<init>(RedisPublisher.scala:21)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at org.bigbluebutton.Boot$.delayedEndpoint$org$bigbluebutton$Boot$1(Boot.scala:35)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at org.bigbluebutton.Boot$delayedInit$body.apply(Boot.scala:15)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at scala.Function0.apply$mcV$sp(Function0.scala:39)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at scala.App.$anonfun$main$1$adapted(App.scala:80)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at scala.collection.immutable.List.foreach(List.scala:392)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at scala.App.main(App.scala:80)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at scala.App.main$(App.scala:78)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at org.bigbluebutton.Boot$.main(Boot.scala:15)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at org.bigbluebutton.Boot.main(Boot.scala)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]: Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:636)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         at java.lang.Thread.run(Thread.java:748)
Jun 25 14:44:24 kischt bbb-apps-akka[2267]: Caused by: java.net.ConnectException: Connection refused
Jun 25 14:44:24 kischt bbb-apps-akka[2267]:         ... 11 more
```

**Comment by yashodhank** [comment]
I was able to solve it on BBB version 2.5.8 recently when my instance crashed due to no disk space left and then bbb-recording services failed along with redis, although redis-server status was active but app was not able to connect and anyone joining room was getting 408 Auth timeout and Authorisation error in browser and in logs `Invalid session token` all over, rebooting did not help nor anything else posted related to this topic on internet forums.

then I ran following commands after performing manual clean up to free up disk space via SSH to server.
```
redis-cli FLUSHDB
redis-cli FLUSHALL ASYNC
redis-cli FLUSHALL
```
followed by `bbb-config --restart` and users were able to login into rooms without issue.

**Comment by mharjac** [comment]
I've hit the same issue with a fresh installation of version 2.6.10 (1306) in a LXD container. Overriding fdlimit, as suggested from @TheJJ, solved it.

**Comment by privatejava** [comment]
@yashodhank you actually saved my day man !!! Huge kudos . I checked in bbb logs , webrtc logs but nothing that much and when i used that redis-cli commands  it worked with restart of `bbb-conf --restart`

 I am using BigBluebutton 2.5.18
