### ISSUE TITLE
Error on join meeting: java.lang.NullPointerException

### ISSUE THREAD

**Issue by plancked** [bigbluebutton/bigbluebutton#9838]
Hello,

This drives me nuts. When entering a demo meeting, I get this error:

Status Code | 500
Exception Type | null
Message | null

java.lang.NullPointerException
	at org.apache.jsp.demoHTML5_jsp.getJoinURLExtended(demoHTML5_jsp.java:259)
	at org.apache.jsp.demoHTML5_jsp._jspService(demoHTML5_jsp.java:1257)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:400)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:344)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by plancked** [comment]
This is the bbb-conf --check:

------

BigBlueButton Server 2.2.15 (1976)
                    Kernel version: 4.4.0-142-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 4045 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://liveclass.proaudio.courses
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: liveclass.proaudio.courses
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://liveclass.proaudio.courses
                              red5: liveclass.proaudio.courses
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 10.1.1.56
                   external_rtp_ip: liveclass.proaudio.courses
                   external_sip_ip: liveclass.proaudio.courses

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: liveclass.proaudio.courses
                        ext-sip-ip: liveclass.proaudio.courses
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: liveclass.proaudio.courses
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: liveclass.proaudio.courses

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 212.32.232.56
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 10.1.1.56
                    localIpAddress: 10.1.1.56
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 933
                        kurentoUrl: wss://liveclass.proaudio.courses/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 10.1.1.56
#   /etc/nginx/sites-available/bigbluebutton: liveclass.proaudio.courses
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 10.1.1.56
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: liveclass.proaudio.courses

................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    https://liveclass.proaudio.courses/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Warning: The setting of liveclass.proaudio.courses for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (10.1.1.56).
# (This is OK if you've manually changed the values)

# Warning: The API demos are installed and accessible from:
#
#    https://liveclass.proaudio.courses
#
# and
#
#    https://liveclass.proaudio.courses/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

# Error: Unable to reach default URL for presentation:
#
#    https://liveclass.proaudio.courses/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

**Comment by matiasilva** [comment]
Hello! Thanks for posting here. Unfortunately, the GitHub issue tracker is only for development-related topics. Please post your query in https://groups.google.com/forum/#!forum/bigbluebutton-setup, people will be able to better help you there.

**Comment by matiasilva** [comment]
Closing this until further discussion.
