### ISSUE TITLE
Unable to join bigbluebutton

### ISSUE THREAD

**Issue by durga83** [bigbluebutton/bigbluebutton#9967]
Client Error
==========
Link:-
https://raysha.in/demo/demoHTML5.jsp?username=durga&isModerator=true&action=create

java.lang.NullPointerException
	at org.apache.jsp.demoHTML5_jsp.getJoinURLExtended(demoHTML5_jsp.java:259)
	at org.apache.jsp.demoHTML5_jsp._jspService(demoHTML5_jsp.java:1257)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:400)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:344)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

===========================================
 sudo bbb-conf --check

BigBlueButton Server 2.2.17 (1992)
                    Kernel version: 4.15.0-106-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 16424 MB
                         CPU cores: 6

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://raysha.in
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: raysha.in
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://raysha.in
                              red5: raysha.in
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 167.86.121.161
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: raysha.in
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 167.86.121.161

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 167.86.121.161
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 167.86.121.161
                    localIpAddress: 167.86.121.161
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 937
                        kurentoUrl: wss://raysha.in/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 167.86.121.161
#   /etc/nginx/sites-available/bigbluebutton: raysha.in
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 167.86.121.161
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: raysha.in

................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    https://raysha.in/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Warning: The API demos are installed and accessible from:
#
#    https://raysha.in
#
# and
#
#    https://raysha.in/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

# Error: Unable to reach default URL for presentation:
#
#    https://raysha.in/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
