### ISSUE TITLE
Recordings archive workflow KO

### ISSUE THREAD

**Issue by MonsieurPoutounours** [bigbluebutton/bigbluebutton#9984]
**Describe the bug**
Recordings never pass through the archive workflow and the bbb-rap-archive-worker.service always fail.

**To Reproduce**
Install BBB on Ubuntu 16.04 using official documentation
bbb-record --list ( show that bbb-rap-archive-worker.service fails )
bbb-record --debug ( shows that all recordings are under -- Ingest and Processing: found recorded meeting but no archive files-- )

**Expected behavior**
Recordings are archived, then pass through next workflow

**Actual behavior**
Recordings are not archived and never pass through workflows

**Additional context**
No log files related to bbb-rap-archive-worker.service exist.
Here is the ouput of /usr/local/bigbluebutton/core/scripts/rap-archive-worker.rb

:/usr/local/bigbluebutton/core/scripts# su -c /usr/local/bigbluebutton/core/scripts/rap-archive-worker.rb -s /bin/bash bigbluebutton

```
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated                                                                                      [47/4894]/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/nokogiri.so: warning: already initialized constant Nokogiri::LIBXML_VERSION
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/nokogiri.so: warning: already initialized constant Nokogiri::LIBXML_PARSER_VERSION
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/nokogiri.so: warning: already initialized constant Nokogiri::NOKOGIRI_USE_PACKAGED_LIBRARIES
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/nokogiri.so: warning: already initialized constant Nokogiri::NOKOGIRI_LIBXML2_PATH
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/nokogiri.so: warning: already initialized constant Nokogiri::NOKOGIRI_LIBXSLT_PATH
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/nokogiri.so: warning: already initialized constant Nokogiri::NOKOGIRI_LIBXML2_PATCHES
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/nokogiri.so: warning: already initialized constant Nokogiri::NOKOGIRI_LIBXSLT_PATCHES
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/nokogiri.so: warning: already initialized constant Nokogiri::LIBXML_ICONV_ENABLED
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/nokogiri.so: warning: already initialized constant Nokogiri::XML::EntityDecl::INTERNAL_GENERAL
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/nokogiri.so: warning: already initialized constant Nokogiri::XML::EntityDecl::EXTERNAL_GENERAL_PARSED
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/nokogiri.so: warning: already initialized constant Nokogiri::XML::EntityDecl::EXTERNAL_GENERAL_UNPARSED
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/nokogiri.so: warning: already initialized constant Nokogiri::XML::EntityDecl::INTERNAL_PARAMETER
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/nokogiri.so: warning: already initialized constant Nokogiri::XML::EntityDecl::EXTERNAL_PARAMETER
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/nokogiri.so: warning: already initialized constant Nokogiri::XML::EntityDecl::INTERNAL_PREDEFINED
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/version.rb:3: warning: already initialized constant Nokogiri::VERSION
/usr/lib/ruby/vendor_ruby/nokogiri/version.rb:3: warning: previous definition of VERSION was here
WARNING: Nokogiri was built against LibXML version 2.9.10, but has dynamically loaded 2.9.3
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/version.rb:100: warning: already initialized constant Nokogiri::VERSION_INFO
/usr/lib/ruby/vendor_ruby/nokogiri/version.rb:95: warning: previous definition of VERSION_INFO was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:29: warning: already initialized constant Nokogiri::XML::ParseOptions::STRICT
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:7: warning: previous definition of STRICT was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:31: warning: already initialized constant Nokogiri::XML::ParseOptions::RECOVER
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:9: warning: previous definition of RECOVER was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:33: warning: already initialized constant Nokogiri::XML::ParseOptions::NOENT
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:11: warning: previous definition of NOENT was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:35: warning: already initialized constant Nokogiri::XML::ParseOptions::DTDLOAD
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:13: warning: previous definition of DTDLOAD was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:37: warning: already initialized constant Nokogiri::XML::ParseOptions::DTDATTR
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:15: warning: previous definition of DTDATTR was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:39: warning: already initialized constant Nokogiri::XML::ParseOptions::DTDVALID
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:17: warning: previous definition of DTDVALID was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:41: warning: already initialized constant Nokogiri::XML::ParseOptions::NOERROR
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:19: warning: previous definition of NOERROR was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:43: warning: already initialized constant Nokogiri::XML::ParseOptions::NOWARNING
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:21: warning: previous definition of NOWARNING was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:45: warning: already initialized constant Nokogiri::XML::ParseOptions::PEDANTIC
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:23: warning: previous definition of PEDANTIC was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:47: warning: already initialized constant Nokogiri::XML::ParseOptions::NOBLANKS
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:25: warning: previous definition of NOBLANKS was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:49: warning: already initialized constant Nokogiri::XML::ParseOptions::SAX1
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:27: warning: previous definition of SAX1 was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:51: warning: already initialized constant Nokogiri::XML::ParseOptions::XINCLUDE
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:29: warning: previous definition of XINCLUDE was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:53: warning: already initialized constant Nokogiri::XML::ParseOptions::NONET
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:31: warning: previous definition of NONET was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:55: warning: already initialized constant Nokogiri::XML::ParseOptions::NODICT
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:33: warning: previous definition of NODICT was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:57: warning: already initialized constant Nokogiri::XML::ParseOptions::NSCLEAN
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:35: warning: previous definition of NSCLEAN was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:59: warning: already initialized constant Nokogiri::XML::ParseOptions::NOCDATA
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:37: warning: previous definition of NOCDATA was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:61: warning: already initialized constant Nokogiri::XML::ParseOptions::NOXINCNODE
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:39: warning: previous definition of NOXINCNODE was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:63: warning: already initialized constant Nokogiri::XML::ParseOptions::COMPACT
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:41: warning: previous definition of COMPACT was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:65: warning: already initialized constant Nokogiri::XML::ParseOptions::OLD10
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:43: warning: previous definition of OLD10 was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:67: warning: already initialized constant Nokogiri::XML::ParseOptions::NOBASEFIX
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:45: warning: previous definition of NOBASEFIX was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:69: warning: already initialized constant Nokogiri::XML::ParseOptions::HUGE
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:47: warning: previous definition of HUGE was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:72: warning: already initialized constant Nokogiri::XML::ParseOptions::DEFAULT_XML
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:50: warning: previous definition of DEFAULT_XML was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/parse_options.rb:74: warning: already initialized constant Nokogiri::XML::ParseOptions::DEFAULT_HTML
/usr/lib/ruby/vendor_ruby/nokogiri/xml/parse_options.rb:52: warning: previous definition of DEFAULT_HTML was here
/var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/sax/parser.rb:33:in `<class:Parser>': superclass mismatch for class Attribute (TypeError)
        from /var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/sax/parser.rb:32:in `<module:SAX>'
        from /var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/sax/parser.rb:3:in `<module:XML>'
        from /var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/sax/parser.rb:2:in `<module:Nokogiri>'
        from /var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/sax/parser.rb:1:in `<top (required)>'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/sax.rb:3:in `<top (required)>'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri/xml.rb:3:in `<top (required)>'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /var/lib/gems/2.3.0/gems/nokogiri-1.10.8/lib/nokogiri.rb:36:in `<top (required)>'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /var/lib/gems/2.3.0/gems/loofah-2.3.1/lib/loofah.rb:3:in `<top (required)>'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:168:in `require'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:178:in `require'
        from /usr/local/bigbluebutton/core/lib/recordandplayback/generators/events.rb:25:in `<top (required)>'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /usr/local/bigbluebutton/core/lib/recordandplayback.rb:27:in `<top (required)>'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /usr/local/bigbluebutton/core/scripts/rap-archive-worker.rb:21:in `<main>'

```

**Comment by matiasilva** [comment]
Version? More details of your setup needed!

**Comment by MonsieurPoutounours** [comment]
Hi,

Setup was done with bbb-install.sh on up to date Ubuntu 16.04. I just added SSL based on this : https://docs.bigbluebutton.org/2.2/install.html#configure-ssl-on-your-bigbluebutton-server

It is a standalone node. 

BBBversion : bbb-conf --version

```
ii  bbb-apps                              1:2.2.0-45                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.2.0-87                                        all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.2.0-45                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                          1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.2.0-42                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.2.0-40                                      amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.2.0-196                                     amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                          1:2.2.0-51                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                   2:2.2.0-112                                     amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-6                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.2.0-65                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.2.0-960                                     amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-3                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.2.0-31                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.2.0-67                                      amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-transcode-akka                    2.2.0-8                                         all          BigBlueButton Transcoder
ii  bbb-web                               1:2.2.0-130                                     amd64        BigBlueButton API
ii  bbb-webrtc-sfu                        1:2.2.0-102                                     amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.2.0-5                                       amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                7:4.2.2-1bbb1~ubuntu16.04                       amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                           0.2.1-1bbb1                                     amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for image scaling and various conversions - runtime files
```

**Comment by MonsieurPoutounours** [comment]
Hi,

Script output shows that nokogiri gem is to blame.

So, i listed installed gems with 

`gem list `

It show that two different versions of this gem is installed : 

`nokogiri (1.10.8, 1.6.7.2)`

Uninstalling the newest one : 

`gem uninstall nokogiri --version 1.10.8`

Now, recordings are working. 

The thing is i installed nothing more than bbb-install.sh does. Maybe someone can check this ?

**Comment by matiasilva** [comment]
Are you storing your files on NFS?

**Comment by MonsieurPoutounours** [comment]
No, i am not.

**Comment by pedrobmarin** [comment]
Currently running nokogiri `v1.11` at `development`

**Comment by pedrobmarin** [comment]
Hmmm, still maybe someone will have to check if the multiple versions are being installed. Reopening and suggesting verification.
